// packages/angular/src/viewer/extrusion-3d-overlay.component.ts
import { NgStyle } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

import type { Extrusion3DData, Extrusion3dCss } from '../internal/shared';
import type { StyleMap } from './element-style';

/**
 * Convert a framework-neutral `Extrusion3dCss` map (shared `build3DExtrusionData`)
 * into this binding's kebab-case `StyleMap`.
 *
 * The shared builder returns bare numbers for length values (`width`,
 * `height`, `left`, `top`, `inset`), relying on React's automatic `px`
 * suffixing for inline styles. Angular's `[ngStyle]` does NOT append units to
 * numbers (unlike React's `CSSProperties` object, and like Vue's `:style`,
 * which has its own `toCss` doing exactly this coercion in
 * `Extrusion3DOverlay.vue`), so a bare `200` here would set an invalid,
 * ignored CSS length. Every key in the map is also unitless-safe (no
 * unitless CSS property, such as `opacity` or `z-index`, ever appears in this
 * particular map), so a blanket numeric -> `px` string coercion is safe.
 */
function toStyleMap(style: Extrusion3dCss): StyleMap {
	const map: StyleMap = {};
	for (const [key, value] of Object.entries(style)) {
		const kebab = key.replace(/[A-Z]/gu, (m) => `-${m.toLowerCase()}`);
		map[kebab] = typeof value === 'number' ? `${value}px` : value;
	}
	return map;
}

/**
 * Extrusion3DOverlayComponent: Angular port of React's `Extrusion3DOverlay.tsx`
 * / Vue's `Extrusion3DOverlay.vue`.
 *
 * Renders the CSS 3D extrusion side faces (top/bottom/left/right panels) of a
 * shape with `a:sp3d` extrusion depth, from the framework-agnostic panel data
 * shared `build3DExtrusionData` computes. Each panel is a plain `<div>`
 * positioned in 3D space around the shape's bounding box to form the sides of
 * the extrusion volume; an optional material gradient overlays the front face.
 *
 * Before this component existed, Angular vendored `build3DExtrusionData`
 * (via `../internal/shared`) but no template ever called it: an extruded
 * shape's depth showed only as the flat `box-shadow` approximation from
 * `getShapeFillStrokeStyle`/`merge3dStyleMap`, the fallback every other
 * binding treats as a fallback ONLY for a scene the panel geometry cannot
 * cover, while React/Vue/Svelte/Vanilla additionally rendered these real,
 * camera-rotated 3D panels on top. This is purely visual
 * (`pointer-events: none`, `aria-hidden`): no interactivity on the panels.
 */
@Component({
	selector: 'pptx-extrusion-3d-overlay',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [NgStyle],
	template: `
		@if (data().hasExtrusion && data().panels.length > 0) {
			<div class="pptx-ng-extrusion-3d-wrapper" aria-hidden="true" [ngStyle]="wrapperStyle()">
				@for (panel of panels(); track panel.side) {
					<div
						class="pptx-ng-extrusion-3d-panel"
						[class]="'pptx-ng-extrusion-3d-panel pptx-ng-extrusion-3d-panel--' + panel.side"
						[ngStyle]="panel.style"
					></div>
				}
				@if (materialOverlayStyle(); as mo) {
					<div class="pptx-ng-extrusion-3d-material-overlay" [ngStyle]="mo"></div>
				}
			</div>
		}
	`,
})
export class Extrusion3DOverlayComponent {
	/** Extrusion data computed by shared `build3DExtrusionData`. */
	readonly data = input.required<Extrusion3DData>();

	readonly wrapperStyle = computed<StyleMap>(() => toStyleMap(this.data().wrapperStyle));

	readonly panels = computed(() =>
		this.data().panels.map((panel) => ({ side: panel.side, style: toStyleMap(panel.style) })),
	);

	readonly materialOverlayStyle = computed<StyleMap | undefined>(() => {
		const overlay = this.data().materialOverlay;
		if (!overlay) {
			return undefined;
		}
		const style: StyleMap = {
			position: 'absolute',
			inset: '0',
			'background-image': overlay,
			'pointer-events': 'none',
			'border-radius': 'inherit',
			'transform-style': 'preserve-3d',
			'backface-visibility': 'hidden',
			'mix-blend-mode': 'normal',
		};
		const frontTransform = this.data().frontFaceStyle.transform;
		if (frontTransform !== undefined) {
			style['transform'] = frontTransform;
		}
		return style;
	});
}

// packages/react/src/viewer/components/elements/Extrusion3DOverlay.tsx
/**
 * Extrusion3DOverlay: renders CSS 3D extrusion side faces for shapes
 * with `a:sp3d` extrusion depth.
 *
 * This component creates the side panels (top, bottom, left, right) of a
 * 3D-extruded shape using CSS 3D transforms (`transform-style: preserve-3d`,
 * `perspective`, `rotateX/Y`). Each panel is a plain `<div>` positioned in
 * 3D space around the shape's bounding box to form the sides of the extrusion.
 *
 * The front face of the shape (the original content) gets a `translateZ`
 * offset applied through inline styles so it sits at the front of the
 * extrusion volume.
 *
 * A material overlay gradient is rendered on the front face to simulate
 * specular highlights and environment reflections based on the material preset.
 *
 * This is purely visual: no interactivity on the panels.
 */
import React from 'react';

import type { Extrusion3DData, ExtrusionPanel } from '../../utils/shape-visual-3d';

interface Extrusion3DOverlayProps {
	/** Extrusion data computed by `build3DExtrusionData`. */
	data: Extrusion3DData;
}

/**
 * Renders the 3D extrusion side panels as absolutely-positioned divs
 * within a `preserve-3d` container. This component should be rendered
 * as a sibling or wrapper alongside the shape's main content.
 */
export const Extrusion3DOverlay: React.FC<Extrusion3DOverlayProps> = React.memo(
	// oxlint-disable-next-line prefer-arrow-callback -- named fn gives the memo component its displayName
	function Extrusion3DOverlayInner({ data }) {
		if (!data.hasExtrusion || data.panels.length === 0) {
			return null;
		}

		return (
			<div className='extrusion-3d-wrapper' style={data.wrapperStyle} aria-hidden='true'>
				{data.panels.map((panel: ExtrusionPanel) => (
					<div
						key={panel.side}
						className={`extrusion-3d-panel extrusion-3d-panel--${panel.side}`}
						style={panel.style}
					/>
				))}
				{data.materialOverlay && (
					<div
						className='extrusion-3d-material-overlay'
						style={{
							position: 'absolute',
							inset: 0,
							backgroundImage: data.materialOverlay,
							pointerEvents: 'none',
							borderRadius: 'inherit',
							transform: data.frontFaceStyle.transform,
							transformStyle: 'preserve-3d',
							backfaceVisibility: 'hidden',
							mixBlendMode: 'normal',
						}}
					/>
				)}
			</div>
		);
	},
);

Extrusion3DOverlay.displayName = 'Extrusion3DOverlay';
