// packages/vue/src/viewer/components/InlineTextEditor.vue
<script setup lang="ts">
/**
 * InlineTextEditor: a `contentEditable` overlay for editing an element's text
 * in place (Vue port of the React `elements/InlineTextEditor.tsx`).
 *
 * It is mounted inside the scaled slide stage (same coordinate space as
 * {@link SelectionOverlay}), positioned over the element's box, and seeded once
 * from the element's plain text. It does NOT re-bind its value while the user
 * types (the DOM owns the text during an edit) and only reports changes via
 * `change`, committing on blur (`commit`) or cancelling on Escape (`cancel`).
 * The host commits the typed text back onto the element's rich `textSegments`
 * (via `remapTextToSegments`) so per-run styling is preserved.
 */
import type { PptxElement, TextStyle } from 'pptx-viewer-core';
import { placeCaretAtEnd } from 'pptx-viewer-shared';
import type { CSSProperties } from 'vue';
import { computed, onMounted, ref } from 'vue';
import { useI18n } from 'vue-i18n';

const { t } = useI18n();

const props = withDefaults(
	defineProps<{
		element: PptxElement;
		/** Draw the browser's native red spell-check squiggles while editing (View ▸ Spell). */
		spellCheck?: boolean;
	}>(),
	{ spellCheck: true },
);

const emit = defineEmits<{
	change: [text: string];
	commit: [];
	cancel: [];
	/** Ctrl/Cmd+B/I/U formatting toggle while editing (parity with React). */
	format: [updates: Partial<TextStyle>];
}>();

const editorRef = ref<HTMLDivElement | null>(null);

/** The element's current plain text (seed value). */
function seedText(): string {
	return (props.element as { text?: string }).text ?? '';
}

/** Read the live text out of the contentEditable node. */
function extractText(): string {
	return editorRef.value?.innerText ?? '';
}

const editorStyle = computed<CSSProperties>(() => {
	const el = props.element;
	const style = (el as { textStyle?: Record<string, unknown> }).textStyle ?? {};
	const fontSize = typeof style.fontSize === 'number' ? `${style.fontSize}px` : undefined;
	const align =
		typeof style.align === 'string' ? (style.align as CSSProperties['textAlign']) : undefined;
	return {
		position: 'absolute',
		left: `${el.x}px`,
		top: `${el.y}px`,
		width: `${el.width}px`,
		height: `${el.height}px`,
		display: 'flex',
		flexDirection: 'column',
		justifyContent: 'center',
		boxSizing: 'border-box',
		padding: '2px 4px',
		margin: 0,
		outline: '2px solid var(--pptx-vue-selection-color, #3b82f6)',
		// Transparent: the element's own shape fill (still rendered underneath by
		// `ElementRenderer`, which only suppresses its TEXT while this element is
		// being edited) shows through, matching React and the element's actual
		// authored appearance. A near-opaque white used to sit here as a stand-in
		// backdrop; with the static text no longer duplicated underneath (issue
		// #182), it only mismatched non-white fills.
		background: 'transparent',
		color: typeof style.color === 'string' ? (style.color as string) : '#111827',
		fontFamily: typeof style.fontFamily === 'string' ? (style.fontFamily as string) : 'inherit',
		fontSize: fontSize ?? 'inherit',
		fontWeight: style.bold ? 700 : 'normal',
		fontStyle: style.italic ? 'italic' : 'normal',
		textAlign: align ?? 'left',
		overflow: 'hidden',
		whiteSpace: 'pre-wrap',
		cursor: 'text',
		zIndex: 60,
	};
});

onMounted(() => {
	const node = editorRef.value;
	if (!node) {
		return;
	}
	node.innerText = seedText();
	node.focus();
	// Place the caret at the end of the seeded text (shared contract helper).
	placeCaretAtEnd(node);
});

function onInput(): void {
	emit('change', extractText());
}

function onBlur(): void {
	emit('change', extractText());
	emit('commit');
}

/** The style the B/I/U toggles read their current state from. */
function currentTextStyle(): TextStyle | undefined {
	const el = props.element as {
		textSegments?: Array<{ style?: TextStyle }>;
		textStyle?: TextStyle;
	};
	return el.textSegments?.[0]?.style ?? el.textStyle;
}

/**
 * When the caret sits at a soft word-wrap boundary (no explicit line break,
 * just CSS wrapping), the space separating the two words is still part of the
 * text and lands right before the caret. Pressing Enter there splits the DOM
 * at that exact position, leaving the new paragraph break preceded by a stray
 * space (mirrors the React inline editor's fix). Since a space immediately
 * before a paragraph break is never visually meaningful, drop it before the
 * browser performs its native Enter/paragraph-split.
 */
function trimTrailingSpaceBeforeCaret(): void {
	const selection = window.getSelection();
	if (!selection || !selection.isCollapsed || selection.rangeCount === 0) {
		return;
	}
	const range = selection.getRangeAt(0);
	const { startContainer, startOffset } = range;
	if (startContainer.nodeType !== Node.TEXT_NODE || startOffset === 0) {
		return;
	}
	const text = startContainer.textContent ?? '';
	if (text.charAt(startOffset - 1) !== ' ') {
		return;
	}
	const trimRange = document.createRange();
	trimRange.setStart(startContainer, startOffset - 1);
	trimRange.setEnd(startContainer, startOffset);
	trimRange.deleteContents();
}

function onKeydown(event: KeyboardEvent): void {
	// Inline formatting shortcuts (Ctrl/Cmd + B/I/U), matching the React editor.
	if ((event.ctrlKey || event.metaKey) && !event.shiftKey) {
		const key = event.key.toLowerCase();
		if (key === 'b' || key === 'i' || key === 'u') {
			event.preventDefault();
			event.stopPropagation();
			const ts = currentTextStyle();
			if (key === 'b') {
				emit('format', { bold: !ts?.bold });
			} else if (key === 'i') {
				emit('format', { italic: !ts?.italic });
			} else {
				emit('format', { underline: !ts?.underline });
			}
			return;
		}
	}
	if (event.key === 'Escape') {
		event.preventDefault();
		emit('cancel');
		return;
	}
	if (event.key === 'Enter') {
		trimTrailingSpaceBeforeCaret();
	}
}
</script>

<template>
	<div
		ref="editorRef"
		class="pptx-vue-inline-editor"
		data-inline-editor
		contenteditable="true"
		:spellcheck="props.spellCheck"
		role="textbox"
		:aria-label="t('pptx.inlineEditor.editText')"
		:style="editorStyle"
		@input="onInput"
		@blur="onBlur"
		@keydown="onKeydown"
		@pointerdown.stop
	/>
</template>

// packages/react/src/viewer/components/elements/InlineTextEditor.tsx
import type { PptxElement, TextStyle } from 'pptx-viewer-core';
import { hasTextProperties } from 'pptx-viewer-core';
import { placeCaretAtEnd, readEditableText } from 'pptx-viewer-shared';
import React, { useRef, useEffect, useLayoutEffect, useCallback } from 'react';

import { DEFAULT_TEXT_COLOR } from '../../constants';
import { getTextCompensationTransform, getTextWarpStyle, renderTextSegments } from '../../utils';
import {
	getPendingSelectionRestore,
	restoreSegmentSelection,
} from '../../utils/inline-selection-utils';

/**
 * Rich inline text editor: uses a `contentEditable` div that renders the same
 * rich text segments as view mode so formatting (per-run fonts, sizes, colors,
 * bullets, paragraph indentation, text effects) is preserved while editing.
 *
 * The editor extracts plain text on commit via `innerText` and passes it to the
 * parent's `onEditChange` callback, which feeds into `remapTextToSegments` to
 * redistribute the edited text across the original rich segments.
 *
 * The outer wrapper matches the view-mode text container exactly:
 * - `getTextLayoutStyle` for flex vertical alignment, body-inset padding, columns
 * - `getTextStyleForElement` (textStyle) for element-level font defaults
 * - `getTextWarpStyle` for text warp 3D transforms
 * - `getTextCompensationTransform` for rotation compensation
 */
export function InlineTextEditor({
	initialText,
	spellCheck,
	rtl,
	textDirection: _textDirection,
	textStyle,
	textStyleRaw,
	layoutStyle,
	element,
	onCommit,
	onCancel,
	onEditChange,
	onFormatText,
}: {
	initialText: string;
	spellCheck: boolean;
	rtl?: boolean;
	textDirection?: TextStyle['textDirection'];
	textStyle: React.CSSProperties;
	/** Raw TextStyle object for computing warp transforms. */
	textStyleRaw?: TextStyle;
	/** Layout style from getTextLayoutStyle; provides flex vertical alignment. */
	layoutStyle: React.CSSProperties;
	element: PptxElement;
	onCommit: () => void;
	onCancel: () => void;
	onEditChange: (t: string) => void;
	/** Called when the user applies formatting via keyboard shortcut (Ctrl+B/I/U). */
	onFormatText?: (updates: Partial<TextStyle>) => void;
}) {
	const editorRef = useRef<HTMLDivElement>(null);

	// The editor is UNCONTROLLED: its content is seeded exactly once (below) and
	// the DOM owns the text from then on. `initialText` is updated by the parent
	// on every keystroke (via onEditChange), so if we rendered it as children
	// React would rewrite the text node on each change and the caret would jump
	// back to the start / typing would reverse. We therefore capture the seed
	// content on first render and never re-render it; live edits flow out through
	// handleInput, and the latest value is read from the DOM on commit/blur.
	const seedRef = useRef<{ initialText: string; hasRichSegments: boolean } | null>(null);
	if (seedRef.current === null) {
		seedRef.current = {
			initialText,
			hasRichSegments: Boolean(
				hasTextProperties(element) && element.textSegments && element.textSegments.length > 0,
			),
		};
	}
	const seed = seedRef.current;

	// Extract authored text from the contentEditable div. Rendered list markers
	// are annotated presentation chrome and are intentionally excluded.
	const extractText = useCallback((): string => {
		const el = editorRef.current;
		if (!el) {
			return seed.initialText;
		}
		return readEditableText(el);
	}, [seed]);

	// Sync text to parent on every input via ref (no re-render)
	const handleInput = useCallback(() => {
		onEditChange(extractText());
	}, [extractText, onEditChange]);

	// When the caret sits at a soft word-wrap boundary (no explicit line break,
	// just CSS wrapping), the space that separates the two words is still part
	// of the text and lands right before the caret. Pressing Enter there splits
	// the DOM at that exact position, leaving the new paragraph break preceded
	// by a stray space: e.g. "fox jumps" wrapped as "fox " / "jumps" becomes
	// paragraphs "fox " and "jumps" instead of "fox" and "jumps". That extra,
	// invisible trailing character then counts toward the paragraph's measured
	// width, occasionally forcing an unwanted extra wrapped line. Since a space
	// immediately before a paragraph break is never visually meaningful, drop it
	// before the browser performs its native Enter/paragraph-split.
	const trimTrailingSpaceBeforeCaret = useCallback(() => {
		const selection = window.getSelection();
		if (!selection || !selection.isCollapsed || selection.rangeCount === 0) {
			return;
		}
		const range = selection.getRangeAt(0);
		const { startContainer, startOffset } = range;
		if (startContainer.nodeType !== Node.TEXT_NODE || startOffset === 0) {
			return;
		}
		const text = startContainer.textContent ?? '';
		if (text.charAt(startOffset - 1) !== ' ') {
			return;
		}
		const trimRange = document.createRange();
		trimRange.setStart(startContainer, startOffset - 1);
		trimRange.setEnd(startContainer, startOffset);
		trimRange.deleteContents();
	}, []);

	// Auto-focus on mount and place cursor at end
	useEffect(() => {
		const el = editorRef.current;
		if (!el) {
			return;
		}
		el.focus();
		// Place cursor at end of content (shared contract helper).
		placeCaretAtEnd(el);
	}, []);

	// After a formatting update, React re-renders the contentEditable children
	// which destroys the DOM selection. Restore it from the pending info.
	const mountedRef = useRef(false);
	useLayoutEffect(() => {
		// Skip the initial mount; cursor is already placed by the effect above.
		if (!mountedRef.current) {
			mountedRef.current = true;
			return;
		}
		const pending = getPendingSelectionRestore();
		if (!pending || !editorRef.current) {
			return;
		}
		restoreSegmentSelection(
			editorRef.current,
			pending.startSegIdx,
			pending.startOffset,
			pending.endSegIdx,
			pending.endOffset,
		);
	});

	// Build wrapper style matching view-mode exactly:
	// layoutStyle (flex alignment, vertical padding, columns) + textStyle (font defaults,
	// horizontal padding/insets) + warp transforms + compensation transform.
	//
	// View mode applies: getTextLayoutStyle + txtS + getTextWarpStyle + compensationTransform
	// We replicate that same order here.
	const warpStyle = getTextWarpStyle(textStyleRaw);

	// Merge the compensation transform with warp transform if both exist
	const compensationTransform = getTextCompensationTransform(element);
	const warpTransform = warpStyle?.transform;
	const mergedTransform =
		[compensationTransform, warpTransform].filter(Boolean).join(' ') || undefined;

	const wrapperStyle: React.CSSProperties = {
		...layoutStyle,
		...textStyle,
		...warpStyle,
		transform: mergedTransform,
		transformOrigin: warpStyle?.transformOrigin || 'center',
	};

	return (
		<div
			ref={editorRef}
			contentEditable
			suppressContentEditableWarning
			data-inline-editor
			spellCheck={spellCheck}
			dir={rtl ? 'rtl' : 'ltr'}
			className='relative z-10 w-full h-full whitespace-pre-wrap break-words leading-[1.3] outline-none'
			style={{
				...wrapperStyle,
				cursor: 'text',
				minHeight: '1em',
			}}
			// Touch surfaces drive canvas drag/marquee through onPointerDown (see
			// useCanvasEventHandlers.handleStagePointerDown). Without stopping it
			// here, tapping inside the editor to reposition the caret would bubble
			// to the stage and start dragging the element instead of editing.
			onPointerDown={(e) => e.stopPropagation()}
			onMouseDown={(e) => e.stopPropagation()}
			onClick={(e) => e.stopPropagation()}
			onInput={handleInput}
			onBlur={() => {
				onEditChange(extractText());
				onCommit();
			}}
			onKeyDown={(e) => {
				// Inline formatting shortcuts (Ctrl/Cmd + B/I/U)
				if ((e.ctrlKey || e.metaKey) && !e.shiftKey && onFormatText) {
					const key = e.key.toLowerCase();
					if (key === 'b' || key === 'i' || key === 'u') {
						e.preventDefault();
						e.stopPropagation();
						const seg = hasTextProperties(element) ? element.textSegments?.[0] : undefined;
						const ts = seg?.style ?? (hasTextProperties(element) ? element.textStyle : undefined);
						switch (key) {
							case 'b':
								onFormatText({ bold: !ts?.bold });
								break;
							case 'i':
								onFormatText({ italic: !ts?.italic });
								break;
							case 'u':
								onFormatText({ underline: !ts?.underline });
								break;
						}
						return;
					}
				}
				if (e.key === 'Escape') {
					e.preventDefault();
					onCancel();
					return;
				}
				if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) {
					e.preventDefault();
					onEditChange(extractText());
					onCommit();
					return;
				}
				if (e.key === 'Enter') {
					trimTrailingSpaceBeforeCaret();
				}
			}}
			// Prevent paste from inserting HTML: paste as plain text only
			onPaste={(e) => {
				e.preventDefault();
				const text = e.clipboardData.getData('text/plain');
				document.execCommand('insertText', false, text);
			}}
		>
			{seed.hasRichSegments ? renderTextSegments(element, DEFAULT_TEXT_COLOR) : seed.initialText}
		</div>
	);
}
