// packages/react/src/viewer/components/toolbar/TitleBar.tsx
import {
	filterCommands,
	resolveTitleBarStatusKey,
	TITLE_BAR_CLASSES as TB,
	TITLE_BAR_DEFAULT_FILE_KEY,
} from 'pptx-viewer-shared';
import type { CommandSearchEntry, ToolbarActionId } from 'pptx-viewer-shared';
import React, { useCallback, useEffect, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { LuRedo, LuSave, LuSearch, LuUndo } from 'react-icons/lu';

import type { AutosaveStatus } from '../../hooks/useAutosave';
import { useToolbarVisibility } from '../../hooks/useToolbarVisibility';
import type { ViewerMode } from '../../types';
import { cn } from '../../utils';
import { useViewerOptionsContext } from '../viewer-options-context';
import { TitleBarQuickExtras } from './TitleBarQuickExtras';

export interface TitleBarProps {
	mode: ViewerMode;
	canEdit: boolean;
	/** Display name of the open document (host-supplied). */
	fileName?: string;
	isDirty: boolean;
	autosaveStatus?: AutosaveStatus;
	autosaveEnabled: boolean;
	onToggleAutosave: () => void;
	canUndo: boolean;
	canRedo: boolean;
	undoLabel?: string | null;
	redoLabel?: string | null;
	onUndo: () => void;
	onRedo: () => void;
	/** Quick-access save (downloads the .pptx). */
	onSave?: () => void;
	findReplaceOpen: boolean;
	onToggleFindReplace: () => void;
	/** Dispatch a command from the search palette. */
	onCommandSearch?: (command: string) => void;
	/** Host-supplied list of toolbar buttons/ribbon tabs to hide. */
	hiddenActions?: readonly ToolbarActionId[];
	/**
	 * Run a Quick Access command that is not one of the dedicated
	 * Save/Undo/Redo buttons (`presentFromStart`, `print`, ...), by catalog id.
	 */
	onQuickCommand?: (id: string) => void;
}

/**
 * PowerPoint-style title bar: AutoSave toggle, quick-access Save/Undo/Redo,
 * file name + save-location status, and a centred search box that opens the
 * Find & Replace panel. Rendered above (outside) the ribbon toolbar.
 */
export function TitleBar(p: TitleBarProps): React.ReactElement {
	const { t } = useTranslation();
	const editing = (p.mode === 'edit' || p.mode === 'master') && p.canEdit;
	const { isHidden } = useToolbarVisibility(p.hiddenActions);
	const quickAccess = useViewerOptionsContext().quickAccess;

	const [searchQuery, setSearchQuery] = useState('');
	const [searchFocused, setSearchFocused] = useState(false);
	const searchRef = useRef<HTMLDivElement>(null);

	const commandResults = filterCommands(searchQuery, t);

	const handleCommandSelect = useCallback(
		(entry: CommandSearchEntry) => {
			p.onCommandSearch?.(entry.command);
			setSearchQuery('');
			setSearchFocused(false);
		},
		[p],
	);

	const handleSearchKeyDown = useCallback(
		(e: React.KeyboardEvent) => {
			if (e.key === 'Enter' && searchQuery.trim()) {
				if (commandResults.length > 0) {
					handleCommandSelect(commandResults[0]);
				} else {
					p.onToggleFindReplace();
					setSearchFocused(false);
				}
			} else if (e.key === 'Escape') {
				setSearchQuery('');
				setSearchFocused(false);
			}
		},
		[searchQuery, commandResults, handleCommandSelect, p],
	);

	useEffect(() => {
		const handler = (e: MouseEvent) => {
			if (searchRef.current && !searchRef.current.contains(e.target as Node)) {
				setSearchFocused(false);
			}
		};
		document.addEventListener('mousedown', handler);
		return () => document.removeEventListener('mousedown', handler);
	}, []);

	const statusKey = resolveTitleBarStatusKey({
		autosaveState: p.autosaveStatus?.state ?? 'idle',
		isDirty: p.isDirty,
		autosaveEnabled: p.autosaveEnabled,
		disabledReason: p.autosaveStatus?.state === 'disabled' ? p.autosaveStatus.reason : undefined,
	});

	return (
		<div className={TB.container} data-pptx-title-bar=''>
			<span className={TB.logo} aria-hidden='true'>
				P
			</span>

			{editing && (
				<>
					<span className={TB.autosaveGroup}>
						<span className={TB.autosaveLabel}>{t('pptx.titleBar.autoSave')}</span>
						<button
							type='button'
							role='switch'
							aria-checked={p.autosaveEnabled}
							onClick={p.onToggleAutosave}
							className={cn(
								TB.toggleTrack,
								p.autosaveEnabled ? TB.toggleTrackOn : TB.toggleTrackOff,
							)}
							title={t('pptx.titleBar.toggleAutoSave')}
							aria-label={t('pptx.titleBar.toggleAutoSave')}
						>
							<span
								className={cn(
									TB.toggleKnob,
									p.autosaveEnabled ? TB.toggleKnobOn : TB.toggleKnobOff,
								)}
							/>
						</button>
						<span className={TB.autosaveLabel}>
							{t(p.autosaveEnabled ? 'pptx.titleBar.autoSaveOn' : 'pptx.titleBar.autoSaveOff')}
						</span>
					</span>

					<div className={TB.separator} />

					{p.onSave && (
						<button
							type='button'
							onClick={p.onSave}
							className={TB.quickButton}
							title={t('pptx.titleBar.save')}
							aria-label={t('pptx.titleBar.save')}
						>
							<LuSave className='w-3.5 h-3.5' />
						</button>
					)}
					{!isHidden('undo') && (
						<button
							type='button'
							onClick={p.onUndo}
							disabled={!p.canUndo}
							className={TB.quickButton}
							title={
								p.undoLabel
									? t('pptx.toolbar.undoAction', { action: p.undoLabel })
									: t('pptx.toolbar.undo')
							}
							aria-label={t('pptx.toolbar.undo')}
						>
							<LuUndo className='w-3.5 h-3.5' />
						</button>
					)}
					{!isHidden('redo') && (
						<button
							type='button'
							onClick={p.onRedo}
							disabled={!p.canRedo}
							className={TB.quickButton}
							title={
								p.redoLabel
									? t('pptx.toolbar.redoAction', { action: p.redoLabel })
									: t('pptx.toolbar.redo')
							}
							aria-label={t('pptx.toolbar.redo')}
						>
							<LuRedo className='w-3.5 h-3.5' />
						</button>
					)}
					{/*
					 * Everything else File > Options > Quick Access Toolbar asks for, in
					 * configured order. Without this the strip was hardcoded to the three
					 * buttons above and silently ignored the options model, so it showed
					 * three commands where the shared default (and Angular) had four.
					 *
					 * Suppressed here when position is "below": the same commands then
					 * render in a row under the ribbon (`Toolbar`'s own
					 * `TitleBarQuickExtras` usage) instead, so they show in exactly one
					 * place. The dedicated Save/Undo/Redo trio above always stays here,
					 * matching Angular's `belowRibbonQuickAccess`.
					 */}
					{quickAccess.position !== 'below' && (
						<TitleBarQuickExtras quickAccess={quickAccess} onCommand={p.onQuickCommand} />
					)}

					<div className={TB.separator} />
				</>
			)}

			<span className={TB.fileGroup}>
				<span className={TB.fileName}>{p.fileName || t(TITLE_BAR_DEFAULT_FILE_KEY)}</span>
				{editing && (
					<>
						<span className={TB.statusDot} aria-hidden='true'>
							&bull;
						</span>
						<span
							className={cn(
								TB.statusText,
								p.autosaveStatus?.state === 'error' && p.autosaveEnabled && TB.statusError,
								p.autosaveStatus?.state === 'saving' && p.autosaveEnabled && TB.statusSaving,
							)}
						>
							{t(statusKey)}
						</span>
					</>
				)}
			</span>

			<span className={TB.searchWrap}>
				{(p.mode === 'edit' || p.mode === 'master') && (
					<div ref={searchRef} className='relative w-full max-w-md'>
						<div
							className={cn(
								TB.searchBox,
								(searchFocused || p.findReplaceOpen) && 'text-foreground bg-background',
							)}
						>
							<LuSearch className={TB.searchIcon} />
							<input
								type='text'
								value={searchQuery}
								onChange={(e) => setSearchQuery(e.target.value)}
								onFocus={() => setSearchFocused(true)}
								onKeyDown={handleSearchKeyDown}
								placeholder={t('pptx.titleBar.searchPlaceholder')}
								className='flex-1 bg-transparent text-[11px] outline-none placeholder:text-muted-foreground/60'
								aria-label={t('pptx.titleBar.search')}
							/>
						</div>
						{searchFocused && searchQuery.trim() && (
							<div className='absolute left-0 right-0 top-full z-50 mt-1 rounded-lg border border-border bg-popover shadow-xl max-h-64 overflow-y-auto'>
								{commandResults.length > 0 ? (
									<>
										<div className='px-3 py-1.5 text-[10px] font-semibold text-muted-foreground uppercase tracking-wider'>
											{t('pptx.titleBar.searchCommands')}
										</div>
										{commandResults.slice(0, 8).map((entry) => (
											<button
												key={entry.command}
												type='button'
												className='flex w-full items-center gap-2 px-3 py-1.5 text-xs text-foreground hover:bg-accent transition-colors'
												onMouseDown={() => handleCommandSelect(entry)}
											>
												<span className='truncate'>{t(entry.labelKey)}</span>
												<span className='ml-auto text-[10px] text-muted-foreground capitalize'>
													{entry.category}
												</span>
											</button>
										))}
									</>
								) : (
									<div className='px-3 py-2 text-xs text-muted-foreground'>
										{t('pptx.titleBar.searchNoResults')}
									</div>
								)}
								<div className='border-t border-border/60'>
									<button
										type='button'
										className='flex w-full items-center gap-2 px-3 py-1.5 text-xs text-foreground hover:bg-accent transition-colors'
										onMouseDown={() => {
											p.onToggleFindReplace();
											setSearchFocused(false);
											setSearchQuery('');
										}}
									>
										<LuSearch className='w-3 h-3 shrink-0' />
										<span>
											{t('pptx.titleBar.searchContent')} &ldquo;{searchQuery}&rdquo;
										</span>
									</button>
								</div>
							</div>
						)}
					</div>
				)}
			</span>

			{/* Right block mirrors the left visually; kept minimal. */}
			<span className={TB.rightSpacer} />
		</div>
	);
}

// packages/vue/src/viewer/components/ribbon/TitleBar.vue
<script setup lang="ts">
import { Redo, Save, Search, Undo } from 'lucide-vue-next';
import {
	DEFAULT_VIEWER_OPTIONS,
	extraQuickAccessCommands,
	filterCommands,
	resolveTitleBarStatusKey,
	TITLE_BAR_CLASSES as TB,
	TITLE_BAR_DEFAULT_FILE_KEY,
} from 'pptx-viewer-shared';
import type { CommandSearchEntry, ToolbarActionId } from 'pptx-viewer-shared';
import { computed, inject, onBeforeUnmount, onMounted, ref } from 'vue';
import { useI18n } from 'vue-i18n';

import { cn } from '../../../utils';
import type { AutosaveStatus } from '../../composables/useAutosave';
import { useToolbarVisibility } from '../../composables/useToolbarVisibility';
import { ViewerOptionsKey } from '../../composables/useViewerOptionsStore';
import type { ViewerMode } from './ribbon-types';
import TitleBarQuickAccess from './TitleBarQuickAccess.vue';

interface Props {
	mode: ViewerMode;
	canEdit: boolean;
	fileName?: string;
	isDirty: boolean;
	autosaveStatus?: AutosaveStatus;
	autosaveEnabled: boolean;
	autosaveDisabledReason?: string;
	onToggleAutosave: () => void;
	canUndo: boolean;
	canRedo: boolean;
	undoLabel?: string | null;
	redoLabel?: string | null;
	onUndo: () => void;
	onRedo: () => void;
	onSave?: () => void;
	findReplaceOpen: boolean;
	onToggleFindReplace: () => void;
	onCommandSearch?: (command: string) => void;
	/** Toolbar buttons the host has asked to hide (gates Undo/Redo independently below). */
	hiddenActions?: ToolbarActionId[];
	/**
	 * Run a Quick Access command that is not one of the dedicated
	 * Save/Undo/Redo buttons (`presentFromStart`, `print`, ...), by catalog id.
	 */
	onQuickCommand?: (id: string) => void;
}

const props = defineProps<Props>();
const { t } = useI18n();
const { isHidden } = useToolbarVisibility(() => props.hiddenActions);

// The strip beyond Save/Undo/Redo comes from File > Options; hardcoding three
// buttons is what left this binding a command short of the shared default.
const viewerOptions = inject(ViewerOptionsKey, undefined);
const quickAccess = computed(
	() => viewerOptions?.value.quickAccess ?? DEFAULT_VIEWER_OPTIONS.quickAccess,
);
// Options > Quick Access Toolbar > position: when set to "below the Ribbon",
// `PowerPointViewer.vue` renders the strip in its own row under the ribbon
// instead, so the title bar suppresses its inline copy to avoid duplicates.
const extraQuickCommands = computed(() =>
	(quickAccess.value.visible && quickAccess.value.position !== 'below'
		? extraQuickAccessCommands(quickAccess.value.commandIds)
		: []
	).map((command) => ({ id: command.id, label: t(command.labelKey), icon: command.icon })),
);

const editing = computed(() => (props.mode === 'edit' || props.mode === 'master') && props.canEdit);

const statusKey = computed(() =>
	resolveTitleBarStatusKey({
		autosaveState: props.autosaveStatus ?? 'idle',
		isDirty: props.isDirty,
		autosaveEnabled: props.autosaveEnabled,
		disabledReason: props.autosaveDisabledReason,
	}),
);

const searchQuery = ref('');
const searchFocused = ref(false);
const searchRef = ref<HTMLDivElement | null>(null);

const commandResults = computed(() => filterCommands(searchQuery.value, t));

function handleCommandSelect(entry: CommandSearchEntry): void {
	props.onCommandSearch?.(entry.command);
	searchQuery.value = '';
	searchFocused.value = false;
}

function handleSearchKeyDown(e: KeyboardEvent): void {
	if (e.key === 'Enter' && searchQuery.value.trim()) {
		if (commandResults.value.length > 0) {
			handleCommandSelect(commandResults.value[0]);
		} else {
			props.onToggleFindReplace();
			searchFocused.value = false;
		}
	} else if (e.key === 'Escape') {
		searchQuery.value = '';
		searchFocused.value = false;
	}
}

function handleOutsideClick(e: MouseEvent): void {
	if (searchRef.value && !searchRef.value.contains(e.target as Node)) {
		searchFocused.value = false;
	}
}

onMounted(() => document.addEventListener('mousedown', handleOutsideClick));
onBeforeUnmount(() => document.removeEventListener('mousedown', handleOutsideClick));
</script>

<template>
	<div :class="TB.container" data-pptx-title-bar>
		<span :class="TB.logo" aria-hidden="true">P</span>

		<template v-if="editing">
			<span :class="TB.autosaveGroup">
				<span :class="TB.autosaveLabel">{{ t('pptx.titleBar.autoSave') }}</span>
				<button
					type="button"
					role="switch"
					:aria-checked="props.autosaveEnabled"
					:class="cn(TB.toggleTrack, props.autosaveEnabled ? TB.toggleTrackOn : TB.toggleTrackOff)"
					:title="t('pptx.titleBar.toggleAutoSave')"
					:aria-label="t('pptx.titleBar.toggleAutoSave')"
					@click="props.onToggleAutosave()"
				>
					<span
						:class="cn(TB.toggleKnob, props.autosaveEnabled ? TB.toggleKnobOn : TB.toggleKnobOff)"
					/>
				</button>
				<span :class="TB.autosaveLabel">
					{{ t(props.autosaveEnabled ? 'pptx.titleBar.autoSaveOn' : 'pptx.titleBar.autoSaveOff') }}
				</span>
			</span>

			<div :class="TB.separator" />

			<button
				v-if="props.onSave"
				type="button"
				:class="TB.quickButton"
				:title="t('pptx.titleBar.save')"
				:aria-label="t('pptx.titleBar.save')"
				@click="props.onSave()"
			>
				<Save class="w-3.5 h-3.5" />
			</button>
			<button
				v-if="!isHidden('undo')"
				type="button"
				:disabled="!props.canUndo"
				:class="TB.quickButton"
				:title="
					props.undoLabel
						? t('pptx.toolbar.undoAction', { action: props.undoLabel })
						: t('pptx.toolbar.undo')
				"
				:aria-label="t('pptx.toolbar.undo')"
				@click="props.onUndo()"
			>
				<Undo class="w-3.5 h-3.5" />
			</button>
			<button
				v-if="!isHidden('redo')"
				type="button"
				:disabled="!props.canRedo"
				:class="TB.quickButton"
				:title="
					props.redoLabel
						? t('pptx.toolbar.redoAction', { action: props.redoLabel })
						: t('pptx.toolbar.redo')
				"
				:aria-label="t('pptx.toolbar.redo')"
				@click="props.onRedo()"
			>
				<Redo class="w-3.5 h-3.5" />
			</button>
			<!-- Everything else File > Options > Quick Access Toolbar asks for. -->
			<TitleBarQuickAccess
				v-if="extraQuickCommands.length > 0"
				:items="extraQuickCommands"
				:show-labels="quickAccess.showCommandLabels"
				:on-command="(id: string) => props.onQuickCommand?.(id)"
			/>

			<div :class="TB.separator" />
		</template>

		<span :class="TB.fileGroup">
			<span :class="TB.fileName">{{ props.fileName || t(TITLE_BAR_DEFAULT_FILE_KEY) }}</span>
			<template v-if="editing">
				<span :class="TB.statusDot" aria-hidden="true">&bull;</span>
				<span
					:class="
						cn(
							TB.statusText,
							props.autosaveStatus === 'error' && props.autosaveEnabled ? TB.statusError : '',
							props.autosaveStatus === 'saving' && props.autosaveEnabled ? TB.statusSaving : '',
						)
					"
				>
					{{ t(statusKey) }}
				</span>
			</template>
		</span>

		<span :class="TB.searchWrap">
			<div
				v-if="props.mode === 'edit' || props.mode === 'master'"
				ref="searchRef"
				class="relative w-full max-w-md"
			>
				<div
					:class="
						cn(
							TB.searchBox,
							searchFocused || props.findReplaceOpen ? 'text-foreground bg-background' : '',
						)
					"
				>
					<Search :class="TB.searchIcon" />
					<input
						v-model="searchQuery"
						type="text"
						class="flex-1 bg-transparent text-[11px] outline-none placeholder:text-muted-foreground/60"
						:placeholder="t('pptx.titleBar.searchPlaceholder')"
						:aria-label="t('pptx.titleBar.search')"
						@focus="searchFocused = true"
						@keydown="handleSearchKeyDown"
					/>
				</div>
				<div
					v-if="searchFocused && searchQuery.trim()"
					class="absolute left-0 right-0 top-full z-50 mt-1 rounded-lg border border-border bg-popover shadow-xl max-h-64 overflow-y-auto"
				>
					<template v-if="commandResults.length > 0">
						<div
							class="px-3 py-1.5 text-[10px] font-semibold text-muted-foreground uppercase tracking-wider"
						>
							{{ t('pptx.titleBar.searchCommands') }}
						</div>
						<button
							v-for="entry in commandResults.slice(0, 8)"
							:key="entry.command"
							type="button"
							class="flex w-full items-center gap-2 px-3 py-1.5 text-xs text-foreground hover:bg-accent transition-colors"
							@mousedown="handleCommandSelect(entry)"
						>
							<span class="truncate">{{ t(entry.labelKey) }}</span>
							<span class="ml-auto text-[10px] text-muted-foreground capitalize">{{
								entry.category
							}}</span>
						</button>
					</template>
					<div v-else class="px-3 py-2 text-xs text-muted-foreground">
						{{ t('pptx.titleBar.searchNoResults') }}
					</div>
					<div class="border-t border-border/60">
						<button
							type="button"
							class="flex w-full items-center gap-2 px-3 py-1.5 text-xs text-foreground hover:bg-accent transition-colors"
							@mousedown="
								props.onToggleFindReplace();
								searchFocused = false;
								searchQuery = '';
							"
						>
							<Search class="w-3 h-3 shrink-0" />
							<span>{{ t('pptx.titleBar.searchContent') }} &ldquo;{{ searchQuery }}&rdquo;</span>
						</button>
					</div>
				</div>
			</div>
		</span>

		<!-- Right block mirrors the left visually; kept minimal. -->
		<span :class="TB.rightSpacer" />
	</div>
</template>
