// packages/react/src/viewer/components/toolbar/ViewSection.tsx
import React from 'react';
import { useTranslation } from 'react-i18next';
import {
	LuBookOpen,
	LuCode,
	LuGrid3X3,
	LuIndentIncrease,
	LuLayoutGrid,
	LuList,
	LuMaximize2,
	LuPanelTop,
	LuPipette,
	LuPresentation,
	LuRuler,
	LuStickyNote,
	LuZoomIn,
} from 'react-icons/lu';

import {
	RibbonCommand,
	RibbonCommandStack,
	RibbonGroup,
	RibbonToggle,
} from './PowerPointRibbonControls';

export interface ViewSectionProps {
	canEdit: boolean;
	editTemplateMode: boolean;
	onSetEditTemplateMode: (mode: boolean) => void;
	spellCheckEnabled: boolean;
	onSetSpellCheckEnabled: (enabled: boolean) => void;
	showGrid: boolean;
	showRulers: boolean;
	showGuides: boolean;
	snapToGrid: boolean;
	snapToShape: boolean;
	onSetShowGrid: (enabled: boolean) => void;
	onSetShowRulers: (enabled: boolean) => void;
	onSetShowGuides: (enabled: boolean) => void;
	onSetSnapToGrid: (enabled: boolean) => void;
	onSetSnapToShape: (enabled: boolean) => void;
	onAddGuide: (axis: 'h' | 'v') => void;
	onEnterMasterView: () => void;
	isSelectionPaneOpen?: boolean;
	onToggleSelectionPane?: () => void;
	eyedropperActive?: boolean;
	onToggleEyedropper?: () => void;
	onToggleSlideSorter?: () => void;
	/** Enter PowerPoint's Reading View (full window, not the fullscreen show). */
	onOpenReadingView?: () => void;
	/** Enter PowerPoint's Outline view: the deck as editable indented text. */
	onOpenOutlineView?: () => void;
	onZoomToFit?: () => void;
}

export function ViewSection(p: ViewSectionProps): React.ReactElement {
	const { t } = useTranslation();
	return (
		<>
			<RibbonGroup label={t('pptx.view.presentationViews')}>
				<RibbonCommand
					label={t('pptx.view.normal')}
					icon={<LuPanelTop />}
					title={t('pptx.statusBar.normalView')}
				/>
				<RibbonCommand
					label={t('pptx.slideSorter.title')}
					icon={<LuLayoutGrid />}
					onClick={p.onToggleSlideSorter}
					title={t('pptx.view.slideSorterTooltip')}
				/>
				<RibbonCommand
					label={t('pptx.view.outlineView')}
					icon={<LuIndentIncrease />}
					onClick={p.onOpenOutlineView}
					title={t('pptx.view.outlineViewTooltip')}
				/>
				<RibbonCommand
					label={t('pptx.view.readingView')}
					icon={<LuBookOpen />}
					onClick={p.onOpenReadingView}
					title={t('pptx.view.readingView')}
				/>
			</RibbonGroup>
			<RibbonGroup label={t('pptx.view.masterViews')}>
				<RibbonCommand
					label={t('pptx.master.title')}
					icon={<LuPresentation />}
					onClick={p.onEnterMasterView}
					disabled={!p.canEdit}
					title={t('pptx.view.slideMasterTooltip')}
				/>
				<RibbonCommand
					label={t('pptx.master.handoutMasterTitle', { defaultValue: 'Handout Master' })}
					icon={<LuGrid3X3 />}
					disabled
				/>
				<RibbonCommand
					label={t('pptx.master.notesMasterTitle', { defaultValue: 'Notes Master' })}
					icon={<LuStickyNote />}
					disabled
				/>
			</RibbonGroup>
			<RibbonGroup label={t('pptx.view.show', { defaultValue: 'Show' })}>
				<RibbonCommandStack>
					<RibbonToggle
						label={t('pptx.ruler.rulers')}
						checked={p.showRulers}
						onChange={p.onSetShowRulers}
					/>
					<RibbonToggle
						label={t('pptx.grid.grid')}
						checked={p.showGrid}
						onChange={p.onSetShowGrid}
						title={t('pptx.grid.toggleGrid')}
					/>
					{/*
						Guides shows and hides the drawing guides, nothing else. It used
						to drive shape snapping instead, which left the "Snap to shape"
						command below permanently disabled and described a feature that
						lived on a differently-named control.
					*/}
					<RibbonToggle
						label={t('pptx.view.guides', { defaultValue: 'Guides' })}
						checked={p.showGuides}
						onChange={p.onSetShowGuides}
						title={t('pptx.ribbon.toggleGuides')}
					/>
					<RibbonToggle label='Snap to grid' checked={p.snapToGrid} onChange={p.onSetSnapToGrid} />
				</RibbonCommandStack>
				<RibbonCommandStack>
					<RibbonCommand
						compact
						label={t('pptx.view.selection')}
						icon={<LuList />}
						onClick={p.onToggleSelectionPane}
						active={p.isSelectionPaneOpen}
						title={t('pptx.selectionPane.title')}
					/>
					<RibbonCommand
						compact
						label={t('pptx.ribbon.eyedropper')}
						icon={<LuPipette />}
						onClick={p.onToggleEyedropper}
						active={p.eyedropperActive}
						disabled={!p.canEdit}
					/>
					<RibbonCommand
						compact
						label={t('pptx.view.snapToShape')}
						icon={<LuGrid3X3 />}
						onClick={() => p.onSetSnapToShape(!p.snapToShape)}
						active={p.snapToShape}
						title={t('pptx.view.snapToShape')}
					/>
					<RibbonCommand
						compact
						label='H Guide'
						icon={<LuRuler />}
						onClick={() => p.onAddGuide('h')}
						title={t('pptx.view.addHorizontalGuide')}
					/>
					<RibbonCommand
						compact
						label='V Guide'
						icon={<LuRuler />}
						onClick={() => p.onAddGuide('v')}
						title={t('pptx.view.addVerticalGuide')}
					/>
				</RibbonCommandStack>
			</RibbonGroup>
			<RibbonGroup label={t('pptx.slideSorter.zoom')}>
				<RibbonCommand label={t('pptx.slideSorter.zoom')} icon={<LuZoomIn />} disabled />
				<RibbonCommand
					label={t('pptx.view.zoomToFit')}
					icon={<LuMaximize2 />}
					onClick={p.onZoomToFit}
				/>
			</RibbonGroup>
			<RibbonGroup label={t('pptx.view.window', { defaultValue: 'Window' })}>
				<RibbonCommand
					label={t(p.editTemplateMode ? 'pptx.ribbon.templatesOn' : 'pptx.ribbon.templatesOff')}
					icon={<LuRuler />}
					onClick={() => p.onSetEditTemplateMode(!p.editTemplateMode)}
					active={p.editTemplateMode}
					disabled={!p.canEdit}
					title={t('pptx.view.templateEditingTooltip', {
						defaultValue: 'Toggle template/master element editing',
					})}
				/>
				<RibbonCommand
					label={t('pptx.view.macros', { defaultValue: 'Macros' })}
					icon={<LuCode />}
					disabled
				/>
			</RibbonGroup>
		</>
	);
}

// packages/vue/src/viewer/components/ribbon/ViewSection.vue
<script setup lang="ts">
import { Code, Grid3X3, List, Pipette, StickyNote, ZoomIn } from 'lucide-vue-next';
import { useI18n } from 'vue-i18n';

/**
 * ViewSection: the Vue 3 port of React's `toolbar/ViewSection.tsx`. Renders the
 * View ribbon tab's Presentation Views, Master Views, Show, Zoom and Window
 * groups.
 *
 * Reading View is live: it opens the windowed reading overlay (see
 * `ReadingViewOverlay.vue`). It shipped `disabled` in every binding for a year,
 * which is why the test below asserts it is enabled rather than asserting the
 * placeholder.
 *
 * "Guides" and "Snap to shape" are one control each, for the one thing each of
 * them names. They used to be crossed: Guides drove shape snapping and Snap to
 * shape was a permanently disabled placeholder, i.e. a label describing a
 * feature that lives on a differently-named control. Guide visibility and shape
 * snapping are genuinely separate settings (you can want the guides drawn
 * without every drag magnetising to a neighbour), and the editor already
 * carries both flags.
 */
import { cn } from '../../../utils';
import { GROUP_LABEL, ic, pill, SEP } from './ribbon-constants';

interface Props {
	canEdit: boolean;
	editTemplateMode: boolean;
	onSetEditTemplateMode: (mode: boolean) => void;
	spellCheckEnabled: boolean;
	onSetSpellCheckEnabled: (enabled: boolean) => void;
	showGrid: boolean;
	showRulers: boolean;
	/** Guide-overlay visibility only; the guides themselves stay in the model. */
	showGuides: boolean;
	snapToGrid: boolean;
	snapToShape: boolean;
	onSetShowGrid: (enabled: boolean) => void;
	onSetShowRulers: (enabled: boolean) => void;
	onSetShowGuides: (enabled: boolean) => void;
	onSetSnapToGrid: (enabled: boolean) => void;
	onSetSnapToShape: (enabled: boolean) => void;
	onAddGuide: (axis: 'h' | 'v') => void;
	onEnterMasterView: () => void;
	isSelectionPaneOpen?: boolean;
	onToggleSelectionPane?: () => void;
	eyedropperActive?: boolean;
	onToggleEyedropper?: () => void;
	onToggleSlideSorter?: () => void;
	onOpenReadingView?: () => void;
	/** Enter PowerPoint's Outline view: the deck as editable indented text. */
	onOpenOutlineView?: () => void;
	onZoomToFit?: () => void;
}

const props = defineProps<Props>();
const { t } = useI18n();

const toggleRow = 'flex h-[19px] items-center gap-1 whitespace-nowrap rounded-sm px-1 text-[10px]';
</script>

<template>
	<!--
		Every group below is a direct child of the ribbon content row
		(`RibbonToolbar.vue`'s `items-center` row), so a group that keeps its
		own intrinsic height sits vertically centered at that height rather than
		reaching the row's true bottom edge whenever a taller sibling group sets
		the row's height (View's five-row "Show" group next to its two-row
		"Zoom" group is the clearest case: without `self-stretch` + `justify-
		between`, "Show"'s caption lands well below the other four groups'
		captions, and their border-right dividers stop short of the row's own
		bottom edge). `self-stretch` claims the row's full height per group;
		`justify-between` then pins each group's caption to that stretched
		box's own bottom, independent of its neighbours' heights, matching
		every other binding's `RibbonGroup`.
	-->
	<!-- Presentation Views group -->
	<div class="flex flex-col items-center justify-between self-stretch gap-0.5">
		<div class="flex items-center gap-0.5">
			<button :class="pill" :title="t('pptx.statusBar.normalView')">
				{{ t('pptx.view.normal') }}
			</button>
			<button
				:class="pill"
				:title="t('pptx.view.slideSorterTooltip')"
				@click="props.onToggleSlideSorter?.()"
			>
				{{ t('pptx.slideSorter.title') }}
			</button>
			<button
				:class="pill"
				:title="t('pptx.view.outlineViewTooltip')"
				@click="props.onOpenOutlineView?.()"
			>
				{{ t('pptx.view.outlineView') }}
			</button>
			<button
				:class="pill"
				:title="t('pptx.view.readingView')"
				@click="props.onOpenReadingView?.()"
			>
				{{ t('pptx.view.readingView') }}
			</button>
		</div>
		<span :class="GROUP_LABEL">{{ t('pptx.view.presentationViews') }}</span>
	</div>
	<div :class="SEP" />

	<!-- Master Views group -->
	<div class="flex flex-col items-center justify-between self-stretch gap-0.5">
		<div class="flex items-center gap-0.5">
			<button
				:disabled="!props.canEdit"
				:class="pill"
				:title="t('pptx.view.slideMasterTooltip')"
				@click="props.onEnterMasterView()"
			>
				{{ t('pptx.master.title') }}
			</button>
			<button disabled :class="pill">
				<Grid3X3 :class="ic" />
				{{ t('pptx.master.handoutMasterTitle') }}
			</button>
			<button disabled :class="pill">
				<StickyNote :class="ic" />
				{{ t('pptx.master.notesMasterTitle') }}
			</button>
		</div>
		<span :class="GROUP_LABEL">{{ t('pptx.view.masterViews') }}</span>
	</div>
	<div :class="SEP" />

	<!-- Show group -->
	<div class="flex flex-col items-center justify-between self-stretch gap-0.5">
		<div class="flex items-start gap-2">
			<div class="flex flex-col justify-start gap-0.5">
				<label :class="cn(toggleRow, props.showRulers ? 'bg-primary/15 text-primary' : '')">
					<input
						type="checkbox"
						class="h-3 w-3 accent-primary"
						:checked="props.showRulers"
						@change="props.onSetShowRulers(($event.target as HTMLInputElement).checked)"
					/>
					{{ t('pptx.ruler.rulers') }}
				</label>
				<label :class="cn(toggleRow, props.showGrid ? 'bg-primary/15 text-primary' : '')">
					<input
						type="checkbox"
						class="h-3 w-3 accent-primary"
						:checked="props.showGrid"
						:title="t('pptx.grid.toggleGrid')"
						@change="props.onSetShowGrid(($event.target as HTMLInputElement).checked)"
					/>
					{{ t('pptx.grid.grid') }}
				</label>
				<label :class="cn(toggleRow, props.showGuides ? 'bg-primary/15 text-primary' : '')">
					<input
						type="checkbox"
						class="h-3 w-3 accent-primary"
						:checked="props.showGuides"
						:title="t('pptx.ribbon.toggleGuides')"
						@change="props.onSetShowGuides(($event.target as HTMLInputElement).checked)"
					/>
					{{ t('pptx.view.guides') }}
				</label>
				<label :class="cn(toggleRow, props.snapToGrid ? 'bg-primary/15 text-primary' : '')">
					<input
						type="checkbox"
						class="h-3 w-3 accent-primary"
						:checked="props.snapToGrid"
						@change="props.onSetSnapToGrid(($event.target as HTMLInputElement).checked)"
					/>
					{{ t('pptx.grid.snapToGrid') }}
				</label>
			</div>
			<div class="flex flex-col justify-start gap-0.5">
				<button
					v-if="props.onToggleSelectionPane"
					type="button"
					:class="
						cn(pill, props.isSelectionPaneOpen ? 'bg-primary hover:bg-primary/80 text-white' : '')
					"
					:title="t('pptx.selectionPane.title')"
					@click="props.onToggleSelectionPane()"
				>
					<List :class="ic" />
					{{ t('pptx.view.selection') }}
				</button>
				<button
					v-if="props.onToggleEyedropper"
					type="button"
					:disabled="!props.canEdit"
					:class="
						cn(
							pill,
							props.eyedropperActive ? 'bg-purple-600 hover:bg-purple-500 text-purple-50' : '',
						)
					"
					:title="t('pptx.view.eyedropperTooltip')"
					@click="props.onToggleEyedropper()"
				>
					<Pipette :class="ic" />
					{{ t('pptx.ribbon.eyedropper') }}
				</button>
				<button
					type="button"
					:class="cn(pill, props.snapToShape ? 'bg-primary hover:bg-primary/80 text-white' : '')"
					:aria-pressed="props.snapToShape"
					:title="t('pptx.view.snapToShape')"
					@click="props.onSetSnapToShape(!props.snapToShape)"
				>
					<Grid3X3 :class="ic" />
					{{ t('pptx.view.snapToShape') }}
				</button>
				<button
					:class="pill"
					:title="t('pptx.view.addHorizontalGuide')"
					@click="props.onAddGuide('h')"
				>
					{{ t('pptx.view.hGuide') }}
				</button>
				<button
					:class="pill"
					:title="t('pptx.view.addVerticalGuide')"
					@click="props.onAddGuide('v')"
				>
					{{ t('pptx.view.vGuide') }}
				</button>
			</div>
		</div>
		<span :class="GROUP_LABEL">{{ t('pptx.view.show') }}</span>
	</div>
	<div :class="SEP" />

	<!-- Zoom group -->
	<div class="flex flex-col items-center justify-between self-stretch gap-0.5">
		<div class="flex items-center gap-0.5">
			<button disabled :class="pill">
				<ZoomIn :class="ic" />
				{{ t('pptx.slideSorter.zoom') }}
			</button>
			<button :class="pill" :title="t('pptx.view.zoomToFitTooltip')" @click="props.onZoomToFit?.()">
				{{ t('pptx.view.zoomToFit') }}
			</button>
		</div>
		<span :class="GROUP_LABEL">{{ t('pptx.slideSorter.zoom') }}</span>
	</div>
	<div :class="SEP" />

	<!-- Window group -->
	<div class="flex flex-col items-center justify-between self-stretch gap-0.5">
		<div class="flex items-center gap-0.5">
			<button
				:disabled="!props.canEdit"
				:class="
					cn(pill, props.editTemplateMode ? 'bg-amber-600 hover:bg-amber-500 text-amber-50' : '')
				"
				:title="t('pptx.view.templateEditingTooltip')"
				@click="props.onSetEditTemplateMode(!props.editTemplateMode)"
			>
				{{ props.editTemplateMode ? t('pptx.ribbon.templatesOn') : t('pptx.ribbon.templatesOff') }}
			</button>
			<button disabled :class="pill">
				<Code :class="ic" />
				{{ t('pptx.view.macros') }}
			</button>
		</div>
		<span :class="GROUP_LABEL">{{ t('pptx.view.window') }}</span>
	</div>
</template>
