// packages/vue/src/viewer/components/ribbon/DrawingGroup.vue
<script setup lang="ts">
import { Layers, PaintBucket, PenLine, Shapes, Sparkles } from 'lucide-vue-next';
/**
 * DrawingGroup: Drawing ribbon group with Shapes dropdown, Arrange layer
 * controls, Shape Fill/Outline colour popovers, and a Shape Effects placeholder.
 * Vue port of React's `toolbar/DrawingGroup.tsx`.
 */
import type { PptxElement, ShapeStyle } from 'pptx-viewer-core';
import { RIBBON_SHAPE_SWATCHES, shapeFillChange, shapeOutlineChange } from 'pptx-viewer-shared';
import { useI18n } from 'vue-i18n';

import { cn } from '../../../utils';
import { injectRecentColors } from '../../composables/recent-colors-context';
import RecentColorsRow from '../RecentColorsRow.vue';
import { vAnchoredPopup } from './anchored-popup';
import { ic, MENU_ITEM, MENU_PANEL, pill, SEP } from './ribbon-constants';
import type { SupportedShapeType } from './ribbon-types';
import { useDropdown } from './use-dropdown';

interface Props {
	canEdit: boolean;
	selectedElement: PptxElement | null;
	newShapeType: string;
	onSetNewShapeType: (type: SupportedShapeType) => void;
	onAddShape: () => void;
	onMoveLayer: (direction: string) => void;
	onMoveLayerToEdge: (direction: string) => void;
	/**
	 * Patch the selected shape's style. Optional only because the mobile menu
	 * sheet renders the group without one; the desktop ribbon always passes it.
	 * It used to be passed by nobody, so both swatch grids were decorative.
	 */
	onUpdateElementStyle?: (style: Partial<ShapeStyle>) => void;
}

const props = defineProps<Props>();
const { t } = useI18n();
const recentColors = injectRecentColors();

const TOP_SHAPES: Array<{ type: SupportedShapeType; labelKey: string }> = [
	{ type: 'rect', labelKey: 'pptx.editorToolbar.shapeRectangle' },
	{ type: 'roundRect', labelKey: 'pptx.editorToolbar.shapeRoundedRectangle' },
	{ type: 'ellipse', labelKey: 'pptx.editorToolbar.shapeEllipse' },
	{ type: 'triangle', labelKey: 'pptx.editorToolbar.shapeTriangle' },
	{ type: 'diamond', labelKey: 'pptx.shapePresets.diamond' },
	{ type: 'pentagon', labelKey: 'pptx.shapePresets.pentagon' },
	{ type: 'hexagon', labelKey: 'pptx.shapePresets.hexagon' },
	{ type: 'star5', labelKey: 'pptx.ribbon.shapeStar5' },
	{ type: 'rtArrow', labelKey: 'pptx.shapePresets.arrow' },
	{ type: 'chevron', labelKey: 'pptx.shapePresets.chevron' },
	{ type: 'heart', labelKey: 'pptx.shapePresets.heart' },
	{ type: 'cloud', labelKey: 'pptx.shapePresets.cloud' },
];

const FILL_COLORS = RIBBON_SHAPE_SWATCHES;

const shapesMenu = useDropdown();
const arrangeMenu = useDropdown();
const fillMenu = useDropdown();
const outlineMenu = useDropdown();

function handlePickShape(s: { type: SupportedShapeType }): void {
	props.onSetNewShapeType(s.type);
	props.onAddShape();
	shapesMenu.close();
}

function handleArrange(action: string, edge: boolean): void {
	if (edge) {
		props.onMoveLayerToEdge(action);
	} else {
		props.onMoveLayer(action);
	}
	arrangeMenu.close();
}

function handleFill(color: string): void {
	props.onUpdateElementStyle?.(shapeFillChange(color));
	recentColors?.push(color);
	fillMenu.close();
}

function handleOutline(color: string): void {
	props.onUpdateElementStyle?.(shapeOutlineChange(color));
	recentColors?.push(color);
	outlineMenu.close();
}
</script>

<template>
	<div class="flex flex-col items-center gap-0.5">
		<div class="flex items-center gap-1">
			<!-- Shapes dropdown -->
			<div :ref="shapesMenu.root" class="relative">
				<button
					type="button"
					:disabled="!props.canEdit"
					:class="pill"
					:title="t('pptx.drawing.shapes')"
					@click="shapesMenu.toggle()"
				>
					<Shapes :class="ic" />
					{{ t('pptx.drawing.shapes') }}
				</button>
				<div
					v-if="shapesMenu.open.value"
					class="z-50 flex flex-col w-52 pt-1"
					v-anchored-popup="{ anchor: shapesMenu.root.value }"
				>
					<div :class="MENU_PANEL">
						<button
							v-for="s in TOP_SHAPES"
							:key="s.type"
							type="button"
							:class="cn(MENU_ITEM, props.newShapeType === s.type && 'bg-accent')"
							@click="handlePickShape(s)"
						>
							{{ t(s.labelKey) }}
						</button>
					</div>
				</div>
			</div>

			<!-- Arrange dropdown -->
			<div :ref="arrangeMenu.root" class="relative">
				<button
					type="button"
					:disabled="!props.canEdit || !props.selectedElement"
					:class="pill"
					:title="t('pptx.ribbon.arrange')"
					@click="arrangeMenu.toggle()"
				>
					<Layers :class="ic" />
					{{ t('pptx.ribbon.arrange') }}
				</button>
				<div
					v-if="arrangeMenu.open.value"
					class="z-50 flex flex-col w-44 pt-1"
					v-anchored-popup="{ anchor: arrangeMenu.root.value }"
				>
					<div :class="MENU_PANEL">
						<button type="button" :class="MENU_ITEM" @click="handleArrange('forward', false)">
							{{ t('pptx.contextMenu.bringForward') }}
						</button>
						<button type="button" :class="MENU_ITEM" @click="handleArrange('backward', false)">
							{{ t('pptx.contextMenu.sendBackward') }}
						</button>
						<button type="button" :class="MENU_ITEM" @click="handleArrange('front', true)">
							{{ t('pptx.contextMenu.bringToFront') }}
						</button>
						<button type="button" :class="MENU_ITEM" @click="handleArrange('back', true)">
							{{ t('pptx.contextMenu.sendToBack') }}
						</button>
					</div>
				</div>
			</div>

			<!-- Shape Fill -->
			<div :ref="fillMenu.root" class="relative">
				<button
					type="button"
					:disabled="!props.canEdit || !props.selectedElement"
					:class="pill"
					:title="t('pptx.drawing.shapeFill')"
					@click="fillMenu.toggle()"
				>
					<PaintBucket :class="ic" />
				</button>
				<div
					v-if="fillMenu.open.value"
					class="z-50 pt-1"
					v-anchored-popup="{ anchor: fillMenu.root.value }"
				>
					<div class="rounded-lg border border-border bg-popover backdrop-blur-lg shadow-2xl p-2">
						<div class="grid grid-cols-6 gap-1">
							<button
								v-for="c in FILL_COLORS"
								:key="c"
								type="button"
								:aria-label="`Fill colour ${c}`"
								class="w-5 h-5 rounded border border-border/60 hover:scale-110 transition-transform"
								data-pptx-compact
								:style="{ backgroundColor: c }"
								:title="c"
								@mousedown.prevent
								@click="handleFill(c)"
							/>
						</div>
						<RecentColorsRow
							v-if="recentColors"
							:colors="recentColors.recent.value"
							:disabled="!props.canEdit || !props.selectedElement"
							@pick="handleFill"
						/>
					</div>
				</div>
			</div>

			<!-- Shape Outline -->
			<div :ref="outlineMenu.root" class="relative">
				<button
					type="button"
					:disabled="!props.canEdit || !props.selectedElement"
					:class="pill"
					:title="t('pptx.drawing.shapeOutline')"
					@click="outlineMenu.toggle()"
				>
					<PenLine :class="ic" />
				</button>
				<div
					v-if="outlineMenu.open.value"
					class="z-50 pt-1"
					v-anchored-popup="{ anchor: outlineMenu.root.value }"
				>
					<div class="rounded-lg border border-border bg-popover backdrop-blur-lg shadow-2xl p-2">
						<div class="grid grid-cols-6 gap-1">
							<button
								v-for="c in FILL_COLORS"
								:key="c"
								type="button"
								:aria-label="`Outline colour ${c}`"
								class="w-5 h-5 rounded border border-border/60 hover:scale-110 transition-transform"
								data-pptx-compact
								:style="{ backgroundColor: c }"
								:title="c"
								@mousedown.prevent
								@click="handleOutline(c)"
							/>
						</div>
						<RecentColorsRow
							v-if="recentColors"
							:colors="recentColors.recent.value"
							:disabled="!props.canEdit || !props.selectedElement"
							@pick="handleOutline"
						/>
					</div>
				</div>
			</div>

			<!-- Shape Effects (placeholder) -->
			<button
				type="button"
				disabled
				:class="cn(pill, 'opacity-50 cursor-not-allowed')"
				:title="t('pptx.drawing.shapeEffectsUnavailable')"
			>
				<Sparkles :class="ic" />
			</button>
		</div>
		<span class="text-[9px] text-muted-foreground leading-none">{{
			t('pptx.ribbon.groupDrawing')
		}}</span>
	</div>

	<div :class="SEP" />
</template>

// packages/react/src/viewer/components/toolbar/DrawingGroup.tsx
import type { PptxElement, ShapeStyle } from 'pptx-viewer-core';
import { shapeFillChange, shapeOutlineChange } from 'pptx-viewer-shared';
import React, { useState, useRef, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { LuLayers, LuPaintBucket, LuPenLine, LuShapes, LuSparkles } from 'react-icons/lu';

import { SHAPE_PRESETS } from '../../constants';
import type { SupportedShapeType } from '../../types-core';
import { cn } from '../../utils';
import { useRecentColors } from '../inspector/RecentColorsContext';
import { RibbonMenu } from './RibbonMenu';
import { ShapeColorPopover } from './ShapeColorPopover';
import { ic, pill, sep } from './toolbar-constants';

export interface DrawingGroupProps {
	canEdit: boolean;
	selectedElement: PptxElement | null;
	newShapeType: SupportedShapeType;
	onSetNewShapeType: (type: SupportedShapeType) => void;
	onAddShape: () => void;
	onMoveLayer: (direction: string) => void;
	onMoveLayerToEdge: (direction: string) => void;
	/**
	 * Patch the selected shape's style. Optional only because the mobile menu
	 * sheet renders the group without one; the desktop ribbon always passes it.
	 * It used to be passed by nobody, so both swatch grids were decorative.
	 */
	onUpdateElementStyle?: (style: Partial<ShapeStyle>) => void;
}

const TOP_SHAPES = SHAPE_PRESETS.slice(0, 12);

export function DrawingGroup(p: DrawingGroupProps): React.ReactElement {
	const { t } = useTranslation();
	const { pushColor } = useRecentColors();
	const [shapesOpen, setShapesOpen] = useState(false);
	const [arrangeOpen, setArrangeOpen] = useState(false);
	const [fillOpen, setFillOpen] = useState(false);
	const [outlineOpen, setOutlineOpen] = useState(false);
	const shapesRef = useRef<HTMLDivElement>(null);
	const arrangeRef = useRef<HTMLDivElement>(null);
	const fillRef = useRef<HTMLDivElement>(null);
	const outlineRef = useRef<HTMLDivElement>(null);

	useEffect(() => {
		if (!shapesOpen) {
			return;
		}
		const handler = (e: MouseEvent) => {
			if (shapesRef.current && !shapesRef.current.contains(e.target as Node)) {
				setShapesOpen(false);
			}
		};
		document.addEventListener('mousedown', handler);
		return () => document.removeEventListener('mousedown', handler);
	}, [shapesOpen]);

	useEffect(() => {
		if (!arrangeOpen) {
			return;
		}
		const handler = (e: MouseEvent) => {
			if (arrangeRef.current && !arrangeRef.current.contains(e.target as Node)) {
				setArrangeOpen(false);
			}
		};
		document.addEventListener('mousedown', handler);
		return () => document.removeEventListener('mousedown', handler);
	}, [arrangeOpen]);

	useEffect(() => {
		if (!fillOpen) {
			return;
		}
		const handler = (e: MouseEvent) => {
			if (fillRef.current && !fillRef.current.contains(e.target as Node)) {
				setFillOpen(false);
			}
		};
		document.addEventListener('mousedown', handler);
		return () => document.removeEventListener('mousedown', handler);
	}, [fillOpen]);

	useEffect(() => {
		if (!outlineOpen) {
			return;
		}
		const handler = (e: MouseEvent) => {
			if (outlineRef.current && !outlineRef.current.contains(e.target as Node)) {
				setOutlineOpen(false);
			}
		};
		document.addEventListener('mousedown', handler);
		return () => document.removeEventListener('mousedown', handler);
	}, [outlineOpen]);

	return (
		<>
			<div className='flex flex-col items-center gap-0.5'>
				<div className='flex items-center gap-1'>
					{/* Shapes dropdown */}
					<div className='relative' ref={shapesRef}>
						<button
							type='button'
							disabled={!p.canEdit}
							className={pill}
							title={t('pptx.drawing.shapes')}
							onClick={() => setShapesOpen((v) => !v)}
						>
							<LuShapes className={ic} />
							{t('pptx.drawing.shapes')}
						</button>
						{shapesOpen && (
							<RibbonMenu anchorRef={shapesRef} className='flex flex-col w-52 pt-1'>
								<div className='rounded-lg border border-border bg-popover backdrop-blur-lg shadow-2xl py-1 max-h-60 overflow-y-auto'>
									{TOP_SHAPES.map((s) => (
										<button
											key={s.type}
											type='button'
											className={cn(
												'flex items-center gap-2 w-full px-3 py-1.5 text-xs text-foreground hover:bg-muted transition-colors',
												p.newShapeType === s.type && 'bg-accent',
											)}
											onClick={() => {
												p.onSetNewShapeType(s.type);
												p.onAddShape();
												setShapesOpen(false);
											}}
										>
											{s.icon}
											{t(s.i18nKey)}
										</button>
									))}
								</div>
							</RibbonMenu>
						)}
					</div>

					{/* Arrange dropdown */}
					<div className='relative' ref={arrangeRef}>
						<button
							type='button'
							disabled={!p.canEdit || !p.selectedElement}
							className={pill}
							title={t('pptx.ribbon.arrange')}
							onClick={() => setArrangeOpen((v) => !v)}
						>
							<LuLayers className={ic} />
							{t('pptx.ribbon.arrange')}
						</button>
						{arrangeOpen && (
							<RibbonMenu anchorRef={arrangeRef} className='flex flex-col w-44 pt-1'>
								<div className='rounded-lg border border-border bg-popover backdrop-blur-lg shadow-2xl py-1'>
									<button
										type='button'
										className='flex items-center w-full px-3 py-1.5 text-xs text-foreground hover:bg-muted transition-colors'
										onClick={() => {
											p.onMoveLayer('forward');
											setArrangeOpen(false);
										}}
									>
										{t('pptx.contextMenu.bringForward')}
									</button>
									<button
										type='button'
										className='flex items-center w-full px-3 py-1.5 text-xs text-foreground hover:bg-muted transition-colors'
										onClick={() => {
											p.onMoveLayer('backward');
											setArrangeOpen(false);
										}}
									>
										{t('pptx.contextMenu.sendBackward')}
									</button>
									<button
										type='button'
										className='flex items-center w-full px-3 py-1.5 text-xs text-foreground hover:bg-muted transition-colors'
										onClick={() => {
											p.onMoveLayerToEdge('front');
											setArrangeOpen(false);
										}}
									>
										{t('pptx.contextMenu.bringToFront')}
									</button>
									<button
										type='button'
										className='flex items-center w-full px-3 py-1.5 text-xs text-foreground hover:bg-muted transition-colors'
										onClick={() => {
											p.onMoveLayerToEdge('back');
											setArrangeOpen(false);
										}}
									>
										{t('pptx.contextMenu.sendToBack')}
									</button>
								</div>
							</RibbonMenu>
						)}
					</div>

					{/* Shape Fill */}
					<ShapeColorPopover
						icon={<LuPaintBucket className={ic} />}
						title={t('pptx.drawing.shapeFill')}
						prefix='shape-fill'
						anchorRef={fillRef}
						open={fillOpen}
						onToggle={() => setFillOpen((v) => !v)}
						disabled={!p.canEdit || !p.selectedElement}
						swatchAriaLabel='Fill colour'
						onApply={(c) => {
							p.onUpdateElementStyle?.(shapeFillChange(c));
							pushColor(c);
						}}
						onClose={() => setFillOpen(false)}
					/>

					{/* Shape Outline */}
					<ShapeColorPopover
						icon={<LuPenLine className={ic} />}
						title={t('pptx.drawing.shapeOutline')}
						prefix='shape-outline'
						anchorRef={outlineRef}
						open={outlineOpen}
						onToggle={() => setOutlineOpen((v) => !v)}
						disabled={!p.canEdit || !p.selectedElement}
						swatchAriaLabel='Outline colour'
						onApply={(c) => {
							p.onUpdateElementStyle?.(shapeOutlineChange(c));
							pushColor(c);
						}}
						onClose={() => setOutlineOpen(false)}
					/>

					{/* Shape Effects (placeholder) */}
					<button
						type='button'
						disabled
						className={pill}
						title={t('pptx.drawing.shapeEffectsUnavailable')}
					>
						<LuSparkles className={ic} />
					</button>
				</div>
				<span className='text-[9px] text-muted-foreground leading-none'>Drawing</span>
			</div>

			{sep}
		</>
	);
}
