// packages/vue/src/viewer/components/ribbon/DrawSection.vue
<script setup lang="ts">
/**
 * DrawSection: the Vue 3 port of React's `toolbar/DrawSection.tsx`. Renders the
 * Draw ribbon tab: the inking-tool button cluster (Select / Pen / Highlighter /
 * Eraser / Freeform) plus the pen-colour swatch and stroke-width slider. A
 * faithful, mechanical port for visual + behavioral parity: class strings are
 * copied verbatim and `cn` composes the active-tool highlight, exactly as React.
 * The shared `DRAW_TOOLS` table supplies lucide icon component refs, rendered via
 * `<component :is="…" />`.
 */
import { useI18n } from 'vue-i18n';

import { cn } from '../../../utils';
import { injectRecentColors } from '../../composables/recent-colors-context';
import { DRAW_TOOLS, gB, gL, grp, ic } from './ribbon-constants';
import type { DrawingTool } from './ribbon-types';

interface Props {
	activeTool: DrawingTool;
	drawingColor: string;
	drawingWidth: number;
	onSetActiveTool: (tool: DrawingTool) => void;
	onSetDrawingColor: (color: string) => void;
	onSetDrawingWidth: (width: number) => void;
}

const props = defineProps<Props>();

const { t } = useI18n();

// The pen colour joins the deck's "Recent colours" list like every other
// picker, but only on `change` (the committed pick): `input` is the continuous
// stream while the dialog is dragged, which keeps driving the live pen colour.
const recentColors = injectRecentColors();
function commitPenColor(event: Event): void {
	recentColors?.push((event.target as HTMLInputElement).value);
}
</script>

<template>
	<div :class="grp">
		<button
			v-for="(tool, i) in DRAW_TOOLS"
			:key="tool.id"
			type="button"
			:class="
				cn(
					i < DRAW_TOOLS.length - 1 ? gB : gL,
					props.activeTool === tool.id ? (tool.ac ?? 'bg-accent text-foreground') : '',
				)
			"
			:title="t(tool.labelKey)"
			@click="props.onSetActiveTool(tool.id)"
		>
			<component :is="tool.icon" :class="ic" />
		</button>
	</div>
	<div class="inline-flex items-center gap-2 text-xs">
		<label
			class="inline-flex items-center gap-1 text-muted-foreground"
			:title="t('pptx.ribbon.penColour')"
		>
			{{ t('pptx.ribbon.colour') }}
			<input
				type="color"
				:value="props.drawingColor"
				class="w-6 h-6 rounded border border-border bg-transparent cursor-pointer"
				@input="props.onSetDrawingColor(($event.target as HTMLInputElement).value)"
				@change="commitPenColor"
			/>
		</label>
		<label
			class="inline-flex items-center gap-1 text-muted-foreground"
			:title="t('pptx.ribbon.strokeWidth')"
		>
			{{ t('pptx.ribbon.width') }}
			<input
				type="range"
				:min="1"
				:max="12"
				:value="props.drawingWidth"
				class="w-16 h-1 accent-primary"
				@input="props.onSetDrawingWidth(Number(($event.target as HTMLInputElement).value))"
			/>
			<span class="text-foreground w-4 text-right">{{ props.drawingWidth }}</span>
		</label>
	</div>
</template>

// packages/react/src/viewer/components/toolbar/DrawSection.tsx
import React, { useEffect, useRef } from 'react';
import { useTranslation } from 'react-i18next';

import type { DrawingTool } from '../../types';
import { cn } from '../../utils';
import { useRecentColors } from '../inspector/RecentColorsContext';
import { gB, gL, grp, DRAW_TOOLS } from './toolbar-constants';

export interface DrawSectionProps {
	activeTool: DrawingTool;
	drawingColor: string;
	drawingWidth: number;
	onSetActiveTool: (tool: DrawingTool) => void;
	onSetDrawingColor: (color: string) => void;
	onSetDrawingWidth: (width: number) => void;
}

export function DrawSection(p: DrawSectionProps): React.ReactElement {
	const { t } = useTranslation();
	const { pushColor } = useRecentColors();

	// The pen colour joins the deck's "Recent colours" list like every other
	// picker, but only on the native `change` (the committed pick): React's
	// `onChange` is the continuous `input` stream while the dialog is dragged,
	// which must keep driving the live pen colour without flooding the list.
	const colorRef = useRef<HTMLInputElement>(null);
	useEffect(() => {
		const el = colorRef.current;
		if (!el) {
			return;
		}
		const handler = () => pushColor(el.value);
		el.addEventListener('change', handler);
		return () => el.removeEventListener('change', handler);
	}, [pushColor]);

	return (
		<>
			<div className={grp}>
				{DRAW_TOOLS.map((tool, i, a) => (
					<button
						key={tool.id}
						type='button'
						onClick={() => p.onSetActiveTool(tool.id)}
						className={cn(
							i < a.length - 1 ? gB : gL,
							p.activeTool === tool.id ? (tool.ac ?? 'bg-accent text-foreground') : '',
						)}
						title={t(tool.labelKey)}
					>
						{tool.icon}
					</button>
				))}
			</div>
			<div className='inline-flex items-center gap-2 text-xs'>
				<label
					className='inline-flex items-center gap-1 text-muted-foreground'
					title={t('pptx.ribbon.penColour')}
				>
					{t('pptx.ribbon.colour')}
					<input
						ref={colorRef}
						type='color'
						value={p.drawingColor}
						onChange={(e) => p.onSetDrawingColor(e.target.value)}
						className='w-6 h-6 rounded border border-border bg-transparent cursor-pointer'
					/>
				</label>
				<label
					className='inline-flex items-center gap-1 text-muted-foreground'
					title={t('pptx.ribbon.strokeWidth')}
				>
					{t('pptx.ribbon.width')}
					<input
						type='range'
						min={1}
						max={12}
						value={p.drawingWidth}
						onChange={(e) => p.onSetDrawingWidth(Number(e.target.value))}
						className='w-16 h-1 accent-primary'
					/>
					<span className='text-foreground w-4 text-right'>{p.drawingWidth}</span>
				</label>
			</div>
		</>
	);
}
