// packages/vue/src/viewer/components/ribbon/HelpSection.vue
<script setup lang="ts">
/**
 * HelpSection: the Help ribbon tab (Settings + Keyboard Shortcuts +
 * Accessibility Check). Extracted from `RibbonToolbar.vue`'s inline
 * `<template>` to keep that file under the repo's ~300 LOC convention and match
 * the one-component-per-tab pattern the other sections already follow.
 */
import { useI18n } from 'vue-i18n';

import { pill } from './ribbon-constants';

interface Props {
	/** Opens the File > Options dialog; falls back to the shortcuts sheet when unwired. */
	onOpenSettings?: () => void;
	onToggleShortcuts: () => void;
	onRunAccessibilityCheck: () => void;
}

const props = defineProps<Props>();
const { t } = useI18n();
</script>

<template>
	<button
		type="button"
		:class="pill"
		:title="t('pptx.settings.title')"
		@click="(props.onOpenSettings ?? props.onToggleShortcuts)()"
	>
		{{ t('pptx.settings.title') }}
	</button>
	<button
		type="button"
		:class="pill"
		:title="t('pptx.settings.keyboardShortcuts')"
		@click="props.onToggleShortcuts()"
	>
		{{ t('pptx.settings.keyboardShortcuts') }}
	</button>
	<button
		type="button"
		:class="pill"
		:title="t('pptx.ribbon.accessibilityCheck')"
		@click="props.onRunAccessibilityCheck()"
	>
		{{ t('pptx.ribbon.accessibilityCheck') }}
	</button>
</template>

// packages/react/src/viewer/components/toolbar/HelpSection.tsx
import React from 'react';
import { useTranslation } from 'react-i18next';

import { pill } from './toolbar-constants';

export interface HelpSectionProps {
	/** Opens the File > Options dialog. Falls back to the shortcuts sheet when the host wires neither. */
	onOpenSettings?: () => void;
	onToggleShortcuts: () => void;
	onRunAccessibilityCheck: () => void;
}

/**
 * The Help ribbon tab.
 *
 * Lifted out of `Toolbar.tsx`'s inline JSX so the shell stays routing-only and
 * this tab can grow (it gained Settings, which angular/vanilla/svelte already
 * offered and react/vue did not) without pushing that file further past the
 * repo's ~300 LOC ceiling.
 */
export function HelpSection(p: HelpSectionProps): React.ReactElement {
	const { t } = useTranslation();
	return (
		<>
			<button
				type='button'
				onClick={p.onOpenSettings ?? p.onToggleShortcuts}
				className={pill}
				title={t('pptx.settings.title')}
			>
				{t('pptx.settings.title')}
			</button>
			<button
				type='button'
				onClick={p.onToggleShortcuts}
				className={pill}
				title={t('pptx.settings.keyboardShortcuts')}
			>
				{t('pptx.settings.keyboardShortcuts')}
			</button>
			<button
				type='button'
				onClick={p.onRunAccessibilityCheck}
				className={pill}
				title={t('pptx.ribbon.accessibilityCheck')}
			>
				{t('pptx.ribbon.accessibilityCheck')}
			</button>
		</>
	);
}
