// packages/vue/src/viewer/components/ribbon/ReviewSection.vue
<script setup lang="ts">
/**
 * ReviewSection: the Vue 3 port of React's `toolbar/ReviewSection.tsx`.
 *
 * Proofing (Spelling, Thesaurus), Accessibility, Language (Translate, Language),
 * Changes (Mark All Read, Compare), Comments (Comments, Delete, Previous, Next,
 * Show Comments) and Protect (Read Only, Restrict Permission, Hide Ink).
 *
 * Entries the reference renders inert pending a backing feature are rendered
 * inert here too rather than omitted: a tab that is merely shorter is the way
 * this binding drifts without any layout spec noticing.
 */
import {
	BookOpen,
	ChevronLeft,
	ChevronRight,
	Copy,
	EyeOff,
	GitCompare,
	Globe,
	Languages,
	LockKeyhole,
	MessageSquare,
	MessageSquarePlus,
	ShieldCheck,
	SpellCheck,
	Trash2,
} from 'lucide-vue-next';
import { useI18n } from 'vue-i18n';

import { cn } from '../../../utils';
import { ic, pill, SEP } from './ribbon-constants';

interface Props {
	canEdit: boolean;
	spellCheckEnabled: boolean;
	onSetSpellCheckEnabled: (enabled: boolean) => void;
	onToggleComments?: () => void;
	isCommentsPanelOpen?: boolean;
	slideCommentCount?: number;
	onCompare?: () => void;
	onOpenAccessibilityCheck?: () => void;
	onSetLanguage?: () => void;
}

const props = defineProps<Props>();

const { t } = useI18n();
</script>

<template>
	<!-- Proofing -->
	<button
		:class="cn(pill, props.spellCheckEnabled ? 'bg-primary hover:bg-primary/80 text-white' : '')"
		:title="t('pptx.review.toggleSpellCheck')"
		@click="props.onSetSpellCheckEnabled(!props.spellCheckEnabled)"
	>
		<SpellCheck :class="ic" />
		{{ t('pptx.review.spelling') }}
	</button>
	<button disabled :class="pill">
		<BookOpen :class="ic" />
		{{ t('pptx.review.thesaurus') }}
	</button>

	<div :class="SEP" />

	<!-- Accessibility -->
	<button
		v-if="props.onOpenAccessibilityCheck"
		:class="pill"
		:title="t('pptx.review.accessibilityCheckTooltip')"
		@click="props.onOpenAccessibilityCheck()"
	>
		<ShieldCheck :class="ic" />
		{{ t('pptx.review.accessibilityCheck') }}
	</button>

	<div :class="SEP" />

	<!-- Language -->
	<button disabled :class="pill">
		<Languages :class="ic" />
		{{ t('pptx.review.translate') }}
	</button>
	<button
		v-if="props.onSetLanguage"
		:class="pill"
		:title="t('pptx.review.languageTooltip')"
		@click="props.onSetLanguage()"
	>
		<Globe :class="ic" />
		{{ t('pptx.review.language') }}
	</button>

	<div :class="SEP" />

	<!-- Changes -->
	<button disabled :class="pill">
		<Copy :class="ic" />
		{{ t('pptx.review.markAllRead') }}
	</button>
	<button
		v-if="props.onCompare"
		:disabled="!props.canEdit"
		:class="pill"
		:title="t('pptx.ribbon.compareTitle')"
		@click="props.onCompare()"
	>
		<GitCompare :class="ic" />
		{{ t('pptx.ribbon.compare') }}
	</button>

	<div :class="SEP" />

	<!-- Comments -->
	<button
		v-if="props.onToggleComments"
		:class="cn(pill, props.isCommentsPanelOpen ? 'bg-primary hover:bg-primary/80 text-white' : '')"
		:title="t('pptx.review.toggleComments')"
		@click="props.onToggleComments()"
	>
		<MessageSquarePlus :class="ic" />
		{{ t('pptx.toolbar.comments') }}
		<span
			v-if="(props.slideCommentCount ?? 0) > 0"
			class="inline-flex items-center justify-center min-w-[16px] h-4 rounded-full bg-amber-500 text-[10px] font-medium text-white px-1"
		>
			{{ props.slideCommentCount }}
		</span>
	</button>
	<button disabled :class="pill">
		<Trash2 :class="ic" />
		{{ t('pptx.common.delete') }}
	</button>
	<button disabled :class="pill">
		<ChevronLeft :class="ic" />
		{{ t('pptx.common.previous') }}
	</button>
	<button disabled :class="pill">
		<ChevronRight :class="ic" />
		{{ t('pptx.common.next') }}
	</button>
	<button :class="pill" @click="props.onToggleComments?.()">
		<MessageSquare :class="ic" />
		{{ t('pptx.review.showComments') }}
	</button>

	<div :class="SEP" />

	<!-- Protect -->
	<button disabled :class="pill">
		<LockKeyhole :class="ic" />
		{{ t('pptx.review.readOnly') }}
	</button>
	<button disabled :class="pill">
		<ShieldCheck :class="ic" />
		{{ t('pptx.review.restrictPermission') }}
	</button>
	<button disabled :class="pill">
		<EyeOff :class="ic" />
		{{ t('pptx.review.hideInk') }}
	</button>
</template>

// packages/react/src/viewer/components/toolbar/ReviewSection.tsx
import React from 'react';
import { useTranslation } from 'react-i18next';
import {
	LuBookOpen,
	LuChevronLeft,
	LuChevronRight,
	LuCopy,
	LuEyeOff,
	LuGitCompare,
	LuGlobe,
	LuLanguages,
	LuLockKeyhole,
	LuMessageSquare,
	LuMessageSquarePlus,
	LuShieldCheck,
	LuSpellCheck,
	LuTrash2,
} from 'react-icons/lu';

import { RibbonCommand, RibbonCommandStack, RibbonGroup } from './PowerPointRibbonControls';

export interface ReviewSectionProps {
	canEdit: boolean;
	spellCheckEnabled: boolean;
	onSetSpellCheckEnabled: (enabled: boolean) => void;
	onToggleComments?: () => void;
	isCommentsPanelOpen?: boolean;
	slideCommentCount?: number;
	onCompare?: () => void;
	onOpenAccessibilityCheck?: () => void;
	onSetLanguage?: () => void;
}

export function ReviewSection(p: ReviewSectionProps): React.ReactElement {
	const { t } = useTranslation();
	return (
		<>
			<RibbonGroup label={t('pptx.review.proofing', { defaultValue: 'Proofing' })}>
				<RibbonCommand
					label={t('pptx.review.spelling')}
					icon={<LuSpellCheck />}
					onClick={() => p.onSetSpellCheckEnabled(!p.spellCheckEnabled)}
					active={p.spellCheckEnabled}
					title={t('pptx.review.toggleSpellCheck')}
				/>
				<RibbonCommand
					label={t('pptx.review.thesaurus', { defaultValue: 'Thesaurus' })}
					icon={<LuBookOpen />}
					disabled
				/>
			</RibbonGroup>
			<RibbonGroup label={t('pptx.review.accessibility', { defaultValue: 'Accessibility' })}>
				<RibbonCommand
					label={t('pptx.review.accessibilityCheck')}
					icon={<LuShieldCheck />}
					onClick={p.onOpenAccessibilityCheck}
				/>
			</RibbonGroup>
			<RibbonGroup label={t('pptx.review.language')}>
				<RibbonCommand
					label={t('pptx.review.translate', { defaultValue: 'Translate' })}
					icon={<LuLanguages />}
					disabled
				/>
				<RibbonCommand
					label={t('pptx.review.language')}
					icon={<LuGlobe />}
					onClick={p.onSetLanguage}
				/>
			</RibbonGroup>
			<RibbonGroup label={t('pptx.review.changes', { defaultValue: 'Changes' })}>
				<RibbonCommand
					label={t('pptx.review.markAllRead', { defaultValue: 'Mark All as Read' })}
					icon={<LuCopy />}
					disabled
				/>
				{p.onCompare && (
					<RibbonCommand
						label={t('pptx.ribbon.compare')}
						icon={<LuGitCompare />}
						onClick={p.onCompare}
						disabled={!p.canEdit}
						title={t('pptx.ribbon.compareTitle')}
					/>
				)}
			</RibbonGroup>
			<RibbonGroup label={t('pptx.toolbar.comments')}>
				{p.onToggleComments && (
					<div className='relative'>
						<RibbonCommand
							label={t('pptx.toolbar.comments')}
							icon={<LuMessageSquarePlus />}
							onClick={p.onToggleComments}
							active={p.isCommentsPanelOpen}
							title={t('pptx.review.toggleComments')}
						/>
						{Boolean(p.slideCommentCount) && (
							<span className='absolute right-0 top-0 rounded-full bg-primary px-1 text-[9px] text-white'>
								{p.slideCommentCount}
							</span>
						)}
					</div>
				)}
				<RibbonCommandStack>
					<RibbonCommand
						compact
						label={t('pptx.common.delete', { defaultValue: 'Delete' })}
						icon={<LuTrash2 />}
						disabled
					/>
					<RibbonCommand
						compact
						label={t('pptx.common.previous', { defaultValue: 'Previous' })}
						icon={<LuChevronLeft />}
						disabled
					/>
				</RibbonCommandStack>
				<RibbonCommandStack>
					<RibbonCommand
						compact
						label={t('pptx.common.next', { defaultValue: 'Next' })}
						icon={<LuChevronRight />}
						disabled
					/>
					<RibbonCommand
						compact
						label={t('pptx.review.showComments', { defaultValue: 'Show Comments' })}
						icon={<LuMessageSquare />}
						onClick={p.onToggleComments}
					/>
				</RibbonCommandStack>
			</RibbonGroup>
			<RibbonGroup label={t('pptx.review.protect', { defaultValue: 'Protect' })}>
				<RibbonCommand
					label={t('pptx.review.readOnly', { defaultValue: 'Always Open Read-only' })}
					icon={<LuLockKeyhole />}
					disabled
				/>
				<RibbonCommand
					label={t('pptx.review.restrictPermission', { defaultValue: 'Restrict Permission' })}
					icon={<LuShieldCheck />}
					disabled
				/>
				<RibbonCommand
					label={t('pptx.review.hideInk', { defaultValue: 'Hide Ink' })}
					icon={<LuEyeOff />}
					disabled
				/>
			</RibbonGroup>
		</>
	);
}
