// packages/vue/src/viewer/components/inspector/ChartDisplayOptions.vue
<script setup lang="ts">
import type { PptxChartData, PptxChartStyle } from 'pptx-viewer-core';
import {
	chartGridlinesPatch,
	chartGridlinesState,
	LEGEND_POSITION_OPTIONS,
} from 'pptx-viewer-shared';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

/**
 * ChartDisplayOptions: chart-level display toggles (title / legend visibility +
 * position / gridlines / data-labels master toggle). Mirrors React's
 * `ChartDisplayOptions`. Emits a shallow `PptxChartStyle` patch via `update`
 * for every field except gridlines.
 *
 * Gridlines is the one field that is NOT a `PptxChartStyle` round-trip: every
 * binding used to wire the checkbox straight to `style.hasGridlines`, a field
 * the renderer never actually reads (real gridline visibility comes from the
 * value axis's `c:majorGridlines`), so toggling the checkbox silently did
 * nothing. Shared's `chart-gridlines-toggle.ts` fixes this by reading/writing
 * the primary value axis instead (`style.hasGridlines` stays in sync as a
 * legacy mirror), which needs the full `PptxChartData`, not just `style` - so
 * this component takes `chartData` and emits gridline changes via the separate
 * `update-chart-data` event with a full `Partial<PptxChartData>` patch.
 */
const props = defineProps<{
	chartData: PptxChartData | undefined;
}>();

const emit = defineEmits<{
	update: [patch: Partial<PptxChartStyle>];
	'update-chart-data': [patch: Partial<PptxChartData>];
}>();

const { t } = useI18n();

const style = computed(() => props.chartData?.style);
const gridlinesOn = computed(() =>
	props.chartData ? chartGridlinesState(props.chartData) : (style.value?.hasGridlines ?? false),
);

function patch(p: Partial<PptxChartStyle>): void {
	emit('update', p);
}

function onCheckbox(event: Event, key: keyof PptxChartStyle): void {
	patch({ [key]: (event.target as HTMLInputElement).checked } as Partial<PptxChartStyle>);
}

function onLegendPosition(event: Event): void {
	patch({ legendPosition: (event.target as HTMLSelectElement).value });
}

function onGridlinesToggle(event: Event): void {
	if (!props.chartData) {
		return;
	}
	const checked = (event.target as HTMLInputElement).checked;
	emit('update-chart-data', chartGridlinesPatch(props.chartData, checked));
}
</script>

<template>
	<div class="pptx-vue-chart-card rounded border border-border bg-card p-2 space-y-2">
		<div class="pptx-vue-chart-heading text-[11px] uppercase tracking-wide text-muted-foreground">
			{{ t('pptx.chart.display') }}
		</div>
		<div class="space-y-1.5">
			<label class="flex items-center gap-2 cursor-pointer">
				<input
					type="checkbox"
					data-testid="chart-show-title"
					class="accent-primary"
					:checked="style?.hasTitle ?? false"
					@change="onCheckbox($event, 'hasTitle')"
				/>
				<span class="text-[11px]">{{ t('pptx.chart.showTitle') }}</span>
			</label>

			<label class="flex items-center gap-2 cursor-pointer">
				<input
					type="checkbox"
					data-testid="chart-show-legend"
					class="accent-primary"
					:checked="style?.hasLegend ?? false"
					@change="onCheckbox($event, 'hasLegend')"
				/>
				<span class="text-[11px]">{{ t('pptx.chart.showLegend') }}</span>
			</label>

			<label v-if="style?.hasLegend" class="flex items-center gap-2 text-[11px] ml-4">
				<span class="w-12 text-muted-foreground shrink-0">{{
					t('pptx.chart.legendPosition')
				}}</span>
				<select
					:aria-label="t('pptx.chart.legendPosition')"
					class="pptx-vue-chart-input flex-1 bg-muted border border-border rounded px-1.5 py-0.5 w-full"
					data-testid="chart-legend-position"
					:value="style?.legendPosition ?? 'b'"
					@change="onLegendPosition"
				>
					<option v-for="opt in LEGEND_POSITION_OPTIONS" :key="opt.value" :value="opt.value">
						{{ t(opt.labelKey) }}
					</option>
				</select>
			</label>

			<label class="flex items-center gap-2 cursor-pointer">
				<input
					type="checkbox"
					data-testid="chart-show-gridlines"
					class="accent-primary"
					:checked="gridlinesOn"
					@change="onGridlinesToggle"
				/>
				<span class="text-[11px]">{{ t('pptx.chart.showGridlines') }}</span>
			</label>

			<label class="flex items-center gap-2 cursor-pointer">
				<input
					type="checkbox"
					data-testid="chart-show-data-labels"
					class="accent-primary"
					:checked="style?.hasDataLabels ?? false"
					@change="onCheckbox($event, 'hasDataLabels')"
				/>
				<span class="text-[11px]">{{ t('pptx.chart.showDataLabels') }}</span>
			</label>
		</div>
	</div>
</template>

// packages/react/src/viewer/components/inspector/ChartDisplayOptions.tsx
import type { PptxChartStyle } from 'pptx-viewer-core';
import { useTranslation } from 'react-i18next';

import { CARD, HEADING, INPUT, LEGEND_POSITION_OPTIONS } from './chart-panel-constants';

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------
export interface ChartDisplayOptionsProps {
	style: PptxChartStyle | undefined;
	canEdit: boolean;
	onUpdateStyle: (patch: Partial<PptxChartStyle>) => void;
	/**
	 * Whether the chart currently shows major gridlines, per the shared
	 * `chartGridlinesState` (render/chart-gridlines-toggle.ts): the RENDERER
	 * draws gridlines from the primary value axis's `majorGridlines`, not from
	 * `style.hasGridlines`, so this must be read from the axis (via the shared
	 * helper), not from `style`, or the checkbox silently disagrees with the
	 * canvas.
	 */
	hasGridlines: boolean;
	/** Toggle major gridlines via the shared `chartGridlinesPatch`. */
	onToggleGridlines: (show: boolean) => void;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------
export function ChartDisplayOptions({
	style,
	canEdit,
	onUpdateStyle,
	hasGridlines,
	onToggleGridlines,
}: ChartDisplayOptionsProps) {
	const { t } = useTranslation();

	return (
		<div className={CARD}>
			<div className={HEADING}>{t('pptx.chart.display')}</div>
			<div className='space-y-1.5'>
				{/* Show title */}
				<label className='flex items-center gap-2 cursor-pointer'>
					<input
						type='checkbox'
						disabled={!canEdit}
						checked={style?.hasTitle ?? false}
						onChange={(e) => onUpdateStyle({ hasTitle: e.target.checked })}
						className='accent-primary'
					/>
					<span className='text-[11px]'>{t('pptx.chart.showTitle')}</span>
				</label>

				{/* Show legend */}
				<label className='flex items-center gap-2 cursor-pointer'>
					<input
						type='checkbox'
						disabled={!canEdit}
						checked={style?.hasLegend ?? false}
						onChange={(e) => onUpdateStyle({ hasLegend: e.target.checked })}
						className='accent-primary'
					/>
					<span className='text-[11px]'>{t('pptx.chart.showLegend')}</span>
				</label>

				{/* Legend position (only when legend visible) */}
				{style?.hasLegend && (
					<label className='flex items-center gap-2 text-[11px] ml-4'>
						<span className='w-12 text-muted-foreground shrink-0'>
							{t('pptx.chart.legendPosition')}
						</span>
						<select
							aria-label={t('pptx.chart.legendPosition')}
							disabled={!canEdit}
							className={INPUT}
							value={style.legendPosition ?? 'b'}
							onChange={(e) =>
								onUpdateStyle({
									legendPosition: e.target.value,
								})
							}
						>
							{LEGEND_POSITION_OPTIONS.map((opt) => (
								<option key={opt.value} value={opt.value}>
									{t(opt.labelKey)}
								</option>
							))}
						</select>
					</label>
				)}

				{/* Gridlines */}
				<label className='flex items-center gap-2 cursor-pointer'>
					<input
						type='checkbox'
						disabled={!canEdit}
						checked={hasGridlines}
						onChange={(e) => onToggleGridlines(e.target.checked)}
						className='accent-primary'
					/>
					<span className='text-[11px]'>{t('pptx.chart.showGridlines')}</span>
				</label>

				{/* Data labels */}
				<label className='flex items-center gap-2 cursor-pointer'>
					<input
						type='checkbox'
						disabled={!canEdit}
						checked={style?.hasDataLabels ?? false}
						onChange={(e) =>
							onUpdateStyle({
								hasDataLabels: e.target.checked,
							})
						}
						className='accent-primary'
					/>
					<span className='text-[11px]'>{t('pptx.chart.showDataLabels')}</span>
				</label>
			</div>
		</div>
	);
}
