// packages/vue/src/viewer/components/inspector/DebouncedColorInput.vue
<script setup lang="ts">
import { ref, watch } from 'vue';

import { injectRecentColors } from '../../composables/recent-colors-context';

/**
 * DebouncedColorInput: a native colour picker that commits live as the user
 * drags through the swatch, keeping the canvas in sync while a local mirror
 * keeps the control responsive. Vue equivalent of React's DebouncedColorInput;
 * undo grouping is handled downstream in the editor history.
 *
 * Every caller wraps the same native `<input type="color">`, so the
 * "Recent colours" push (wave-4 B6) is wired here once, on the native
 * `change` event (the committed value, never the continuous `input` stream),
 * instead of every one of this component's callers repeating it.
 */
const props = defineProps<{
	value: string;
	disabled?: boolean;
	ariaLabel?: string;
}>();

const emit = defineEmits<{
	commit: [hex: string];
}>();

/** Local mirror so the swatch stays responsive during a drag. */
const local = ref<string>(props.value);
const recentColors = injectRecentColors();

// Re-sync when the selected element (external value) changes.
watch(
	() => props.value,
	(next) => {
		local.value = next;
	},
);

function onInput(event: Event): void {
	const next = (event.target as HTMLInputElement).value;
	local.value = next;
	emit('commit', next);
}

function onChange(event: Event): void {
	recentColors?.push((event.target as HTMLInputElement).value);
}
</script>

<template>
	<input
		type="color"
		class="pptx-vue-color-input h-6 w-8 rounded border border-border bg-transparent cursor-pointer"
		:aria-label="ariaLabel ?? 'Color'"
		:disabled="disabled"
		:value="local"
		@input="onInput"
		@change="onChange"
	/>
</template>

// packages/react/src/viewer/components/inspector/DebouncedColorInput.tsx
import React, { useState, useEffect, useCallback, useRef } from 'react';

import { useRecentColors } from './RecentColorsContext';

// ---------------------------------------------------------------------------
// DebouncedColorInput
// ---------------------------------------------------------------------------
// A colour-picker that commits live as the user moves through the picker, so
// the canvas reflects fill / stroke / text-colour changes immediately. A local
// state mirror keeps the swatch responsive; undo grouping is handled downstream
// in useEditorHistory (snapshots are diffed and gated by pointer interaction),
// so live commits do not flood the undo stack.
// ---------------------------------------------------------------------------

interface DebouncedColorInputProps {
	value: string;
	disabled?: boolean;
	className?: string;
	/** Accessible label for the colour control (defaults to "Color"). */
	ariaLabel?: string;
	onCommit: (hex: string) => void;
}

export function DebouncedColorInput({
	value,
	disabled,
	className,
	ariaLabel,
	onCommit,
}: DebouncedColorInputProps): React.ReactElement {
	const [local, setLocal] = useState(value);
	const commitRef = useRef(onCommit);
	commitRef.current = onCommit;
	const { pushColor } = useRecentColors();

	// Sync external value when the selected element changes. Not pure derived
	// state: `local` is then mutated independently by every keystroke until the
	// next external change, which the "calculate during render" rewrite can't
	// express.
	useEffect(() => {
		// oxlint-disable-next-line react/no-deriving-state-in-effects -- see comment above
		setLocal(value);
	}, [value]);

	// Commit live on every change so the canvas updates immediately, while
	// mirroring the value locally to keep the picker swatch responsive.
	const handleChange = useCallback(
		(e: React.ChangeEvent<HTMLInputElement>) => {
			const next = e.target.value;
			setLocal(next);
			commitRef.current(next);
			pushColor(next);
		},
		[pushColor],
	);

	return (
		<input
			type='color'
			aria-label={ariaLabel ?? 'Color'}
			disabled={disabled}
			value={local}
			className={className}
			onChange={handleChange}
		/>
	);
}
