// packages/vue/src/viewer/components/inspector/ImageCropSection.vue
<script setup lang="ts">
import type { PptxElement } from 'pptx-viewer-core';
import { canInteractWithElement } from 'pptx-viewer-shared';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import {
	useCropSides,
	cropFractionToPercent,
	cropPercentToFraction,
} from '../../composables/useImageEditing';

/**
 * ImageCropSection: crop-inset sliders (left/top/right/bottom), a Reset Crop
 * action, and a "Replace Image" button. Crop fields are TOP-LEVEL element
 * fields (fractions 0..1), so patches are emitted as shallow element patches
 * (e.g. `{ cropLeft: 0.05 }`), not nested under `imageEffects`.
 *
 * Replace Image reads the chosen file as a data-URL and emits `{ imageData }`
 * so the swap happens entirely within the panel (no host wiring required).
 */
const props = defineProps<{
	element: PptxElement;
}>();

const emit = defineEmits<{
	update: [patch: Partial<PptxElement>];
}>();

const { t } = useI18n();

const sides = useCropSides();

// G7: `a:picLocks/@noCrop` forbids cropping this specific picture.
const croppable = computed(() => canInteractWithElement(props.element, 'crop'));

const cropPercents = computed<Record<string, number>>(() => {
	const el = props.element as unknown as Record<string, number | undefined>;
	const out: Record<string, number> = {};
	for (const side of sides) {
		out[side.key] = cropFractionToPercent(el[side.key]);
	}
	return out;
});

function onCrop(key: (typeof sides)[number]['key'], event: Event): void {
	if (!croppable.value) {
		return;
	}
	const percent = Number((event.target as HTMLInputElement).value);
	emit('update', { [key]: cropPercentToFraction(percent) } as Partial<PptxElement>);
}

function onResetCrop(): void {
	if (!croppable.value) {
		return;
	}
	emit('update', {
		cropLeft: 0,
		cropTop: 0,
		cropRight: 0,
		cropBottom: 0,
	} as Partial<PptxElement>);
}

function onReplaceImage(event: Event): void {
	const input = event.target as HTMLInputElement;
	const file = input.files?.[0];
	input.value = '';
	if (!file) {
		return;
	}
	const reader = new FileReader();
	reader.onload = () => {
		if (typeof reader.result === 'string') {
			emit('update', { imageData: reader.result } as Partial<PptxElement>);
		}
	};
	reader.readAsDataURL(file);
}
</script>

<template>
	<div class="pptx-vue-image-crop flex flex-col gap-2 text-[11px]">
		<label
			class="pptx-vue-image-crop__replace w-full text-center rounded border border-border bg-muted hover:bg-accent px-2 py-1 cursor-pointer transition-colors"
		>
			{{ t('pptx.image.replaceImage') }}
			<input
				type="file"
				class="hidden"
				accept="image/png,image/jpeg,image/gif,image/webp,image/svg+xml"
				@change="onReplaceImage"
			/>
		</label>

		<label
			v-for="side in sides"
			:key="side.key"
			class="pptx-vue-image-crop__slider grid grid-cols-[72px_1fr_36px] items-center gap-2"
		>
			<span class="text-muted-foreground">{{ side.label }}</span>
			<input
				type="range"
				class="w-full accent-primary"
				min="0"
				max="80"
				step="1"
				:disabled="!croppable"
				:value="cropPercents[side.key]"
				@input="onCrop(side.key, $event)"
			/>
			<span class="text-right tabular-nums text-muted-foreground"
				>{{ cropPercents[side.key] }}%</span
			>
		</label>

		<button
			type="button"
			class="pptx-vue-image-crop__reset w-full rounded border border-border bg-muted hover:bg-accent px-2 py-1 transition-colors"
			:disabled="!croppable"
			@click="onResetCrop"
		>
			{{ t('pptx.image.resetCrop') }}
		</button>
	</div>
</template>

// packages/react/src/viewer/components/inspector/ImageCropSection.tsx
/**
 * ImageCropSection: the four crop sliders (plus a reset) for a picture, shown
 * inside the live image-properties card.
 *
 * WHY it is here at all: cropping had no other entry point in React. The
 * component existed but was only reachable from the unreferenced
 * `ElementProperties`, so the viewer parsed and re-serialised `a:srcRect`
 * faithfully while offering no way to change it. Alt text and "replace image"
 * are deliberately NOT repeated here; `ImagePropertiesPanel` already owns the
 * former and there is no image-picker handler on the live path for the latter.
 */
import type { PptxElement } from 'pptx-viewer-core';
import { isImageLikeElement } from 'pptx-viewer-core';
import { canInteractWithElement } from 'pptx-viewer-shared';
import React from 'react';
import { useTranslation } from 'react-i18next';

import { clampCropValue } from '../../utils';
import { BTN_CLS } from './element-properties-constants';

/** OOXML stores each crop as a fraction of the source edge; the UI shows %. */
const CROP_SIDES = ['Left', 'Top', 'Right', 'Bottom'] as const;

/** PowerPoint's own sliders stop well before the image collapses to nothing. */
const MAX_CROP_PERCENT = 80;

interface ImageCropSectionProps {
	selectedElement: PptxElement;
	canEdit: boolean;
	onUpdateElement: (updates: Partial<PptxElement>) => void;
}

export function ImageCropSection({
	selectedElement,
	canEdit,
	onUpdateElement,
}: ImageCropSectionProps): React.ReactElement | null {
	const { t } = useTranslation();
	if (!isImageLikeElement(selectedElement)) {
		return null;
	}
	// G7: `a:picLocks/@noCrop` forbids cropping this specific picture, even on
	// an otherwise-editable deck.
	const croppable = canEdit && canInteractWithElement(selectedElement, 'crop');

	return (
		<div className='space-y-1.5' data-pptx-image-crop>
			{CROP_SIDES.map((side) => {
				const key = `crop${side}` as keyof PptxElement;
				return (
					<label key={side} className='flex flex-col gap-1 text-[11px]'>
						<span className='text-muted-foreground'>Crop {side}</span>
						<input
							type='range'
							min={0}
							max={MAX_CROP_PERCENT}
							disabled={!croppable}
							className='accent-primary'
							value={Math.round(clampCropValue(selectedElement[key] as number | undefined) * 100)}
							onChange={(e) =>
								onUpdateElement({
									[key]: Number(e.target.value) / 100,
								} as Partial<PptxElement>)
							}
						/>
					</label>
				);
			})}
			<button
				type='button'
				disabled={!croppable}
				className={`${BTN_CLS} w-full`}
				onClick={() =>
					onUpdateElement({
						cropLeft: 0,
						cropTop: 0,
						cropRight: 0,
						cropBottom: 0,
					} as Partial<PptxElement>)
				}
			>
				{t('pptx.image.resetCrop')}
			</button>
		</div>
	);
}
