// packages/vue/src/viewer/components/SlideSizeRescalePrompt.vue
<script setup lang="ts">
/**
 * SlideSizeRescalePrompt: PowerPoint's "Maximize / Ensure Fit" choice, shown
 * when a Design > Slide Size change would leave existing content mismatched
 * against the new canvas. The two decisions (what to show, what each choice
 * does to every slide's elements) both live in shared
 * (`slide-size-rescale.ts`); this component only renders the two buttons and
 * forwards the pick to `useInspectorDeckActions().chooseSlideSizeRescale`.
 */
import type { SlideSizeRescaleMode } from 'pptx-viewer-shared';
import { useI18n } from 'vue-i18n';

import ModalDialog from './ModalDialog.vue';

const props = defineProps<{
	open: boolean;
}>();

const emit = defineEmits<{
	choose: [mode: SlideSizeRescaleMode];
	close: [];
}>();

const { t } = useI18n();
</script>

<template>
	<ModalDialog
		:open="props.open"
		:title="t('pptx.slideSize.rescaleTitle')"
		marker-attr="data-pptx-slide-size-rescale"
		@close="emit('close')"
	>
		<p class="text-sm text-muted-foreground">{{ t('pptx.slideSize.rescaleDescription') }}</p>

		<template #footer>
			<button
				type="button"
				data-testid="pptx-slide-size-rescale-maximize"
				:title="t('pptx.slideSize.rescaleMaximizeHint')"
				class="inline-flex items-center gap-1.5 rounded-md border border-border bg-background px-4 py-2 text-sm font-medium text-foreground transition-colors hover:bg-accent"
				@click="emit('choose', 'maximize')"
			>
				{{ t('pptx.slideSize.rescaleMaximize') }}
			</button>
			<button
				type="button"
				data-testid="pptx-slide-size-rescale-ensure-fit"
				:title="t('pptx.slideSize.rescaleEnsureFitHint')"
				class="inline-flex items-center gap-1.5 rounded-md bg-primary px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-primary/90"
				@click="emit('choose', 'ensureFit')"
			>
				{{ t('pptx.slideSize.rescaleEnsureFit') }}
			</button>
		</template>
	</ModalDialog>
</template>

// packages/react/src/viewer/components/inspector/SlideSizeRescalePrompt.tsx
import type { SlideSizeRescaleMode } from 'pptx-viewer-shared';
import React from 'react';
import { useTranslation } from 'react-i18next';

/**
 * SlideSizeRescalePrompt: PowerPoint's Maximize/Ensure Fit choice, shown by
 * `SlideSizeCard` when a picked preset/orientation size differs from the
 * current one and the deck has content to rescale. Confirming either applies
 * the shared `scaleSlidesForSizeChange` transform (via the caller) together
 * with the size change.
 */
export interface SlideSizeRescalePromptProps {
	onChoose: (mode: SlideSizeRescaleMode) => void;
}

export function SlideSizeRescalePrompt({
	onChoose,
}: SlideSizeRescalePromptProps): React.ReactElement {
	const { t } = useTranslation();

	return (
		<div className='space-y-1.5 rounded border border-border bg-muted/40 p-2 text-[11px]'>
			<div className='font-medium'>{t('pptx.slideSize.rescaleTitle')}</div>
			<div className='text-muted-foreground'>{t('pptx.slideSize.rescaleDescription')}</div>
			<div className='grid grid-cols-2 gap-1.5 pt-1'>
				<button
					type='button'
					data-testid='pptx-slide-size-rescale-maximize'
					title={t('pptx.slideSize.rescaleMaximizeHint')}
					className='rounded bg-primary px-2 py-1 text-primary-foreground transition-colors hover:opacity-90'
					onClick={() => onChoose('maximize')}
				>
					{t('pptx.slideSize.rescaleMaximize')}
				</button>
				<button
					type='button'
					data-testid='pptx-slide-size-rescale-ensure-fit'
					title={t('pptx.slideSize.rescaleEnsureFitHint')}
					className='rounded bg-muted px-2 py-1 transition-colors hover:bg-accent'
					onClick={() => onChoose('ensureFit')}
				>
					{t('pptx.slideSize.rescaleEnsureFit')}
				</button>
			</div>
		</div>
	);
}
