// packages/vue/src/viewer/components/inspector/TableStyleEditor.vue
<script setup lang="ts">
import type { ParsedTableStyleMap } from 'pptx-viewer-core';
import {
	addTableStyleToMap,
	createTableStyleEntry,
	deleteTableStyleFromMap,
	normalizeTableStyleGuid,
} from 'pptx-viewer-core';
import type { TableStyleEditorFieldEdit, TableStyleEditorPartId } from 'pptx-viewer-shared';
import {
	applyTableStyleFieldEdit,
	describeTableStyleEditor,
	TABLE_STYLE_EDITOR_PARTS,
} from 'pptx-viewer-shared';
import { computed, ref, toRaw } from 'vue';
import { useI18n } from 'vue-i18n';

import { injectThemeColorMap } from '../../composables/theme-color-map-context';
import TableStyleEditorFields from './TableStyleEditorFields.vue';

/**
 * "Edit style..." panel for a table style's own DEFINITION (`a:tblStyleLst`
 * section fill/text/borders/cell3D), distinct from `TableStyleOptions.vue`'s
 * "which style does this table use" picker. Vue port of React's
 * `TableStyleEditor.tsx`.
 */
const props = defineProps<{
	styleMap: ParsedTableStyleMap | undefined;
	/** The style currently assigned to the table being edited. */
	styleId: string | undefined;
	canEdit: boolean;
}>();

const emit = defineEmits<{
	/** Commit a full replacement style map (section edit, create, or delete already applied). */
	styleMapChange: [nextMap: ParsedTableStyleMap];
	/** Record a styleId for save-time removal from `ppt/tableStyles.xml`. */
	deleteStyle: [styleId: string];
	/** A newly-created style, for a parent that wants to assign it to the table. */
	assignStyle: [styleId: string];
	close: [];
}>();

const { t } = useI18n();
const themeColorMap = injectThemeColorMap();

const activeStyleId = ref(props.styleId ? normalizeTableStyleGuid(props.styleId) : '');
const selectedPart = ref<TableStyleEditorPartId>('wholeTbl');

/**
 * `toRaw` on the (Vue-reactive) prop map: `createTableStyleEntry` deep-clones
 * `basedOn` with `structuredClone`, which throws on a Vue reactive Proxy
 * (`DataCloneError`). Reading through the raw map also returns raw, unproxied
 * entries, so every downstream core/shared call below gets plain objects.
 */
const rawStyleMap = computed(() => (props.styleMap ? toRaw(props.styleMap) : undefined));
const entry = computed(() =>
	activeStyleId.value ? rawStyleMap.value?.[activeStyleId.value] : undefined,
);
const descriptor = computed(() =>
	describeTableStyleEditor(entry.value, selectedPart.value, themeColorMap?.value),
);

function onFieldEdit(fieldEdit: TableStyleEditorFieldEdit): void {
	if (!entry.value || !rawStyleMap.value) {
		return;
	}
	const { entry: nextEntry } = applyTableStyleFieldEdit(entry.value, selectedPart.value, fieldEdit);
	emit('styleMapChange', { ...rawStyleMap.value, [nextEntry.styleId]: nextEntry });
}

function createFromCurrent(): void {
	const name = window.prompt(
		t('pptx.tableStyleEditor.newStyleNamePrompt'),
		entry.value ? `${entry.value.styleName ?? ''} Copy`.trim() : '',
	);
	if (!name) {
		return;
	}
	const nextMap: ParsedTableStyleMap = { ...(rawStyleMap.value ?? {}) };
	const created = createTableStyleEntry(nextMap, { styleName: name, basedOn: entry.value });
	addTableStyleToMap(nextMap, created);
	emit('styleMapChange', nextMap);
	activeStyleId.value = created.styleId;
	emit('assignStyle', created.styleId);
}

function handleDelete(): void {
	if (
		!entry.value ||
		!rawStyleMap.value ||
		!window.confirm(t('pptx.tableStyleEditor.deleteConfirm'))
	) {
		return;
	}
	const nextMap: ParsedTableStyleMap = { ...rawStyleMap.value };
	deleteTableStyleFromMap(nextMap, entry.value.styleId);
	emit('styleMapChange', nextMap);
	emit('deleteStyle', entry.value.styleId);
	emit('close');
}
</script>

<template>
	<div class="rounded border border-border bg-card p-2 space-y-2" data-testid="table-style-editor">
		<div class="flex items-center justify-between">
			<div class="text-[11px] uppercase tracking-wide text-muted-foreground">
				{{ t('pptx.tableStyleEditor.title') }}
			</div>
			<button
				type="button"
				class="rounded bg-muted hover:bg-accent px-2 py-1 text-[11px] transition-colors"
				@click="emit('close')"
			>
				{{ t('pptx.tableStyleEditor.close') }}
			</button>
		</div>

		<div v-if="!entry" class="text-[11px] text-muted-foreground">
			{{ t('pptx.tableStyleEditor.noStyleSelected') }}
		</div>

		<div v-if="entry" class="flex flex-wrap gap-1">
			<button
				v-for="part in TABLE_STYLE_EDITOR_PARTS"
				:key="part.id"
				type="button"
				:disabled="!canEdit"
				class="rounded px-2 py-1 text-[11px] transition-colors"
				:class="selectedPart === part.id ? 'bg-accent' : 'bg-muted hover:bg-accent'"
				@click="selectedPart = part.id"
			>
				{{ t(part.labelKey) }}
			</button>
		</div>

		<TableStyleEditorFields
			v-if="descriptor"
			:descriptor="descriptor"
			:can-edit="canEdit"
			@edit="onFieldEdit"
		/>

		<div class="flex gap-1.5 pt-1 border-t border-border">
			<button
				type="button"
				class="rounded bg-muted hover:bg-accent px-2 py-1 text-[11px] transition-colors"
				:disabled="!canEdit"
				@click="createFromCurrent"
			>
				{{
					entry ? t('pptx.tableStyleEditor.newFromCurrent') : t('pptx.tableStyleEditor.newStyle')
				}}
			</button>
			<button
				v-if="entry"
				type="button"
				class="rounded bg-muted hover:bg-accent px-2 py-1 text-[11px] transition-colors"
				:disabled="!canEdit"
				@click="handleDelete"
			>
				{{ t('pptx.tableStyleEditor.deleteStyle') }}
			</button>
		</div>
	</div>
</template>

// packages/react/src/viewer/components/inspector/TableStyleEditor.tsx
import type { ParsedTableStyleMap } from 'pptx-viewer-core';
import {
	addTableStyleToMap,
	createTableStyleEntry,
	deleteTableStyleFromMap,
	normalizeTableStyleGuid,
} from 'pptx-viewer-core';
import type { TableStyleEditorFieldEdit, TableStyleEditorPartId } from 'pptx-viewer-shared';
import {
	applyTableStyleFieldEdit,
	describeTableStyleEditor,
	TABLE_STYLE_EDITOR_PARTS,
} from 'pptx-viewer-shared';
import React, { useState } from 'react';
import { useTranslation } from 'react-i18next';

import { BTN, CARD, HEADING } from './inspector-pane-constants';
import { TableStyleEditorFields } from './TableStyleEditorFields';
import { useThemeColorMap } from './ThemeColorMapContext';

export interface TableStyleEditorProps {
	styleMap: ParsedTableStyleMap | undefined;
	/** The style currently assigned to the table being edited. */
	styleId: string | undefined;
	canEdit: boolean;
	/** Commit a full replacement style map (section edit, create, or delete already applied). */
	onStyleMapChange: (nextMap: ParsedTableStyleMap) => void;
	/** Record a styleId for save-time removal from `ppt/tableStyles.xml`. */
	onDeleteStyle: (styleId: string) => void;
	/** Optional: assign a newly-created style to the table being edited. */
	onAssignStyle?: (styleId: string) => void;
	onClose: () => void;
}

/**
 * "Edit style..." panel for a table style's own DEFINITION (`a:tblStyleLst`
 * section fill/text/borders/cell3D), distinct from `TablePropertiesPanel`'s
 * "which style does this table use" picker. Renders inline in the inspector
 * (mirrors `ThemeEditorPanel`), not a modal, so it can sit directly under the
 * button that opens it.
 */
export function TableStyleEditor({
	styleMap,
	styleId,
	canEdit,
	onStyleMapChange,
	onDeleteStyle,
	onAssignStyle,
	onClose,
}: TableStyleEditorProps): React.ReactElement {
	const { t } = useTranslation();
	const themeColorMap = useThemeColorMap();
	const [activeStyleId, setActiveStyleId] = useState(
		styleId ? normalizeTableStyleGuid(styleId) : '',
	);
	const [selectedPart, setSelectedPart] = useState<TableStyleEditorPartId>('wholeTbl');

	const entry = activeStyleId ? styleMap?.[activeStyleId] : undefined;
	const descriptor = describeTableStyleEditor(entry, selectedPart, themeColorMap);

	function edit(fieldEdit: TableStyleEditorFieldEdit): void {
		if (!entry || !styleMap) {
			return;
		}
		const { entry: nextEntry } = applyTableStyleFieldEdit(entry, selectedPart, fieldEdit);
		onStyleMapChange({ ...styleMap, [nextEntry.styleId]: nextEntry });
	}

	function createFromCurrent(): void {
		const name = window.prompt(
			t('pptx.tableStyleEditor.newStyleNamePrompt'),
			entry ? `${entry.styleName ?? ''} Copy`.trim() : '',
		);
		if (!name) {
			return;
		}
		const nextMap: ParsedTableStyleMap = { ...(styleMap ?? {}) };
		const created = createTableStyleEntry(nextMap, { styleName: name, basedOn: entry });
		addTableStyleToMap(nextMap, created);
		onStyleMapChange(nextMap);
		setActiveStyleId(created.styleId);
		onAssignStyle?.(created.styleId);
	}

	function handleDelete(): void {
		if (!entry || !styleMap || !window.confirm(t('pptx.tableStyleEditor.deleteConfirm'))) {
			return;
		}
		const nextMap: ParsedTableStyleMap = { ...styleMap };
		deleteTableStyleFromMap(nextMap, entry.styleId);
		onStyleMapChange(nextMap);
		onDeleteStyle(entry.styleId);
		onClose();
	}

	return (
		<div className={CARD} data-testid='table-style-editor'>
			<div className='flex items-center justify-between'>
				<div className={HEADING}>{t('pptx.tableStyleEditor.title')}</div>
				<button type='button' className={BTN} onClick={onClose}>
					{t('pptx.tableStyleEditor.close')}
				</button>
			</div>

			{!entry && (
				<div className='text-[11px] text-muted-foreground'>
					{t('pptx.tableStyleEditor.noStyleSelected')}
				</div>
			)}

			{entry && (
				<div className='flex flex-wrap gap-1'>
					{TABLE_STYLE_EDITOR_PARTS.map((part) => (
						<button
							key={part.id}
							type='button'
							disabled={!canEdit}
							className={`${BTN} ${selectedPart === part.id ? 'bg-accent' : ''}`}
							onClick={() => setSelectedPart(part.id)}
						>
							{t(part.labelKey)}
						</button>
					))}
				</div>
			)}

			{descriptor && (
				<TableStyleEditorFields descriptor={descriptor} canEdit={canEdit} onEdit={edit} />
			)}

			<div className='flex gap-1.5 pt-1 border-t border-border'>
				<button type='button' className={BTN} disabled={!canEdit} onClick={createFromCurrent}>
					{entry ? t('pptx.tableStyleEditor.newFromCurrent') : t('pptx.tableStyleEditor.newStyle')}
				</button>
				{entry && (
					<button type='button' className={BTN} disabled={!canEdit} onClick={handleDelete}>
						{t('pptx.tableStyleEditor.deleteStyle')}
					</button>
				)}
			</div>
		</div>
	);
}
