// packages/svelte/src/viewer/components/AutosaveRecoveryDialog.svelte
<script lang="ts">
	/**
	 * AutosaveRecoveryDialog: "Recover unsaved changes?" for a deck that has a
	 * crash-recovery snapshot in the shared IndexedDB store.
	 *
	 * Purely presentational, and deliberately dumb: every decision (whether a
	 * snapshot is worth offering, how old it is, which strings describe it) is
	 * already made by `pptx-viewer-shared`'s `autosaveRecoveryPrompt` and arrives
	 * here as the descriptor below, so all five bindings show the same dialog.
	 */
	import History from '@lucide/svelte/icons/history';
	import RotateCcw from '@lucide/svelte/icons/rotate-ccw';
	import Trash2 from '@lucide/svelte/icons/trash-2';
	import type { AutosaveRecoveryPrompt } from 'pptx-viewer-shared';

	import { useTranslator } from '../../i18n/context';

	const { prompt, onrestore, ondiscard }: { prompt: AutosaveRecoveryPrompt; onrestore: () => void; ondiscard: () => void } = $props();
	const t = useTranslator();
	const title = $derived(t(prompt.titleKey));
	const savedLabel = $derived(t('pptx.autosave.recovery.savedLabel', { when: t(prompt.ageKey, prompt.ageParams) }));
</script>
<div class="backdrop" data-pptx-autosave-recovery="true"><!-- svelte-ignore a11y_no_noninteractive_element_to_interactive_role --><section role="dialog" tabindex="-1" aria-modal="true" aria-label={title}><header><b><History size={20} aria-hidden="true" /></b><div><h2>{title}</h2><p>{t(prompt.messageKey, prompt.messageParams)}</p><small>{savedLabel}</small></div></header><footer><button type="button" onclick={ondiscard}><Trash2 size={16} aria-hidden="true" /> {t(prompt.discardKey)}</button><button class="primary" type="button" onclick={onrestore}><RotateCcw size={16} aria-hidden="true" /> {t(prompt.restoreKey)}</button></footer></section></div>
<style>
	.backdrop{position:fixed;inset:0;z-index:1250;display:grid;place-items:center;background:#0009}section{width:min(420px,calc(100vw - 32px));padding:22px;border:1px solid var(--pptx-border,#3f3f52);border-radius:12px;background:var(--pptx-card,#1e1e2e);box-shadow:0 24px 80px #0009}header{display:flex;gap:12px}header>b{display:grid;width:40px;height:40px;place-items:center;border-radius:50%;background:color-mix(in srgb,var(--pptx-primary,#c43b32) 18%,transparent);color:var(--pptx-primary,#c43b32)}h2,p{margin:0}h2{font-size:16px}p{margin-top:4px;color:var(--pptx-muted-foreground,#94a3b8);font-size:13px}small{display:block;margin-top:6px;color:var(--pptx-muted-foreground,#94a3b8);font-size:12px}footer{display:flex;justify-content:flex-end;gap:8px;margin-top:24px}button{display:inline-flex;align-items:center;gap:6px;border:1px solid var(--pptx-border,#3f3f52);border-radius:6px;padding:8px 12px;background:var(--pptx-muted,#2a2a3d);color:inherit}.primary{background:var(--pptx-primary,#c43b32);color:#fff}
</style>

// packages/react/src/viewer/components/AutosaveRecoveryDialog.tsx
/**
 * AutosaveRecoveryDialog: "we found unsaved changes for this deck, want them?"
 *
 * Pure presentation over the shared `AutosaveRecoveryPrompt` descriptor, so the
 * five bindings offer the same recovery with the same words. Every string is a
 * key chosen by `pptx-viewer-shared`; this component picks none of them.
 */
import type { AutosaveRecoveryPrompt } from 'pptx-viewer-shared';
import React from 'react';
import { useTranslation } from 'react-i18next';
import { LuHistory, LuTrash2 } from 'react-icons/lu';

export interface AutosaveRecoveryDialogProps {
	/** The descriptor to render, or null to render nothing. */
	prompt: AutosaveRecoveryPrompt | null;
	onRestore: () => void;
	onDiscard: () => void;
}

export function AutosaveRecoveryDialog({
	prompt,
	onRestore,
	onDiscard,
}: AutosaveRecoveryDialogProps): React.ReactElement | null {
	const { t } = useTranslation();

	if (!prompt) {
		return null;
	}

	const title = t(prompt.titleKey);
	const when = t(prompt.ageKey, prompt.ageParams);

	return (
		<div
			style={{ zIndex: 1200 }}
			className='fixed inset-0 flex items-center justify-center bg-black/50'
			data-pptx-autosave-recovery='true'
		>
			<div
				role='dialog'
				aria-modal='true'
				aria-label={title}
				className='bg-background border border-border rounded-lg shadow-xl w-[440px] max-w-[90vw] p-6'
			>
				<div className='flex items-center gap-3 mb-3'>
					<div className='flex items-center justify-center w-10 h-10 rounded-full bg-primary/10'>
						<LuHistory className='w-5 h-5 text-primary' />
					</div>
					<h2 className='text-base font-semibold text-foreground'>{title}</h2>
				</div>
				<p className='text-sm text-muted-foreground'>
					{t(prompt.messageKey, prompt.messageParams)}
				</p>
				<p className='text-xs text-muted-foreground mt-2'>
					{t('pptx.autosave.recovery.savedLabel', { when })}
				</p>
				<div className='flex justify-end gap-2 mt-6'>
					<button
						type='button'
						className='inline-flex items-center gap-1.5 px-4 py-2 text-sm font-medium rounded-md border border-border bg-background text-foreground hover:bg-accent transition-colors'
						onClick={onDiscard}
					>
						<LuTrash2 className='w-4 h-4' />
						{t(prompt.discardKey)}
					</button>
					<button
						type='button'
						className='inline-flex items-center gap-1.5 px-4 py-2 text-sm font-medium rounded-md bg-primary text-white hover:bg-primary/90 transition-colors'
						onClick={onRestore}
					>
						<LuHistory className='w-4 h-4' />
						{t(prompt.restoreKey)}
					</button>
				</div>
			</div>
		</div>
	);
}
