// packages/vue/src/viewer/components/EquationEditorDialog.vue
<script setup lang="ts">
import type { PptxElement, TextSegment, TextStyle } from 'pptx-viewer-core';
import {
	EQUATION_TEMPLATES,
	compileEquationTemplateMathMl,
	compileLatexEquation,
	convertOmmlToLatex,
} from 'pptx-viewer-shared';
import { computed, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';

import ModalDialog from './ModalDialog.vue';

/**
 * EquationEditorDialog: LaTeX input with a live MathML preview for inserting or
 * editing an OMML equation.
 *
 * Vue port of the React `EquationEditorDialog.tsx`. The user types LaTeX (or
 * picks a template); shared's `compileLatexEquation` turns it into OMML plus
 * sanitised MathML (the same path `EquationRenderer` uses) for the live
 * preview, which is why the `v-html` bindings below are safe. On confirm it
 * emits both:
 *
 *  - `insert(element)`: a ready-to-add core {@link PptxElement} (a shape
 *    carrying the equation as a `textSegments[].equationXml` OMML tree, so
 *    `SmartArtRenderer`/`EquationRenderer` render it directly). Route to
 *    `ops.addElement`.
 *  - `apply(segment)`: the equation {@link TextSegment} alone, for updating an
 *    existing equation in place. Route to `ops.updateText` / a segment patch.
 *
 * When `existingOmml` is supplied the dialog opens in edit mode, seeding the
 * textarea from the reverse `convertOmmlToLatex`.
 */
const props = defineProps<{
	/** Whether the dialog is open. */
	open: boolean;
	/** When editing an existing equation, its OMML; otherwise null/undefined. */
	existingOmml?: Record<string, unknown> | null;
}>();

const emit = defineEmits<{
	/** Emitted with a ready-to-add equation element. */
	(e: 'insert', element: PptxElement): void;
	/** Emitted with the equation segment alone (for in-place updates). */
	(e: 'apply', segment: TextSegment): void;
	/** Emitted when the dialog should close without inserting. */
	(e: 'close'): void;
}>();

const { t } = useI18n();

/**
 * Pre-built equation templates (LaTeX + i18n label key), shared across every
 * binding's equation dialog.
 */
const TEMPLATES = EQUATION_TEMPLATES;

/** Pre-computed MathML for each template tile (sanitised by shared). */
const templateMathMl = computed(() => compileEquationTemplateMathMl());

const latex = ref('');

const isEditing = computed(() => Boolean(props.existingOmml));

/** Derive initial LaTeX from existing OMML (edit mode). */
function initialLatex(): string {
	if (!props.existingOmml) {
		return '';
	}
	try {
		return convertOmmlToLatex(props.existingOmml);
	} catch {
		return '';
	}
}

/** Re-seed the form whenever the dialog opens. */
watch(
	[() => props.open, () => props.existingOmml],
	([isOpen]) => {
		if (isOpen) {
			latex.value = initialLatex();
		}
	},
	{ immediate: true },
);

/** Live LaTeX -> OMML -> sanitised MathML for the preview + the segment payload. */
const computedEquation = computed(() => compileLatexEquation(latex.value));

/** True when there is renderable equation content to insert. */
const hasContent = computed(
	() => latex.value.trim().length > 0 && Object.keys(computedEquation.value.omml).length > 0,
);

function selectTemplate(tmplLatex: string): void {
	latex.value = tmplLatex;
}

/** Build the equation {@link TextSegment} from the current OMML. */
function buildSegment(omml: Record<string, unknown>): TextSegment {
	return {
		text: '[Equation]',
		style: { fontSize: 18, fontFamily: 'Cambria Math' } as TextStyle,
		equationXml: omml,
	};
}

/** Best-effort unique id, mirroring the core element-factory style. */
function newId(prefix: string): string {
	if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
		return `${prefix}-${crypto.randomUUID()}`;
	}
	return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
}

/**
 * Build a renderable equation element. Mirrors the React `handleInsertEquation`:
 * a shape carrying `[Equation]` text plus the equation segment.
 */
function buildEquationElement(segment: TextSegment): PptxElement {
	return {
		id: newId('shp'),
		type: 'shape',
		x: 120,
		y: 200,
		width: 400,
		height: 80,
		text: '[Equation]',
		textStyle: { fontSize: 18, fontFamily: 'Cambria Math' } as TextStyle,
		textSegments: [segment],
	} as PptxElement;
}

function confirm(): void {
	if (!hasContent.value) {
		return;
	}
	const segment = buildSegment(computedEquation.value.omml);
	// Edit mode updates the existing equation's segment in place (`apply`);
	// insert mode adds a brand-new element (`insert`). Emitting only the one
	// that matches the mode keeps the parent from both patching AND inserting.
	if (isEditing.value) {
		emit('apply', segment);
	} else {
		emit('insert', buildEquationElement(segment));
	}
	emit('close');
}

function close(): void {
	emit('close');
}

function onTextareaKeydown(event: KeyboardEvent): void {
	if (event.key === 'Enter' && (event.metaKey || event.ctrlKey)) {
		event.preventDefault();
		confirm();
	}
}
</script>

<template>
	<ModalDialog
		:open="open"
		:title="isEditing ? t('pptx.equation.editTitle') : t('pptx.equation.insertTitle')"
		@close="close"
	>
		<div class="pptx-vue-equation-editor flex w-[min(82vw,600px)] flex-col gap-3.5">
			<!-- Live preview -->
			<div
				class="pptx-vue-equation-preview flex min-h-[80px] items-center justify-center rounded-md border border-border bg-muted/60 p-3"
			>
				<div
					v-if="hasContent"
					class="pptx-vue-equation-preview-math text-2xl text-foreground"
					v-html="computedEquation.mathml"
				/>
				<span
					v-else
					class="pptx-vue-equation-preview-empty text-[13px] italic text-muted-foreground"
				>
					{{ t('pptx.equation.previewPlaceholder') }}
				</span>
			</div>

			<!-- LaTeX input -->
			<label class="pptx-vue-equation-field flex flex-col gap-1">
				<span class="pptx-vue-equation-label text-xs font-medium text-muted-foreground">{{
					t('pptx.equation.latexInput')
				}}</span>
				<textarea
					v-model="latex"
					class="pptx-vue-equation-textarea w-full resize-y rounded border border-border bg-background px-2.5 py-2 font-mono text-[13px] text-foreground outline-none focus:border-primary focus:ring-1 focus:ring-primary"
					rows="3"
					spellcheck="false"
					placeholder="\frac{a}{b} + \sqrt{c}"
					@keydown="onTextareaKeydown"
				/>
				<span class="pptx-vue-equation-hint text-[11px] text-muted-foreground">{{
					t('pptx.equation.latexHint')
				}}</span>
			</label>

			<!-- Templates -->
			<div class="pptx-vue-equation-templates-wrap flex flex-col gap-1.5">
				<span class="pptx-vue-equation-label text-xs font-medium text-muted-foreground">{{
					t('pptx.equation.templates')
				}}</span>
				<div class="pptx-vue-equation-templates grid grid-cols-4 gap-1.5">
					<button
						v-for="(tmpl, idx) in TEMPLATES"
						:key="tmpl.latex"
						type="button"
						class="pptx-vue-equation-template flex flex-col items-center gap-1 rounded-md border p-2 transition-colors"
						:class="
							latex === tmpl.latex
								? 'pptx-vue-equation-template--active border-primary bg-primary/10'
								: 'border-border bg-muted/40 hover:bg-accent/60'
						"
						:title="t(tmpl.i18nKey)"
						@click="selectTemplate(tmpl.latex)"
					>
						<span
							class="pptx-vue-equation-template-math flex h-7 items-center justify-center overflow-hidden text-foreground"
							v-html="templateMathMl[idx]"
						/>
						<span
							class="pptx-vue-equation-template-label w-full truncate text-center text-[10px] text-muted-foreground"
							>{{ t(tmpl.i18nKey) }}</span
						>
					</button>
				</div>
			</div>
		</div>

		<template #footer>
			<button
				type="button"
				class="pptx-vue-equation-btn pptx-vue-equation-btn--secondary rounded border border-border px-3 py-1.5 text-xs text-foreground transition-colors hover:bg-muted"
				@click="close"
			>
				{{ t('pptx.equation.cancel') }}
			</button>
			<button
				type="button"
				class="pptx-vue-equation-btn pptx-vue-equation-btn--primary rounded border border-transparent bg-primary px-3 py-1.5 text-xs font-medium text-primary-foreground transition-colors hover:bg-primary/80 disabled:cursor-not-allowed disabled:opacity-45"
				:disabled="!hasContent"
				@click="confirm"
			>
				{{ isEditing ? t('pptx.equation.update') : t('pptx.equation.insert') }}
			</button>
		</template>
	</ModalDialog>
</template>

<style scoped>
/* Math glyph font: not expressible as a Tailwind utility. Matches React's
   inline `fontFamily: '"Cambria Math", "STIX Two Math", serif'`. */
.pptx-vue-equation-preview-math,
.pptx-vue-equation-template-math {
	font-family: 'Cambria Math', 'STIX Two Math', serif;
}
</style>

// packages/react/src/viewer/components/EquationEditorDialog.tsx
import {
	compileEquationTemplateMathMl,
	compileLatexEquation,
	EQUATION_TEMPLATES,
	sanitizeMathMl,
} from 'pptx-viewer-shared';
import React, { useState, useMemo, useCallback, useRef, useEffect, useDeferredValue } from 'react';
import { useTranslation } from 'react-i18next';
import { LuX } from 'react-icons/lu';

import { useModalDismissDrag } from '../hooks';
import { useModalFocus } from '../hooks/useModalFocus';
import { cn } from '../utils';
import { convertLatexToOmml, convertOmmlToLatex } from '../utils/latex-to-omml';

// ── Equation templates ────────────────────────────────────────────────────

/**
 * Pre-defined equation templates covering common mathematical formulas
 * (shared across every binding's equation dialog).
 */
const TEMPLATES = EQUATION_TEMPLATES;

/** Pre-computed MathML strings for each template (computed once at module load). */
const TEMPLATE_MATHML: string[] = compileEquationTemplateMathMl();

// ── MathML preview renderer ──────────────────────────────────────────────

/**
 * Renders a MathML string into the DOM via `innerHTML`.
 *
 * Uses a ref-based approach because React cannot render MathML natively.
 * The container is updated whenever the `mathml` prop changes.
 *
 * Sanitises again on the way in even though the shared `compileLatexEquation`
 * pipeline already did: this is the component's `innerHTML` sink and it accepts
 * any caller's string, so the guarantee belongs at the sink too. DOMPurify is
 * idempotent, so the second pass is a no-op for already-clean markup.
 *
 * @param props.mathml - The MathML markup string to render.
 */
function MathMlPreview({ mathml }: { mathml: string }) {
	const containerRef = useRef<HTMLDivElement>(null);

	useEffect(() => {
		if (!containerRef.current) {
			return;
		}
		if (mathml) {
			containerRef.current.innerHTML = sanitizeMathMl(mathml);
		} else {
			containerRef.current.innerHTML = '';
		}
	}, [mathml]);

	return (
		<div
			ref={containerRef}
			className='flex items-center justify-center min-h-[80px] text-2xl text-foreground'
			style={{ fontFamily: '"Cambria Math", "STIX Two Math", serif' }}
		/>
	);
}

// ── Dialog ───────────────────────────────────────────────────────────────

/**
 * Props for the {@link EquationEditorDialog} component.
 */
export interface EquationEditorDialogProps {
	isOpen: boolean;
	onClose: () => void;
	/** Called with the OMML object to insert/update on the slide. */
	onInsert: (omml: Record<string, unknown>) => void;
	/** When editing an existing equation, provide its OMML here. */
	existingOmml?: Record<string, unknown> | null;
}

/**
 * Modal dialog for inserting or editing LaTeX-based equations.
 *
 * The dialog provides:
 * - A live MathML preview rendered from the LaTeX input.
 * - A textarea for entering / editing LaTeX source.
 * - A grid of clickable equation templates.
 * - Keyboard shortcut support (Ctrl+Enter to insert, Escape to close).
 *
 * Internally converts LaTeX to OMML (Office Math Markup Language) and
 * then to MathML for the live preview. The final OMML object is passed
 * to the parent via `onInsert`.
 *
 * @param props - {@link EquationEditorDialogProps}
 * @returns The dialog element, or `null` when `isOpen` is `false`.
 */
export function EquationEditorDialog({
	isOpen,
	onClose,
	onInsert,
	existingOmml,
}: EquationEditorDialogProps): React.ReactElement | null {
	const { t } = useTranslation();
	const { panelStyle, handlers: dragHandlers } = useModalDismissDrag(onClose);

	// Derive initial LaTeX from existing OMML if provided
	const initialLatex = useMemo(() => {
		if (!existingOmml) {
			return '';
		}
		return convertOmmlToLatex(existingOmml);
	}, [existingOmml]);

	const [latex, setLatex] = useState(initialLatex);
	// Defer the latex value used for the (relatively expensive) MathML compute
	// path so rapid keystrokes stay responsive.
	const deferredLatex = useDeferredValue(latex);
	const textareaRef = useRef<HTMLTextAreaElement>(null);
	const dialogRef = useRef<HTMLDivElement>(null);
	useModalFocus(isOpen, dialogRef, onClose, textareaRef);

	// Reset latex when the dialog opens with new OMML
	useEffect(() => {
		if (isOpen) {
			setLatex(initialLatex);
		}
	}, [isOpen, initialLatex]);

	// Convert LaTeX -> OMML -> sanitised MathML for live preview (shared pipeline).
	const { mathml, omml } = useMemo(() => compileLatexEquation(deferredLatex), [deferredLatex]);

	const handleInsert = useCallback(() => {
		if (!latex.trim()) {
			return;
		}
		// Recompute from the current `latex` value rather than the deferred `omml`
		// to avoid inserting stale OMML when the user types and clicks quickly.
		let insertOmml = omml;
		try {
			const fresh = convertLatexToOmml(latex);
			if (fresh && Object.keys(fresh).length > 0) {
				insertOmml = fresh;
			}
		} catch {
			// fall back to deferred omml
		}
		onInsert(insertOmml);
		onClose();
	}, [latex, omml, onInsert, onClose]);

	const handleTemplateClick = useCallback((templateLatex: string) => {
		setLatex(templateLatex);
	}, []);

	const handleKeyDown = useCallback(
		(e: React.KeyboardEvent) => {
			if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) {
				e.preventDefault();
				handleInsert();
			}
			if (e.key === 'Escape') {
				e.preventDefault();
				onClose();
			}
		},
		[handleInsert, onClose],
	);

	if (!isOpen) {
		return null;
	}

	const isEditing = Boolean(existingOmml);
	const hasContent = latex.trim().length > 0 && Object.keys(omml).length > 0;

	return (
		<div
			className='fixed inset-0 z-[9999] flex items-center justify-center bg-black/60 backdrop-blur-sm'
			onClick={(e) => {
				if (e.target === e.currentTarget) {
					onClose();
				}
			}}
			onKeyDown={handleKeyDown}
		>
			{/* eslint-disable-next-line jsx-a11y/no-noninteractive-element-interactions -- stopPropagation only, so a click inside the panel doesn't bubble to the backdrop's close handler or the canvas's click-outside deselect logic; the panel has no interactive semantics of its own */}
			<div
				ref={dialogRef}
				style={panelStyle}
				className='bg-background border border-border rounded-xl shadow-2xl w-[640px] max-h-[85vh] flex flex-col overflow-hidden max-md:fixed max-md:inset-x-0 max-md:bottom-0 max-md:top-auto max-md:w-full max-md:max-h-[88dvh] max-md:rounded-t-2xl max-md:rounded-b-none max-md:border-x-0 max-md:border-b-0 max-md:pb-[max(env(safe-area-inset-bottom),0px)]'
				onClick={(e) => e.stopPropagation()}
				role='dialog'
				aria-modal='true'
				tabIndex={-1}
				aria-label={
					isEditing
						? t('pptx.equation.editTitle', 'Edit Equation')
						: t('pptx.equation.insertTitle', 'Insert Equation')
				}
			>
				{/* Header — also a swipe-down-to-dismiss grab region on touch. */}
				<div
					{...dragHandlers}
					className='flex items-center justify-between px-5 py-3 border-b border-border touch-none'
				>
					<h2 className='text-sm font-semibold text-foreground'>
						{isEditing
							? t('pptx.equation.editTitle', 'Edit Equation')
							: t('pptx.equation.insertTitle', 'Insert Equation')}
					</h2>
					<button
						type='button'
						onClick={onClose}
						className='p-1 rounded hover:bg-accent text-muted-foreground hover:text-foreground transition-colors'
						aria-label={t('pptx.settings.close')}
					>
						<LuX className='w-4 h-4' />
					</button>
				</div>

				{/* Body */}
				<div className='flex-1 overflow-y-auto px-5 py-4 space-y-4'>
					{/* Live preview */}
					<div className='rounded-lg border border-border bg-muted/60 p-4 min-h-[80px] flex items-center justify-center'>
						{hasContent ? (
							<MathMlPreview mathml={mathml} />
						) : (
							<span className='text-sm text-muted-foreground italic'>
								{t('pptx.equation.previewPlaceholder', 'Equation preview will appear here')}
							</span>
						)}
					</div>

					{/* LaTeX input */}
					<div>
						<label className='block text-xs font-medium text-muted-foreground mb-1.5'>
							{t('pptx.equation.latexInput', 'LaTeX Input')}
						</label>
						<textarea
							ref={textareaRef}
							value={latex}
							onChange={(e) => setLatex(e.target.value)}
							placeholder='\\frac{a}{b} + \\sqrt{c}'
							className='w-full h-24 px-3 py-2 rounded-lg border border-border bg-muted text-foreground text-sm font-mono resize-none focus:outline-none focus:ring-2 focus:ring-primary/50 focus:border-primary placeholder:text-muted-foreground'
							spellCheck={false}
						/>
						<p className='mt-1 text-[11px] text-muted-foreground'>
							{t('pptx.equation.latexHint', 'Use LaTeX syntax. Ctrl+Enter to insert.')}
						</p>
					</div>

					{/* Templates */}
					<div>
						<h3 className='text-xs font-medium text-muted-foreground mb-2'>
							{t('pptx.equation.templates', 'Common Templates')}
						</h3>
						<div className='grid grid-cols-4 gap-1.5'>
							{TEMPLATES.map((tmpl, idx) => {
								const tmplMathml = TEMPLATE_MATHML[idx];
								return (
									<button
										key={tmpl.latex}
										type='button'
										onClick={() => handleTemplateClick(tmpl.latex)}
										className={cn(
											'flex flex-col items-center gap-1 p-2 rounded-lg border transition-colors',
											latex === tmpl.latex
												? 'border-primary bg-primary/10'
												: 'border-border bg-muted/40 hover:bg-accent/60 hover:border-border',
										)}
										title={t(tmpl.i18nKey, tmpl.label)}
									>
										<div
											className='text-sm text-foreground h-8 flex items-center justify-center overflow-hidden'
											style={{
												fontFamily: '"Cambria Math", "STIX Two Math", serif',
											}}
											dangerouslySetInnerHTML={{ __html: tmplMathml }}
										/>
										<span className='text-[10px] text-muted-foreground truncate w-full text-center'>
											{t(tmpl.i18nKey, tmpl.label)}
										</span>
									</button>
								);
							})}
						</div>
					</div>
				</div>

				{/* Footer */}
				<div className='flex items-center justify-end gap-2 px-5 py-3 border-t border-border'>
					<button
						type='button'
						onClick={onClose}
						className='px-4 py-1.5 rounded-lg text-xs text-foreground hover:bg-accent transition-colors'
					>
						{t('pptx.equation.cancel', 'Cancel')}
					</button>
					<button
						type='button'
						onClick={handleInsert}
						disabled={!hasContent}
						className='px-4 py-1.5 rounded-lg text-xs font-medium bg-primary hover:bg-primary/80 text-white disabled:opacity-40 disabled:cursor-not-allowed transition-colors'
					>
						{isEditing ? t('pptx.equation.update', 'Update') : t('pptx.equation.insert', 'Insert')}
					</button>
				</div>
			</div>
		</div>
	);
}
