// packages/vue/src/viewer/components/PresenterView.vue
<script setup lang="ts">
import { ChevronLeft, ChevronRight, Minus, Plus, X } from 'lucide-vue-next';
import type { PptxSlide } from 'pptx-viewer-core';
import {
	createInitialPresentationSnapshot,
	presenterPaneAdvancesOnClick,
	stepPresenterZoom,
} from 'pptx-viewer-shared';
import type { PresentationPointerTool, PresentationSnapshot } from 'pptx-viewer-shared';
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';
import { useI18n } from 'vue-i18n';

import {
	clampNotesFontSize,
	formatElapsed,
	formatTime,
	notesSegmentsToSpans,
	NOTES_FONT_SIZE_DEFAULT,
	NOTES_FONT_SIZE_MAX,
	NOTES_FONT_SIZE_MIN,
	NOTES_FONT_SIZE_STEP,
} from '../composables/presenter-view-utils';
import type { CanvasSize } from '../types';
import PresenterControlStrip from './PresenterControlStrip.vue';
import PresenterSlideGrid from './PresenterSlideGrid.vue';
import SlideStage from './SlideStage.vue';

/**
 * PresenterView - split-screen presenter layout: current slide (left, 70%) plus
 * a control rail (right, 30%) with the wall-clock time, elapsed timer, prev/next
 * navigation, a next-slide preview, scalable speaker notes, and a 5-minute
 * timer progress bar. Vue port of the React `PresenterView`.
 *
 * Rendered as an absolute overlay by the host (`PresentationMode`). Keyboard
 * navigation is owned by the host; this component only emits navigation /
 * exit intents.
 */
const props = withDefaults(
	defineProps<{
		slides: PptxSlide[];
		currentSlideIndex: number;
		canvasSize: CanvasSize;
		mediaDataUrls: Map<string, string>;
		/** Timestamp (ms) the presentation started, or `null`. */
		presentationStartTime: number | null;
		audienceOpen?: boolean;
		snapshot?: PresentationSnapshot;
	}>(),
	{
		snapshot: () => createInitialPresentationSnapshot(),
	},
);

const emit = defineEmits<{
	(e: 'move', direction: 1 | -1): void;
	(e: 'exit' | 'open-audience' | 'close-audience'): void;
	(e: 'navigate', index: number): void;
	(e: 'update-snapshot', patch: Partial<PresentationSnapshot>): void;
}>();

const { t } = useI18n();
const showSlides = ref(false);

/**
 * Clicking the current-slide pane advances the show, the way PowerPoint's
 * presenter console does: it is how presenters actually drive a deck, with the
 * Next button and the keyboard as fallbacks. A drawing tool owns the pointer
 * instead, so clicking then annotates rather than jumping the deck.
 */
const paneAdvancesOnClick = computed(() =>
	presenterPaneAdvancesOnClick(props.snapshot?.pointer?.tool),
);
function onSlidePaneClick(): void {
	if (paneAdvancesOnClick.value) {
		emit('move', 1);
	}
}
function update(patch: Partial<PresentationSnapshot>): void {
	emit('update-snapshot', patch);
}
function setTool(tool: PresentationPointerTool): void {
	update({
		pointer: { ...(props.snapshot.pointer ?? { x: 0.5, y: 0.5, color: '#ef4444' }), tool },
	});
}
function zoom(direction: -1 | 1): void {
	update({
		zoom: stepPresenterZoom(
			props.snapshot.zoom ?? { scale: 1, originX: 0.5, originY: 0.5 },
			direction,
		),
	});
}

// -- Live clock -------------------------------------------------------------
const now = ref(Date.now());
let clockId: ReturnType<typeof setInterval> | null = null;

onMounted(() => {
	clockId = setInterval(() => {
		now.value = Date.now();
	}, 1000);
});

onBeforeUnmount(() => {
	if (clockId !== null) {
		clearInterval(clockId);
		clockId = null;
	}
});

const elapsed = computed(() =>
	props.presentationStartTime ? now.value - props.presentationStartTime : 0,
);

const clockText = computed(() => formatTime(new Date(now.value)));
const elapsedText = computed(() => formatElapsed(elapsed.value));

// -- Timer progress (5-minute segments) ------------------------------------
const TIMER_SEGMENT_MS = 5 * 60 * 1000;
const timerProgress = computed(() =>
	Math.min(100, ((elapsed.value % TIMER_SEGMENT_MS) / TIMER_SEGMENT_MS) * 100),
);
const timerSegment = computed(() => Math.floor(elapsed.value / TIMER_SEGMENT_MS));

// -- Notes font size --------------------------------------------------------
const notesFontSize = ref(NOTES_FONT_SIZE_DEFAULT);

function increaseNotesFontSize(): void {
	notesFontSize.value = clampNotesFontSize(notesFontSize.value + NOTES_FONT_SIZE_STEP);
}

function decreaseNotesFontSize(): void {
	notesFontSize.value = clampNotesFontSize(notesFontSize.value - NOTES_FONT_SIZE_STEP);
}

function toggleAudience(): void {
	if (props.audienceOpen) {
		emit('close-audience');
	} else {
		emit('open-audience');
	}
}

// -- Slide data -------------------------------------------------------------
const currentSlide = computed<PptxSlide | undefined>(() => props.slides[props.currentSlideIndex]);
const nextSlide = computed<PptxSlide | undefined>(() =>
	props.slides.slice(props.currentSlideIndex + 1).find((slide) => !slide.hidden),
);

const notesText = computed(() => currentSlide.value?.notes ?? '');
const notesSpans = computed(() => {
	const segments = currentSlide.value?.notesSegments;
	return segments && segments.length > 0 ? notesSegmentsToSpans(segments) : null;
});
const hasPlainNotes = computed(() => notesText.value.trim().length > 0);

const atFirst = computed(() => props.currentSlideIndex === 0);
const atLast = computed(() => props.currentSlideIndex >= props.slides.length - 1);

// -- Preview scaling (fit into a ~260px-wide rail panel) --------------------
const PREVIEW_WIDTH = 240;
const previewScale = computed(() =>
	props.canvasSize.width > 0 ? PREVIEW_WIDTH / props.canvasSize.width : 1,
);
const previewFrameStyle = computed(() => ({
	width: `${props.canvasSize.width * previewScale.value}px`,
	height: `${props.canvasSize.height * previewScale.value}px`,
}));

// -- Main-stage scaling: fit the slide into a notional area; the flex layout
// (70% width) plus overflow clipping handles the rest.
const MAIN_FIT_WIDTH = 760;
const MAIN_FIT_HEIGHT = 460;
const mainScale = computed(() => {
	const { width, height } = props.canvasSize;
	if (width <= 0 || height <= 0) {
		return 1;
	}
	return Math.min(MAIN_FIT_WIDTH / width, MAIN_FIT_HEIGHT / height);
});
const previewMainFrameStyle = computed(() => ({
	width: `${props.canvasSize.width * mainScale.value}px`,
	height: `${props.canvasSize.height * mainScale.value}px`,
	transform: `scale(${props.snapshot.zoom?.scale ?? 1})`,
	transformOrigin: `${(props.snapshot.zoom?.originX ?? 0.5) * 100}% ${(props.snapshot.zoom?.originY ?? 0.5) * 100}%`,
}));
</script>

<template>
	<div
		v-if="!currentSlide"
		class="pptx-vue-presenter pptx-vue-presenter--empty absolute inset-0 z-50 flex items-center justify-center bg-card text-muted-foreground"
	>
		<PresenterControlStrip
			:snapshot="snapshot"
			:audience-open="Boolean(audienceOpen)"
			@timer="update({ paused: !snapshot.paused })"
			@reset-timer="update({ paused: false, elapsedMs: 0 })"
			@slides="showSlides = true"
			@zoom="zoom"
			@reset-zoom="update({ zoom: { scale: 1, originX: 0.5, originY: 0.5 } })"
			@blackout="(value) => update({ blackout: value })"
			@tool="setTool"
			@subtitles="update({ subtitlesVisible: !snapshot.subtitlesVisible })"
			@audience="toggleAudience"
			@exit="emit('exit')"
		/>
		{{ t('pptx.mpresenter.noSlides') }}
	</div>
	<div
		v-else
		class="pptx-vue-presenter absolute inset-0 z-50 flex flex-col bg-card text-foreground"
	>
		<div class="pptx-vue-presenter-body flex flex-1 min-h-0">
			<!-- Left: current slide -->
			<div
				role="presentation"
				data-pptx-presenter-slide
				class="pptx-vue-presenter-main flex flex-[7] min-w-0 flex-col items-center justify-center overflow-hidden bg-black p-6"
				:class="{ 'cursor-pointer': paneAdvancesOnClick }"
				@click="onSlidePaneClick"
			>
				<div
					class="pptx-vue-presenter-stage relative overflow-hidden"
					:style="previewMainFrameStyle"
				>
					<SlideStage
						:slide="currentSlide"
						:canvas-size="canvasSize"
						:media-data-urls="mediaDataUrls"
						:scale="mainScale"
					/>
				</div>
				<div
					class="pptx-vue-presenter-slide-label mt-3 select-none font-mono text-xs tabular-nums text-white/50"
				>
					{{
						t('pptx.statusBar.slideOf', { current: currentSlideIndex + 1, total: slides.length })
					}}
				</div>
			</div>

			<!-- Right: controls -->
			<div
				class="pptx-vue-presenter-rail flex flex-[3] min-w-[260px] max-w-[440px] flex-col border-l border-border bg-background"
			>
				<!-- Header: clock + elapsed + exit -->
				<div
					class="pptx-vue-presenter-header flex items-center justify-between gap-2 border-b border-border/60 px-4 py-3"
				>
					<div class="pptx-vue-presenter-time flex flex-col">
						<span
							class="pptx-vue-presenter-label text-[10px] uppercase tracking-wider text-muted-foreground"
							>{{ t('pptx.presenterView.currentTime') }}</span
						>
						<span class="pptx-vue-presenter-clock font-mono text-lg tabular-nums text-foreground">{{
							clockText
						}}</span>
					</div>
					<div
						class="pptx-vue-presenter-time pptx-vue-presenter-time--right flex flex-col items-end"
					>
						<span
							class="pptx-vue-presenter-label text-[10px] uppercase tracking-wider text-muted-foreground"
							>{{ t('pptx.mpresenter.elapsed') }}</span
						>
						<span class="pptx-vue-presenter-elapsed font-mono text-lg tabular-nums text-primary">{{
							elapsedText
						}}</span>
					</div>
					<div class="flex items-center gap-1">
						<button
							type="button"
							class="pptx-vue-presenter-audience-btn flex h-7 items-center justify-center rounded px-2 text-xs text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
							:title="
								audienceOpen
									? t('pptx.presenter.closeAudienceWindow')
									: t('pptx.presenter.openAudienceWindow')
							"
							@click="toggleAudience"
						>
							{{ audienceOpen ? 'Disconnect display' : 'Audience display' }}
						</button>
						<button
							type="button"
							class="pptx-vue-presenter-icon-btn flex h-7 w-7 items-center justify-center rounded text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
							:title="t('pptx.presenter.endPresentation')"
							:aria-label="t('pptx.presenter.endPresentation')"
							@click="emit('exit')"
						>
							<X class="h-4 w-4" aria-hidden="true" />
						</button>
					</div>
				</div>

				<!-- Navigation -->
				<div
					class="pptx-vue-presenter-nav flex items-center justify-between border-b border-border/60 px-4 py-2"
				>
					<button
						type="button"
						class="pptx-vue-presenter-nav-btn inline-flex items-center gap-1.5 rounded bg-muted px-3 py-1.5 text-xs transition-colors hover:bg-accent disabled:cursor-not-allowed disabled:opacity-40"
						:disabled="atFirst"
						:title="t('pptx.mobileBar.previousSlide')"
						@click="emit('move', -1)"
					>
						<ChevronLeft class="h-4 w-4" aria-hidden="true" />
						{{ t('pptx.mpresenter.prev') }}
					</button>
					<span class="pptx-vue-presenter-counter font-mono text-sm tabular-nums text-foreground">
						{{ currentSlideIndex + 1 }} / {{ slides.length }}
					</span>
					<button
						type="button"
						class="pptx-vue-presenter-nav-btn inline-flex items-center gap-1.5 rounded bg-muted px-3 py-1.5 text-xs transition-colors hover:bg-accent disabled:cursor-not-allowed disabled:opacity-40"
						:disabled="atLast"
						:title="t('pptx.mobileBar.nextSlide')"
						@click="emit('move', 1)"
					>
						{{ t('pptx.mpresenter.next') }}
						<ChevronRight class="h-4 w-4" aria-hidden="true" />
					</button>
				</div>

				<!-- Next slide preview -->
				<div class="pptx-vue-presenter-section border-b border-border/60 px-4 py-3">
					<div
						class="pptx-vue-presenter-label mb-2 text-[10px] uppercase tracking-wider text-muted-foreground"
					>
						{{ t('pptx.mobileBar.nextSlide') }}
					</div>
					<div
						v-if="nextSlide"
						class="pptx-vue-presenter-preview-frame relative mt-2 overflow-hidden rounded border border-border/30"
						:style="previewFrameStyle"
					>
						<SlideStage
							:slide="nextSlide"
							:canvas-size="canvasSize"
							:media-data-urls="mediaDataUrls"
							:scale="previewScale"
						/>
					</div>
					<div
						v-else
						class="pptx-vue-presenter-preview-empty mt-2 flex h-16 items-center justify-center rounded border border-border/30 bg-muted/40 text-xs italic text-muted-foreground"
					>
						{{ t('pptx.mpresenter.endOfPresentation') }}
					</div>
				</div>

				<!-- Speaker notes -->
				<div class="pptx-vue-presenter-notes-section flex flex-1 min-h-0 flex-col px-4 py-3">
					<div class="pptx-vue-presenter-notes-head mb-2 flex items-center justify-between">
						<div
							class="pptx-vue-presenter-label text-[10px] uppercase tracking-wider text-muted-foreground"
						>
							{{ t('pptx.presenter.speakerNotes') }}
						</div>
						<div class="pptx-vue-presenter-font-ctl flex items-center gap-1">
							<button
								type="button"
								class="pptx-vue-presenter-font-btn rounded p-0.5 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground disabled:cursor-not-allowed disabled:opacity-30"
								:disabled="notesFontSize <= NOTES_FONT_SIZE_MIN"
								:title="t('pptx.presenterView.decreaseFontSize')"
								:aria-label="t('pptx.presenterView.decreaseFontSize')"
								@click="decreaseNotesFontSize"
							>
								<Minus class="h-3.5 w-3.5" aria-hidden="true" />
							</button>
							<span
								class="pptx-vue-presenter-font-val min-w-[28px] select-none text-center font-mono text-[10px] tabular-nums text-muted-foreground"
								>{{ notesFontSize }}px</span
							>
							<button
								type="button"
								class="pptx-vue-presenter-font-btn rounded p-0.5 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground disabled:cursor-not-allowed disabled:opacity-30"
								:disabled="notesFontSize >= NOTES_FONT_SIZE_MAX"
								:title="t('pptx.presenterView.increaseFontSize')"
								:aria-label="t('pptx.presenterView.increaseFontSize')"
								@click="increaseNotesFontSize"
							>
								<Plus class="h-3.5 w-3.5" aria-hidden="true" />
							</button>
						</div>
					</div>
					<div
						class="pptx-vue-presenter-notes flex-1 overflow-y-auto whitespace-pre-wrap rounded border border-border/30 bg-muted/40 px-3 py-2 leading-relaxed text-foreground"
						:style="{ fontSize: `${notesFontSize}px` }"
					>
						<template v-if="notesSpans">
							<template v-for="span in notesSpans" :key="span.key">
								<br v-if="span.kind === 'break'" />
								<span v-else :style="span.style">{{ span.text }}</span>
							</template>
						</template>
						<template v-else-if="hasPlainNotes">{{ notesText }}</template>
						<span v-else class="pptx-vue-presenter-notes-empty italic text-muted-foreground">{{
							t('pptx.mpresenter.noNotes')
						}}</span>
					</div>
				</div>
			</div>
		</div>
		<PresenterSlideGrid
			v-if="showSlides"
			:slides="slides"
			:current="currentSlideIndex"
			:canvas-size="canvasSize"
			:media-data-urls="mediaDataUrls"
			@select="
				(index) => {
					emit('navigate', index);
					showSlides = false;
				}
			"
			@close="showSlides = false"
		/>

		<!-- Timer progress bar -->
		<div
			class="pptx-vue-presenter-progress h-1.5 w-full flex-shrink-0 bg-muted/60"
			role="progressbar"
			:aria-valuenow="Math.round(timerProgress)"
			:aria-valuemin="0"
			:aria-valuemax="100"
			:aria-label="t('pptx.presenterView.timerProgress')"
			:title="
				t('pptx.presenterView.timerTitle', { elapsed: elapsedText, segment: timerSegment + 1 })
			"
		>
			<div
				class="pptx-vue-presenter-progress-fill h-full bg-primary transition-[width] duration-1000 ease-linear"
				:style="{ width: `${timerProgress}%` }"
			/>
		</div>
	</div>
</template>

// packages/react/src/viewer/components/PresenterView.tsx
import type { PptxElement, PptxSlide } from 'pptx-viewer-core';
import type { PresentationPointerTool, PresentationSnapshot } from 'pptx-viewer-shared';
/**
 * PresenterView: Split-screen presenter layout with current slide,
 * next slide preview, speaker notes, timer, and navigation controls.
 *
 * Rendered as an absolute overlay when presenterMode is active during
 * presentation mode. Uses ScaledSlidePreview for slide rendering.
 *
 * Supports opening an audience window via `window.open()` for dual-screen
 * presenter workflows. The audience window receives slide changes via
 * `postMessage()` cross-window communication.
 *
 * Keyboard navigation (arrows, space, escape) is handled by the parent
 * `usePresentationKeyboard` hook; this component does NOT register its
 * own keydown listener to avoid double-handling.
 */
import React, { useCallback, useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';

import type { SlideAdvanceTrigger } from '../hooks/presentation-mode/types';
import type { CanvasSize } from '../types';
import { PresenterSlideFrame } from './presentation/PresenterSlideFrame';
import { PresentationAudienceEffects } from './PresentationAudienceEffects';
import { PresentationEndOverlay } from './PresentationEndOverlay';
import { PresentationSubtitleBar } from './PresentationSubtitleBar';
import { formatElapsed, presenterPaneAdvancesOnClick } from './presenter-view-utils';
import { PresenterConsoleToolbar } from './PresenterConsoleToolbar';
import { PresenterNotesRail } from './PresenterNotesRail';
import { PresenterSlideNavigator } from './PresenterSlideNavigator';
import { ScaledSlidePreview } from './ScaledSlidePreview';
import { usePresenterInk } from './usePresenterInk';

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

export interface PresenterViewProps {
	slides: PptxSlide[];
	currentSlideIndex: number;
	canvasSize: CanvasSize;
	templateElements: PptxElement[];
	presentationStartTime: number | null;
	/**
	 * `trigger` mirrors the show stage: `'click'` steps through pending element
	 * builds first and honours the slide's `advanceOnClick` transition flag,
	 * `'explicit'` (the default) is unconditional navigation.
	 */
	onMovePresentationSlide: (direction: 1 | -1, trigger?: SlideAdvanceTrigger) => void;
	onExit: () => void;
	/** Open the audience display in a separate browser window. */
	onOpenAudienceWindow?: () => boolean;
	/** Close the audience display window. */
	onCloseAudienceWindow?: () => void;
	/** Whether the audience window is currently open. */
	isAudienceWindowOpen?: boolean;
	/**
	 * True once the show has run past its last slide and the black "End of slide
	 * show" screen is up. The console MUST surface it: while it is up the next
	 * input is swallowed (backward) or ends the show (forward), so a console that
	 * kept painting the last slide looked stuck and then dumped the presenter
	 * into the editor with no warning.
	 */
	endOfShowVisible?: boolean;
	snapshot: PresentationSnapshot;
	onNavigateToSlide: (index: number) => void;
	onToggleTimer: () => void;
	onResetTimer: () => void;
	onStepZoom: (direction: 1 | -1) => void;
	onResetZoom: () => void;
	onSetBlackout: (value: PresentationSnapshot['blackout']) => void;
	onUpdateSnapshot: (patch: Partial<PresentationSnapshot>) => void;
	onToggleSubtitles: () => void;
	onSwapDisplays: () => void;
	onUpdateNotes?: (notes: string) => void;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function PresenterView({
	slides,
	currentSlideIndex,
	canvasSize,
	templateElements,
	presentationStartTime,
	onMovePresentationSlide,
	onExit,
	onOpenAudienceWindow,
	onCloseAudienceWindow,
	isAudienceWindowOpen,
	endOfShowVisible,
	snapshot,
	onNavigateToSlide,
	onToggleTimer,
	onResetTimer,
	onStepZoom,
	onResetZoom,
	onSetBlackout,
	onUpdateSnapshot,
	onToggleSubtitles,
	onSwapDisplays,
	onUpdateNotes,
}: PresenterViewProps): React.ReactElement {
	const { t } = useTranslation();

	// -- Clock + elapsed timer -----------------------------------------------
	const [now, setNow] = useState(Date.now());

	useEffect(() => {
		const interval = window.setInterval(() => setNow(Date.now()), 1000);
		return () => window.clearInterval(interval);
	}, []);

	const elapsed = snapshot.elapsedMs ?? (presentationStartTime ? now - presentationStartTime : 0);

	const [showSlides, setShowSlides] = useState(false);
	const ink = usePresenterInk(snapshot, onUpdateSnapshot);

	// Click the current-slide pane to advance, the way PowerPoint's presenter
	// console does - it is how presenters actually drive a show, and without it
	// the console could only be advanced from the keyboard or the Next button.
	// The end-of-show screen owns the pane's click (it exits the show), so the
	// advance handler stands down while it is up.
	const paneAdvancesOnClick =
		presenterPaneAdvancesOnClick(snapshot.pointer?.tool) && !endOfShowVisible;
	const handleSlidePaneClick = useCallback(() => {
		if (!paneAdvancesOnClick) {
			return;
		}
		onMovePresentationSlide(1, 'click');
	}, [paneAdvancesOnClick, onMovePresentationSlide]);
	const handleCaptionChange = useCallback(
		(caption: string) => onUpdateSnapshot({ caption }),
		[onUpdateSnapshot],
	);

	// -- Slide data ----------------------------------------------------------
	const currentSlide = slides[currentSlideIndex];

	if (!currentSlide) {
		return (
			<div className='absolute inset-0 z-50 flex items-center justify-center bg-card text-muted-foreground'>
				{t('pptx.presenter.noSlides')}
			</div>
		);
	}

	// -- Timer progress (5-minute segments) ------------------------------------
	const TIMER_SEGMENT_MS = 5 * 60 * 1000; // 5 minutes per bar fill
	const timerProgress = Math.min(100, ((elapsed % TIMER_SEGMENT_MS) / TIMER_SEGMENT_MS) * 100);
	const timerSegment = Math.floor(elapsed / TIMER_SEGMENT_MS);

	return (
		<div className='absolute inset-0 z-50 flex flex-col bg-card text-foreground'>
			<PresenterConsoleToolbar
				snapshot={snapshot}
				audienceOpen={Boolean(isAudienceWindowOpen)}
				onToggleAudience={() =>
					isAudienceWindowOpen ? onCloseAudienceWindow?.() : onOpenAudienceWindow?.()
				}
				onSwapDisplays={onSwapDisplays}
				onToggleTimer={onToggleTimer}
				onResetTimer={onResetTimer}
				onShowSlides={() => setShowSlides(true)}
				onStepZoom={onStepZoom}
				onResetZoom={onResetZoom}
				onBlackout={onSetBlackout}
				onPointerTool={(tool: PresentationPointerTool) =>
					onUpdateSnapshot({
						pointer: { ...(snapshot.pointer ?? { x: 0.5, y: 0.5, color: '#ef4444' }), tool },
					})
				}
				onToggleSubtitles={onToggleSubtitles}
				onExit={onExit}
			/>
			<div className='flex flex-1 min-h-0'>
				{/* Left panel -- current slide (70%). Clicking it advances the show. */}
				<div
					role='presentation'
					data-pptx-presenter-slide
					onClick={handleSlidePaneClick}
					className={`relative flex-[7] flex flex-col items-center justify-center bg-black p-6 min-w-0 overflow-hidden ${
						paneAdvancesOnClick ? 'cursor-pointer' : ''
					}`}
				>
					{/* The show has run past its last slide. The console has to say so:
					    while this is up the next input either goes nowhere (backward) or
					    ends the show (forward), and a console still painting the last
					    slide made that look like the deck was stuck, then dumped the
					    presenter into the editor with no warning. */}
					{endOfShowVisible && <PresentationEndOverlay onExit={() => onMovePresentationSlide(1)} />}
					<PresenterSlideFrame
						canvasSize={canvasSize}
						zoomScale={snapshot.zoom?.scale ?? 1}
						zoomOriginX={snapshot.zoom?.originX ?? 0.5}
						zoomOriginY={snapshot.zoom?.originY ?? 0.5}
						inkProps={ink}
					>
						<ScaledSlidePreview
							slide={currentSlide}
							templateElements={templateElements}
							canvasSize={canvasSize}
						/>
						<PresentationAudienceEffects snapshot={snapshot} />
					</PresenterSlideFrame>
					{/* Slide number badge */}
					<div className='mt-3 text-xs font-mono tabular-nums text-white/50 select-none'>
						{t('pptx.presenter.slideLabel', {
							current: currentSlideIndex + 1,
							total: slides.length,
							defaultValue: `Slide ${currentSlideIndex + 1} of ${slides.length}`,
						})}
					</div>
				</div>

				<PresenterNotesRail
					slides={slides}
					current={currentSlideIndex}
					canvasSize={canvasSize}
					templateElements={templateElements}
					now={now}
					elapsed={elapsed}
					onMove={onMovePresentationSlide}
					onUpdateNotes={onUpdateNotes}
				/>
			</div>
			<PresentationSubtitleBar
				visible={Boolean(snapshot.subtitlesVisible)}
				onCaptionChange={handleCaptionChange}
			/>
			{showSlides && (
				<PresenterSlideNavigator
					slides={slides}
					current={currentSlideIndex}
					canvasSize={canvasSize}
					templateElements={templateElements}
					onSelect={(index) => {
						onNavigateToSlide(index);
						setShowSlides(false);
					}}
					onClose={() => setShowSlides(false)}
				/>
			)}

			{/* Timer progress bar */}
			<div
				className='h-1.5 w-full bg-muted/60 flex-shrink-0'
				role='progressbar'
				aria-valuenow={Math.round(timerProgress)}
				aria-valuemin={0}
				aria-valuemax={100}
				aria-label={t('pptx.presenter.timerProgress')}
				title={`${formatElapsed(elapsed)} (segment ${timerSegment + 1})`}
			>
				<div
					className='h-full bg-primary transition-[width] duration-1000 ease-linear'
					style={{ width: `${timerProgress}%` }}
				/>
			</div>
		</div>
	);
}
