// packages/angular/src/viewer/presentation-transition-overlay.component.ts
import { NgStyle } from '@angular/common';
import {
	ChangeDetectionStrategy,
	Component,
	DestroyRef,
	computed,
	effect,
	inject,
	input,
	output,
} from '@angular/core';
import type { PptxElement, PptxSlide, PptxSlideTransition } from 'pptx-viewer-core';

import type { CanvasSize, MorphTransitionPlan } from '../internal/shared';
import {
	buildMorphScopedCss,
	buildMorphTransitionPlan,
	MORPH_CROSSFADE_GROUP_STYLE,
	MORPH_CROSSFADE_HALF_BLEND_MODE,
	morphOptionToMode,
} from '../internal/shared';
import type { StyleMap } from './element-style';
import { SlideCanvasComponent } from './slide-canvas.component';
import {
	getSlideTransitionAnimations,
	resolveOverlayDurationMs,
	transitionSlideBoxSize,
} from './transition-helpers';
import type { SlideTransitionAnimations } from './transition-helpers';
import { ensureTransitionKeyframes } from './transition-keyframes';

/** Safety margin (ms) added to the animation duration before firing complete. */
const COMPLETE_MARGIN_MS = 50;

/**
 * The slide the incoming (arriving) layer paints for a CLASSIC transition, or
 * `undefined` when no such layer may exist.
 *
 * Without this layer the overlay painted only the outgoing slide: a wipe
 * (whose outgoing half is `none`) sat opaque for the whole duration and the
 * arriving slide - only ever the live stage beneath - popped in the instant
 * the overlay tore down ("takes the time, then instantly replaced"). Types
 * whose incoming half is `none` (the uncover family) deliberately reveal the
 * live stage and get no layer, and a morph paints its own halves.
 *
 * Exported and pure so it can be unit-tested: this package renders no component
 * under test (see `action-settings-panel.component.test.ts`).
 */
export function classicIncomingLayerSlide(
	isMorph: boolean,
	incomingAnimation: string,
	incomingSlide: PptxSlide | undefined,
	templateElements: readonly PptxElement[],
): PptxSlide | undefined {
	if (isMorph || incomingAnimation === 'none' || !incomingSlide) {
		return undefined;
	}
	if (templateElements.length === 0) {
		return incomingSlide;
	}
	return { ...incomingSlide, elements: [...templateElements, ...incomingSlide.elements] };
}

/**
 * The slide the overlay paints ABOVE its ghosts, or `undefined` when a morph
 * has nothing to lift.
 *
 * A shape arriving inside a shape that persists is drawn on the live stage,
 * UNDER this overlay, so the persisting shape's opaque ghost hides it for the
 * whole transition (issue #146). `buildMorphTransitionPlan` names those few and
 * holds their stage copy invisible; this wraps them as a slide the component's
 * own `pptx-slide-canvas` can render.
 *
 * Exported and pure so it can be unit-tested: this package renders no component
 * under test (see `action-settings-panel.component.test.ts`).
 */
export function morphLiftedSlide(
	plan: MorphTransitionPlan | undefined,
	incomingSlide: PptxSlide | undefined,
): PptxSlide | undefined {
	if (!plan || !incomingSlide || plan.overlayIncomingElements.length === 0) {
		return undefined;
	}
	return { ...incomingSlide, elements: [...plan.overlayIncomingElements] };
}

/** One cross-dissolving pair, as the two single-element slides that paint it. */
export interface MorphCrossfadeGroupSlides {
	key: string;
	style: StyleMap;
	/**
	 * The departing half's layer style, carrying the dissolve itself.
	 *
	 * A pair dissolving in place never moves, and an animation on the small
	 * element box gives it a compositing layer whose raster snaps to whole device
	 * pixels - the wording is then painted a fraction of a pixel off the live
	 * stage and twitches as the overlay comes and goes (issue #161).
	 */
	outgoingStyle: StyleMap;
	/** The arriving half's layer style. @see MorphCrossfadeGroupSlides.outgoingStyle */
	incomingStyle: StyleMap;
	outgoing: PptxSlide;
	incoming: PptxSlide;
}

/**
 * The pairs the overlay paints BOTH halves of, as one isolated group each.
 *
 * Stacking the halves composites them source-over, which leaves the ink they
 * share at 0.75 of full strength halfway through instead of summing it, biting
 * chunks out of glyphs that cross during a text dissolve. PowerPoint's own
 * render holds the two blend coefficients at a sum of 1.0 for every frame
 * (issue #161), which `isolation: isolate` plus `mix-blend-mode: plus-lighter`
 * on the two halves reproduces.
 *
 * Exported and pure so it can be unit-tested: this package renders no component
 * under test (see `action-settings-panel.component.test.ts`).
 */
export function morphCrossfadeGroupSlides(
	plan: MorphTransitionPlan | undefined,
	outgoingSlide: PptxSlide | undefined,
	incomingSlide: PptxSlide | undefined,
): MorphCrossfadeGroupSlides[] {
	if (!plan || !outgoingSlide || !incomingSlide) {
		return [];
	}
	const half = (animation: string | undefined): StyleMap => ({
		'mix-blend-mode': MORPH_CROSSFADE_HALF_BLEND_MODE,
		...(animation === undefined ? {} : { animation }),
	});
	return plan.crossfadeGroups.map((group, index) => ({
		key: group.incoming.id,
		style: {
			...MORPH_CROSSFADE_GROUP_STYLE,
			// `isolation` makes the group a stacking context, so it carries a
			// z-index of its own to stay above the ghost layer (40) and the lifted
			// layer (41) its halves came from.
			'z-index': String(42 + index),
		},
		outgoingStyle: half(group.outgoingAnimation),
		incomingStyle: half(group.incomingAnimation),
		outgoing: { ...outgoingSlide, elements: [group.outgoing] },
		incoming: { ...incomingSlide, elements: [group.incoming] },
	}));
}

/**
 * PresentationTransitionOverlayComponent: plays a PowerPoint slide transition
 * over the presentation stage.
 *
 * Renders the *outgoing* (previous) slide as an absolutely-positioned layer
 * with the resolved CSS exit animation; the *incoming* slide is rendered by the
 * underlying stage (the existing `pptx-presentation-overlay`). The `outgoingOnTop`
 * descriptor controls whether the outgoing layer sits above or below the stage,
 * letting cover/uncover/push read correctly. Fires `complete` once the animation
 * finishes so the orchestrator can tear the overlay down.
 *
 * Selector: `pptx-presentation-transition-overlay`
 *
 * Inputs:
 *   - `outgoingSlide`    (required): the leaving slide to animate
 *   - `canvasSize`       (required): logical slide dimensions (px)
 *   - `transition`       (required): the transition definition (from the slide)
 *   - `templateElements`: master/layout elements behind the outgoing slide
 *   - `mediaDataUrls`   : data-URL map for media assets
 *   - `durationMs`      : explicit override; otherwise derived from `transition`
 *   - `zoom`            : the stage's live zoom, so the outgoing slide animates
 *                         at the same size as the incoming one
 *
 * Outputs:
 *   - `complete`: emits void when the transition animation completes
 *
 * Designed to compose with `PresentationOverlayComponent` WITHOUT editing it:
 * the orchestrator stacks this overlay on top of the stage while a transition
 * is in flight and removes it on `complete`.
 */
@Component({
	selector: 'pptx-presentation-transition-overlay',
	host: { 'data-pptx-transition-overlay': '' },
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [NgStyle, SlideCanvasComponent],
	styles: `
		:host {
			display: block;
			position: absolute;
			inset: 0;
			overflow: hidden;
			pointer-events: none;
		}

		.pptx-ng-transition-layer {
			position: absolute;
			inset: 0;
			display: flex;
			align-items: center;
			justify-content: center;
		}
	`,
	template: `
		@if (incomingLayerSlide(); as incoming) {
			<div
				class="pptx-ng-transition-layer"
				data-pptx-transition-layer="incoming"
				[ngStyle]="incomingLayerStyle()"
			>
				<div [ngStyle]="slideBoxStyle()">
					<pptx-slide-canvas
						[slide]="incoming"
						[canvasSize]="canvasSize()"
						[mediaDataUrls]="mediaDataUrls()"
						[zoom]="zoom()"
						[autoFit]="false"
						[interactive]="false"
					/>
				</div>
			</div>
		}

		<div
			class="pptx-ng-transition-layer"
			data-pptx-transition-layer="outgoing"
			[attr.data-pptx-morph-outgoing]="morphPlan() ? 'true' : null"
			[ngStyle]="layerStyle()"
		>
			<div [ngStyle]="slideBoxStyle()">
				<pptx-slide-canvas
					[slide]="layerSlide()"
					[canvasSize]="canvasSize()"
					[mediaDataUrls]="mediaDataUrls()"
					[zoom]="zoom()"
					[autoFit]="false"
					[interactive]="false"
					[transparentBackground]="isMorph()"
				/>
			</div>
		</div>

		<!-- The arriving shapes that dissolve in ABOVE a departing one. They are on
		     the live stage below this overlay, where the departing layer hides them
		     for the whole morph, so they are painted again here. -->
		@if (liftedSlide(); as lifted) {
			<div
				class="pptx-ng-transition-layer"
				data-pptx-transition-layer="lifted"
				data-pptx-morph-lifted="true"
				[ngStyle]="{ 'z-index': '41' }"
			>
				<div [ngStyle]="slideBoxStyle()">
					<pptx-slide-canvas
						[slide]="lifted"
						[canvasSize]="canvasSize()"
						[mediaDataUrls]="mediaDataUrls()"
						[zoom]="zoom()"
						[autoFit]="false"
						[interactive]="false"
						[transparentBackground]="true"
					/>
				</div>
			</div>
		}

		<!-- A pair dissolving in place, painted as ONE isolated group whose two
		     halves sum instead of stacking (issue #161). -->
		@for (group of crossfadeGroups(); track group.key) {
			<div [attr.data-pptx-morph-crossfade]="group.key" [ngStyle]="group.style">
				<div
					class="pptx-ng-transition-layer"
					data-pptx-transition-layer="outgoing"
					data-pptx-morph-outgoing="true"
					[ngStyle]="group.outgoingStyle"
				>
					<div [ngStyle]="slideBoxStyle()">
						<pptx-slide-canvas
							[slide]="group.outgoing"
							[canvasSize]="canvasSize()"
							[mediaDataUrls]="mediaDataUrls()"
							[zoom]="zoom()"
							[autoFit]="false"
							[interactive]="false"
							[transparentBackground]="true"
						/>
					</div>
				</div>
				<div
					class="pptx-ng-transition-layer"
					data-pptx-transition-layer="lifted"
					data-pptx-morph-lifted="true"
					[ngStyle]="group.incomingStyle"
				>
					<div [ngStyle]="slideBoxStyle()">
						<pptx-slide-canvas
							[slide]="group.incoming"
							[canvasSize]="canvasSize()"
							[mediaDataUrls]="mediaDataUrls()"
							[zoom]="zoom()"
							[autoFit]="false"
							[interactive]="false"
							[transparentBackground]="true"
						/>
					</div>
				</div>
			</div>
		}
	`,
})
export class PresentationTransitionOverlayComponent {
	// ------------------------------------------------------------------
	// Inputs
	// ------------------------------------------------------------------

	readonly outgoingSlide = input.required<PptxSlide>();
	readonly canvasSize = input.required<CanvasSize>();
	readonly transition = input.required<PptxSlideTransition>();
	readonly templateElements = input<readonly PptxElement[]>([]);
	readonly mediaDataUrls = input<Map<string, string>>(new Map());
	/** Explicit duration override (ms). When omitted, derived from `transition`. */
	readonly durationMs = input<number | undefined>(undefined);
	/**
	 * The stage's live zoom (the same value the underlying `pptx-slide-canvas`
	 * renders at). The outgoing layer MUST use it: left at 1 the leaving slide
	 * animates out at its intrinsic size over a full-screen incoming slide,
	 * which reads as the slide snapping small the instant a transition starts.
	 */
	readonly zoom = input<number>(1);
	/**
	 * The arriving slide. Required only for Morph, which has to match shapes
	 * across both slides; every other transition ignores it.
	 */
	readonly incomingSlide = input<PptxSlide | undefined>(undefined);

	// ------------------------------------------------------------------
	// Outputs
	// ------------------------------------------------------------------

	readonly complete = output<void>();

	// ------------------------------------------------------------------
	// Internal
	// ------------------------------------------------------------------

	private readonly destroyRef = inject(DestroyRef);
	/** Active completion timer handle, so re-running re-arms cleanly. */
	private completeTimer: ReturnType<typeof setTimeout> | null = null;
	/** Active transition-sound element, paused on teardown. */
	private audio: HTMLAudioElement | null = null;
	/** Whether `complete` has already fired for the current run. */
	private fired = false;

	constructor() {
		ensureTransitionKeyframes();

		// Re-arm the completion timer + sound whenever the transition or its
		// resolved duration changes.
		effect(() => {
			const ms = this.resolvedDurationMs();
			const soundPath = this.transition().soundPath;
			this.playSound(soundPath);
			this.armCompletion(ms);
		});

		// Morph keyframes + per-element rules. They must reach the LIVE stage,
		// which is a sibling component, so they are injected at document level.
		// Element ids embed their slide path, so unscoped rules cannot leak onto
		// another slide's elements.
		effect(() => {
			const plan = this.morphPlan();
			this.applyMorphStyle(
				plan
					? [
							buildMorphScopedCss(plan, '', 'incoming'),
							buildMorphScopedCss(plan, 'data-pptx-morph-outgoing', 'outgoing'),
							// Scoped, so it outranks the unscoped `incoming` rule that holds
							// the stage's copy of the same element invisible.
							buildMorphScopedCss(plan, 'data-pptx-morph-lifted', 'lifted'),
						].join('\n')
					: null,
			);
		});

		this.destroyRef.onDestroy(() => {
			this.clearTimer();
			this.stopSound();
			this.applyMorphStyle(null);
		});
	}

	/** Owned `<style>` element carrying the active morph rules, if any. */
	private morphStyle: HTMLStyleElement | null = null;

	private applyMorphStyle(css: string | null): void {
		if (typeof document === 'undefined') {
			return;
		}
		if (css === null) {
			this.morphStyle?.remove();
			this.morphStyle = null;
			return;
		}
		if (!this.morphStyle) {
			this.morphStyle = document.createElement('style');
			document.head.appendChild(this.morphStyle);
		}
		this.morphStyle.textContent = css;
	}

	// ------------------------------------------------------------------
	// Derived state
	// ------------------------------------------------------------------

	/** Effective transition duration (ms), floored/defaulted. */
	protected readonly resolvedDurationMs = computed<number>(() =>
		resolveOverlayDurationMs(this.durationMs(), this.transition()),
	);

	/** Resolved CSS animation descriptors for the outgoing/incoming layers. */
	protected readonly animations = computed<SlideTransitionAnimations>(() => {
		const tr = this.transition();
		return getSlideTransitionAnimations(
			tr.type,
			this.resolvedDurationMs(),
			tr.direction,
			tr.orient,
			tr.spokes,
		);
	});

	/**
	 * Active Morph plan, or `undefined` for every other transition.
	 *
	 * Morph travels individual shapes between the two slides rather than wiping
	 * the surface, so it changes what this overlay paints: a per-shape copy of
	 * the outgoing slide, each one gliding onto its counterpart (dissolving into
	 * it when its appearance changed) or fading out in place when it has none.
	 * The incoming halves are animated on the live stage by document-level rules
	 * (see `morphStyleEffect`).
	 */
	protected readonly morphPlan = computed(() =>
		this.transition().type === 'morph'
			? buildMorphTransitionPlan(
					this.outgoingSlide(),
					this.incomingSlide(),
					this.resolvedDurationMs(),
					morphOptionToMode(this.transition().morphOption),
				)
			: undefined,
	);

	/**
	 * Whether this overlay is playing a morph.
	 *
	 * A morph layer paints only the departing slide's paired shapes over the live
	 * incoming stage, so its stage background must be dropped
	 * (`transparentBackground`). Every other transition animates a whole slide
	 * surface out and keeps its own background.
	 */
	protected readonly isMorph = computed<boolean>(() => this.morphPlan() !== undefined);

	/** The slide rendered in the animated layer (outgoing + its template). */
	protected readonly layerSlide = computed<PptxSlide>(() => {
		const slide = this.outgoingSlide();
		const plan = this.morphPlan();
		if (plan) {
			return { ...slide, elements: [...plan.outgoingElements] };
		}
		const template = this.templateElements();
		if (template.length === 0) {
			return slide;
		}
		return { ...slide, elements: [...template, ...slide.elements] };
	});

	/**
	 * The arriving shapes the morph has to paint over its own ghosts, or
	 * `undefined` when there are none (issue #146). They sit on the live stage
	 * below this overlay, where the departing layer would hide them for the whole
	 * transition; the plan holds that copy invisible and hands them here instead.
	 */
	protected readonly liftedSlide = computed<PptxSlide | undefined>(() =>
		morphLiftedSlide(this.morphPlan(), this.incomingSlide()),
	);

	/**
	 * The cross-dissolving pairs this overlay paints both halves of, each in its
	 * own isolated group so the halves are summed rather than stacked.
	 */
	protected readonly crossfadeGroups = computed<MorphCrossfadeGroupSlides[]>(() =>
		morphCrossfadeGroupSlides(this.morphPlan(), this.outgoingSlide(), this.incomingSlide()),
	);

	/** Layer container style: animation + stacking relative to the stage. */
	protected readonly layerStyle = computed<StyleMap>(() => {
		const anims = this.animations();
		const plan = this.morphPlan();
		const style: StyleMap = {
			'z-index': plan ? '40' : anims.outgoingOnTop ? '40' : '20',
		};
		// A layer-wide animation would drag every shape as one block and cancel
		// the morph, so during a morph the layer itself stays still.
		if (!plan && anims.outgoing !== 'none') {
			style['animation'] = anims.outgoing;
		}
		return style;
	});

	/**
	 * The arriving slide rendered ABOVE the outgoing layer for a classic
	 * transition, carrying the incoming animation (wipe/cover/fade/push), or
	 * `undefined` for morphs and the uncover family (which reveal the live
	 * stage instead).
	 */
	protected readonly incomingLayerSlide = computed<PptxSlide | undefined>(() =>
		classicIncomingLayerSlide(
			this.isMorph(),
			this.animations().incoming,
			this.incomingSlide(),
			this.templateElements(),
		),
	);

	/** Style for that arriving layer: the incoming animation + its stacking. */
	protected readonly incomingLayerStyle = computed<StyleMap>(() => ({
		'z-index': this.animations().outgoingOnTop ? '30' : '25',
		animation: this.animations().incoming,
	}));

	/**
	 * Slide box sized to the ZOOMED slide footprint, matching the stage's own
	 * `pptx-slide-canvas`. The inner canvas renders at the same `zoom` with
	 * `autoFit` off, so the outgoing slide is pixel-for-pixel the size of the
	 * incoming one for the whole animation.
	 */
	protected readonly slideBoxStyle = computed<StyleMap>(() => {
		const box = transitionSlideBoxSize(this.canvasSize(), this.zoom());
		return {
			width: `${box.width}px`,
			height: `${box.height}px`,
			'transform-origin': 'center',
		};
	});

	// ------------------------------------------------------------------
	// Completion timing + sound
	// ------------------------------------------------------------------

	private armCompletion(durationMs: number): void {
		this.clearTimer();
		this.fired = false;
		if (typeof setTimeout === 'undefined') {
			return;
		}
		this.completeTimer = setTimeout(() => {
			this.completeTimer = null;
			if (this.fired) {
				return;
			}
			this.fired = true;
			this.complete.emit();
		}, durationMs + COMPLETE_MARGIN_MS);
	}

	private clearTimer(): void {
		if (this.completeTimer !== null) {
			clearTimeout(this.completeTimer);
			this.completeTimer = null;
		}
	}

	private playSound(soundPath: string | undefined): void {
		this.stopSound();
		if (!soundPath || typeof Audio === 'undefined') {
			return;
		}
		const audio = new Audio(soundPath);
		this.audio = audio;
		// Browser autoplay policy may reject; ignore silently.
		void audio.play().catch(() => {});
	}

	private stopSound(): void {
		if (this.audio) {
			this.audio.pause();
			this.audio.src = '';
			this.audio = null;
		}
	}
}

// packages/react/src/viewer/components/PresentationTransitionOverlay.tsx
import type { PptxElement, PptxSlide, PptxSlideTransition } from 'pptx-viewer-core';
/**
 * Overlay rendered during slide transitions in presentation mode.
 *
 * Displays the *outgoing* (previous) slide as an absolutely-positioned layer
 * with CSS exit animation. The *incoming* (new) slide is rendered by the
 * main SlideCanvas underneath (or on top, depending on `outgoingOnTop`).
 */
import type { MorphTransitionPlan } from 'pptx-viewer-shared';
import { MORPH_CROSSFADE_GROUP_STYLE, MORPH_CROSSFADE_HALF_STYLE } from 'pptx-viewer-shared';
import React, { useEffect, useRef, useMemo, useState } from 'react';

import type { CanvasSize } from '../types';
import { normalizeHexColor } from '../utils';
import {
	getSlideTransitionAnimations,
	SLIDE_TRANSITION_KEYFRAMES,
} from '../utils/slide-transitions';
import type { SlideTransitionAnimations } from '../utils/slide-transitions';
import { SlideBackgroundImageLayer } from './SlideBackgroundImageLayer';
import { StaticElementRenderer } from './StaticElementRenderer';

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

export interface PresentationTransitionOverlayProps {
	/** The outgoing (old) slide to render in the overlay layer. */
	outgoingSlide: PptxSlide;
	/** Template/master elements that belong to the outgoing slide. */
	templateElements: PptxElement[];
	/** Canvas dimensions (slide width × height in EMU-derived px). */
	canvasSize: CanvasSize;
	/** Transition definition from the incoming slide. */
	transition: PptxSlideTransition;
	/** Resolved transition duration in ms. */
	durationMs: number;
	/**
	 * The live stage scale (slide box scale) supplied by `PresentationStage`.
	 *
	 * Passing it is what keeps the outgoing slide the same size as the incoming
	 * one on the very first painted frame. Without it the overlay has to measure
	 * itself after mount, and the first frame paints the outgoing slide at its
	 * intrinsic (unscaled) size over a full-screen incoming slide - a one-frame
	 * flash right after the transition starts.
	 */
	scale?: number;
	/**
	 * Active Morph plan, when the incoming slide's transition is `morph`.
	 *
	 * Morph is not a whole-slide effect, so the overlay changes shape when this
	 * is present: instead of animating the entire outgoing slide as one block, it
	 * paints each outgoing shape separately and glides it onto its counterpart -
	 * dissolving into it when its appearance changed, fading out in place when it
	 * has none. The incoming halves animate on the live stage underneath (their
	 * `incomingAnimations` are already merged into the stage's element states by
	 * `usePresentationMode`).
	 */
	morphPlan?: MorphTransitionPlan;
	/**
	 * The arriving slide, needed only as the render context for the few of its
	 * own shapes a morph has to paint above the ghosts (see
	 * {@link MorphTransitionPlan.overlayIncomingElements}). Every other
	 * transition ignores it.
	 */
	incomingSlide?: PptxSlide;
	/** Called when the transition animation completes. */
	onComplete: () => void;
}

// ---------------------------------------------------------------------------
// Slide layer renderer (simplified non-interactive slide, like SlideThumbnail)
// ---------------------------------------------------------------------------

interface SlideLayerProps {
	slide: PptxSlide;
	templateElements: PptxElement[];
	canvasSize: CanvasSize;
}

function SlideLayer({ slide, templateElements, canvasSize }: SlideLayerProps): React.ReactElement {
	const safeWidth = Math.max(canvasSize.width, 1);
	const safeHeight = Math.max(canvasSize.height, 1);
	const elements = [...templateElements, ...slide.elements];

	return (
		<div
			className='relative overflow-hidden'
			style={{
				width: safeWidth,
				height: safeHeight,
				backgroundColor: slide.backgroundColor
					? normalizeHexColor(slide.backgroundColor, '#ffffff')
					: '#ffffff',
				backgroundImage: slide.backgroundImage
					? `url(${slide.backgroundImage})`
					: slide.backgroundGradient
						? slide.backgroundGradient
						: undefined,
				backgroundSize: slide.backgroundImage ? 'cover' : undefined,
				backgroundPosition: slide.backgroundImage ? 'center' : undefined,
			}}
		>
			<SlideBackgroundImageLayer slide={slide} />
			{elements.map((element, index) => (
				<StaticElementRenderer
					key={element.id}
					element={element}
					activeSlide={slide}
					allSlides={[slide]}
					zIndex={index}
				/>
			))}
		</div>
	);
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function PresentationTransitionOverlay({
	outgoingSlide,
	templateElements,
	canvasSize,
	transition,
	durationMs,
	scale: stageScale,
	morphPlan,
	incomingSlide,
	onComplete,
}: PresentationTransitionOverlayProps): React.ReactElement | null {
	const containerRef = useRef<HTMLDivElement>(null);
	const [containerSize, setContainerSize] = useState<{
		width: number;
		height: number;
	} | null>(null);
	const resolvedStageScale =
		typeof stageScale === 'number' && Number.isFinite(stageScale) && stageScale > 0
			? stageScale
			: null;

	// Fallback measurement for hosts that mount the overlay without a stage
	// scale. Skipped entirely when the stage supplied one, since measuring only
	// ever reproduces the value we were already handed - one frame later.
	useEffect(() => {
		if (resolvedStageScale !== null) {
			return;
		}
		const el = containerRef.current;
		if (!el) {
			return;
		}
		const rect = el.getBoundingClientRect();
		setContainerSize({ width: rect.width, height: rect.height });
	}, [resolvedStageScale]);

	// Fire completion callback after duration
	useEffect(() => {
		const timer = window.setTimeout(onComplete, durationMs + 50);
		return () => {
			window.clearTimeout(timer);
		};
	}, [durationMs, onComplete]);

	// Compute transition animations
	const animations: SlideTransitionAnimations = useMemo(
		() =>
			getSlideTransitionAnimations(
				transition.type,
				durationMs,
				transition.direction,
				transition.orient,
				transition.spokes,
			),
		[transition.type, transition.direction, transition.orient, transition.spokes, durationMs],
	);

	// Scale for the slide layer. Prefer the stage's own scale: it is already
	// correct on the first render, so the outgoing slide never paints unscaled.
	const scale = useMemo(() => {
		if (resolvedStageScale !== null) {
			return resolvedStageScale;
		}
		if (!containerSize) {
			return 1;
		}
		const scaleX = containerSize.width / Math.max(canvasSize.width, 1);
		const scaleY = containerSize.height / Math.max(canvasSize.height, 1);
		return Math.min(scaleX, scaleY);
	}, [resolvedStageScale, containerSize, canvasSize]);

	const outgoingZIndex = animations.outgoingOnTop ? 40 : 20;

	// Morph: paint only the departing shapes, unanimated as a layer, each
	// carrying its own fade-out. The persisting shapes are already gliding on
	// the live stage below, so covering them with a copy of the whole outgoing
	// slide would hide the effect entirely.
	if (morphPlan) {
		return (
			<div
				ref={containerRef}
				data-pptx-transition-overlay
				data-pptx-transition-morph='true'
				className='pptx-react-transition-overlay absolute inset-0 pointer-events-none overflow-hidden'
				style={{ zIndex: 40 }}
			>
				<style>{morphPlan.keyframesCss}</style>
				<div className='absolute inset-0 flex items-center justify-center'>
					<div
						style={{
							width: canvasSize.width,
							height: canvasSize.height,
							// The slide box is a flex ITEM, so it shrinks to the container
							// unless told not to. A show surface narrower than the deck's own
							// canvas (a windowed show, or a display scaled past 100%) squeezed
							// the unscaled 1280px box down to the container width and only
							// then scaled it, landing the whole outgoing slide up to ~77px to
							// the right of the live one for the length of the morph (issue
							// #161). The stage below positions its slide box absolutely and is
							// unaffected, so the two layers disagreed.
							flexShrink: 0,
							transform: `scale(${scale})`,
							transformOrigin: 'center',
							position: 'relative',
						}}
					>
						{morphPlan.outgoingElements.map((element, index) => (
							<div
								key={element.id}
								data-pptx-morph-outgoing={element.id}
								style={{ position: 'absolute', inset: 0 }}
							>
								{/* The animation rides the element's own positioned container:
								    ghost keyframes are element-local (they restate the static
								    rotation/flips and pivot on the element centre), so a
								    slide-sized wrapper would pivot them around the slide
								    centre and double-apply the static transform. */}
								<StaticElementRenderer
									element={element}
									activeSlide={outgoingSlide}
									allSlides={[outgoingSlide]}
									zIndex={index}
									animation={morphPlan.outgoingAnimations.get(element.id)}
									imageAnimation={morphPlan.outgoingImageAnimations.get(element.id)}
								/>
							</div>
						))}
						{/* The arriving shapes a ghost above them would otherwise hide for
						    the whole morph, painted here instead so they dissolve in where
						    a viewer can see them (issue #146). Their copy on the live stage
						    is held invisible by the plan, so nothing composites twice. */}
						{incomingSlide &&
							morphPlan.overlayIncomingElements.map((element, index) => (
								<div
									key={element.id}
									data-pptx-morph-lifted={element.id}
									style={{ position: 'absolute', inset: 0 }}
								>
									<StaticElementRenderer
										element={element}
										activeSlide={incomingSlide}
										allSlides={[incomingSlide]}
										zIndex={morphPlan.outgoingElements.length + index}
										animation={morphPlan.overlayIncomingAnimations.get(element.id)}
									/>
								</div>
							))}
						{/* Pairs the overlay paints both halves of, summed inside their own
						    isolated group instead of stacked: two source-over fades dip the
						    ink they share toward the backdrop, which bites chunks out of
						    glyphs that cross during a text dissolve (issue #161). The group
						    carries an explicit z-index because `isolation` makes it a
						    stacking context, so the halves' own z-indexes no longer place
						    it against the ghosts. */}
						{incomingSlide &&
							morphPlan.crossfadeGroups.map((group, index) => (
								<div
									key={group.incoming.id}
									data-pptx-morph-crossfade={group.incoming.id}
									style={{
										...MORPH_CROSSFADE_GROUP_STYLE,
										zIndex:
											morphPlan.outgoingElements.length +
											morphPlan.overlayIncomingElements.length +
											index,
									}}
								>
									{/* The dissolve rides the WRAPPER, not the element: a pair that
									    dissolves in place never moves, and an animation on the small
									    element box gives it a compositing layer whose raster snaps
									    to whole device pixels, painting the wording a fraction of a
									    pixel off the live stage (issue #161). */}
									<div
										data-pptx-morph-outgoing={group.outgoing.id}
										style={{ ...MORPH_CROSSFADE_HALF_STYLE, animation: group.outgoingAnimation }}
									>
										<StaticElementRenderer
											element={group.outgoing}
											activeSlide={outgoingSlide}
											allSlides={[outgoingSlide]}
											zIndex={0}
											animation={morphPlan.outgoingAnimations.get(group.outgoing.id)}
											imageAnimation={morphPlan.outgoingImageAnimations.get(group.outgoing.id)}
										/>
									</div>
									<div
										data-pptx-morph-lifted={group.incoming.id}
										style={{ ...MORPH_CROSSFADE_HALF_STYLE, animation: group.incomingAnimation }}
									>
										<StaticElementRenderer
											element={group.incoming}
											activeSlide={incomingSlide}
											allSlides={[incomingSlide]}
											zIndex={0}
											animation={morphPlan.overlayIncomingAnimations.get(group.incoming.id)}
										/>
									</div>
								</div>
							))}
					</div>
				</div>
			</div>
		);
	}

	return (
		<div
			ref={containerRef}
			data-pptx-transition-overlay
			className='pptx-react-transition-overlay absolute inset-0 pointer-events-none overflow-hidden'
			style={{ zIndex: outgoingZIndex }}
		>
			{/* Inject the transition @keyframes so the `animation` shorthands resolve. */}
			<style>{SLIDE_TRANSITION_KEYFRAMES}</style>
			{/* The ARRIVING slide, carrying the incoming animation. Without this
			    layer the arriving slide is only the live stage BENEATH the
			    overlay: an opaque outgoing layer (wipe/cover leave it in place)
			    hid it for the whole duration, then the teardown revealed it in
			    one frame - "takes the time, then instantly replaced". Types whose
			    incoming half is 'none' (uncover family) must keep revealing the
			    stage, so no static layer is rendered for them. */}
			{!morphPlan && animations.incoming !== 'none' && incomingSlide ? (
				<div
					data-pptx-transition-layer='incoming'
					className='pptx-react-transition-layer absolute inset-0 flex items-center justify-center'
					style={{
						animation: animations.incoming,
						zIndex: animations.outgoingOnTop ? 0 : 10,
					}}
				>
					<div
						style={{
							width: canvasSize.width,
							height: canvasSize.height,
							flexShrink: 0,
							transform: `scale(${scale})`,
							transformOrigin: 'center',
						}}
					>
						<SlideLayer
							slide={incomingSlide}
							templateElements={templateElements}
							canvasSize={canvasSize}
						/>
					</div>
				</div>
			) : null}
			<div
				data-pptx-transition-layer='outgoing'
				className='pptx-react-transition-layer absolute inset-0 flex items-center justify-center'
				style={{
					animation: animations.outgoing !== 'none' ? animations.outgoing : undefined,
					zIndex: animations.outgoingOnTop ? 10 : 0,
				}}
			>
				<div
					style={{
						width: canvasSize.width,
						height: canvasSize.height,
						// See the morph layer above: a flex item shrinks to its container,
						// which offsets the whole outgoing slide on a show surface narrower
						// than the deck's canvas.
						flexShrink: 0,
						transform: `scale(${scale})`,
						transformOrigin: 'center',
					}}
				>
					<SlideLayer
						slide={outgoingSlide}
						templateElements={templateElements}
						canvasSize={canvasSize}
					/>
				</div>
			</div>
		</div>
	);
}
