// packages/vue/src/viewer/components/SetUpSlideShowDialog.vue
<script setup lang="ts">
import type { PptxCustomShow, PptxPresentationProperties } from 'pptx-viewer-core';
import { computed, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';

import ModalDialog from './ModalDialog.vue';
import ShowOptionsFieldset from './ShowOptionsFieldset.vue';
import ShowSlidesFieldset from './ShowSlidesFieldset.vue';

/**
 * SetUpSlideShowDialog: configure slide-show playback settings (show type,
 * slide range, advance mode, loop / narration / animation / subtitles, and the
 * annotation pen colour). Vue port of the React `SetUpSlideShowDialog.tsx`.
 *
 * The dialog edits a local `draft` copy of the presentation properties and
 * only commits it via the `save` event on OK, so cancelling discards edits.
 * The host persists the returned properties through the editor/save path.
 */
const props = defineProps<{
	open: boolean;
	properties: PptxPresentationProperties;
	customShows: PptxCustomShow[];
	slideCount: number;
}>();

const emit = defineEmits<{
	save: [properties: PptxPresentationProperties];
	close: [];
}>();

const { t } = useI18n();

const draft = ref<PptxPresentationProperties>({ ...props.properties });

// Re-seed the draft each time the dialog opens so it reflects the latest saved
// properties and drops any abandoned edits from a previous cancel.
watch(
	() => props.open,
	(open) => {
		if (open) {
			draft.value = { ...props.properties };
		}
	},
	{ immediate: true },
);

const showType = computed(() => draft.value.showType ?? 'presented');
const showSlidesMode = computed(() => draft.value.showSlidesMode ?? 'all');

function update(patch: Partial<PptxPresentationProperties>): void {
	draft.value = { ...draft.value, ...patch };
}

function setShowType(value: 'presented' | 'browsed' | 'kiosk'): void {
	update({ showType: value, ...(value === 'kiosk' ? { loopContinuously: true } : {}) });
}

function onSave(): void {
	emit('save', { ...draft.value });
	emit('close');
}

const showTypes = computed<Array<['presented' | 'browsed' | 'kiosk', string]>>(() => [
	['presented', t('pptx.slideShow.typePresented')],
	['browsed', t('pptx.slideShow.typeBrowsed')],
	['kiosk', t('pptx.slideShow.typeKiosk')],
]);
</script>

<template>
	<ModalDialog :open="props.open" :title="t('pptx.slideShow.title')" @close="emit('close')">
		<div class="flex flex-col gap-5 text-[12px] text-foreground">
			<fieldset class="space-y-1.5">
				<legend class="mb-1 text-[11px] font-medium uppercase tracking-wide text-muted-foreground">
					{{ t('pptx.slideShow.legendShowType') }}
				</legend>
				<label
					v-for="[value, label] in showTypes"
					:key="value"
					class="flex cursor-pointer items-center gap-2"
				>
					<input
						type="radio"
						name="showType"
						class="accent-primary"
						:value="value"
						:checked="showType === value"
						@change="setShowType(value)"
					/>
					<span>{{ label }}</span>
				</label>
			</fieldset>

			<ShowSlidesFieldset
				:draft="draft"
				:show-slides-mode="showSlidesMode"
				:slide-count="props.slideCount"
				:custom-shows="props.customShows"
				@update="update"
			/>

			<fieldset class="space-y-1.5">
				<legend class="mb-1 text-[11px] font-medium uppercase tracking-wide text-muted-foreground">
					{{ t('pptx.slideShow.legendAdvance') }}
				</legend>
				<label class="flex cursor-pointer items-center gap-2">
					<input
						type="radio"
						name="advanceMode"
						value="manual"
						class="accent-primary"
						:checked="draft.advanceMode === 'manual'"
						@change="update({ advanceMode: 'manual' })"
					/>
					<span>{{ t('pptx.slideShow.advanceManual') }}</span>
				</label>
				<label class="flex cursor-pointer items-center gap-2">
					<input
						type="radio"
						name="advanceMode"
						value="useTimings"
						class="accent-primary"
						:checked="(draft.advanceMode ?? 'useTimings') === 'useTimings'"
						@change="update({ advanceMode: 'useTimings' })"
					/>
					<span>{{ t('pptx.slideShow.advanceTimings') }}</span>
				</label>
			</fieldset>

			<ShowOptionsFieldset :draft="draft" @update="update" />
		</div>

		<template #footer>
			<button
				type="button"
				class="rounded bg-muted px-3 py-1.5 text-[12px] text-foreground transition-colors hover:bg-accent"
				@click="emit('close')"
			>
				{{ t('pptx.share.cancel') }}
			</button>
			<button
				type="button"
				class="rounded bg-primary px-3 py-1.5 text-[12px] text-white transition-colors hover:bg-primary/80"
				@click="onSave"
			>
				{{ t('pptx.slideShow.ok') }}
			</button>
		</template>
	</ModalDialog>
</template>

// packages/react/src/viewer/components/SetUpSlideShowDialog.tsx
import type { PptxPresentationProperties, PptxCustomShow } from 'pptx-viewer-core';
/**
 * SetUpSlideShowDialog
 *
 * Modal dialog for configuring slide show settings (show type, slides range,
 * advance mode, loop, narration, animation, subtitles).
 */
import React, { useState, useCallback } from 'react';
import { useTranslation } from 'react-i18next';

import { ShowOptionsFieldset } from './ShowOptionsFieldset';
import { ShowSlidesFieldset } from './ShowSlidesFieldset';

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

export interface SetUpSlideShowDialogProps {
	open: boolean;
	onClose: () => void;
	properties: PptxPresentationProperties;
	onSave: (properties: PptxPresentationProperties) => void;
	customShows: PptxCustomShow[];
	slideCount: number;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function SetUpSlideShowDialog({
	open,
	onClose,
	properties,
	onSave,
	customShows,
	slideCount,
}: SetUpSlideShowDialogProps): React.ReactElement | null {
	const { t } = useTranslation();

	const [draft, setDraft] = useState<PptxPresentationProperties>({
		...properties,
	});

	const update = useCallback((patch: Partial<PptxPresentationProperties>) => {
		setDraft((prev) => ({ ...prev, ...patch }));
	}, []);

	const handleSave = useCallback(() => {
		onSave(draft);
		onClose();
	}, [draft, onSave, onClose]);

	if (!open) {
		return null;
	}

	const showType = draft.showType ?? 'presented';
	const showSlidesMode = draft.showSlidesMode ?? 'all';

	return (
		<>
			{/* Backdrop */}
			<button
				type='button'
				style={{ zIndex: 1200 }}
				className='fixed inset-0 bg-black/50'
				aria-label={t('pptx.share.closeDialog')}
				onClick={onClose}
			/>

			{/* Dialog */}
			<div
				style={{ zIndex: 1201 }}
				className='fixed inset-0 flex items-center justify-center pointer-events-none'
			>
				<div className='pointer-events-auto flex flex-col w-[440px] max-h-[90vh] rounded-xl border border-border bg-background shadow-2xl max-md:fixed max-md:inset-x-0 max-md:bottom-0 max-md:top-auto max-md:w-full max-md:max-w-none max-md:max-h-[88dvh] max-md:rounded-t-2xl max-md:rounded-b-none max-md:border-x-0 max-md:border-b-0 max-md:pb-[max(env(safe-area-inset-bottom),0px)]'>
					{/* Header */}
					<div className='flex items-center justify-between px-5 py-3 border-b border-border shrink-0'>
						<h2 className='text-sm font-semibold text-foreground'>
							{t('pptx.slideShow.setUpTitle')}
						</h2>
						<button
							type='button'
							onClick={onClose}
							className='text-muted-foreground hover:text-foreground text-lg leading-none'
							aria-label={t('pptx.common.close')}
						>
							&times;
						</button>
					</div>

					{/* Body */}
					<div className='flex-1 px-5 py-4 space-y-5 text-[12px] text-foreground overflow-y-auto'>
						{/* Show Type */}
						<fieldset className='space-y-1.5'>
							<legend className='text-[11px] font-medium text-muted-foreground uppercase tracking-wide mb-1'>
								{t('pptx.slideShow.showType')}
							</legend>
							{(
								[
									['presented', t('pptx.slideShow.presentedBySpeaker')],
									['browsed', t('pptx.slideShow.browsedByIndividual')],
									['kiosk', t('pptx.slideShow.browsedAtKiosk')],
								] as const
							).map(([value, label]) => (
								<label key={value} className='flex items-center gap-2 cursor-pointer'>
									<input
										type='radio'
										name='showType'
										value={value}
										checked={showType === value}
										onChange={() =>
											update({
												showType: value,
												...(value === 'kiosk' ? { loopContinuously: true } : {}),
											})
										}
										className='accent-primary'
									/>
									<span>{label}</span>
								</label>
							))}
						</fieldset>

						<ShowSlidesFieldset
							draft={draft}
							update={update}
							showSlidesMode={showSlidesMode}
							slideCount={slideCount}
							customShows={customShows}
						/>

						{/* Advance Slides */}
						<fieldset className='space-y-1.5'>
							<legend className='text-[11px] font-medium text-muted-foreground uppercase tracking-wide mb-1'>
								{t('pptx.slideShow.advanceSlides')}
							</legend>
							<label className='flex items-center gap-2 cursor-pointer'>
								<input
									type='radio'
									name='advanceMode'
									value='manual'
									checked={draft.advanceMode === 'manual'}
									onChange={() => update({ advanceMode: 'manual' })}
									className='accent-primary'
								/>
								<span>{t('pptx.slideShow.manually')}</span>
							</label>
							<label className='flex items-center gap-2 cursor-pointer'>
								<input
									type='radio'
									name='advanceMode'
									value='useTimings'
									checked={(draft.advanceMode ?? 'useTimings') === 'useTimings'}
									onChange={() => update({ advanceMode: 'useTimings' })}
									className='accent-primary'
								/>
								<span>{t('pptx.slideShow.useTimings')}</span>
							</label>
						</fieldset>

						<ShowOptionsFieldset draft={draft} update={update} />
					</div>

					{/* Footer */}
					<div className='flex justify-end gap-2 px-5 py-3 border-t border-border shrink-0'>
						<button
							type='button'
							onClick={onClose}
							className='px-3 py-1.5 rounded bg-muted hover:bg-accent text-[12px] text-foreground transition-colors'
						>
							{t('pptx.common.cancel')}
						</button>
						<button
							type='button'
							onClick={handleSave}
							className='px-3 py-1.5 rounded bg-primary hover:bg-primary/80 text-[12px] text-white transition-colors'
						>
							{t('pptx.common.ok')}
						</button>
					</div>
				</div>
			</div>
		</>
	);
}
