// demos/demo-vue/src/App.vue
<script setup lang="ts">
import { PptxHandler } from 'pptx-viewer-core';
// The openable-file allow list comes from the binding's public surface, not a
// local regex: a hand-rolled `.pptx|.ppt|.json` refused a `.pptm` on drop that
// the viewer's own File > Open accepted.
import {
	PPTX_OPEN_ACCEPT,
	PowerPointViewer,
	isAudienceTab,
	isSupportedPresentationFile,
	loadAudienceContent,
	parsePresentationSessionId,
	rememberSessionDeck,
	restoreSessionDeck,
	themeToCssVars,
} from 'pptx-vue-viewer';
import type { CollaborationConfig } from 'pptx-vue-viewer';
import 'pptx-vue-viewer/styles';
import { computed, onBeforeUnmount, onMounted, ref, shallowRef, watchEffect } from 'vue';
import { useI18n } from 'vue-i18n';

import { useDemoAiConfig } from './ai-config';
import {
	isTrustedServerUrl,
	randomUserColor,
	resolveAutoName,
	resolveAutoRoomId,
	resolveDefaultServerUrl,
} from './collab';
import i18n from './i18n';
import type { LanguageCode } from './languages';
import { languageKeys } from './languages';
import { themes } from './themes';

/**
 * Demo app for `pptx-vue-viewer`, mirroring the React `demo/main.tsx`.
 *
 * The viewer fills the screen; there is no demo header (download lives in the
 * viewer's File menu). URL params drive collaboration / broadcast / audience joins.
 */

const content = shallowRef<Uint8Array | null>(null);
const fileName = ref('');
// Whether the "does this tab have a deck to reopen?" check has finished. The
// `?sample=1` auto-load waits for it so a restored deck wins over the sample.
const restoreChecked = ref(false);

// Demo AI provider: the host builds an OpenAI-compatible browser model from
// localStorage-supplied fields and passes it to the viewer's optional `ai`
// prop. The demo ships no key and no config UI, so this is normally undefined
// and the assistant simply stays off.
const aiConfig = useDemoAiConfig();

const themeKey = ref<string>(readStoredTheme());

function readStoredTheme(): string {
	try {
		return localStorage.getItem('pptx-demo-theme') ?? 'vermilionDark';
	} catch {
		return 'vermilionDark';
	}
}

const currentPreset = computed(() => themes[themeKey.value] ?? themes.vermilionDark);

const { t } = useI18n();

// ── Language ────────────────────────────────────────────────────────────────
function readStoredLanguage(): LanguageCode {
	try {
		const stored = localStorage.getItem('pptx-demo-lang');
		return stored && languageKeys.includes(stored as LanguageCode)
			? (stored as LanguageCode)
			: 'en';
	} catch {
		return 'en';
	}
}

const languageKey = ref<LanguageCode>(readStoredLanguage());
watchEffect(() => {
	i18n.global.locale.value = languageKey.value;
});

// ── Apply theme vars to :root so the dropzone chrome tracks the theme ──────
let appliedVarKeys: string[] = [];
watchEffect(() => {
	const vars = themeToCssVars(currentPreset.value.theme);
	const root = document.documentElement;
	for (const key of appliedVarKeys) {
		root.style.removeProperty(key);
	}
	appliedVarKeys = Object.keys(vars);
	for (const key of appliedVarKeys) {
		root.style.setProperty(key, vars[key]);
	}
});
onBeforeUnmount(() => {
	const root = document.documentElement;
	for (const key of appliedVarKeys) {
		root.style.removeProperty(key);
	}
});

// ── URL-based collaboration / broadcast join ───────────────────────────────
const params = new URLSearchParams(window.location.search);
const urlRoom = ref(params.get('room'));
const urlBroadcast = ref(params.get('broadcast'));
const urlName = params.get('name');
// Serverless peer-to-peer joins carry `?transport=webrtc` (and optional
// `?signaling=a,b`); they need no `?server=` and no file server round-trip.
const urlTransport = params.get('transport');
const urlSignaling = params.get('signaling')?.split(',').filter(Boolean) ?? [];
const isWebrtcJoin = urlTransport === 'webrtc';
// For a webrtc join the server URL is intentionally blank (P2P); otherwise fall
// back to the configured relay / localhost default.
const urlServer = isWebrtcJoin ? '' : (params.get('server') ?? resolveDefaultServerUrl());
// Opt in to the experimental Three.js SmartArt renderer via `?smartArt3D=1`.
const smartArt3D = params.get('smartArt3D') === '1';
// Opt in to the experimental Three.js interactive surface-chart renderer
// (camera orbit/zoom + raycast hover tooltip) via `?surfaceChart3D=1`.
const surfaceChart3D = params.get('surfaceChart3D') === '1';
// Opt in to the experimental Three.js interactive bar3D-chart renderer
// (real box meshes, camera orbit/zoom + raycast hover tooltip) via
// `?barChart3D=1`.
const barChart3D = params.get('barChart3D') === '1';
// Opt in to the experimental Three.js interactive line3D-chart renderer
// (real tube-path meshes, camera orbit/zoom + raycast hover tooltip) via
// `?lineChart3D=1`.
const lineChart3D = params.get('lineChart3D') === '1';
// Opt in to the experimental Three.js interactive area3D-chart renderer
// (real tube-path + ribbon meshes, camera orbit/zoom + raycast hover
// tooltip) via `?areaChart3D=1`.
const areaChart3D = params.get('areaChart3D') === '1';
// Opt in to the experimental Three.js interactive pie3D-chart renderer
// (real wedge meshes, camera orbit/zoom + raycast hover tooltip) via
// `?pieChart3D=1`.
const pieChart3D = params.get('pieChart3D') === '1';
// `?sample=1` auto-loads the bundled sample deck (used by the docs landing
// page to embed a live, pre-populated viewer).
const urlSample = params.get('sample') === '1';

// Stable defaults for the Share dialog (demo-specific).
const autoRoomId = resolveAutoRoomId();
const autoName = resolveAutoName();
const defaultServerUrl = resolveDefaultServerUrl();

// ── Collaboration state ────────────────────────────────────────────────────
const collaborationConfig = shallowRef<CollaborationConfig | null>(null);

// A webrtc join is serverless, so it bypasses the trusted-host allowlist (there
// is no server to trust); a websocket join still requires a trusted server.
const joinAllowed = isWebrtcJoin || isTrustedServerUrl(urlServer);

// Auto-connect if room is in URL (collaboration mode).
watchEffect(() => {
	if (urlRoom.value && !collaborationConfig.value && joinAllowed) {
		collaborationConfig.value = {
			roomId: urlRoom.value,
			serverUrl: urlServer,
			userName: urlName ?? autoName,
			userColor: randomUserColor(),
			...(isWebrtcJoin
				? { transport: 'webrtc', signaling: urlSignaling.length ? urlSignaling : undefined }
				: {}),
		};
	} else if (urlRoom.value && !joinAllowed) {
		console.warn(
			`Ignoring ?room= auto-connect because ?server=${urlServer} is not in the trusted-host allowlist. Use the Share dialog to connect explicitly.`,
		);
	}
});

// Auto-connect if broadcast is in URL (viewer mode).
watchEffect(() => {
	if (urlBroadcast.value && !collaborationConfig.value && joinAllowed) {
		collaborationConfig.value = {
			roomId: urlBroadcast.value,
			serverUrl: urlServer,
			userName: urlName ?? autoName,
			userColor: randomUserColor(),
			role: 'viewer',
			...(isWebrtcJoin
				? { transport: 'webrtc', signaling: urlSignaling.length ? urlSignaling : undefined }
				: {}),
		};
	} else if (urlBroadcast.value && !joinAllowed) {
		console.warn(
			`Ignoring ?broadcast= auto-connect because ?server=${urlServer} is not in the trusted-host allowlist.`,
		);
	}
});

function handleStartCollaboration(config: CollaborationConfig): void {
	collaborationConfig.value = config;
	const webrtc = config.transport === 'webrtc';
	// Update URL with room/broadcast info for sharing.
	const url = new URL(window.location.href);
	// The viewer's broadcast session is the session owner (role 'owner'); a
	// regular collaboration session is role 'collaborator'.
	if (config.role === 'owner') {
		url.searchParams.set('broadcast', config.roomId);
	} else {
		url.searchParams.set('room', config.roomId);
	}
	// A serverless webrtc session shares `transport=webrtc` (no server URL);
	// a websocket session shares its server so joiners fetch the file from it.
	if (webrtc) {
		url.searchParams.set('transport', 'webrtc');
		url.searchParams.delete('server');
		if (config.signaling?.length) {
			url.searchParams.set('signaling', config.signaling.join(','));
		}
	} else {
		url.searchParams.set('server', config.serverUrl);
		url.searchParams.delete('transport');
		url.searchParams.delete('signaling');
	}
	window.history.replaceState({}, '', url.toString());
	// Upload PPTX content to the collab server so joiners can download it.
	// Restricted to trusted hosts to prevent crafted ?server= URLs from
	// exfiltrating user content. Serverless webrtc has no file server: joiners
	// receive the deck through Y.Doc late-joiner sync instead.
	const bytes = content.value;
	if (config.sessionIntent !== 'join' && !webrtc && bytes && isTrustedServerUrl(config.serverUrl)) {
		const httpUrl = config.serverUrl.replace(/^ws/u, 'http');
		void fetch(`${httpUrl}/file/${encodeURIComponent(config.roomId)}`, {
			method: 'POST',
			body: bytes as BodyInit,
		}).catch(() => {
			/* server may not support file storage, fall back silently */
		});
	}
}

function handleStopCollaboration(): void {
	collaborationConfig.value = null;
	urlRoom.value = null;
	urlBroadcast.value = null;
	const url = new URL(window.location.href);
	url.searchParams.delete('room');
	url.searchParams.delete('broadcast');
	url.searchParams.delete('server');
	url.searchParams.delete('transport');
	url.searchParams.delete('signaling');
	url.searchParams.delete('name');
	window.history.replaceState({}, '', url.toString());
}

// Auto-load the bundled sample deck when `?sample=1` is present, so a
// `?sample=1&room=…` host pane seeds the session with the sample. Waits for the
// restore check below: a tab that already has a deck of its own must not have
// the sample dropped back on top of it.
watchEffect((onCleanup) => {
	if (!restoreChecked.value || !urlSample || content.value) {
		return;
	}
	let cancelled = false;
	void fetch(`${import.meta.env.BASE_URL}sample-deck.pptx`)
		.then((res) => {
			if (!res.ok) {
				throw new Error(`HTTP ${res.status}`);
			}
			return res.arrayBuffer();
		})
		.then((buf) => {
			if (!cancelled && !content.value) {
				content.value = new Uint8Array(buf);
				fileName.value = 'sample-deck.pptx';
			}
			return undefined;
		})
		.catch(() => {
			// Sample not available: fall through to the regular dropzone.
		});
	onCleanup(() => {
		cancelled = true;
	});
});

// When joining via URL with a room/broadcast param, download PPTX from the
// collab server, but ONLY if the server is in the trusted-host allowlist.
const joinRoomId = computed(() => urlRoom.value ?? urlBroadcast.value);
watchEffect((onCleanup) => {
	const roomId = joinRoomId.value;
	if (!roomId || content.value) {
		return;
	}
	// Serverless webrtc joins have no file server: the deck arrives via Y.Doc
	// late-joiner sync, so skip the HTTP fetch entirely.
	if (isWebrtcJoin) {
		return;
	}
	if (!isTrustedServerUrl(urlServer)) {
		console.warn(
			`Refusing to fetch presentation from untrusted ?server=${urlServer}. Add the host to TRUSTED_COLLAB_HOSTS or use the Share dialog.`,
		);
		return;
	}
	let cancelled = false;
	const httpUrl = urlServer.replace(/^ws/u, 'http');
	void fetch(`${httpUrl}/file/${encodeURIComponent(roomId)}`)
		.then((res) => {
			if (!res.ok) {
				throw new Error('Not found');
			}
			return res.arrayBuffer();
		})
		.then((buf) => {
			if (cancelled) {
				return undefined;
			}
			content.value = new Uint8Array(buf);
			fileName.value = urlBroadcast.value ? 'Broadcast Session' : 'Collaboration Session';
			return undefined;
		})
		.catch(() => {
			// File not available on server, user will need to load manually.
		});
	onCleanup(() => {
		cancelled = true;
	});
});

// Fallback: try IndexedDB if server download didn't work (same-browser tabs).
// A `?sample=1` host seeds the session from the bundled deck instead, so never
// race it with the IndexedDB / blank-deck fallbacks.
watchEffect((onCleanup) => {
	if (!joinRoomId.value || content.value || urlSample) {
		return;
	}
	let cancelled = false;
	const timer = setTimeout(() => {
		void loadAudienceContent().then((bytes) => {
			if (cancelled || !bytes) {
				return undefined;
			}
			content.value = bytes;
			fileName.value = 'Collaboration Session';
			return undefined;
		});
	}, 1500);
	onCleanup(() => {
		cancelled = true;
		clearTimeout(timer);
	});
});

// Serverless webrtc joins have no file server and no IndexedDB seed: bootstrap
// a blank deck so the viewer mounts and starts collaborating. The owner's real
// slides then arrive through Y.Doc late-joiner sync and replace the blank deck.
watchEffect((onCleanup) => {
	if (!isWebrtcJoin || !joinRoomId.value || content.value || urlSample) {
		return;
	}
	let cancelled = false;
	void PptxHandler.createBlank({ title: 'Collaboration Session', initialSlideCount: 1 })
		.then(({ handler, data }) => handler.save(data.slides))
		.then((bytes) => {
			if (cancelled || content.value) {
				return undefined;
			}
			content.value = bytes;
			fileName.value = 'Collaboration Session';
			return undefined;
		});
	onCleanup(() => {
		cancelled = true;
	});
});

// When opened as an audience tab, load the PPTX content from IndexedDB.
onMounted(() => {
	if (!isAudienceTab()) {
		return;
	}
	void loadAudienceContent(parsePresentationSessionId(window.location.hash) ?? undefined).then(
		(bytes) => {
			if (!bytes) {
				return undefined;
			}
			content.value = bytes;
			fileName.value = 'Audience View';
			return undefined;
		},
	);
});

// ── Refresh survival ───────────────────────────────────────────────────────
// Remember the open deck for THIS tab, and reopen it on the next load. A
// refresh used to drop the presentation and land the user back on the file
// picker; now it comes back, with any autosaved edits (restoreSessionDeck
// prefers the newer of the two). An audience tab is fed by the presenter
// window, so it neither remembers nor restores.
watchEffect(() => {
	const bytes = content.value;
	if (!bytes || isAudienceTab()) {
		return;
	}
	void rememberSessionDeck(fileName.value, bytes);
});

onMounted(() => {
	// Collaboration / broadcast / audience tabs are fed by the session; they never
	// restore, and must not hold the sample fetch up either.
	if (joinRoomId.value || isAudienceTab()) {
		restoreChecked.value = true;
		return;
	}
	void restoreSessionDeck().then((deck) => {
		if (deck && !content.value) {
			// This tab has moved on from the bundled sample (the user opened a deck
			// of their own, possibly through the viewer's own File > Open), so a
			// leftover `?sample=1` must not re-seed it on the next refresh.
			dropSampleParam();
			content.value = deck.data;
			fileName.value = deck.fileName;
		}
		restoreChecked.value = true;
		return undefined;
	});
});

/**
 * Drop `?sample=1` from the address bar.
 *
 * The docs landing page embeds the demo with `?sample=1` so it opens
 * pre-populated. Once the user opens a deck of their own that param is stale:
 * left in place it would re-seed the bundled sample on the next refresh and
 * throw away what they were looking at.
 */
function dropSampleParam(): void {
	const url = new URL(window.location.href);
	if (!url.searchParams.has('sample')) {
		return;
	}
	url.searchParams.delete('sample');
	window.history.replaceState({}, '', url.toString());
}

// Update document title when in collaboration/broadcast mode.
watchEffect(() => {
	const config = collaborationConfig.value;
	if (config && content.value) {
		const prefix =
			config.role === 'owner'
				? '[Broadcasting]'
				: config.role === 'viewer'
					? '[Watching]'
					: '[Collab]';
		document.title = `${prefix} ${fileName.value} - PPTX Viewer`;
	}
});

// Reflect the loaded deck's name in the document title (all other demos do
// this). The collaboration effect above owns the title while a session is
// active; otherwise show "<fileName> - PPTX Viewer", falling back to the plain
// demo title before any deck is opened.
watchEffect(() => {
	if (collaborationConfig.value) {
		return;
	}
	document.title =
		content.value && fileName.value ? `${fileName.value} - PPTX Viewer` : 'pptx-vue-viewer demo';
});

function onDirtyChange(dirty: boolean): void {
	document.title = dirty ? `* ${fileName.value} - PPTX Viewer` : `${fileName.value} - PPTX Viewer`;
}

// ── Loading ────────────────────────────────────────────────────────────────
function loadFile(file: File): void {
	dropSampleParam();
	fileName.value = file.name;
	const reader = new FileReader();
	reader.onload = () => {
		content.value = new Uint8Array(reader.result as ArrayBuffer);
	};
	reader.readAsArrayBuffer(file);
}

async function newPresentation(): Promise<void> {
	dropSampleParam();
	const { handler, data } = await PptxHandler.createBlank({
		title: 'Untitled Presentation',
		initialSlideCount: 1,
	});
	content.value = await handler.save(data.slides);
	fileName.value = 'Untitled Presentation';
}

function onDrop(e: DragEvent): void {
	e.preventDefault();
	const file = e.dataTransfer?.files?.[0];
	if (file && isSupportedPresentationFile(file.name)) {
		loadFile(file);
	}
}

function onInputChange(e: Event): void {
	const file = (e.target as HTMLInputElement).files?.[0];
	if (file) {
		loadFile(file);
	}
}

const fileInput = ref<HTMLInputElement | null>(null);

/** Open the native picker from the explicit Browse control. */
function openFilePicker(): void {
	fileInput.value?.click();
}

/**
 * The dashed zone paints `cursor: pointer` over its whole area and the copy
 * says "click to browse", so the whole area has to open the picker, not just
 * the one text line that happens to be a <label>. Clicks that originate on a
 * button, on the label, or on the input itself are already handled by those
 * elements; re-opening from here would double-fire or loop.
 */
function onZoneClick(e: MouseEvent): void {
	if ((e.target as HTMLElement).closest('button, label[for="file-input"], #file-input')) {
		return;
	}
	openFilePicker();
}
</script>

<template>
	<main v-if="content" class="demo-shell">
		<PowerPointViewer
			:content="content"
			:file-name="fileName"
			autosave
			:autosave-interval-ms="2000"
			can-edit
			:smartArt3D="smartArt3D"
			:surfaceChart3D="surfaceChart3D"
			:barChart3D="barChart3D"
			:lineChart3D="lineChart3D"
			:areaChart3D="areaChart3D"
			:pieChart3D="pieChart3D"
			:ai="aiConfig"
			:author-name="collaborationConfig?.userName ?? autoName"
			:collaboration="collaborationConfig ?? undefined"
			:share-defaults="{ roomId: autoRoomId, userName: autoName, serverUrl: defaultServerUrl }"
			@start-collaboration="handleStartCollaboration"
			@stop-collaboration="handleStopCollaboration"
			@dirty-change="onDirtyChange"
		/>
	</main>

	<main v-else class="demo-stage">
		<h1 class="sr-only">PPTX Viewer</h1>
		<div
			class="demo-dropzone"
			role="group"
			data-testid="dropzone"
			:aria-label="t('demo.dropzone.uploadAriaLabel')"
			@click="onZoneClick"
			@drop="onDrop"
			@dragover.prevent
		>
			<template v-if="urlBroadcast">
				<p class="demo-join">
					{{ t('demo.dropzone.joiningBroadcast') }} <code>{{ urlBroadcast }}</code>
				</p>
				<p class="demo-hint">{{ t('demo.dropzone.loadingBroadcast') }}</p>
			</template>
			<template v-else-if="urlRoom">
				<p class="demo-join">
					{{ t('demo.dropzone.joiningSession') }} <code>{{ urlRoom }}</code>
				</p>
				<label class="demo-hint" for="file-input">{{ t('demo.dropzone.hintCollab') }}</label>
			</template>
			<template v-else>
				<label class="demo-hint" for="file-input">{{ t('demo.dropzone.hint') }}</label>
			</template>
			<p class="demo-sub">{{ t('demo.dropzone.processed') }}</p>
			<div class="demo-actions">
				<button
					type="button"
					class="demo-browse"
					data-testid="browse-files"
					@click.stop="openFilePicker"
				>
					{{ t('demo.dropzone.browse') }}
				</button>
				<button type="button" @click.stop="newPresentation">
					{{ t('demo.dropzone.newPresentation') }}
				</button>
			</div>
			<input
				id="file-input"
				ref="fileInput"
				type="file"
				:accept="PPTX_OPEN_ACCEPT"
				:aria-label="t('demo.dropzone.uploadAriaLabel')"
				class="sr-only"
				@change="onInputChange"
			/>
		</div>
	</main>
</template>

<style>
body {
	font-family:
		system-ui,
		-apple-system,
		'Segoe UI',
		Roboto,
		sans-serif;
	/* Never let demo chrome overflow horizontally; on mobile a wider-than-viewport
	   page expands the layout viewport and mis-anchors the viewer's fixed bottom bar. */
	overflow-x: hidden;
}

.demo-shell {
	height: 100dvh;
	width: 100vw;
}

.demo-stage {
	display: flex;
	align-items: center;
	justify-content: center;
	height: 100dvh;
	width: 100vw;
	padding: 2rem;
	color: var(--pptx-foreground, #f3f4f6);
	background: var(--pptx-background, #030712);
}

/*
 * Kept metric-for-metric identical to the React demo's landing card, which is
 * the reference for demo chrome: 900px cap, 3rem padding, 12px hint gap, 16px
 * before the action row, 14px secondary text, and the same corner radii. The
 * Vue card used to run 16px taller with a smaller sub-line, so the two demos
 * did not line up side by side at 1920x1080.
 */
.demo-dropzone {
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
	max-width: 900px;
	width: 100%;
	padding: 3rem;
	text-align: center;
	border: 2px dashed var(--pptx-border, #374151);
	border-radius: 0.625rem;
	cursor: pointer;
	transition:
		border-color 0.15s,
		background 0.15s;
}

.demo-dropzone:hover {
	border-color: var(--pptx-primary, #6366f1);
	background: var(--pptx-accent, #1f2937);
}

.demo-join {
	margin: 0 0 0.5rem;
	font-weight: 500;
	color: var(--pptx-foreground, #f3f4f6);
}

.demo-hint {
	display: block;
	margin: 0;
	font-size: 1rem;
	color: var(--pptx-muted-foreground, #9ca3af);
	/* The copy says "click to browse" and the label really does open the picker,
	   so the pointer has to confirm it (the dashed card's `cursor: pointer` does
	   not reach a <label>, which resets to the default arrow). */
	cursor: pointer;
}

.demo-sub {
	margin: 0;
	font-size: 0.875rem;
	color: var(--pptx-muted-foreground, #9ca3af);
}

.sr-only {
	position: absolute;
	width: 1px;
	height: 1px;
	padding: 0;
	margin: -1px;
	overflow: hidden;
	clip: rect(0, 0, 0, 0);
	white-space: nowrap;
	border: 0;
}

.demo-dropzone code {
	padding: 0.1rem 0.3rem;
	border-radius: 0.25rem;
	background: var(--pptx-muted, #1f2937);
	color: var(--pptx-primary, #6366f1);
	font-family: ui-monospace, monospace;
}

.demo-actions {
	display: flex;
	flex-wrap: wrap;
	align-items: center;
	justify-content: center;
	gap: 0.5rem;
	margin-top: 1rem;
}

.demo-dropzone button {
	padding: 0.5rem 1rem;
	border-radius: 0.375rem;
	border: 1px solid var(--pptx-border, #374151);
	background: var(--pptx-muted, #1f2937);
	color: var(--pptx-foreground, #f3f4f6);
	font-size: 0.875rem;
	cursor: pointer;
	transition: background 0.15s;
}

.demo-dropzone button:hover {
	background: var(--pptx-accent, #1f2937);
}

/* The primary call to action: the explicit "browse" control the copy promises. */
.demo-dropzone button.demo-browse {
	border-color: var(--pptx-primary, #6366f1);
	background: var(--pptx-primary, #6366f1);
	color: var(--pptx-primary-foreground, #ffffff);
	font-weight: 500;
}

.demo-dropzone button.demo-browse:hover {
	background: var(--pptx-primary, #6366f1);
	opacity: 0.9;
}
</style>

// demos/demo-angular/src/app.component.ts
import {
	ChangeDetectionStrategy,
	Component,
	computed,
	effect,
	inject,
	signal,
} from '@angular/core';
import { TranslateService } from '@ngx-translate/core';
import {
	isAudienceTab,
	loadAudienceContent,
	parseAudienceNonce,
	PowerPointViewerComponent,
	rememberSessionDeck,
	restoreSessionDeck,
	themeToCssVars,
	translationsEn,
} from 'pptx-angular-viewer';
import type { CollaborationConfig, PptxAiConfig, ViewerTheme } from 'pptx-angular-viewer';
import { PptxHandler } from 'pptx-viewer-core';
import 'pptx-angular-viewer/styles';
import { translationsDe, translationsEs, translationsFr } from 'pptx-viewer-locales';

import { buildDemoAiConfig, readStoredAiFields } from './ai-config';
import {
	ensureAutoRoomId,
	generateAutoName,
	isTrustedServerUrl,
	randomCursorColor,
	resolveDefaultServerUrl,
} from './collab-utils';
import { demoStringsDe, demoStringsEn, demoStringsFr, demoStringsEs } from './demo-locales';
import { DropzoneComponent } from './dropzone.component';
import { restoreLanguageKey } from './languages';
import { restoreThemeKey, THEMES } from './themes';

type DemoContent = Uint8Array | ArrayBuffer;

/**
 * Angular demo app: mirrors the React demo (demos/demo-react/main.tsx).
 *
 * There is no header bar; the viewer fills the screen. Collaboration, broadcast,
 * and audience flows are driven from URL params and auto-connect to trusted servers only.
 */
@Component({
	selector: 'app-root',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [PowerPointViewerComponent, DropzoneComponent],
	styles: [
		`
			:host {
				display: block;
				height: 100dvh;
				width: 100vw;
				overflow: hidden;
				font-family:
					system-ui,
					-apple-system,
					'Segoe UI',
					Roboto,
					sans-serif;
			}
			.demo-viewer-host {
				height: 100dvh;
				width: 100vw;
			}
		`,
	],
	template: `
		@if (content()) {
			<main class="demo-viewer-host">
				<pptx-viewer
					[content]="content()!"
					[canEdit]="true"
					[fileName]="fileName()"
					[filePath]="fileName() || undefined"
					[autosaveIntervalMs]="2000"
					[smartArt3D]="smartArt3D"
					[surfaceChart3D]="surfaceChart3D"
					[barChart3D]="barChart3D"
					[lineChart3D]="lineChart3D"
					[areaChart3D]="areaChart3D"
					[pieChart3D]="pieChart3D"
					[authorName]="autoName"
					[shareDefaults]="{ roomId: autoRoomId, userName: autoName, serverUrl: defaultServerUrl }"
					[collaboration]="collaborationConfig() ?? undefined"
					[ai]="aiConfig() ?? undefined"
					(startCollaboration)="handleStartCollaboration($event)"
					(stopCollaboration)="handleStopCollaboration()"
					(dirtyChange)="onDirtyChange($event)"
				/>
			</main>
		} @else {
			<app-dropzone
				[theme]="activeTheme()"
				[urlRoom]="urlRoom"
				[urlBroadcast]="urlBroadcast"
				[busy]="isBusy()"
				(file)="loadFile($event)"
				(create)="newPresentation()"
			/>
		}
	`,
})
export class AppComponent {
	readonly content = signal<DemoContent | null>(null);
	readonly fileName = signal<string>('');
	readonly themeKey = signal<string>(restoreThemeKey());
	readonly languageKey = signal<string>(restoreLanguageKey());
	readonly isBusy = signal<boolean>(false);
	private readonly translate = inject(TranslateService);

	private readonly params = new URLSearchParams(window.location.search);
	/** Opt in to the experimental Three.js SmartArt renderer via `?smartArt3D=1`. */
	readonly smartArt3D = this.params.get('smartArt3D') === '1';
	/**
	 * Opt in to the experimental Three.js interactive surface-chart renderer
	 * (camera orbit/zoom + raycast hover tooltip) via `?surfaceChart3D=1`.
	 */
	readonly surfaceChart3D = this.params.get('surfaceChart3D') === '1';
	/**
	 * Opt in to the experimental Three.js interactive bar3D-chart renderer
	 * (real box meshes, camera orbit/zoom) via `?barChart3D=1`.
	 */
	readonly barChart3D = this.params.get('barChart3D') === '1';
	/**
	 * Opt in to the experimental Three.js interactive line3D-chart renderer
	 * (real tube-path meshes, camera orbit/zoom) via `?lineChart3D=1`.
	 */
	readonly lineChart3D = this.params.get('lineChart3D') === '1';
	/**
	 * Opt in to the experimental Three.js interactive area3D-chart renderer
	 * (real tube-path + ribbon meshes, camera orbit/zoom) via `?areaChart3D=1`.
	 */
	readonly areaChart3D = this.params.get('areaChart3D') === '1';
	/**
	 * Opt in to the experimental Three.js interactive pie3D-chart renderer
	 * (real wedge meshes, camera orbit/zoom) via `?pieChart3D=1`.
	 */
	readonly pieChart3D = this.params.get('pieChart3D') === '1';
	/** `?sample=1` auto-loads the bundled sample deck (docs landing embed). */
	private readonly urlSample = this.params.get('sample') === '1';
	readonly urlRoom = this.params.get('room');
	readonly urlBroadcast = this.params.get('broadcast');
	private readonly urlServer = this.params.get('server') ?? resolveDefaultServerUrl();
	private readonly urlName = this.params.get('name');
	/** Serverless peer-to-peer join requested via `?transport=webrtc`. */
	private readonly webrtcRequested = this.params.get('transport') === 'webrtc';
	/** Optional `?signaling=a,b` WebRTC signaling server override. */
	private readonly signaling = (this.params.get('signaling') ?? '')
		.split(',')
		.map((s) => s.trim())
		.filter((s) => s.length > 0);

	readonly autoName = generateAutoName();
	/** Stable per-session room id, seeded into the Share dialog defaults. */
	readonly autoRoomId = ensureAutoRoomId();
	/** Default collaboration server URL for the Share dialog (trusted ws relay in dev). */
	readonly defaultServerUrl = resolveDefaultServerUrl();

	readonly collaborationConfig = signal<CollaborationConfig | null>(null);

	/**
	 * Viewer `ai` config built from localStorage-supplied fields, or undefined
	 * when nothing is stored. The demo ships no key and no config UI, so this is
	 * normally undefined and the assistant simply stays off.
	 */
	readonly aiConfig = signal<PptxAiConfig | undefined>(buildDemoAiConfig(readStoredAiFields()));

	readonly activeTheme = computed<ViewerTheme>(
		() => (THEMES[this.themeKey()] ?? THEMES['vermilionDark']).theme,
	);

	/** CSS-custom-property keys applied to `:root` by the most recent theme, so
	 *  the next theme change can clear them before applying its own. */
	private appliedRootVarKeys: string[] = [];

	constructor() {
		// Mirror the React demo's `useRootTheme`: write the active theme's
		// `--pptx-*` / `--color-*` custom properties onto `document.documentElement`
		// so BOTH the landing dropzone and the mounted viewer chrome track the
		// picker. The viewer never receives a `[theme]` input (that would disable
		// its own Settings > Appearance picker); it derives every colour from
		// these root vars, falling back to the built-in dark palette when unset.
		effect(() => {
			const vars = themeToCssVars(this.activeTheme());
			const root = document.documentElement;
			for (const key of this.appliedRootVarKeys) {
				root.style.removeProperty(key);
			}
			const keys = Object.keys(vars);
			for (const key of keys) {
				root.style.setProperty(key, vars[key]);
			}
			this.appliedRootVarKeys = keys;
		});

		this.translate.setTranslation('en', { ...translationsEn, ...demoStringsEn });
		this.translate.setTranslation('fr', { ...translationsFr, ...demoStringsFr });
		this.translate.setTranslation('es', { ...translationsEs, ...demoStringsEs });
		this.translate.setTranslation('de', { ...translationsDe, ...demoStringsDe });
		this.translate.use(this.languageKey());

		this.autoConnectFromUrl();
		// Restore first: a tab that already has a deck of its own must not have the
		// `?sample=1` deck dropped back on top of it.
		void this.restoreSession().then(() => this.loadSampleFromUrl());
		this.joinFromUrl();
		void this.loadAudienceTab();

		// Remember the open deck for THIS tab so the next load can reopen it (see
		// `restoreSession`). Audience tabs are fed by the presenter, never restored.
		effect(() => {
			const bytes = this.content();
			const name = this.fileName();
			if (!bytes || isAudienceTab()) {
				return;
			}
			void rememberSessionDeck(name, bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes));
		});

		// Keep the document title in sync with the collaboration / broadcast role.
		effect(() => {
			const config = this.collaborationConfig();
			const loaded = this.content();
			if (config && loaded) {
				const prefix =
					config.role === 'viewer'
						? '[Watching]'
						: config.role === 'owner'
							? '[Broadcasting]'
							: '[Collab]';
				document.title = `${prefix} ${this.fileName()} - PPTX Viewer`;
			}
		});
	}

	onDirtyChange(dirty: boolean): void {
		const name = this.fileName();
		document.title = dirty ? `* ${name} - PPTX Viewer` : `${name} - PPTX Viewer`;
	}

	/**
	 * Started a Share or Broadcast session from the viewer's dialog: persist the
	 * config, reflect it in the URL (`?broadcast=` for owner role, else `?room=`)
	 * and upload the deck bytes so joiners can download it (trusted hosts only).
	 */
	handleStartCollaboration(config: CollaborationConfig): void {
		this.collaborationConfig.set(config);
		const url = new URL(window.location.href);
		if (config.role === 'owner') {
			url.searchParams.set('broadcast', config.roomId);
		} else {
			url.searchParams.set('room', config.roomId);
		}
		if (config.transport === 'webrtc') {
			// Serverless P2P: carry the transport, not a (blank) server URL.
			url.searchParams.set('transport', 'webrtc');
			url.searchParams.delete('server');
			if (config.signaling?.length) {
				url.searchParams.set('signaling', config.signaling.join(','));
			}
		} else {
			url.searchParams.set('server', config.serverUrl);
			url.searchParams.delete('transport');
			url.searchParams.delete('signaling');
		}
		window.history.replaceState({}, '', url.toString());
		const bytes = this.content();
		// P2P has no file server; joiners receive the deck via Y.Doc sync instead.
		if (
			config.sessionIntent !== 'join' &&
			bytes &&
			config.transport !== 'webrtc' &&
			isTrustedServerUrl(config.serverUrl)
		) {
			const httpUrl = config.serverUrl.replace(/^ws/u, 'http');
			void fetch(`${httpUrl}/file/${encodeURIComponent(config.roomId)}`, {
				method: 'POST',
				body: bytes as BodyInit,
			}).catch(() => {
				// Server may not support file storage; joiners fall back to IndexedDB.
			});
		}
	}

	/** Stopped collaborating: clear the config and strip the URL params. */
	handleStopCollaboration(): void {
		this.collaborationConfig.set(null);
		const url = new URL(window.location.href);
		url.searchParams.delete('room');
		url.searchParams.delete('broadcast');
		url.searchParams.delete('server');
		url.searchParams.delete('transport');
		url.searchParams.delete('signaling');
		url.searchParams.delete('name');
		window.history.replaceState({}, '', url.toString());
	}

	// ── File loading ─────────────────────────────────────────────────────────
	async loadFile(file: File): Promise<void> {
		this.dropSampleParam();
		this.fileName.set(file.name);
		this.content.set(new Uint8Array(await file.arrayBuffer()));
	}

	async newPresentation(): Promise<void> {
		this.dropSampleParam();
		this.isBusy.set(true);
		try {
			const { handler, data } = await PptxHandler.createBlank({
				title: 'Untitled Presentation',
				initialSlideCount: 1,
			});
			const bytes = await handler.save(data.slides);
			this.content.set(bytes);
			this.fileName.set('Untitled Presentation');
		} finally {
			this.isBusy.set(false);
		}
	}

	/**
	 * Drop `?sample=1` from the address bar.
	 *
	 * The docs landing page embeds the demo with `?sample=1` so it opens
	 * pre-populated. Once the user opens a deck of their own that param is stale:
	 * left in place it would re-seed the bundled sample on the next refresh and
	 * throw away what they were looking at.
	 */
	private dropSampleParam(): void {
		const url = new URL(window.location.href);
		if (!url.searchParams.has('sample')) {
			return;
		}
		url.searchParams.delete('sample');
		window.history.replaceState({}, '', url.toString());
	}

	/**
	 * Reopen the deck this tab had before a refresh (with any autosaved edits;
	 * `restoreSessionDeck` prefers whichever of the two is newer).
	 */
	private async restoreSession(): Promise<void> {
		// Collaboration / broadcast / audience tabs are fed by the session and never
		// restore.
		if (this.content() || this.urlRoom || this.urlBroadcast || isAudienceTab()) {
			return;
		}
		const deck = await restoreSessionDeck();
		if (!deck || this.content()) {
			return;
		}
		// This tab has moved on from the bundled sample (the user opened a deck of
		// their own, possibly through the viewer's own File > Open), so a leftover
		// `?sample=1` must not re-seed it on the next refresh.
		this.dropSampleParam();
		this.content.set(deck.data);
		this.fileName.set(deck.fileName);
	}

	// ── Collaboration / broadcast / audience wiring ──────────────────────────
	private autoConnectFromUrl(): void {
		const joinRoomId = this.urlRoom ?? this.urlBroadcast;
		if (!joinRoomId) {
			return;
		}
		const role = this.urlBroadcast ? ('viewer' as const) : undefined;

		// Serverless peer-to-peer: no server to trust; join over WebRTC directly.
		if (this.webrtcRequested) {
			this.collaborationConfig.set({
				roomId: joinRoomId,
				serverUrl: '',
				transport: 'webrtc',
				...(this.signaling.length > 0 ? { signaling: this.signaling } : {}),
				userName: this.urlName ?? this.autoName,
				userColor: randomCursorColor(),
				...(role ? { role } : {}),
			});
			return;
		}

		if (!isTrustedServerUrl(this.urlServer)) {
			console.warn(
				`Ignoring auto-connect because ?server=${this.urlServer} is not in the trusted-host allowlist. Use the Share dialog to connect explicitly.`,
			);
			return;
		}
		this.collaborationConfig.set({
			roomId: joinRoomId,
			serverUrl: this.urlServer,
			userName: this.urlName ?? this.autoName,
			userColor: randomCursorColor(),
			...(role ? { role } : {}),
		});
	}

	/**
	 * Auto-load the bundled sample deck when `?sample=1` is present (docs landing
	 * embed), so a `?sample=1&room=…` host pane seeds the session with the sample.
	 */
	private async loadSampleFromUrl(): Promise<void> {
		if (!this.urlSample || this.content()) {
			return;
		}
		try {
			const res = await fetch(`${import.meta.env.BASE_URL}sample-deck.pptx`);
			if (!res.ok) {
				throw new Error(`HTTP ${res.status}`);
			}
			const buf = await res.arrayBuffer();
			if (this.content()) {
				return;
			}
			this.content.set(new Uint8Array(buf));
			this.fileName.set('sample-deck.pptx');
		} catch {
			// Sample not available: fall through to the regular dropzone.
		}
	}

	private joinFromUrl(): void {
		const joinRoomId = this.urlRoom ?? this.urlBroadcast;
		// A `?sample=1` host seeds the session from the bundled deck instead, so
		// never race it with the blank-deck / IndexedDB fallbacks.
		if (!joinRoomId || this.content() || this.urlSample) {
			return;
		}
		// Serverless peer-to-peer: there is no file server to fetch from. Bootstrap
		// a placeholder deck so the viewer mounts and connects; the Y.Doc
		// late-joiner sync then populates the real slides via applyRemoteSlides.
		if (this.webrtcRequested) {
			void this.bootstrapForRemoteSync();
			return;
		}
		if (!isTrustedServerUrl(this.urlServer)) {
			console.warn(
				`Refusing to fetch presentation from untrusted ?server=${this.urlServer}. Add the host to the trusted-host allowlist or use the Share dialog.`,
			);
			return;
		}
		void this.downloadFromServer(joinRoomId);
		this.scheduleAudienceFallback();
	}

	/** Bootstrap a blank deck so a serverless (webrtc) joiner mounts + syncs. */
	private async bootstrapForRemoteSync(): Promise<void> {
		if (this.content()) {
			return;
		}
		const { handler, data } = await PptxHandler.createBlank({
			title: 'Collaboration Session',
			initialSlideCount: 1,
		});
		const bytes = await handler.save(data.slides);
		if (this.content()) {
			return;
		}
		this.content.set(bytes);
		this.fileName.set(this.urlBroadcast ? 'Broadcast Session' : 'Collaboration Session');
	}

	private async downloadFromServer(joinRoomId: string): Promise<void> {
		const httpUrl = this.urlServer.replace(/^ws/u, 'http');
		try {
			const res = await fetch(`${httpUrl}/file/${encodeURIComponent(joinRoomId)}`);
			if (!res.ok) {
				throw new Error('Not found');
			}
			const buf = await res.arrayBuffer();
			if (this.content()) {
				return;
			}
			this.content.set(new Uint8Array(buf));
			this.fileName.set(this.urlBroadcast ? 'Broadcast Session' : 'Collaboration Session');
		} catch {
			// File not available on server; the IndexedDB fallback may still recover it.
		}
	}

	/** Fallback: try IndexedDB if the server download didn't work (same-browser tabs). */
	private scheduleAudienceFallback(): void {
		setTimeout(() => {
			void this.tryAudienceFallback();
		}, 1500);
	}

	private async tryAudienceFallback(): Promise<void> {
		if (this.content()) {
			return;
		}
		const bytes = await loadAudienceContent();
		if (!bytes || this.content()) {
			return;
		}
		this.content.set(bytes);
		this.fileName.set('Collaboration Session');
	}

	/** When opened as an audience tab, load the PPTX content from IndexedDB. */
	private async loadAudienceTab(): Promise<void> {
		if (!isAudienceTab()) {
			return;
		}
		const bytes = await loadAudienceContent(parseAudienceNonce() ?? undefined);
		if (!bytes || this.content()) {
			return;
		}
		this.content.set(bytes);
		this.fileName.set('Audience View');
	}
}
