// packages/angular/src/viewer/action-settings-panel.component.ts
import {
	ChangeDetectionStrategy,
	Component,
	computed,
	inject,
	input,
	output,
	signal,
} from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import type {
	ElementAction,
	ElementActionType,
	PptxCustomShow,
	PptxElement,
} from 'pptx-viewer-core';
import { elementActionToPptxAction, pptxActionToElementAction } from 'pptx-viewer-core';

import {
	canCommitActionType,
	ELEMENT_ACTION_TYPE_OPTIONS,
	resolveActionType,
	toSlideIndex,
} from '../internal/shared';
import { ActionTargetFieldsComponent } from './action-target-fields.component';
import { LoadContentService } from './load-content.service';

type Trigger = 'click' | 'hover';

/** A type the user picked, remembered against the element it was picked on. */
export interface PendingActionType {
	elementId: string;
	types: Partial<Record<Trigger, ElementActionType>>;
}

/** Nothing picked yet. */
export const NO_PENDING_ACTION_TYPE: PendingActionType = { elementId: '', types: {} };

/**
 * Record the type the user just picked for one trigger.
 *
 * A pick belongs to the element it was made on, so a pick for a different
 * element replaces the whole record instead of merging: otherwise selecting
 * another shape would show it a half-made choice it never had.
 */
export function withPendingActionType(
	previous: PendingActionType,
	elementId: string,
	trigger: Trigger,
	type: ElementActionType,
): PendingActionType {
	const types = previous.elementId === elementId ? previous.types : {};
	return { elementId, types: { ...types, [trigger]: type } };
}

/**
 * The action type a trigger's controls should render, which is also the
 * predicate deciding whether the URL / slide input exists.
 *
 * Exported (and pure) so it can be unit-tested without a TestBed, matching the
 * rest of this package; see `inspector-panel.component.ts` for the convention.
 */
export function displayedActionType(
	pending: PendingActionType,
	elementId: string,
	trigger: Trigger,
	committedType: ElementActionType | undefined,
): ElementActionType {
	const picked = pending.elementId === elementId ? pending.types[trigger] : undefined;
	return resolveActionType(picked, committedType);
}

@Component({
	selector: 'pptx-action-settings-panel',
	standalone: true,
	imports: [TranslatePipe, ActionTargetFieldsComponent],
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `
		<section class="pptx-ng-action">
			<h3 class="pptx-ng-action__heading">{{ 'pptx.action.title' | translate }}</h3>
			@for (trigger of triggers; track trigger) {
				<div class="pptx-ng-action__trigger">
					<label class="pptx-ng-action__label" [for]="'action-' + trigger">
						{{ (trigger === 'click' ? 'pptx.action.onClick' : 'pptx.action.onHover') | translate }}
					</label>
					<select
						[id]="'action-' + trigger"
						class="pptx-ng-action__input"
						[value]="typeFor(trigger)"
						(change)="onType($event, trigger)"
					>
						@for (option of actionTypes; track option.value) {
							<option [value]="option.value" [selected]="option.value === typeFor(trigger)">
								{{ option.labelKey | translate }}
							</option>
						}
					</select>
					<pptx-action-target-fields
						[type]="typeFor(trigger)"
						[action]="actionFor(trigger)"
						[slideCount]="slideCount()"
						[customShows]="customShows()"
						[idPrefix]="'action-' + trigger"
						(urlChange)="onUrl($event, trigger)"
						(slideChange)="onSlide($event, trigger)"
						(customShowChange)="onCustomShow($event, trigger)"
						(returnAfterChange)="onReturnAfter($event, trigger)"
					/>
				</div>
			}
		</section>
	`,
	styles: `
		.pptx-ng-action {
			display: grid;
			gap: 8px;
		}
		.pptx-ng-action__heading {
			margin: 0;
			color: var(--pptx-inspector-muted, #aaa);
			font-size: 11px;
			letter-spacing: 0.04em;
			text-transform: uppercase;
		}
		.pptx-ng-action__trigger {
			display: grid;
			gap: 4px;
		}
		.pptx-ng-action__label {
			color: var(--pptx-inspector-muted, #aaa);
			font-size: 11px;
			font-weight: 600;
		}
		.pptx-ng-action__input {
			box-sizing: border-box;
			width: 100%;
			padding: 4px 6px;
			border: 1px solid var(--pptx-inspector-border, #444);
			border-radius: 3px;
			background: var(--pptx-inspector-input-bg, #2d2d2d);
			color: inherit;
			font-size: 11px;
		}
	`,
})
export class ActionSettingsPanelComponent {
	readonly element = input.required<PptxElement>();
	readonly slideCount = input(0);
	readonly patch = output<Partial<PptxElement>>();

	protected readonly triggers = ['click', 'hover'] as const;
	protected readonly actionTypes = ELEMENT_ACTION_TYPE_OPTIONS;
	/**
	 * The type the user just picked, per trigger.
	 *
	 * WHY it exists: "Go to URL" / "Go to Slide" only become a stored action once
	 * they carry a target, so controls driven purely by the committed element
	 * never revealed the input needed to supply that target, leaving both kinds
	 * unreachable. The pick is tagged with its element id so moving the inspector
	 * to another shape does not carry a half-made choice across.
	 */
	private readonly pending = signal<PendingActionType>(NO_PENDING_ACTION_TYPE);
	private readonly clickAction = computed(() =>
		this.element().actionClick
			? pptxActionToElementAction(this.element().actionClick!, 'click')
			: undefined,
	);
	private readonly hoverAction = computed(() =>
		this.element().actionHover
			? pptxActionToElementAction(this.element().actionHover!, 'hover')
			: undefined,
	);

	protected actionFor(trigger: Trigger): ElementAction | undefined {
		return trigger === 'click' ? this.clickAction() : this.hoverAction();
	}

	/** The action type this trigger's controls should render right now. */
	protected typeFor(trigger: Trigger): ElementActionType {
		return displayedActionType(
			this.pending(),
			this.element().id,
			trigger,
			this.actionFor(trigger)?.type,
		);
	}

	/** `data.customShows`, for the `customShow` type's target `<select>`. */
	private readonly loader = inject(LoadContentService, { optional: true });
	protected readonly customShows = computed<readonly PptxCustomShow[]>(
		() => this.loader?.customShows() ?? [],
	);

	private update(trigger: Trigger, next: Partial<ElementAction>): void {
		const type = next.type ?? this.typeFor(trigger);
		const action = elementActionToPptxAction({
			trigger,
			...this.actionFor(trigger),
			...next,
			type,
		});
		this.patch.emit(
			(trigger === 'click'
				? { actionClick: action }
				: { actionHover: action }) as Partial<PptxElement>,
		);
	}

	protected onType(event: Event, trigger: Trigger): void {
		const type = (event.target as HTMLSelectElement).value as ElementActionType;
		const elementId = this.element().id;
		this.pending.update((previous) => withPendingActionType(previous, elementId, trigger, type));
		const current = this.actionFor(trigger);
		const target = {
			url: current?.url,
			slideIndex: current?.slideIndex,
			customShowId: current?.customShowId,
		};
		// `typeFor(trigger)` (fed by `pending` above) is what makes the target
		// control (URL / slide number / custom-show select) appear at all, the
		// same set `actionTypeNeedsTarget` names; `canCommitActionType` is the
		// separate question of whether THIS pick may be written yet (it already
		// carries a target, or needs none).
		if (canCommitActionType(type, target)) {
			this.update(trigger, { type });
		}
	}

	protected onUrl(url: string, trigger: Trigger): void {
		this.update(trigger, { url });
	}

	protected onSlide(oneBasedSlide: number, trigger: Trigger): void {
		const index = toSlideIndex(oneBasedSlide, this.slideCount());
		if (index !== undefined) {
			this.update(trigger, { slideIndex: index });
		}
	}

	protected onCustomShow(customShowId: string, trigger: Trigger): void {
		if (!customShowId) {
			return;
		}
		this.update(trigger, { customShowId });
	}

	protected onReturnAfter(returnAfter: boolean, trigger: Trigger): void {
		this.update(trigger, { returnAfter });
	}
}

// packages/vue/src/viewer/components/inspector/ActionSettingsPanel.vue
<script setup lang="ts">
/**
 * ActionSettingsPanel: PowerPoint's Insert > Action dialog as an inspector
 * card, at parity with React's `inspector/ActionSettingsPanel.tsx`.
 *
 * An element carries two independent actions, one per trigger (`actionClick` /
 * `actionHover`), stored as the OOXML-shaped `PptxAction`; core's
 * `pptxActionToElementAction` / `elementActionToPptxAction` convert both ways so
 * this panel never hand-rolls a `ppaction://` URI. The option catalogue, the
 * pending-type rule and the 1-based to 0-based slide-number clamp all come from
 * `pptx-viewer-shared`, so a new action kind reaches every binding at once.
 */
import type {
	ElementAction,
	ElementActionType,
	PptxCustomShow,
	PptxElement,
} from 'pptx-viewer-core';
import { elementActionToPptxAction, pptxActionToElementAction } from 'pptx-viewer-core';
import {
	canCommitActionType,
	ELEMENT_ACTION_TYPE_OPTIONS,
	resolveActionType,
	toSlideIndex,
} from 'pptx-viewer-shared';
import { computed, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';

type Trigger = 'click' | 'hover';

const props = withDefaults(
	defineProps<{
		element: PptxElement;
		slideCount?: number;
		canEdit?: boolean;
		/** Named custom shows, for the "Custom show" target picker. */
		customShows?: readonly PptxCustomShow[];
	}>(),
	{ slideCount: 0, canEdit: true },
);
const emit = defineEmits<{ update: [patch: Partial<PptxElement>] }>();
const { t } = useI18n();

const triggers: readonly Trigger[] = ['click', 'hover'];

/**
 * The type the user just picked, per trigger.
 *
 * WHY it exists: "Go to URL" / "Go to Slide" only become a stored action once
 * they carry a target, so a select driven purely by the committed element
 * snapped straight back to "None" and the input needed to supply that target
 * never rendered, leaving both kinds unreachable.
 */
const pendingType = ref<Partial<Record<Trigger, ElementActionType>>>({});

// A pending pick belongs to the element it was made on, so drop it when the
// inspector moves to another element; otherwise the next shape would inherit a
// phantom "Go to URL" it never had.
watch(
	() => props.element.id,
	() => {
		pendingType.value = {};
	},
);

const clickAction = computed(() =>
	props.element.actionClick
		? pptxActionToElementAction(props.element.actionClick, 'click')
		: undefined,
);
const hoverAction = computed(() =>
	props.element.actionHover
		? pptxActionToElementAction(props.element.actionHover, 'hover')
		: undefined,
);

function actionFor(trigger: Trigger): ElementAction | undefined {
	return trigger === 'click' ? clickAction.value : hoverAction.value;
}

/** The action type the trigger's controls should render right now. */
function typeFor(trigger: Trigger): ElementActionType {
	return resolveActionType(pendingType.value[trigger], actionFor(trigger)?.type);
}

function update(
	trigger: Trigger,
	type: ElementActionType,
	url?: string,
	slideIndex?: number,
	customShowId?: string,
	returnAfter?: boolean,
): void {
	const action = elementActionToPptxAction({
		trigger,
		type,
		url,
		slideIndex,
		customShowId,
		returnAfter,
	});
	emit(
		'update',
		(trigger === 'click'
			? { actionClick: action }
			: { actionHover: action }) as Partial<PptxElement>,
	);
}

function onType(event: Event, trigger: Trigger): void {
	const type = (event.target as HTMLSelectElement).value as ElementActionType;
	pendingType.value = { ...pendingType.value, [trigger]: type };
	const current = actionFor(trigger);
	const target = {
		url: current?.url,
		slideIndex: current?.slideIndex,
		customShowId: current?.customShowId,
	};
	if (canCommitActionType(type, target)) {
		update(trigger, type, target.url, target.slideIndex, target.customShowId, current?.returnAfter);
	}
}

/** `url`, `openFile` and `openPresentation` all commit through the shared `url` target field. */
function onUrl(event: Event, trigger: Trigger): void {
	update(trigger, typeFor(trigger), (event.target as HTMLInputElement).value);
}

function onSlide(event: Event, trigger: Trigger): void {
	const index = toSlideIndex(Number((event.target as HTMLInputElement).value), props.slideCount);
	if (index !== undefined) {
		update(trigger, 'slide', undefined, index);
	}
}

function onCustomShow(event: Event, trigger: Trigger): void {
	const customShowId = (event.target as HTMLSelectElement).value;
	const current = actionFor(trigger);
	if (canCommitActionType('customShow', { customShowId })) {
		update(trigger, 'customShow', undefined, undefined, customShowId, current?.returnAfter);
	}
}

function onCustomShowReturn(event: Event, trigger: Trigger): void {
	const returnAfter = (event.target as HTMLInputElement).checked;
	const current = actionFor(trigger);
	if (!current?.customShowId) {
		return;
	}
	update(trigger, 'customShow', undefined, undefined, current.customShowId, returnAfter);
}
</script>

<template>
	<div class="pptx-vue-action-settings rounded border border-border bg-card p-2 space-y-2">
		<div class="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">
			{{ t('pptx.action.title') }}
		</div>
		<div v-for="trigger in triggers" :key="trigger" class="space-y-1.5">
			<label class="block text-[11px] font-medium text-muted-foreground">
				{{ t(trigger === 'click' ? 'pptx.action.onClick' : 'pptx.action.onHover') }}
			</label>
			<select
				class="w-full rounded border border-border bg-muted px-1.5 py-1 text-[11px]"
				:aria-label="t(trigger === 'click' ? 'pptx.action.onClick' : 'pptx.action.onHover')"
				:disabled="!canEdit"
				:value="typeFor(trigger)"
				@change="onType($event, trigger)"
			>
				<option
					v-for="option in ELEMENT_ACTION_TYPE_OPTIONS"
					:key="option.value"
					:value="option.value"
				>
					{{ t(option.labelKey) }}
				</option>
			</select>
			<input
				v-if="
					typeFor(trigger) === 'url' ||
					typeFor(trigger) === 'openFile' ||
					typeFor(trigger) === 'openPresentation'
				"
				:type="typeFor(trigger) === 'url' ? 'url' : 'text'"
				class="w-full rounded border border-border bg-muted px-1.5 py-1 text-[11px]"
				:aria-label="
					t(
						typeFor(trigger) === 'url'
							? 'pptx.action.gotoUrl'
							: typeFor(trigger) === 'openFile'
								? 'pptx.hyperlink.actionOpenFile'
								: 'pptx.hyperlink.actionOpenPresentation',
					)
				"
				:disabled="!canEdit"
				:value="actionFor(trigger)?.url ?? ''"
				placeholder="https://..."
				@input="onUrl($event, trigger)"
			/>
			<input
				v-if="typeFor(trigger) === 'slide'"
				type="number"
				class="w-full rounded border border-border bg-muted px-1.5 py-1 text-[11px]"
				:aria-label="t('pptx.action.gotoSlide')"
				:disabled="!canEdit"
				:min="1"
				:max="slideCount"
				:value="(actionFor(trigger)?.slideIndex ?? 0) + 1"
				@change="onSlide($event, trigger)"
			/>
			<template v-if="typeFor(trigger) === 'customShow'">
				<select
					data-testid="pptx-action-custom-show"
					class="w-full rounded border border-border bg-muted px-1.5 py-1 text-[11px]"
					:aria-label="t('pptx.hyperlink.customShowLabel')"
					:disabled="!canEdit"
					:value="actionFor(trigger)?.customShowId ?? ''"
					@change="onCustomShow($event, trigger)"
				>
					<option value="" disabled>{{ t('pptx.hyperlink.customShowLabel') }}</option>
					<option v-for="show in customShows ?? []" :key="show.id" :value="show.id">
						{{ show.name }}
					</option>
				</select>
				<label class="flex items-center gap-1.5 text-[11px] text-muted-foreground">
					<input
						type="checkbox"
						data-testid="pptx-action-custom-show-return"
						:disabled="!canEdit"
						:checked="actionFor(trigger)?.returnAfter ?? false"
						@change="onCustomShowReturn($event, trigger)"
					/>
					{{ t('pptx.hyperlink.customShowReturn') }}
				</label>
			</template>
		</div>
	</div>
</template>
