// packages/angular/src/viewer/chart-display-options.component.ts
/**
 * chart-display-options.component.ts: Chart-level display toggles.
 *
 * Selector: `pptx-chart-display-options`
 *
 * Mirrors React's `ChartDisplayOptions.tsx`: show/hide title, legend (with
 * position), gridlines, and the data-labels master toggle. Emits a complete new
 * `ChartPptxElement` via `elementChange` after each edit; holds no mutable state.
 *
 * @module angular-viewer/chart-display-options
 */

import { ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import type { ChartPptxElement, PptxChartLegendPosition } from 'pptx-viewer-core';

import {
	chartGridlinesPatch,
	chartGridlinesState,
	LEGEND_POSITION_OPTIONS,
} from '../internal/shared';
import { setDataLabels, setLegend } from './chart-advanced-helpers';
import { patchChartData, patchChartStyle } from './chart-data-helpers';
import { CHART_EDITOR_STYLES } from './chart-editor-styles';
import { boolFromEvent, selectValue } from './chart-event-helpers';

@Component({
	selector: 'pptx-chart-display-options',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [TranslatePipe],
	template: `
		<section class="pptx-chart-card" [attr.aria-label]="'pptx.chart.display' | translate">
			<h4 class="pptx-chart-card__heading">{{ 'pptx.chart.display' | translate }}</h4>
			<div class="pptx-chart-card__group">
				<label class="pptx-chart-card__check">
					<input
						type="checkbox"
						[disabled]="!canEdit()"
						[checked]="style().hasTitle ?? false"
						(change)="onToggleTitle($event)"
					/>
					<span>{{ 'pptx.chart.showTitle' | translate }}</span>
				</label>

				<label class="pptx-chart-card__check">
					<input
						type="checkbox"
						[disabled]="!canEdit()"
						[checked]="style().hasLegend ?? false"
						(change)="onToggleLegend($event)"
					/>
					<span>{{ 'pptx.chart.showLegend' | translate }}</span>
				</label>

				@if (style().hasLegend) {
					<label class="pptx-chart-card__row pptx-chart-card__group--indent">
						<span class="pptx-chart-card__label">{{
							'pptx.chart.legendPosition' | translate
						}}</span>
						<select
							[attr.aria-label]="'pptx.chart.legendPosition' | translate"
							class="pptx-chart-card__input"
							[disabled]="!canEdit()"
							[value]="style().legendPosition ?? 'b'"
							(change)="onLegendPosition($event)"
						>
							@for (opt of legendPositions; track opt.value) {
								<option [value]="opt.value">{{ opt.labelKey | translate }}</option>
							}
						</select>
					</label>
				}

				<label class="pptx-chart-card__check">
					<input
						type="checkbox"
						[disabled]="!canEdit()"
						[checked]="gridlinesShown()"
						(change)="onToggleGridlines($event)"
					/>
					<span>{{ 'pptx.chart.showGridlines' | translate }}</span>
				</label>

				<label class="pptx-chart-card__check">
					<input
						type="checkbox"
						[disabled]="!canEdit()"
						[checked]="style().hasDataLabels ?? false"
						(change)="onToggleDataLabels($event)"
					/>
					<span>{{ 'pptx.chart.showDataLabels' | translate }}</span>
				</label>
			</div>
		</section>
	`,
	styles: CHART_EDITOR_STYLES,
})
export class ChartDisplayOptionsComponent {
	readonly element = input.required<ChartPptxElement>();
	readonly canEdit = input<boolean>(true);
	readonly elementChange = output<ChartPptxElement>();

	protected readonly legendPositions = LEGEND_POSITION_OPTIONS;
	protected readonly style = computed(() => this.element().chartData?.style ?? {});
	/**
	 * Read from the primary value axis's `majorGridlines`, matching what the
	 * cartesian renderer actually draws; `style.hasGridlines` alone is a legacy
	 * field the renderer never reads, so wiring the checkbox straight to it
	 * silently did nothing (see `chart-gridlines-toggle.ts` in shared).
	 */
	protected readonly gridlinesShown = computed(() => {
		const chartData = this.element().chartData;
		return chartData ? chartGridlinesState(chartData) : false;
	});

	protected onToggleTitle(event: Event): void {
		this.elementChange.emit(patchChartStyle(this.element(), { hasTitle: boolFromEvent(event) }));
	}

	protected onToggleLegend(event: Event): void {
		this.elementChange.emit(setLegend(this.element(), { show: boolFromEvent(event) }));
	}

	protected onLegendPosition(event: Event): void {
		const value = selectValue(event);
		if (value === null) {
			return;
		}
		this.elementChange.emit(
			setLegend(this.element(), { position: value as PptxChartLegendPosition }),
		);
	}

	protected onToggleGridlines(event: Event): void {
		const chartData = this.element().chartData;
		if (!chartData) {
			return;
		}
		this.elementChange.emit(
			patchChartData(this.element(), chartGridlinesPatch(chartData, boolFromEvent(event))),
		);
	}

	protected onToggleDataLabels(event: Event): void {
		// Route through the dedicated op so content keys initialise consistently.
		this.elementChange.emit(setDataLabels(this.element(), { show: boolFromEvent(event) }));
	}
}

// packages/vue/src/viewer/components/inspector/ChartDisplayOptions.vue
<script setup lang="ts">
import type { PptxChartData, PptxChartStyle } from 'pptx-viewer-core';
import {
	chartGridlinesPatch,
	chartGridlinesState,
	LEGEND_POSITION_OPTIONS,
} from 'pptx-viewer-shared';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

/**
 * ChartDisplayOptions: chart-level display toggles (title / legend visibility +
 * position / gridlines / data-labels master toggle). Mirrors React's
 * `ChartDisplayOptions`. Emits a shallow `PptxChartStyle` patch via `update`
 * for every field except gridlines.
 *
 * Gridlines is the one field that is NOT a `PptxChartStyle` round-trip: every
 * binding used to wire the checkbox straight to `style.hasGridlines`, a field
 * the renderer never actually reads (real gridline visibility comes from the
 * value axis's `c:majorGridlines`), so toggling the checkbox silently did
 * nothing. Shared's `chart-gridlines-toggle.ts` fixes this by reading/writing
 * the primary value axis instead (`style.hasGridlines` stays in sync as a
 * legacy mirror), which needs the full `PptxChartData`, not just `style` - so
 * this component takes `chartData` and emits gridline changes via the separate
 * `update-chart-data` event with a full `Partial<PptxChartData>` patch.
 */
const props = defineProps<{
	chartData: PptxChartData | undefined;
}>();

const emit = defineEmits<{
	update: [patch: Partial<PptxChartStyle>];
	'update-chart-data': [patch: Partial<PptxChartData>];
}>();

const { t } = useI18n();

const style = computed(() => props.chartData?.style);
const gridlinesOn = computed(() =>
	props.chartData ? chartGridlinesState(props.chartData) : (style.value?.hasGridlines ?? false),
);

function patch(p: Partial<PptxChartStyle>): void {
	emit('update', p);
}

function onCheckbox(event: Event, key: keyof PptxChartStyle): void {
	patch({ [key]: (event.target as HTMLInputElement).checked } as Partial<PptxChartStyle>);
}

function onLegendPosition(event: Event): void {
	patch({ legendPosition: (event.target as HTMLSelectElement).value });
}

function onGridlinesToggle(event: Event): void {
	if (!props.chartData) {
		return;
	}
	const checked = (event.target as HTMLInputElement).checked;
	emit('update-chart-data', chartGridlinesPatch(props.chartData, checked));
}
</script>

<template>
	<div class="pptx-vue-chart-card rounded border border-border bg-card p-2 space-y-2">
		<div class="pptx-vue-chart-heading text-[11px] uppercase tracking-wide text-muted-foreground">
			{{ t('pptx.chart.display') }}
		</div>
		<div class="space-y-1.5">
			<label class="flex items-center gap-2 cursor-pointer">
				<input
					type="checkbox"
					data-testid="chart-show-title"
					class="accent-primary"
					:checked="style?.hasTitle ?? false"
					@change="onCheckbox($event, 'hasTitle')"
				/>
				<span class="text-[11px]">{{ t('pptx.chart.showTitle') }}</span>
			</label>

			<label class="flex items-center gap-2 cursor-pointer">
				<input
					type="checkbox"
					data-testid="chart-show-legend"
					class="accent-primary"
					:checked="style?.hasLegend ?? false"
					@change="onCheckbox($event, 'hasLegend')"
				/>
				<span class="text-[11px]">{{ t('pptx.chart.showLegend') }}</span>
			</label>

			<label v-if="style?.hasLegend" class="flex items-center gap-2 text-[11px] ml-4">
				<span class="w-12 text-muted-foreground shrink-0">{{
					t('pptx.chart.legendPosition')
				}}</span>
				<select
					:aria-label="t('pptx.chart.legendPosition')"
					class="pptx-vue-chart-input flex-1 bg-muted border border-border rounded px-1.5 py-0.5 w-full"
					data-testid="chart-legend-position"
					:value="style?.legendPosition ?? 'b'"
					@change="onLegendPosition"
				>
					<option v-for="opt in LEGEND_POSITION_OPTIONS" :key="opt.value" :value="opt.value">
						{{ t(opt.labelKey) }}
					</option>
				</select>
			</label>

			<label class="flex items-center gap-2 cursor-pointer">
				<input
					type="checkbox"
					data-testid="chart-show-gridlines"
					class="accent-primary"
					:checked="gridlinesOn"
					@change="onGridlinesToggle"
				/>
				<span class="text-[11px]">{{ t('pptx.chart.showGridlines') }}</span>
			</label>

			<label class="flex items-center gap-2 cursor-pointer">
				<input
					type="checkbox"
					data-testid="chart-show-data-labels"
					class="accent-primary"
					:checked="style?.hasDataLabels ?? false"
					@change="onCheckbox($event, 'hasDataLabels')"
				/>
				<span class="text-[11px]">{{ t('pptx.chart.showDataLabels') }}</span>
			</label>
		</div>
	</div>
</template>
