// packages/react/src/viewer/components/inspector/ChartDataPointOptions.tsx
import type { PptxChartDataPoint, PptxChartSeries, PptxChartType } from 'pptx-viewer-core';
import { useState } from 'react';
import { useTranslation } from 'react-i18next';

import { CARD, EXPLOSION_SUPPORTED_TYPES, HEADING, INPUT } from './chart-panel-constants';
import { useRecentColors } from './RecentColorsContext';

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------
export interface ChartDataPointOptionsProps {
	chartType: PptxChartType;
	categories: string[];
	series: PptxChartSeries[];
	canEdit: boolean;
	onSetPointFill: (seriesIndex: number, pointIndex: number, color: string | null) => void;
	onSetPointExplosion: (seriesIndex: number, pointIndex: number, explosion: number | null) => void;
	/** Set a custom label text for this point, or pass null to clear the override. */
	onSetPointLabel: (seriesIndex: number, pointIndex: number, text: string | null) => void;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------
export function ChartDataPointOptions({
	chartType,
	categories,
	series,
	canEdit,
	onSetPointFill,
	onSetPointExplosion,
	onSetPointLabel,
}: ChartDataPointOptionsProps) {
	const { t } = useTranslation();
	const { pushColor } = useRecentColors();
	const [seriesIndex, setSeriesIndex] = useState(0);

	if (series.length === 0 || categories.length === 0) {
		return null;
	}

	const activeSeries = series[Math.min(seriesIndex, series.length - 1)];
	const showExplosion = EXPLOSION_SUPPORTED_TYPES.has(chartType);
	const pointFor = (idx: number): PptxChartDataPoint | undefined =>
		activeSeries.dataPoints?.find((p) => p.idx === idx);

	return (
		<div className={CARD}>
			<div className={HEADING}>{t('pptx.chart.dataPoints')}</div>

			{/* Series picker (per-point overrides target one series at a time). */}
			{series.length > 1 && (
				<label className='flex items-center gap-2 text-[11px]'>
					<span className='w-12 text-muted-foreground shrink-0'>{t('pptx.chart.series')}</span>
					<select
						aria-label={t('pptx.chart.series')}
						disabled={!canEdit}
						className={INPUT}
						value={Math.min(seriesIndex, series.length - 1)}
						onChange={(e) => setSeriesIndex(Number.parseInt(e.target.value, 10))}
					>
						{series.map((s, i) => (
							<option key={`${s.name}-${i}`} value={i}>
								{s.name}
							</option>
						))}
					</select>
				</label>
			)}

			<div className='space-y-1.5'>
				{categories.map((cat, idx) => {
					const point = pointFor(idx);
					return (
						<div key={`${cat}-${idx}`} className='flex items-center gap-2 text-[11px]'>
							<span className='flex-1 truncate' title={cat}>
								{cat}
							</span>

							{/* Per-point label text override */}
							<input
								type='text'
								disabled={!canEdit}
								title={t('pptx.chart.pointLabelOverride')}
								className='w-20 bg-muted border border-border rounded px-1.5 py-0.5 text-[11px]'
								value={activeSeries.dataLabels?.find((l) => l.idx === idx)?.text ?? ''}
								placeholder={t('pptx.chart.auto')}
								onChange={(e) => {
									const raw = e.target.value;
									onSetPointLabel(seriesIndex, idx, raw === '' ? null : raw);
								}}
							/>

							{/* Per-point fill */}
							<input
								type='color'
								disabled={!canEdit}
								title={t('pptx.chart.pointFill')}
								className='h-6 w-8 cursor-pointer rounded border border-border bg-transparent'
								value={point?.spPr?.fillColor ?? activeSeries.color ?? '#4472c4'}
								onChange={(e) => {
									onSetPointFill(seriesIndex, idx, e.target.value);
									pushColor(e.target.value);
								}}
							/>
							{point?.spPr?.fillColor && (
								<button
									type='button'
									disabled={!canEdit}
									title={t('pptx.chart.pointFillClear')}
									className='text-muted-foreground hover:text-foreground'
									onClick={() => onSetPointFill(seriesIndex, idx, null)}
								>
									&times;
								</button>
							)}

							{/* Pie/doughnut slice explosion */}
							{showExplosion && (
								<input
									type='number'
									min={0}
									max={100}
									disabled={!canEdit}
									title={t('pptx.chart.pointExplosion')}
									className='w-14 bg-muted border border-border rounded px-1.5 py-0.5'
									value={point?.explosion ?? ''}
									placeholder='0'
									onChange={(e) => {
										const raw = e.target.value;
										if (raw === '') {
											onSetPointExplosion(seriesIndex, idx, null);
											return;
										}
										const num = Number.parseInt(raw, 10);
										if (Number.isFinite(num)) {
											onSetPointExplosion(seriesIndex, idx, num);
										}
									}}
								/>
							)}
						</div>
					);
				})}
			</div>
		</div>
	);
}

// packages/vue/src/viewer/components/inspector/ChartDataPointOptions.vue
<script setup lang="ts">
import type { PptxChartDataPoint, PptxChartSeries, PptxChartType } from 'pptx-viewer-core';
import { EXPLOSION_SUPPORTED_TYPES } from 'pptx-viewer-shared';
import { computed, ref } from 'vue';
import { useI18n } from 'vue-i18n';

import { injectRecentColors } from '../../composables/recent-colors-context';

/**
 * ChartDataPointOptions: per-data-point fill override + pie/doughnut slice
 * explosion, targeting one series at a time. Mirrors React's
 * `ChartDataPointOptions`. Emits `setPointFill` / `setPointExplosion`.
 */
const props = defineProps<{
	chartType: PptxChartType;
	categories: readonly string[];
	series: readonly PptxChartSeries[];
}>();

const emit = defineEmits<{
	setPointFill: [seriesIndex: number, pointIndex: number, color: string | null];
	setPointExplosion: [seriesIndex: number, pointIndex: number, explosion: number | null];
	setPointLabel: [seriesIndex: number, pointIndex: number, text: string | null];
}>();

const { t } = useI18n();
const recentColors = injectRecentColors();

const seriesIndex = ref(0);

const visible = computed(() => props.series.length > 0 && props.categories.length > 0);

const activeIndex = computed(() => Math.min(seriesIndex.value, props.series.length - 1));
const activeSeries = computed<PptxChartSeries | undefined>(() => props.series[activeIndex.value]);
const showExplosion = computed(() => EXPLOSION_SUPPORTED_TYPES.has(props.chartType));

function pointFor(idx: number): PptxChartDataPoint | undefined {
	return activeSeries.value?.dataPoints?.find((p) => p.idx === idx);
}

function labelFor(idx: number): string {
	return activeSeries.value?.dataLabels?.find((l) => l.idx === idx)?.text ?? '';
}

function onLabel(event: Event, idx: number): void {
	const raw = (event.target as HTMLInputElement).value;
	emit('setPointLabel', activeIndex.value, idx, raw === '' ? null : raw);
}

function onSeriesPick(event: Event): void {
	seriesIndex.value = Number.parseInt((event.target as HTMLSelectElement).value, 10);
}

function onFill(event: Event, idx: number): void {
	emit('setPointFill', activeIndex.value, idx, (event.target as HTMLInputElement).value);
}

function onFillCommit(event: Event): void {
	recentColors?.push((event.target as HTMLInputElement).value);
}

function onClearFill(idx: number): void {
	emit('setPointFill', activeIndex.value, idx, null);
}

function onExplosion(event: Event, idx: number): void {
	const raw = (event.target as HTMLInputElement).value;
	if (raw === '') {
		emit('setPointExplosion', activeIndex.value, idx, null);
		return;
	}
	const num = Number.parseInt(raw, 10);
	if (Number.isFinite(num)) {
		emit('setPointExplosion', activeIndex.value, idx, num);
	}
}
</script>

<template>
	<div
		v-if="visible"
		class="pptx-vue-chart-card rounded border border-border bg-card p-2 space-y-2"
	>
		<div class="pptx-vue-chart-heading text-[11px] uppercase tracking-wide text-muted-foreground">
			{{ t('pptx.chart.dataPoints') }}
		</div>

		<label v-if="props.series.length > 1" class="flex items-center gap-2 text-[11px]">
			<span class="w-12 text-muted-foreground shrink-0">{{ t('pptx.chart.series') }}</span>
			<select
				:aria-label="t('pptx.chart.series')"
				class="pptx-vue-chart-input flex-1 bg-muted border border-border rounded px-1.5 py-0.5 w-full"
				data-testid="chart-point-series"
				:value="activeIndex"
				@change="onSeriesPick"
			>
				<option v-for="(s, i) in props.series" :key="`${s.name}-${i}`" :value="i">
					{{ s.name }}
				</option>
			</select>
		</label>

		<div class="space-y-1.5">
			<div
				v-for="(cat, idx) in props.categories"
				:key="`${cat}-${idx}`"
				class="flex items-center gap-2 text-[11px]"
			>
				<span class="flex-1 truncate" :title="cat">{{ cat }}</span>

				<input
					type="text"
					data-testid="chart-point-label"
					class="w-20 bg-muted border border-border rounded px-1.5 py-0.5 text-[11px]"
					:value="labelFor(idx)"
					:placeholder="t('pptx.chart.auto')"
					:title="t('pptx.chart.pointLabelOverride')"
					@input="onLabel($event, idx)"
				/>

				<input
					type="color"
					data-testid="chart-point-fill"
					class="h-6 w-8 cursor-pointer rounded border border-border bg-transparent"
					:title="t('pptx.chart.pointFill')"
					:value="pointFor(idx)?.spPr?.fillColor ?? activeSeries?.color ?? '#4472c4'"
					@input="onFill($event, idx)"
					@change="onFillCommit"
				/>
				<button
					v-if="pointFor(idx)?.spPr?.fillColor"
					type="button"
					data-testid="chart-point-fill-clear"
					class="text-muted-foreground hover:text-foreground"
					:title="t('pptx.chart.pointFillClear')"
					@click="onClearFill(idx)"
				>
					&times;
				</button>

				<input
					v-if="showExplosion"
					type="number"
					min="0"
					max="100"
					data-testid="chart-point-explosion"
					class="w-14 bg-muted border border-border rounded px-1.5 py-0.5"
					:value="pointFor(idx)?.explosion ?? ''"
					placeholder="0"
					:title="t('pptx.chart.pointExplosion')"
					@input="onExplosion($event, idx)"
				/>
			</div>
		</div>
	</div>
</template>
