// packages/react/src/viewer/components/inspector/SlideThemeOverridePanel.tsx
import type { PptxSlide, PptxTheme, ColorMapAliasKey } from 'pptx-viewer-core';
import {
	applyThemeOverrideToSlide,
	COLOR_MAP_ALIAS_KEYS,
	DEFAULT_COLOR_MAP,
	THEME_COLOR_SCHEME_KEYS,
} from 'pptx-viewer-core';
import { schemaLabel, THEME_COLOR_SLOT_LABEL_KEYS } from 'pptx-viewer-shared';
import React, { useCallback, useMemo } from 'react';
import { useTranslation } from 'react-i18next';

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

interface SlideThemeOverridePanelProps {
	activeSlide: PptxSlide | undefined;
	theme: PptxTheme | undefined;
	canEdit: boolean;
	onUpdateSlide: (updates: Partial<PptxSlide>) => void;
}

// ---------------------------------------------------------------------------
// Friendly labels for the alias keys
// ---------------------------------------------------------------------------

const ALIAS_LABELS: Record<ColorMapAliasKey, string> = {
	bg1: 'Background 1',
	tx1: 'Text 1',
	bg2: 'Background 2',
	tx2: 'Text 2',
	accent1: 'Accent 1',
	accent2: 'Accent 2',
	accent3: 'Accent 3',
	accent4: 'Accent 4',
	accent5: 'Accent 5',
	accent6: 'Accent 6',
	hlink: 'Hyperlink',
	folHlink: 'Followed Hyperlink',
};

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

/**
 * Inspector panel section that allows enabling / editing a per-slide
 * colour-map override (`p:clrMapOvr / a:overrideClrMapping`).
 */
export function SlideThemeOverridePanel({
	activeSlide,
	theme,
	canEdit,
	onUpdateSlide,
}: SlideThemeOverridePanelProps): React.ReactElement | null {
	const { t } = useTranslation();
	// `schemaLabel` takes a plain `(key) => string`; react-i18next's `t` is an
	// overloaded generic, so narrow it once here rather than at each call site.
	const translate = useCallback((key: string): string => t(key), [t]);

	const override = activeSlide?.clrMapOverride;
	const isOverrideActive = override !== undefined;

	/** All possible target slots a logical alias can point to. */
	const targetSlotOptions = useMemo(() => [...THEME_COLOR_SCHEME_KEYS], []);

	const commitOverride = useCallback(
		(nextOverride: Record<string, string> | undefined) => {
			if (!activeSlide || !theme?.colorScheme) {
				onUpdateSlide({ clrMapOverride: nextOverride });
				return;
			}

			const nextSlide = applyThemeOverrideToSlide(activeSlide, theme.colorScheme, nextOverride);
			onUpdateSlide({
				clrMapOverride: nextSlide.clrMapOverride,
				backgroundColor: nextSlide.backgroundColor,
				elements: nextSlide.elements,
			});
		},
		[activeSlide, onUpdateSlide, theme?.colorScheme],
	);

	const handleToggle = useCallback(
		(enabled: boolean) => {
			if (enabled) {
				// Activate with default mapping (identity)
				const defaultMap: Record<string, string> = {};
				for (const key of COLOR_MAP_ALIAS_KEYS) {
					defaultMap[key] = DEFAULT_COLOR_MAP[key];
				}
				commitOverride(defaultMap);
			} else {
				commitOverride(undefined);
			}
		},
		[commitOverride],
	);

	const handleAliasChange = useCallback(
		(alias: ColorMapAliasKey, targetSlot: string) => {
			const current = override ?? {};
			const next = { ...current, [alias]: targetSlot };
			// Fill in defaults for any missing aliases
			for (const key of COLOR_MAP_ALIAS_KEYS) {
				if (!next[key]) {
					next[key] = DEFAULT_COLOR_MAP[key];
				}
			}
			commitOverride(next);
		},
		[commitOverride, override],
	);

	/**
	 * Resolve a theme colour slot to its hex value for preview.
	 */
	const resolveSlotColor = useCallback(
		(slot: string): string | undefined => {
			if (!theme?.colorScheme) {
				return undefined;
			}
			const cs = theme.colorScheme;
			return cs[slot as keyof typeof cs];
		},
		[theme],
	);

	if (!activeSlide) {
		return null;
	}

	return (
		<div className='space-y-2'>
			<label className='inline-flex items-center gap-2 text-xs'>
				<input
					type='checkbox'
					disabled={!canEdit}
					checked={isOverrideActive}
					onChange={(e) => handleToggle(e.target.checked)}
				/>
				{t('pptx.themeOverride.enableOverride')}
			</label>

			{isOverrideActive && override && (
				<div className='space-y-1.5'>
					{COLOR_MAP_ALIAS_KEYS.map((alias) => {
						const currentTarget = override[alias] ?? DEFAULT_COLOR_MAP[alias];
						const resolvedHex = resolveSlotColor(currentTarget);

						return (
							<div key={alias} className='flex items-center gap-2 text-[11px]'>
								<span className='w-24 truncate text-muted-foreground' title={ALIAS_LABELS[alias]}>
									{ALIAS_LABELS[alias]}
								</span>
								<div
									className='h-4 w-4 rounded-sm border border-border shrink-0'
									style={{
										backgroundColor: resolvedHex ? `#${resolvedHex.replace(/^#/, '')}` : undefined,
									}}
								/>
								<select
									disabled={!canEdit}
									className='flex-1 bg-muted border border-border rounded px-1 py-0.5 text-[11px]'
									value={currentTarget}
									onChange={(e) => handleAliasChange(alias, e.target.value)}
								>
									{/*
									 * The option VALUE stays the raw `a:clrScheme` slot (that is what
									 * gets written back into `clrMapOverride`); only the visible text
									 * is spelled, so no option is added, dropped or re-valued.
									 */}
									{targetSlotOptions.map((slot) => (
										<option key={slot} value={slot}>
											{schemaLabel(THEME_COLOR_SLOT_LABEL_KEYS, slot, translate)}
										</option>
									))}
								</select>
							</div>
						);
					})}
				</div>
			)}
		</div>
	);
}

// packages/vue/src/viewer/components/inspector/SlideThemeOverridePanel.vue
<script setup lang="ts">
/**
 * SlideThemeOverridePanel: per-slide colour-map override editing (Vue port of
 * React's `SlideThemeOverridePanel`). Toggles and edits the slide's
 * `clrMapOverride` (`p:clrMapOvr` / `a:overrideClrMapping`), remapping each
 * logical alias (bg1/tx1/accent1/...) to a theme colour-scheme slot.
 *
 * Emits `update` with a `Partial<PptxSlide>` patch; the host applies it to the
 * active slide with history (same path as the background controls).
 */
import type { ColorMapAliasKey, PptxSlide, PptxTheme } from 'pptx-viewer-core';
import {
	applyThemeOverrideToSlide,
	COLOR_MAP_ALIAS_KEYS,
	DEFAULT_COLOR_MAP,
	THEME_COLOR_SCHEME_KEYS,
} from 'pptx-viewer-core';
import { schemaLabel, THEME_COLOR_SLOT_LABEL_KEYS } from 'pptx-viewer-shared';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

const props = withDefaults(
	defineProps<{ slide: PptxSlide | undefined; theme?: PptxTheme; canEdit?: boolean }>(),
	{ canEdit: true },
);

const emit = defineEmits<{ update: [patch: Partial<PptxSlide>] }>();

const { t } = useI18n();

/** Friendly labels for the 12 colour-map aliases. */
const ALIAS_LABELS: Record<ColorMapAliasKey, string> = {
	bg1: 'Background 1',
	tx1: 'Text 1',
	bg2: 'Background 2',
	tx2: 'Text 2',
	accent1: 'Accent 1',
	accent2: 'Accent 2',
	accent3: 'Accent 3',
	accent4: 'Accent 4',
	accent5: 'Accent 5',
	accent6: 'Accent 6',
	hlink: 'Hyperlink',
	folHlink: 'Followed Hyperlink',
};

const override = computed<Record<string, string> | undefined>(() => props.slide?.clrMapOverride);
const isActive = computed(() => override.value !== undefined);
const aliasKeys = COLOR_MAP_ALIAS_KEYS;
const slotOptions = [...THEME_COLOR_SCHEME_KEYS];

function currentTarget(alias: ColorMapAliasKey): string {
	return override.value?.[alias] ?? DEFAULT_COLOR_MAP[alias];
}

/**
 * Spell an `a:clrScheme` slot for display.
 *
 * The option VALUE stays the wire token (that is what lands in
 * `clrMapOverride`); only the text changes, so the select offers exactly the
 * same twelve slots it did before.
 */
function slotLabel(slot: string): string {
	// `t` is an overloaded generic; narrow it to the plain shape `schemaLabel` wants.
	return schemaLabel(THEME_COLOR_SLOT_LABEL_KEYS, slot, (key: string) => t(key));
}

/** Resolve a theme colour slot to a `#rrggbb` value for the preview swatch. */
function slotColor(slot: string): string | undefined {
	const scheme = props.theme?.colorScheme as Record<string, string | undefined> | undefined;
	const hex = scheme?.[slot];
	return hex ? `#${hex.replace(/^#/u, '')}` : undefined;
}

function emitOverride(nextOverride: Record<string, string> | undefined): void {
	if (!props.slide || !props.theme?.colorScheme) {
		emit('update', { clrMapOverride: nextOverride });
		return;
	}

	const nextSlide = applyThemeOverrideToSlide(props.slide, props.theme.colorScheme, nextOverride);
	emit('update', {
		clrMapOverride: nextSlide.clrMapOverride,
		backgroundColor: nextSlide.backgroundColor,
		elements: nextSlide.elements,
	});
}

function onToggle(event: Event): void {
	if ((event.target as HTMLInputElement).checked) {
		const identity: Record<string, string> = {};
		for (const key of COLOR_MAP_ALIAS_KEYS) {
			identity[key] = DEFAULT_COLOR_MAP[key];
		}
		emitOverride(identity);
	} else {
		emitOverride(undefined);
	}
}

function onAliasChange(alias: ColorMapAliasKey, event: Event): void {
	const slot = (event.target as HTMLSelectElement).value;
	const next: Record<string, string> = { ...(override.value ?? {}), [alias]: slot };
	for (const key of COLOR_MAP_ALIAS_KEYS) {
		if (!next[key]) {
			next[key] = DEFAULT_COLOR_MAP[key];
		}
	}
	emitOverride(next);
}
</script>

<template>
	<div class="space-y-2">
		<label class="inline-flex items-center gap-2 text-xs">
			<input type="checkbox" :disabled="!canEdit" :checked="isActive" @change="onToggle" />
			{{ t('pptx.themeOverride.enableOverride') }}
		</label>

		<div v-if="isActive" class="space-y-1.5">
			<div v-for="alias in aliasKeys" :key="alias" class="flex items-center gap-2 text-[11px]">
				<span class="w-24 shrink-0 truncate text-muted-foreground" :title="ALIAS_LABELS[alias]">
					{{ ALIAS_LABELS[alias] }}
				</span>
				<span
					class="h-4 w-4 shrink-0 rounded-sm border border-border"
					:style="{ backgroundColor: slotColor(currentTarget(alias)) }"
				/>
				<select
					:disabled="!canEdit"
					:value="currentTarget(alias)"
					class="flex-1 rounded border border-border bg-muted px-1 py-0.5 text-[11px]"
					:aria-label="`${ALIAS_LABELS[alias]} target slot`"
					@change="(e) => onAliasChange(alias, e)"
				>
					<option v-for="slot in slotOptions" :key="slot" :value="slot">
						{{ slotLabel(slot) }}
					</option>
				</select>
			</div>
		</div>
	</div>
</template>
