// packages/vue/src/viewer/components/inspector/PresentationPropertiesPanel.vue
<script setup lang="ts">
/**
 * PresentationPropertiesPanel: the no-selection Properties tab body, mirroring
 * React's `inspector/PresentationPropertiesPanel.tsx` section order:
 * PRESENTATION, THEME, THEME OVERRIDE, SLIDE SIZE, NOTES & HANDOUT, DOCUMENT,
 * TAGS (when tag collections are provided), then a small read-only Slide info
 * card. Also ports React's
 * `useInspectorPaneState` selected-theme-path handling (falls back to the first
 * master's theme path when the package lists no theme options).
 */
import type {
	PptxAppProperties,
	PptxCoreProperties,
	PptxCustomProperty,
	PptxHandoutMaster,
	PptxNotesMaster,
	PptxPresentationProperties,
	PptxSlide,
	PptxSlideMaster,
	PptxTagCollection,
	PptxTheme,
	PptxThemeOption,
} from 'pptx-viewer-core';
import type { SlideSizeEmu } from 'pptx-viewer-shared';
import { computed, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';

import type { CanvasSize } from '../../types';
import DocumentPropertiesCard from './DocumentPropertiesCard.vue';
import { CARD, HEADING } from './inspector-cards';
import NotesHandoutCard from './NotesHandoutCard.vue';
import PresentationSettingsCard from './PresentationSettingsCard.vue';
import SlideSizeCard from './SlideSizeCard.vue';
import SlideThemeOverridePanel from './SlideThemeOverridePanel.vue';
import SlideTransitionSection from './SlideTransitionSection.vue';
import TagsSection from './TagsSection.vue';
import ThemeSelectorCard from './ThemeSelectorCard.vue';

const props = withDefaults(
	defineProps<{
		slide: PptxSlide | undefined;
		theme?: PptxTheme;
		presentationProperties?: PptxPresentationProperties;
		canEdit?: boolean;
		themeOptions?: PptxThemeOption[];
		slideMasters?: PptxSlideMaster[];
		canvasSize?: CanvasSize;
		/** The deck's `p:sldSz` in EMU, for the Slide Size card's preset match. */
		slideSize?: SlideSizeEmu;
		notesCanvasSize?: CanvasSize;
		notesMaster?: PptxNotesMaster;
		handoutMaster?: PptxHandoutMaster;
		coreProperties?: PptxCoreProperties;
		appProperties?: PptxAppProperties;
		customProperties?: PptxCustomProperty[];
		tagCollections?: PptxTagCollection[];
	}>(),
	{ canEdit: true },
);

const emit = defineEmits<{
	'presentation-update': [patch: Partial<PptxPresentationProperties>];
	'apply-theme': [path: string, allMasters: boolean];
	'slide-update': [patch: Partial<PptxSlide>];
	'canvas-size-update': [size: CanvasSize];
	'slide-size-update': [size: SlideSizeEmu, canvas: CanvasSize];
	'update-core-properties': [patch: Partial<PptxCoreProperties>];
	'update-app-properties': [patch: Partial<PptxAppProperties>];
	'update-custom-properties': [props: PptxCustomProperty[]];
	'update-tag-collections': [next: PptxTagCollection[]];
}>();

const { t } = useI18n();

// ── Theme selection (React's useInspectorPaneState) ─────────────────────
const activeThemePath = computed(() => props.slideMasters?.[0]?.themePath);
const effectiveThemeOptions = computed<PptxThemeOption[]>(() => {
	const options = props.themeOptions ?? [];
	if (options.length > 0 || !activeThemePath.value) {
		return options;
	}
	return [{ path: activeThemePath.value, name: props.theme?.name }];
});

const selectedThemePath = ref('');
watch(
	[activeThemePath, effectiveThemeOptions],
	() => {
		selectedThemePath.value = activeThemePath.value ?? effectiveThemeOptions.value[0]?.path ?? '';
	},
	{ immediate: true },
);
</script>

<template>
	<div class="space-y-3">
		<div v-if="props.presentationProperties" :class="CARD">
			<div :class="HEADING">{{ t('pptx.slideInspector.presentation') }}</div>
			<PresentationSettingsCard
				:presentation-properties="props.presentationProperties"
				:can-edit="props.canEdit"
				@update="(patch) => emit('presentation-update', patch)"
			/>
		</div>

		<ThemeSelectorCard
			:theme-options="effectiveThemeOptions"
			:selected-theme-path="selectedThemePath"
			:can-edit="props.canEdit"
			@select-theme-path="(path) => (selectedThemePath = path)"
			@apply-theme="(path, allMasters) => emit('apply-theme', path, allMasters)"
		/>

		<div :class="CARD">
			<div :class="HEADING">{{ t('pptx.themeOverride.heading') }}</div>
			<SlideThemeOverridePanel
				:slide="props.slide"
				:theme="props.theme"
				:can-edit="props.canEdit"
				@update="(patch) => emit('slide-update', patch)"
			/>
		</div>

		<SlideSizeCard
			v-if="props.canvasSize"
			:canvas-size="props.canvasSize"
			:slide-size="props.slideSize"
			:can-edit="props.canEdit"
			@update="(size) => emit('canvas-size-update', size)"
			@update-slide-size="(size, canvas) => emit('slide-size-update', size, canvas)"
		/>

		<!-- SLIDE TRANSITION sits beside SLIDE SIZE, matching React, Angular,
		     Svelte and Vanilla. This section and its `SlideTransitionPanel` were
		     built and then never mounted, which combined with an inert ribbon left
		     Vue with no way to author a transition at all. -->
		<div :class="CARD">
			<SlideTransitionSection
				:slide="props.slide"
				@transition-update="(next) => emit('slide-update', { transition: next })"
			/>
		</div>

		<NotesHandoutCard
			:notes-canvas-size="props.notesCanvasSize"
			:notes-master="props.notesMaster"
			:handout-master="props.handoutMaster"
		/>

		<DocumentPropertiesCard
			:core-properties="props.coreProperties"
			:app-properties="props.appProperties"
			:custom-properties="props.customProperties ?? []"
			:can-edit="props.canEdit"
			@update-core="(patch) => emit('update-core-properties', patch)"
			@update-app="(patch) => emit('update-app-properties', patch)"
			@update-custom="(next) => emit('update-custom-properties', next)"
		/>

		<TagsSection
			v-if="props.tagCollections"
			:tag-collections="props.tagCollections"
			:can-edit="props.canEdit"
			@update="(next) => emit('update-tag-collections', next)"
		/>

		<div v-if="props.slide" :class="[CARD, 'space-y-1']">
			<div :class="HEADING">Slide</div>
			<div class="text-[11px] text-muted-foreground">
				{{ props.slide.elements?.length ?? 0 }} elements
			</div>
		</div>
	</div>
</template>

// packages/svelte/src/viewer/components/inspector/PresentationPropertiesPanel.svelte
<script lang="ts">
	/**
	 * PresentationPropertiesPanel: the Properties tab's no-selection body,
	 * mirroring React's `inspector/PresentationPropertiesPanel.tsx` section
	 * order: PRESENTATION, THEME, THEME OVERRIDE, SLIDE SIZE, NOTES & HANDOUT,
	 * DOCUMENT. Also ports React's `useInspectorPaneState` selected-theme-path
	 * handling (falls back to the first master's theme path when the package
	 * lists no theme options).
	 *
	 * Deck-level reads/mutations come from the {@link InspectorDeckActions}
	 * context facade (`deck`); when no deck is provided (standalone mounts,
	 * hosts without the viewer root) the panel falls back to the legacy
	 * read-only slide-size summary + theme sections.
	 */
	import type { PptxHandler, PptxTheme, PptxThemeOption } from 'pptx-viewer-core';
	import type { CanvasSize } from 'pptx-viewer-shared';

	import { useTranslator } from '../../../i18n/context';
	import type { EditorState } from '../../editor/editor-state.svelte';
	import type { InspectorDeckActions } from '../../state/inspector-deck';
	import DocumentPropertiesSection from './DocumentPropertiesSection.svelte';
	import NotesHandoutSection from './NotesHandoutSection.svelte';
	import PresentationSettingsSection from './PresentationSettingsSection.svelte';
	import SlideSizeSection from './SlideSizeSection.svelte';
	import SlideTransitionSection from './SlideTransitionSection.svelte';
	import TagsSection from './TagsSection.svelte';
	import TemplateBackgroundSection from './TemplateBackgroundSection.svelte';
	import ThemeSection from './ThemeSection.svelte';
	import ThemeSelectorSection from './ThemeSelectorSection.svelte';

	const {
		editor,
		deck,
		canvasSize,
		handler,
		presentationTheme,
		onthemechange,
	}: {
		editor: EditorState;
		deck?: InspectorDeckActions;
		canvasSize?: CanvasSize;
		handler?: PptxHandler | null;
		presentationTheme?: PptxTheme;
		onthemechange?: (theme: PptxTheme) => void;
	} = $props();
	const t = useTranslator();

	const canEdit = $derived(deck !== undefined && editor.editable);
	const effectiveCanvasSize = $derived(deck?.canvasSize ?? canvasSize);
	const activeSlide = $derived(editor.slides[editor.currentSlideIndex]);

	// ── Theme selection (React's useInspectorPaneState) ──────────────────
	const activeThemePath = $derived(editor.slideMasters[0]?.themePath);
	const effectiveThemeOptions = $derived.by<PptxThemeOption[]>(() => {
		const options = deck?.themeOptions ?? [];
		if (options.length > 0 || !activeThemePath) {
			return options;
		}
		return [{ path: activeThemePath, name: presentationTheme?.name }];
	});
	// The template's onselect callback writes this (invisible to the linter).
	// eslint-disable-next-line prefer-const
	let pickedThemePath = $state<string | undefined>(undefined);
	const selectedThemePath = $derived(
		pickedThemePath ?? activeThemePath ?? effectiveThemeOptions[0]?.path ?? '',
	);
</script>

{#if deck}
	<div class="pptx-svelte-inspector-section">
		<h4>{t('pptx.slideInspector.presentation')}</h4>
		<PresentationSettingsSection
			properties={editor.presentationProperties}
			{canEdit}
			onupdate={(patch) => deck.updatePresentationProperties(patch)}
		/>
	</div>
	<div class="pptx-svelte-inspector-section">
		<h4>{t('pptx.documentProperties.themeHeading')}</h4>
		<ThemeSelectorSection
			options={effectiveThemeOptions}
			selectedPath={selectedThemePath}
			{canEdit}
			onselect={(path) => (pickedThemePath = path)}
			onapply={(path, applyToAllMasters) => deck.applyThemeByPath(path, applyToAllMasters)}
		/>
	</div>
	{#if handler && onthemechange}
		<div class="pptx-svelte-inspector-section">
			<h4>{t('pptx.themeOverride.heading')}</h4>
			<ThemeSection {editor} {handler} theme={presentationTheme} {onthemechange} />
		</div>
	{/if}
	{#if effectiveCanvasSize}
		<div class="pptx-svelte-inspector-section">
			<h4>{t('pptx.slideSize.title')}</h4>
			<SlideSizeSection
				canvasSize={effectiveCanvasSize}
				slideSize={deck.slideSize}
				{canEdit}
				hasContent={deck.hasContent}
				onupdate={(size) => deck.updateCanvasSize(size)}
				onupdateslidesize={(size, rescaleMode) => deck.updateSlideSize(size, rescaleMode)}
			/>
		</div>
	{/if}
	<!-- React pairs slide size + transition in `SlideProperties`; same order. -->
	{#if activeSlide}
		<div class="pptx-svelte-inspector-section">
			<h4>{t('pptx.slideInspector.slideTransition')}</h4>
			<SlideTransitionSection {editor} />
		</div>
	{/if}
	{#if editor.editTemplateMode && activeSlide}
		<div class="pptx-svelte-inspector-section">
			<h4>{t('pptx.slideBackground.templateBackgroundsHeading')}</h4>
			<TemplateBackgroundSection
				{editor}
				{activeSlide}
				slideMasters={editor.slideMasters}
				{deck}
				{canEdit}
			/>
		</div>
	{/if}
	<div class="pptx-svelte-inspector-section">
		<h4>{t('pptx.documentProperties.notesHandoutHeading')}</h4>
		<NotesHandoutSection
			notesCanvasSize={deck.notesCanvasSize}
			notesMaster={editor.notesMaster}
			handoutMaster={editor.handoutMaster}
		/>
	</div>
	<div class="pptx-svelte-inspector-section">
		<h4>{t('pptx.documentProperties.documentHeading')}</h4>
		<DocumentPropertiesSection
			coreProperties={editor.coreProperties}
			appProperties={editor.appProperties}
			customProperties={editor.customProperties}
			{canEdit}
			onupdatecore={(patch) => deck.updateCoreProperties(patch)}
			onupdateapp={(patch) => deck.updateAppProperties(patch)}
			onupdatecustom={(next) => deck.updateCustomProperties(next)}
		/>
	</div>
	<!-- React renders TAGS from the same PresentationPropertiesPanel. -->
	<div class="pptx-svelte-inspector-section">
		<TagsSection
			tagCollections={editor.tagCollections}
			{canEdit}
			onupdate={(next) => editor.updateTagCollections(next)}
		/>
	</div>
	{#if activeSlide}
		<!-- React's SLIDE card: the active slide's element count (literal
		     "Slide" / "elements" copy, matching React which has no key here). -->
		<div class="pptx-svelte-inspector-section">
			<h4>Slide</h4>
			<p class="pptx-svelte-inspector-meta">{activeSlide.elements?.length ?? 0} elements</p>
		</div>
	{/if}
{:else}
	{#if canvasSize}
		<div class="pptx-svelte-inspector-section">
			<h4>{t('pptx.slideSize.title')}</h4>
			<p class="pptx-svelte-inspector-meta">
				{canvasSize.width} &times; {canvasSize.height} px &middot; {t(
					'pptx.customShows.slideCount',
					{ count: editor.slides.length },
				)}
			</p>
		</div>
	{/if}
	{#if handler && onthemechange}
		<div class="pptx-svelte-inspector-section">
			<ThemeSection {editor} {handler} theme={presentationTheme} {onthemechange} />
		</div>
	{/if}
{/if}

<style>
	.pptx-svelte-inspector-section {
		margin-top: 12px;
		padding-top: 12px;
		border-top: 1px solid var(--pptx-border, #33334d);
	}

	.pptx-svelte-inspector-section:first-child {
		margin-top: 0;
		padding-top: 0;
		border-top: none;
	}

	.pptx-svelte-inspector-section h4 {
		margin: 0 0 8px;
		font-size: 11px;
		font-weight: 600;
		text-transform: uppercase;
		letter-spacing: 0.04em;
		color: var(--pptx-muted-foreground, #94a3b8);
	}

	.pptx-svelte-inspector-meta {
		margin: 0;
		color: var(--pptx-muted-foreground, #94a3b8);
	}
</style>
