// packages/react/src/viewer/components/elements/ChartElementView.tsx
/* oxlint-disable eslint/one-var -- pervasive pre-existing pattern in this file:
   independent handler-local `const`s, not one statement */
import type { ChartPptxElement, PptxChartData, PptxElement } from 'pptx-viewer-core';
import {
	advanceChartMarkDrag,
	advanceChartValueDrag,
	applyChartPartHighlight,
	beginChartMarkDrag,
	beginChartValueDrag,
	buildChartMarkDragGeometry,
	canDrillDown,
	ensureChartInteractionStyles,
	findChartPartTarget,
	resolveChartKind,
	resolveRevealedChartData,
	withChartTitle,
} from 'pptx-viewer-shared';
import type {
	ChartMarkDragState,
	ChartValueDragState,
	ElementAnimationState,
} from 'pptx-viewer-shared';
import React, { useContext, useEffect, useMemo, useRef, useState } from 'react';

import { renderChartElement } from '../../utils';
import { formatAxisValue } from '../../utils/chart-helpers';
import { buildReactChartViewModel } from '../../utils/chart-view-model-render';
import { useChartPartSelection } from '../chart-part-selection';
import { AreaChart3DContext } from './area-chart-3d-context';
import { Area3DChartRenderer } from './Area3DChartRenderer';
import { BarChart3DContext } from './bar-chart-3d-context';
import { Bar3DChartRenderer } from './Bar3DChartRenderer';
import { LineChart3DContext } from './line-chart-3d-context';
import { Line3DChartRenderer } from './Line3DChartRenderer';
import { PieChart3DContext } from './pie-chart-3d-context';
import { PieChart3DRenderer } from './PieChart3DRenderer';
import { SurfaceChart3DContext } from './surface-chart-3d-context';
import { SurfaceChart3DRenderer } from './SurfaceChart3DRenderer';

export interface ChartElementViewProps {
	element: ChartPptxElement;
	/** True when the chart is selected and interactive: activates part hit targets. */
	editable: boolean;
	/** Commits a chart-data edit through the normal element-update/history path. */
	onUpdateElement?: (updates: Partial<PptxElement>) => void;
	/**
	 * Playback state for the chart. When it carries a staged chart build
	 * (`build.kind === 'chart'`, or the authored-index `chartReveal`), the
	 * chart reveals its series / categories / cells progressively via
	 * {@link resolveRevealedChartData}.
	 */
	animationState?: ElementAnimationState;
}

/**
 * Renders a chart element and, in edit mode, makes its data marks directly
 * manipulable: click a bar/dot/slice to select that series/point (synced with
 * the chart inspector), drag a mark vertically to change its value (cartesian
 * kinds), and double-click the title to edit it in place.
 */
export function ChartElementView({
	element,
	editable,
	onUpdateElement,
	animationState,
}: ChartElementViewProps): React.ReactElement {
	const wrapperRef = useRef<HTMLDivElement>(null);
	const dragRef = useRef<ChartValueDragState | null>(null);
	// Pie/doughnut slice, radar vertex, and stacked/percentStacked segment drags
	// have no single vertical value axis, so they run through a parallel state
	// machine (chart-interaction-mark-drag.ts) instead of dragRef's cartesian one.
	const markDragRef = useRef<ChartMarkDragState | null>(null);
	const { selection, setSelection } = useChartPartSelection();
	const [previewData, setPreviewData] = useState<PptxChartData | null>(null);
	const [dragValue, setDragValue] = useState<number | null>(null);
	const [titleDraft, setTitleDraft] = useState<string | null>(null);

	const selectedPart = selection?.elementId === element.id ? selection.part : null;
	const canEdit = editable && Boolean(onUpdateElement);

	// Opt-in interactive 3D surface scene (camera orbit/zoom via OrbitControls).
	// Marks are not selectable/draggable in this mode: a mesh facet has no 2D
	// screen geometry to hit-test against, so value-drag editing stays SVG-only.
	const use3D = useContext(SurfaceChart3DContext);
	const isSurfaceKind = resolveChartKind(element.chartData?.chartType ?? 'bar') === 'surface';

	// Opt-in interactive 3D bar scene (real box meshes, camera orbit/zoom via
	// OrbitControls). Same "marks are not selectable/draggable" caveat as the
	// surface scene above: a mesh box has no 2D screen geometry to hit-test.
	const use3DBar = useContext(BarChart3DContext);
	const isBar3DKind = element.chartData?.chartType === 'bar3D';

	// Opt-in interactive 3D line/area scenes (tube path / ribbon meshes, camera
	// orbit/zoom via OrbitControls). Same "marks are not selectable/draggable"
	// caveat as the surface/bar scenes above.
	const use3DLine = useContext(LineChart3DContext);
	const isLine3DKind = element.chartData?.chartType === 'line3D';
	const use3DArea = useContext(AreaChart3DContext);
	const isArea3DKind = element.chartData?.chartType === 'area3D';
	// Opt-in interactive 3D pie scene (real wedge meshes, camera orbit/zoom via
	// OrbitControls). Same "marks are not selectable/draggable" caveat as the
	// surface/bar3D scenes above.
	const use3DPie = useContext(PieChart3DContext);
	const isPie3DKind = element.chartData?.chartType === 'pie3D';

	// The drag context comes from the committed data, captured at drag start, so
	// axis ranges do not rescale under the pointer mid-drag.
	const viewModel = useMemo(
		() => (canEdit ? buildReactChartViewModel(element) : null),
		[canEdit, element],
	);

	useEffect(ensureChartInteractionStyles, []);

	// Drop this chart's part selection when it stops being editable (deselected,
	// mode change) so the inspector highlight does not linger.
	//
	// Guarded on `onUpdateElement`, and that guard is load-bearing: the SAME chart
	// element is mounted several times over (the thumbnail rail alone renders one
	// copy per slide), every one of those copies shares this element id, and none
	// of them is editable. Without the guard the read-only copies raced the canvas
	// on every mark click - the canvas set the selection, a rail copy saw
	// `!canEdit && selection.elementId === element.id` and nulled it a render
	// later, so the highlight class was applied and stripped within ~100ms and no
	// mark ever stayed selected. A mount with no way to commit an edit has no
	// business owning (or clearing) the editing selection.
	useEffect(() => {
		if (!onUpdateElement) {
			return;
		}
		if (!canEdit && selection?.elementId === element.id) {
			setSelection(null);
		}
	}, [canEdit, selection, element.id, setSelection, onUpdateElement]);

	// Re-apply the selected-part highlight class after every render: React
	// re-creates the SVG marks on each chart change, dropping DOM-only classes.
	useEffect(() => {
		applyChartPartHighlight(wrapperRef.current, selectedPart);
	});

	const endDrag = (commit: boolean) => {
		const active = dragRef.current;
		const markActive = markDragRef.current;
		dragRef.current = null;
		markDragRef.current = null;
		setPreviewData(null);
		setDragValue(null);
		if (!commit || !onUpdateElement) {
			return;
		}
		if (active?.moved && active.lastData) {
			onUpdateElement({ chartData: active.lastData } as Partial<PptxElement>);
		} else if (markActive?.moved && markActive.lastData) {
			onUpdateElement({ chartData: markActive.lastData } as Partial<PptxElement>);
		}
	};

	// Cancel an in-flight value drag with Escape.
	useEffect(() => {
		if (dragValue === null) {
			return;
		}
		const onKeyDown = (e: KeyboardEvent) => {
			if (e.key === 'Escape') {
				endDrag(false);
			}
		};
		window.addEventListener('keydown', onKeyDown);
		return () => window.removeEventListener('keydown', onKeyDown);
	});

	const handlePointerDown = (e: React.PointerEvent<HTMLDivElement>) => {
		if (!canEdit) {
			return;
		}
		const part = findChartPartTarget(e.target);
		if (!part) {
			return;
		}
		e.stopPropagation();
		setSelection({ elementId: element.id, part });
		if (!viewModel || !element.chartData) {
			return;
		}
		let captured = false;
		// Pie/doughnut/radar/stacked marks: try the angle/radial/segment drag first.
		const chartKind = resolveChartKind(element.chartData.chartType ?? 'bar');
		if (part.pointIndex !== undefined && chartKind !== 'unsupported') {
			const markGeometry = buildChartMarkDragGeometry({
				kind: chartKind,
				element,
				chartData: element.chartData,
				categoryLabels: element.chartData.categories,
				seriesIndex: part.seriesIndex,
				pointIndex: part.pointIndex,
			});
			const startedMark = beginChartMarkDrag({
				part,
				geometry: markGeometry,
				chartData: element.chartData,
				svgWidth: viewModel.svgWidth,
				svgHeight: viewModel.svgHeight,
				clientX: e.clientX,
				clientY: e.clientY,
			});
			if (startedMark) {
				markDragRef.current = startedMark;
				captured = true;
			}
		}
		// Clustered bar/line/scatter/bubble: the existing vertical value-axis drag.
		if (!captured) {
			const started = beginChartValueDrag({
				part,
				viewModel,
				chartData: element.chartData,
				clientY: e.clientY,
			});
			if (started) {
				dragRef.current = started;
				captured = true;
			}
		}
		if (!captured) {
			return;
		}
		e.preventDefault();
		// Pointer capture keeps the drag alive when the pointer leaves the mark;
		// guarded because test DOMs (and older browsers) may not implement it.
		try {
			e.currentTarget.setPointerCapture?.(e.pointerId);
		} catch {
			// Non-fatal: the drag still works while the pointer stays over the chart.
		}
	};

	const handlePointerMove = (e: React.PointerEvent<HTMLDivElement>) => {
		const markActive = markDragRef.current;
		if (markActive) {
			const rect = wrapperRef.current?.querySelector('svg')?.getBoundingClientRect();
			if (!rect) {
				return;
			}
			const step = advanceChartMarkDrag(markActive, e.clientX, e.clientY, rect);
			if (!step) {
				return;
			}
			setPreviewData(step.chartData);
			setDragValue(step.value);
			return;
		}
		const active = dragRef.current;
		if (!active) {
			return;
		}
		const height = wrapperRef.current?.querySelector('svg')?.getBoundingClientRect().height ?? 0;
		const step = advanceChartValueDrag(active, e.clientY, height);
		if (!step) {
			return;
		}
		setPreviewData(step.chartData);
		setDragValue(step.value);
	};

	const handlePointerUp = () => {
		if (dragRef.current || markDragRef.current) {
			endDrag(true);
		}
	};

	const handleDoubleClick = (e: React.MouseEvent<HTMLDivElement>) => {
		// G8: `a:graphicFrameLocks/@noDrilldown` forbids entering this chart's
		// individual parts (title, series, data points) for editing.
		if (!canEdit || !canDrillDown(element)) {
			return;
		}
		const target = e.target as Partial<Element>;
		if (typeof target.closest !== 'function') {
			return;
		}
		if ((target as Element).closest("[data-chart-part='title']")) {
			e.stopPropagation();
			setTitleDraft(element.chartData?.title ?? '');
			return;
		}
		if (findChartPartTarget(e.target)) {
			// A mark double-click is already handled as two selects; keep it from
			// bubbling into the element-level inline-text-edit handler.
			e.stopPropagation();
		}
	};

	const commitTitle = () => {
		if (titleDraft !== null && element.chartData && onUpdateElement) {
			onUpdateElement({
				chartData: withChartTitle(element.chartData, titleDraft),
			} as Partial<PptxElement>);
		}
		setTitleDraft(null);
	};

	// Base chart data (a live drag preview wins over the committed data), then the
	// staged-build reveal trims it to the stages shown at the current progress.
	const baseChartData = previewData ?? element.chartData;
	const revealedChartData = baseChartData
		? resolveRevealedChartData(baseChartData, animationState)
		: baseChartData;
	const renderedElement: ChartPptxElement =
		revealedChartData === element.chartData
			? element
			: { ...element, chartData: revealedChartData };

	return (
		<div
			ref={wrapperRef}
			className={`relative w-full h-full ${canEdit ? 'pptx-chart-interactive' : ''}`}
			onPointerDown={handlePointerDown}
			onPointerMove={handlePointerMove}
			onPointerUp={handlePointerUp}
			onDoubleClick={handleDoubleClick}
		>
			{use3D && isSurfaceKind ? (
				<SurfaceChart3DRenderer element={renderedElement} />
			) : use3DBar && isBar3DKind ? (
				<Bar3DChartRenderer element={renderedElement} />
			) : use3DLine && isLine3DKind ? (
				<Line3DChartRenderer element={renderedElement} />
			) : use3DArea && isArea3DKind ? (
				<Area3DChartRenderer element={renderedElement} />
			) : use3DPie && isPie3DKind ? (
				<PieChart3DRenderer element={renderedElement} />
			) : (
				renderChartElement(renderedElement)
			)}
			{dragValue !== null && (
				<div className='absolute top-1 right-1 z-10 rounded bg-primary/90 px-1.5 py-0.5 text-[10px] font-medium text-white pointer-events-none'>
					{formatAxisValue(dragValue)}
				</div>
			)}
			{titleDraft !== null && (
				<input
					type='text'
					autoFocus
					value={titleDraft}
					className='absolute left-1/2 top-0.5 z-10 w-3/5 -translate-x-1/2 rounded border border-border bg-background px-1 py-0.5 text-center text-[11px] text-foreground shadow'
					onChange={(e) => setTitleDraft(e.target.value)}
					onPointerDown={(e) => e.stopPropagation()}
					onDoubleClick={(e) => e.stopPropagation()}
					onKeyDown={(e) => {
						if (e.key === 'Enter') {
							commitTitle();
						} else if (e.key === 'Escape') {
							setTitleDraft(null);
						}
						e.stopPropagation();
					}}
					onBlur={commitTitle}
				/>
			)}
		</div>
	);
}

// packages/angular/src/viewer/chart-element-view.component.ts
/* oxlint-disable eslint/one-var -- pervasive pre-existing pattern in this file:
   independent handler-local `const`s, not one statement */
/**
 * ChartElementViewComponent (Angular port of React's `ChartElementView.tsx`):
 * renders a chart and, while it is selected + editable, makes its data marks
 * directly manipulable. Click a mark to select that part (drop-shadow ring +
 * inspector sync via {@link ChartPartSelectionService}); drag a mark
 * vertically to change its value (local preview, floating badge, Escape
 * cancels, committed ONCE on release as one undo step); double-click the
 * title to edit it in place. Otherwise the hit-testing attributes stay inert
 * and rendering is byte-identical to the plain chart renderer.
 */
import {
	afterNextRender,
	ChangeDetectionStrategy,
	Component,
	computed,
	effect,
	ElementRef,
	HostListener,
	inject,
	Injector,
	input,
	signal,
	viewChild,
} from '@angular/core';
import type { PptxChartData, PptxElement } from 'pptx-viewer-core';

import {
	advanceChartMarkDrag,
	advanceChartValueDrag,
	applyChartPartHighlight,
	beginChartMarkDrag,
	beginChartValueDrag,
	buildChartMarkDragGeometry,
	findChartPartTarget,
	resolveRevealedChartData,
	withChartTitle,
} from '../internal/shared';
import type {
	ChartMarkDragState,
	ChartValueDragState,
	ElementAnimationState,
} from '../internal/shared';
import { AreaChart3DRendererComponent } from './area-chart-3d-renderer.component';
import { AreaChart3DService } from './area-chart-3d.service';
import { BarChart3DRendererComponent } from './bar-chart-3d-renderer.component';
import { BarChart3DService } from './bar-chart-3d.service';
import {
	chartCanEditParts,
	chartDragCommitData,
	chartMarkDragCommitData,
	commitChartElementData,
	ensureChartInteractionStyles,
} from './chart-element-view-helpers';
import { ChartPartSelectionService } from './chart-part-selection.service';
import { buildChartViewModel, formatAxisValue, resolveChartKind } from './chart-renderer-helpers';
import { ChartRendererComponent } from './chart-renderer.component';
import { EditorStateService } from './editor-state.service';
import { LineChart3DRendererComponent } from './line-chart-3d-renderer.component';
import { LineChart3DService } from './line-chart-3d.service';
import { PieChart3DRendererComponent } from './pie-chart-3d-renderer.component';
import { PieChart3DService } from './pie-chart-3d.service';
import { SLIDE_CONTEXT } from './slide-context';
import { SurfaceChart3DRendererComponent } from './surface-chart-3d-renderer.component';
import { SurfaceChart3DService } from './surface-chart-3d.service';

@Component({
	selector: 'pptx-chart-element-view',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [
		ChartRendererComponent,
		SurfaceChart3DRendererComponent,
		BarChart3DRendererComponent,
		LineChart3DRendererComponent,
		AreaChart3DRendererComponent,
		PieChart3DRendererComponent,
	],
	template: `
		<div
			#wrapper
			class="pptx-ng-chart-view"
			[class.pptx-chart-interactive]="canEdit()"
			(pointerdown)="onPointerDown($event)"
			(pointermove)="onPointerMove($event)"
			(pointerup)="onPointerUp()"
			(dblclick)="onDblClick($event)"
		>
			@if (use3D() && isSurfaceKind()) {
				<pptx-surface-chart-3d-renderer [element]="renderedElement()" />
			} @else if (use3DBar() && isBar3DKind()) {
				<pptx-bar-chart-3d-renderer [element]="renderedElement()" />
			} @else if (use3DLine() && isLine3DKind()) {
				<pptx-line-chart-3d-renderer [element]="renderedElement()" />
			} @else if (use3DArea() && isArea3DKind()) {
				<pptx-area-chart-3d-renderer [element]="renderedElement()" />
			} @else if (use3DPie() && isPie3DKind()) {
				<pptx-pie-chart-3d-renderer [element]="renderedElement()" />
			} @else {
				<pptx-chart-renderer [element]="renderedElement()" />
			}
			@if (dragValue() !== null) {
				<div class="pptx-ng-chart-drag-badge">{{ dragBadge() }}</div>
			}
			@if (titleDraft() !== null) {
				<input
					#titleEditor
					type="text"
					class="pptx-ng-chart-title-input"
					[value]="titleDraft() ?? ''"
					(input)="onTitleInput($event)"
					(keydown)="onTitleKeydown($event)"
					(blur)="commitTitle()"
					(pointerdown)="$event.stopPropagation()"
					(dblclick)="$event.stopPropagation()"
				/>
			}
		</div>
	`,
})
export class ChartElementViewComponent {
	/** The chart element to render. Must be `type === 'chart'`. */
	readonly element = input.required<PptxElement>();
	/**
	 * Whether the hosting canvas allows editing this element. Direct part
	 * editing additionally requires the element to be SELECTED ({@link canEdit}).
	 */
	readonly editable = input<boolean>(false);

	/**
	 * Native-animation playback state. When it carries a staged chart build
	 * (`build.kind === 'chart'`, or the authored-index `chartReveal`) the chart
	 * reveals its series / categories / cells progressively via the shared
	 * `resolveRevealedChartData`. Absent outside a running presentation, so
	 * ordinary rendering is unaffected.
	 */
	readonly animationState = input<ElementAnimationState | undefined>(undefined);

	/**
	 * The editor state layer. Optional: the renderer is also used outside the
	 * editing viewer (thumbnails, export). On-canvas chart edits commit through
	 * `updateElement` here, the exact channel the inspector uses, so undo/redo
	 * and save round-trip are shared (one history snapshot per commit).
	 */
	private readonly editor = inject(EditorStateService, { optional: true });
	/** Canvas <-> inspector chart-part selection bridge (viewer-scoped). */
	private readonly partSelection = inject(ChartPartSelectionService, { optional: true });
	/** The hosting canvas's slide, for resolving template (master/layout) charts. */
	private readonly slideContext = inject(SLIDE_CONTEXT, { optional: true });
	/** Viewer-scoped opt-in flag for the interactive 3D surface-chart renderer. */
	private readonly surfaceChart3DSvc = inject(SurfaceChart3DService, { optional: true });
	/** Viewer-scoped opt-in flag for the interactive 3D bar3D-chart renderer. */
	private readonly barChart3DSvc = inject(BarChart3DService, { optional: true });
	/** Viewer-scoped opt-in flag for the interactive 3D line3D-chart renderer. */
	private readonly lineChart3DSvc = inject(LineChart3DService, { optional: true });
	/** Viewer-scoped opt-in flag for the interactive 3D area3D-chart renderer. */
	private readonly areaChart3DSvc = inject(AreaChart3DService, { optional: true });
	/** Viewer-scoped opt-in flag for the interactive 3D pie3D-chart renderer. */
	private readonly pieChart3DSvc = inject(PieChart3DService, { optional: true });
	private readonly injector = inject(Injector);

	private readonly wrapper = viewChild<ElementRef<HTMLElement>>('wrapper');
	private readonly titleEditor = viewChild<ElementRef<HTMLInputElement>>('titleEditor');

	/** In-flight vertical value drag, or null. */
	private dragSession: ChartValueDragState | null = null;
	/**
	 * In-flight pie/doughnut slice, radar vertex, or stacked segment drag, or
	 * null. Runs through a parallel state machine (no single vertical value
	 * axis), never both at once.
	 */
	private markDragSession: ChartMarkDragState | null = null;
	/** Local drag preview: rendered instead of the committed data mid-drag. */
	private readonly previewData = signal<PptxChartData | null>(null);
	/** Live value under the pointer mid-drag (drives the floating badge). */
	protected readonly dragValue = signal<number | null>(null);
	/** Inline title editor draft, or null when the editor is closed. */
	protected readonly titleDraft = signal<string | null>(null);

	private readonly chartData = computed<PptxChartData | undefined>(() => {
		const el = this.element();
		return el.type === 'chart' ? el.chartData : undefined;
	});

	/**
	 * Opt-in interactive 3D surface scene (camera orbit/zoom via OrbitControls).
	 * Marks are not selectable/draggable in this mode: a mesh facet has no 2D
	 * screen geometry to hit-test against, so value-drag editing stays SVG-only.
	 */
	protected readonly use3D = computed(() => this.surfaceChart3DSvc?.enabled() ?? false);
	protected readonly isSurfaceKind = computed(
		() => resolveChartKind(this.chartData()?.chartType ?? 'bar') === 'surface',
	);

	/**
	 * Opt-in interactive 3D bar scene (real box meshes, camera orbit/zoom via
	 * OrbitControls). Same "marks are not selectable/draggable" caveat as the
	 * surface scene above. `chartType` is checked directly (NOT via
	 * `resolveChartKind`, which folds `bar`/`bar3D` onto the same 'bar' kind),
	 * so a plain 2-D bar chart never mounts the 3D scene.
	 */
	protected readonly use3DBar = computed(() => this.barChart3DSvc?.enabled() ?? false);
	protected readonly isBar3DKind = computed(() => this.chartData()?.chartType === 'bar3D');

	/**
	 * Opt-in interactive 3D line/area scenes (tube path / ribbon meshes, camera
	 * orbit/zoom via OrbitControls). Same "marks are not selectable/draggable"
	 * caveat as the surface/bar scenes above.
	 */
	protected readonly use3DLine = computed(() => this.lineChart3DSvc?.enabled() ?? false);
	protected readonly isLine3DKind = computed(() => this.chartData()?.chartType === 'line3D');
	protected readonly use3DArea = computed(() => this.areaChart3DSvc?.enabled() ?? false);
	protected readonly isArea3DKind = computed(() => this.chartData()?.chartType === 'area3D');

	/**
	 * Opt-in interactive 3D pie scene (real wedge meshes, camera orbit/zoom via
	 * OrbitControls). Same "marks are not selectable/draggable" caveat as the
	 * bar scene above. `chartType` is checked directly (NOT via
	 * `resolveChartKind`, which folds `pie`/`pie3D`/`doughnut` onto the same
	 * 'pie' kind), so a plain 2-D pie or doughnut chart never mounts the 3D
	 * scene.
	 */
	protected readonly use3DPie = computed(() => this.pieChart3DSvc?.enabled() ?? false);
	protected readonly isPie3DKind = computed(() => this.chartData()?.chartType === 'pie3D');

	/** Whether this chart element is currently selected in the editor. */
	private readonly isSelected = computed(
		() => this.editor?.selectedIds().includes(this.element().id) ?? false,
	);

	/** Direct part editing is active: selected + editable + a commit channel. */
	protected readonly canEdit = computed(() =>
		chartCanEditParts(this.editable(), this.isSelected(), this.editor !== null, this.element()),
	);

	/** VM of the COMMITTED data: drag geometry must not rescale mid-drag. */
	private readonly viewModel = computed(() =>
		this.canEdit() ? buildChartViewModel(this.element()) : null,
	);

	/**
	 * The element to render: committed data, or the local drag preview, with its
	 * data trimmed to the stages revealed at the current staged-build progress (the
	 * drag preview wins first). Whole-chart / no-build renders return the element
	 * unchanged. Mirrors the Vue `ChartRenderer`'s `revealedElement`.
	 */
	protected readonly renderedElement = computed<PptxElement>(() => {
		const preview = this.previewData();
		const base: PptxElement = preview
			? ({ ...this.element(), chartData: preview } as PptxElement)
			: this.element();
		if (base.type !== 'chart' || !base.chartData) {
			return base;
		}
		const revealed = resolveRevealedChartData(base.chartData, this.animationState());
		return revealed === base.chartData ? base : ({ ...base, chartData: revealed } as PptxElement);
	});

	protected readonly dragBadge = computed(() => {
		const value = this.dragValue();
		return value === null ? '' : formatAxisValue(value);
	});

	/** The part selected for THIS chart, or null. */
	private readonly selectedPart = computed(() => {
		const sel = this.partSelection?.selection() ?? null;
		return sel && sel.elementId === this.element().id ? sel.part : null;
	});

	constructor() {
		ensureChartInteractionStyles();

		// Drop this chart's part selection when it stops being editable
		// (deselected, mode change) so the inspector highlight does not linger.
		//
		// Guarded on `editable()`, and that guard is load-bearing: the SAME chart
		// element is mounted several times over (the thumbnail rail alone renders
		// one copy per slide), every copy shares this element id, and only the
		// canvas copy is on an editable surface. Without the guard the read-only
		// copies raced the canvas on every mark click - the canvas set the
		// selection, a rail copy saw `!canEdit()` and cleared it a tick later, so
		// the highlight class was applied and stripped within ~100ms and no mark
		// ever stayed selected. Note the discriminator has to be the `editable`
		// INPUT, not the editor service: that is `inject(..., {optional: true})`,
		// so every mount in the tree shares one non-null instance and testing it
		// excludes nothing. Deselecting still clears, because `editable()` stays
		// true while `isSelected()` goes false. React's `ChartElementView` carried
		// the identical defect (there the read-only mounts are told apart by the
		// absence of an `onUpdateElement` prop).
		effect(() => {
			if (!this.editable()) {
				return;
			}
			if (!this.canEdit()) {
				this.partSelection?.clearForElement(this.element().id);
			}
		});

		// Re-apply the selected-part highlight after each render that re-creates
		// the SVG marks (selection / data / preview changes drop DOM-only classes).
		effect(() => {
			const part = this.selectedPart();
			this.renderedElement();
			afterNextRender(
				() => {
					const root = this.wrapper()?.nativeElement;
					if (root) {
						applyChartPartHighlight(root, part);
					}
				},
				{ injector: this.injector },
			);
		});

		// Focus the inline title editor as soon as it mounts.
		effect(() => {
			if (this.titleDraft() !== null) {
				afterNextRender(() => this.titleEditor()?.nativeElement.focus(), {
					injector: this.injector,
				});
			}
		});
	}

	// ── Pointer interaction (event delegation over data-chart-* marks) ────────

	protected onPointerDown(event: PointerEvent): void {
		if (!this.canEdit()) {
			return;
		}
		const part = findChartPartTarget(event.target);
		if (!part) {
			return;
		}
		event.stopPropagation();
		this.partSelection?.select({ elementId: this.element().id, part });
		const chartData = this.chartData();
		const vm = this.viewModel();
		if (!chartData || !vm) {
			return;
		}
		let captured = false;
		// Pie/doughnut/radar/stacked marks: try the angle/radial/segment drag first.
		const chartKind = resolveChartKind(chartData.chartType ?? 'bar');
		if (part.pointIndex !== undefined && chartKind !== 'unsupported') {
			const markGeometry = buildChartMarkDragGeometry({
				kind: chartKind,
				element: this.element(),
				chartData,
				categoryLabels: chartData.categories,
				seriesIndex: part.seriesIndex,
				pointIndex: part.pointIndex,
			});
			const markSession = beginChartMarkDrag({
				part,
				geometry: markGeometry,
				chartData,
				svgWidth: vm.svgWidth,
				svgHeight: vm.svgHeight,
				clientX: event.clientX,
				clientY: event.clientY,
			});
			if (markSession) {
				this.markDragSession = markSession;
				captured = true;
			}
		}
		// Clustered bar/line/scatter/bubble: the existing vertical value-axis drag.
		if (!captured) {
			const session = beginChartValueDrag({
				part,
				viewModel: vm,
				chartData,
				clientY: event.clientY,
			});
			if (session) {
				this.dragSession = session;
				captured = true;
			}
		}
		if (!captured) {
			return;
		}
		event.preventDefault();
		// Pointer capture keeps the drag alive off-mark; guarded because test
		// DOMs (and older browsers) may not implement it.
		try {
			(event.currentTarget as Element | null)?.setPointerCapture?.(event.pointerId);
		} catch {
			// Non-fatal: the drag still works while the pointer stays over the chart.
		}
	}

	protected onPointerMove(event: PointerEvent): void {
		const markSession = this.markDragSession;
		if (markSession) {
			const rect = this.wrapper()?.nativeElement.querySelector('svg')?.getBoundingClientRect();
			if (!rect) {
				return;
			}
			const step = advanceChartMarkDrag(markSession, event.clientX, event.clientY, rect);
			if (step) {
				this.previewData.set(step.chartData);
				this.dragValue.set(step.value);
			}
			return;
		}
		const session = this.dragSession;
		if (!session) {
			return;
		}
		const svg = this.wrapper()?.nativeElement.querySelector('svg');
		const height = svg?.getBoundingClientRect().height ?? 0;
		const step = advanceChartValueDrag(session, event.clientY, height);
		if (step) {
			this.previewData.set(step.chartData);
			this.dragValue.set(step.value);
		}
	}

	protected onPointerUp(): void {
		if (this.dragSession || this.markDragSession) {
			this.endDrag(true);
		}
	}

	/** Cancel an in-flight value drag with Escape (document-level, like React). */
	@HostListener('document:keydown.escape')
	protected onEscape(): void {
		if (this.dragSession || this.markDragSession) {
			this.endDrag(false);
		}
	}

	private endDrag(commit: boolean): void {
		const data =
			chartDragCommitData(this.dragSession, commit) ??
			chartMarkDragCommitData(this.markDragSession, commit);
		this.dragSession = null;
		this.markDragSession = null;
		this.previewData.set(null);
		this.dragValue.set(null);
		if (data) {
			commitChartElementData(
				this.editor,
				this.element().id,
				data,
				this.slideContext?.slideId() ?? null,
			);
		}
	}

	// ── Inline title editing ──────────────────────────────────────────────────

	protected onDblClick(event: MouseEvent): void {
		if (!this.canEdit()) {
			return;
		}
		const target = event.target as Partial<Element>;
		if (typeof target.closest !== 'function') {
			return;
		}
		if ((target as Element).closest("[data-chart-part='title']")) {
			event.stopPropagation();
			this.titleDraft.set(this.chartData()?.title ?? '');
			return;
		}
		if (findChartPartTarget(event.target)) {
			// A mark double-click is two selects; keep it from bubbling into the
			// canvas-level inline-text-edit handler.
			event.stopPropagation();
		}
	}

	protected onTitleInput(event: Event): void {
		this.titleDraft.set((event.target as HTMLInputElement).value);
	}

	protected onTitleKeydown(event: KeyboardEvent): void {
		if (event.key === 'Enter') {
			this.commitTitle();
		} else if (event.key === 'Escape') {
			this.titleDraft.set(null);
		}
		event.stopPropagation();
	}

	protected commitTitle(): void {
		const draft = this.titleDraft();
		const chartData = this.chartData();
		if (draft !== null && chartData) {
			commitChartElementData(
				this.editor,
				this.element().id,
				withChartTitle(chartData, draft),
				this.slideContext?.slideId() ?? null,
			);
		}
		this.titleDraft.set(null);
	}
}

<div
	#wrapper
	class="pptx-ng-chart-view"
	[class.pptx-chart-interactive]="canEdit()"
	(pointerdown)="onPointerDown($event)"
	(pointermove)="onPointerMove($event)"
	(pointerup)="onPointerUp()"
	(dblclick)="onDblClick($event)"
>
	@if (use3D() && isSurfaceKind()) {
		<pptx-surface-chart-3d-renderer
			[element]="renderedElement()"
			[selectedPart]="selectedPart()"
			[textStyle]="chartTextStyle()"
			(partSelect)="onChartPart3DSelect($event)"
			(valueDragPreview)="onChart3DValueDragPreview($event)"
			(valueDragCommit)="onChart3DValueDragCommit($event)"
		/>
	} @else if (use3DBar() && isBar3DKind()) {
		<pptx-bar-chart-3d-renderer
			[element]="renderedElement()"
			[selectedPart]="selectedPart()"
			[textStyle]="chartTextStyle()"
			(partSelect)="onChartPart3DSelect($event)"
			(valueDragPreview)="onChart3DValueDragPreview($event)"
			(valueDragCommit)="onChart3DValueDragCommit($event)"
		/>
	} @else if (use3DLine() && isLine3DKind()) {
		<pptx-line-chart-3d-renderer
			[element]="renderedElement()"
			[selectedPart]="selectedPart()"
			[textStyle]="chartTextStyle()"
			(partSelect)="onChartPart3DSelect($event)"
			(valueDragPreview)="onChart3DValueDragPreview($event)"
			(valueDragCommit)="onChart3DValueDragCommit($event)"
		/>
	} @else if (use3DArea() && isArea3DKind()) {
		<pptx-area-chart-3d-renderer
			[element]="renderedElement()"
			[selectedPart]="selectedPart()"
			[textStyle]="chartTextStyle()"
			(partSelect)="onChartPart3DSelect($event)"
			(valueDragPreview)="onChart3DValueDragPreview($event)"
			(valueDragCommit)="onChart3DValueDragCommit($event)"
		/>
	} @else if (use3DPie() && isPie3DKind()) {
		<pptx-pie-chart-3d-renderer
			[element]="renderedElement()"
			[selectedPart]="selectedPart()"
			(partSelect)="onChartPart3DSelect($event)"
			(valueDragPreview)="onChart3DValueDragPreview($event)"
			(valueDragCommit)="onChart3DValueDragCommit($event)"
		/>
	} @else {
		<pptx-chart-renderer [element]="renderedElement()" />
	}
	@if (dragValue() !== null) {
		<div class="pptx-ng-chart-drag-badge">{{ dragBadge() }}</div>
	}
	@if (titleDraft() !== null) {
		<input
			#titleEditor
			type="text"
			class="pptx-ng-chart-title-input"
			[value]="titleDraft() ?? ''"
			(input)="onTitleInput($event)"
			(keydown)="onTitleKeydown($event)"
			(blur)="commitTitle()"
			(pointerdown)="$event.stopPropagation()"
			(dblclick)="$event.stopPropagation()"
		/>
	}
</div>
