// packages/vue/src/viewer/components/inspector/ChartMarkerOptions.vue
<script setup lang="ts">
import type { PptxChartMarkerSymbol, PptxChartSeries, PptxChartType } from 'pptx-viewer-core';
import { MARKER_SUPPORTED_TYPES, MARKER_SYMBOL_OPTIONS } from 'pptx-viewer-shared';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import { injectRecentColors } from '../../composables/recent-colors-context';
import type { ChartMarkerEdit } from '../../composables/useChartEditing';

/**
 * ChartMarkerOptions: per-series marker symbol/size/fill for line/scatter/
 * bubble/radar charts. Mirrors React's `ChartMarkerOptions`. Emits
 * `setMarker(index, edit)` where `null` removes the marker.
 */
const props = defineProps<{
	chartType: PptxChartType;
	series: readonly PptxChartSeries[];
}>();

const emit = defineEmits<{
	setMarker: [index: number, marker: ChartMarkerEdit | null];
}>();

const { t } = useI18n();
const recentColors = injectRecentColors();

const visible = computed(
	() => MARKER_SUPPORTED_TYPES.has(props.chartType) && props.series.length > 0,
);

function onSymbol(event: Event, index: number): void {
	const value = (event.target as HTMLSelectElement).value;
	if (value === '') {
		emit('setMarker', index, null);
		return;
	}
	emit('setMarker', index, { symbol: value as PptxChartMarkerSymbol });
}

function onSize(event: Event, index: number): void {
	const num = Number.parseInt((event.target as HTMLInputElement).value, 10);
	emit('setMarker', index, { size: Number.isFinite(num) ? num : undefined });
}

function onFill(event: Event, index: number): void {
	emit('setMarker', index, { fillColor: (event.target as HTMLInputElement).value });
}

function onFillCommit(event: Event): void {
	recentColors?.push((event.target as HTMLInputElement).value);
}
</script>

<template>
	<div
		v-if="visible"
		class="pptx-vue-chart-card rounded border border-border bg-card p-2 space-y-2"
	>
		<div class="pptx-vue-chart-heading text-[11px] uppercase tracking-wide text-muted-foreground">
			{{ t('pptx.chart.markers') }}
		</div>
		<div class="space-y-2">
			<div v-for="(s, i) in props.series" :key="`${s.name}-${i}`" class="space-y-1">
				<div class="flex items-center gap-2 text-[11px]">
					<span class="flex-1 truncate" :title="s.name">{{ s.name }}</span>
					<select
						class="pptx-vue-chart-input flex-1 bg-muted border border-border rounded px-1.5 py-0.5 w-full"
						data-testid="chart-marker-symbol"
						:value="s.marker?.symbol ?? ''"
						@change="onSymbol($event, i)"
					>
						<option v-for="opt in MARKER_SYMBOL_OPTIONS" :key="opt.value" :value="opt.value">
							{{ t(opt.labelKey) }}
						</option>
					</select>
				</div>

				<div v-if="s.marker && s.marker.symbol !== 'none'" class="flex items-center gap-3 ml-2">
					<label class="flex items-center gap-1 text-[11px]">
						<span class="text-muted-foreground">{{ t('pptx.chart.markerSize') }}</span>
						<input
							type="number"
							min="2"
							max="72"
							data-testid="chart-marker-size"
							class="w-14 bg-muted border border-border rounded px-1.5 py-0.5"
							:value="s.marker.size ?? ''"
							:placeholder="t('pptx.chart.auto')"
							@input="onSize($event, i)"
						/>
					</label>
					<label class="flex items-center gap-1 text-[11px]">
						<span class="text-muted-foreground">{{ t('pptx.chart.markerFill') }}</span>
						<input
							type="color"
							data-testid="chart-marker-fill"
							class="h-6 w-8 cursor-pointer rounded border border-border bg-transparent"
							:value="s.marker.spPr?.fillColor ?? '#4472c4'"
							@input="onFill($event, i)"
							@change="onFillCommit"
						/>
					</label>
				</div>
			</div>
		</div>
	</div>
</template>

// packages/angular/src/viewer/chart-marker-options.component.ts
/**
 * chart-marker-options.component.ts: Per-series marker controls.
 *
 * Selector: `pptx-chart-marker-options`
 *
 * Mirrors React's `ChartMarkerOptions.tsx`: for line/scatter/bubble/radar charts,
 * each series gets a marker-symbol selector and (when a visible symbol is chosen)
 * size and fill-colour controls. Routes through `setSeriesMarker` and emits a new
 * `ChartPptxElement`.
 *
 * @module angular-viewer/chart-marker-options
 */

import { ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import type {
	ChartPptxElement,
	PptxChartMarkerSymbol,
	PptxChartSeries,
	PptxChartType,
} from 'pptx-viewer-core';

import { MARKER_SUPPORTED_TYPES, MARKER_SYMBOL_OPTIONS } from '../internal/shared';
import { setSeriesMarker } from './chart-data-helpers';
import { CHART_EDITOR_STYLES } from './chart-editor-styles';
import { numFromEvent, selectValue, stringFromEvent } from './chart-event-helpers';

@Component({
	selector: 'pptx-chart-marker-options',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [TranslatePipe],
	template: `
		@if (supported()) {
			<section class="pptx-chart-card" [attr.aria-label]="'pptx.chart.markers' | translate">
				<h4 class="pptx-chart-card__heading">{{ 'pptx.chart.markers' | translate }}</h4>
				@for (s of series(); track $index; let i = $index) {
					<div class="pptx-chart-card__group">
						<div class="pptx-chart-card__row">
							<span class="pptx-chart-card__name" [title]="s.name">{{ s.name }}</span>
							<select
								class="pptx-chart-card__input"
								[disabled]="!canEdit()"
								[value]="s.marker?.symbol ?? ''"
								(change)="onSymbol(i, $event)"
							>
								@for (opt of symbolOptions; track opt.value) {
									<option [value]="opt.value" [selected]="opt.value === (s.marker?.symbol ?? '')">
										{{ opt.labelKey | translate }}
									</option>
								}
							</select>
						</div>

						@if (s.marker && s.marker.symbol !== 'none') {
							<div class="pptx-chart-card__row pptx-chart-card__group--indent">
								<span class="pptx-chart-card__label">{{
									'pptx.chart.markerSize' | translate
								}}</span>
								<input
									type="number"
									min="2"
									max="72"
									class="pptx-chart-card__input pptx-chart-card__input--num"
									[placeholder]="'pptx.chart.auto' | translate"
									[disabled]="!canEdit()"
									[value]="s.marker.size ?? ''"
									(change)="onSize(i, $event)"
								/>
								<span class="pptx-chart-card__label">{{
									'pptx.chart.markerFill' | translate
								}}</span>
								<input
									type="color"
									class="pptx-chart-card__color"
									[disabled]="!canEdit()"
									[value]="s.marker.spPr?.fillColor ?? '#4472c4'"
									(input)="onFill(i, $event)"
								/>
							</div>
						}
					</div>
				}
			</section>
		}
	`,
	styles: CHART_EDITOR_STYLES,
})
export class ChartMarkerOptionsComponent {
	readonly element = input.required<ChartPptxElement>();
	readonly canEdit = input<boolean>(true);
	readonly elementChange = output<ChartPptxElement>();

	protected readonly symbolOptions = MARKER_SYMBOL_OPTIONS;

	protected readonly series = computed<PptxChartSeries[]>(
		() => this.element().chartData?.series ?? [],
	);

	protected readonly supported = computed(() => {
		const type = this.element().chartData?.chartType as PptxChartType | undefined;
		return type !== undefined && MARKER_SUPPORTED_TYPES.has(type) && this.series().length > 0;
	});

	protected onSymbol(index: number, event: Event): void {
		const value = selectValue(event);
		if (value === null) {
			return;
		}
		this.elementChange.emit(
			setSeriesMarker(
				this.element(),
				index,
				value === '' ? null : { symbol: value as PptxChartMarkerSymbol },
			),
		);
	}

	protected onSize(index: number, event: Event): void {
		const num = numFromEvent(event);
		this.elementChange.emit(
			setSeriesMarker(this.element(), index, { size: typeof num === 'number' ? num : undefined }),
		);
	}

	protected onFill(index: number, event: Event): void {
		const value = stringFromEvent(event);
		if (value === null) {
			return;
		}
		this.elementChange.emit(setSeriesMarker(this.element(), index, { fillColor: value }));
	}
}
