// packages/vue/src/viewer/components/NotesPanel.vue
<script setup lang="ts">
import { ChevronDown, ChevronRight } from 'lucide-vue-next';
import type { PptxSlide, PptxTextStyleLevels } from 'pptx-viewer-core';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import NotesToolbar from './NotesToolbar.vue';
import { useNotesEditor } from './useNotesEditor';

/**
 * NotesPanel - collapsible speaker-notes panel for the Vue editor.
 *
 * Renders below the slide canvas and shows/edits the current slide's speaker
 * notes. Reads the real core fields `PptxSlide.notes` (plain string) and
 * `PptxSlide.notesSegments` (rich runs, when the deck was loaded from a .pptx).
 * The host writes the edited text back to the slide via a history-aware
 * reassignment when `update` is emitted.
 *
 * Rich vs plain
 * -------------
 * The default surface is a contentEditable RICH editor (bold/italic/underline/
 * strikethrough, bullet/numbered lists, indent, hyperlinks), mirroring the
 * React viewer. On a mobile viewport the editor defaults to a plain `<textarea>`
 * so the on-screen keyboard and caret behave (the documented mobile rationale);
 * the toolbar's rich/plain toggle flips between the two on any device. All
 * framework-agnostic logic lives in `pptx-viewer-shared`; this SFC is the view
 * layer and `useNotesEditor` is the thin reactive wiring.
 *
 * Touch / focus correctness
 * -------------------------
 * Both surfaces are UNCONTROLLED: their content is seeded imperatively (once per
 * slide, keyed by slide id) and never re-bound while the user types. Rich edits
 * are debounced; plain edits commit on `change` / `blur`. This keeps the host's
 * per-keystroke history-aware reassignment from remounting the field mid-typing,
 * which on mobile would dismiss the keyboard and jump the caret.
 *
 * Props : `{ slide: PptxSlide | undefined }`
 * Emits : `update: [notes: string]` - the new plain-text notes.
 */
const props = defineProps<{
	slide: PptxSlide | undefined;
	/**
	 * Whether the notes body is expanded. When false the panel collapses to just
	 * its header strip (React parity: the notes footer is always present below
	 * the canvas, the body toggles). Controlled by the host so the status-bar
	 * Notes button and the header chevron stay in sync.
	 */
	expanded?: boolean;
	/**
	 * True when hosted inside a chrome that already renders its own title +
	 * close button (the mobile `MobileSheet`). Suppresses the internal
	 * collapsible header, since the sheet is already fully open and provides
	 * its own close affordance - avoids a mismatched "Notes" / "Speaker Notes"
	 * double header on mobile.
	 */
	embedded?: boolean;
	/**
	 * The deck's notes master `<p:notesStyle>` (`PptxData.notesMaster.
	 * notesStyle`), when the host has it loaded. Its level-0 font/colour/indent
	 * defaults fill in any gap left by a segment that does not already carry an
	 * explicit value, so an authored deck's notes-text defaults reach this
	 * editor and the printed notes pages instead of a hardcoded look.
	 */
	notesStyle?: PptxTextStyleLevels;
}>();

const emit = defineEmits<{
	update: [notes: string];
	toggle: [];
}>();

const { t } = useI18n();

const hasSlide = computed<boolean>(() => props.slide !== undefined);

const {
	richEditorRef,
	textareaRef,
	isRichEnabled,
	showLinkPopover,
	savedSelectionText,
	onRichInput,
	inlineCommand,
	paragraphCommand,
	onRichKeydown,
	onEditorClick,
	openLinkPopover,
	insertLink,
	closeLinkPopover,
	onPlainCommit,
	toggleRich,
	printNotes,
} = useNotesEditor(
	() => props.slide,
	(notes) => emit('update', notes),
	() => props.notesStyle,
);

/**
 * Show the rich surface only when a slide is selected; with no slide we fall
 * back to the disabled plain textarea (its "No slide selected" placeholder).
 */
const showRich = computed<boolean>(() => hasSlide.value && isRichEnabled.value);

const collapsed = computed<boolean>(() => !(props.expanded ?? false));

function toggle(): void {
	emit('toggle');
}
</script>

<template>
	<section
		class="pptx-vue-notes-panel flex flex-col border-t border-border/60 bg-background"
		:data-collapsed="collapsed"
	>
		<button
			v-if="!embedded"
			type="button"
			class="pptx-vue-notes-header flex w-full items-center justify-between px-3 py-2 text-left text-[0.8125rem] font-semibold text-muted-foreground transition-colors hover:bg-accent/30 hover:text-foreground"
			:aria-expanded="!collapsed"
			@click="toggle"
		>
			<span class="pptx-vue-notes-title select-none">{{ t('pptx.presenter.speakerNotes') }}</span>
			<component
				:is="collapsed ? ChevronRight : ChevronDown"
				class="pptx-vue-notes-chevron h-3.5 w-3.5 text-muted-foreground"
				aria-hidden="true"
			/>
		</button>

		<div v-show="!collapsed" id="slide-notes-content" class="pptx-vue-notes-body px-3 pb-3">
			<NotesToolbar
				v-if="hasSlide"
				:is-rich-enabled="isRichEnabled"
				:show-link-popover="showLinkPopover"
				:saved-selection-text="savedSelectionText"
				@inline="inlineCommand"
				@toggle-bullet="paragraphCommand('bullet')"
				@toggle-numbered="paragraphCommand('numbered')"
				@indent="paragraphCommand('indent')"
				@outdent="paragraphCommand('outdent')"
				@link-button-click="openLinkPopover"
				@insert-link="insertLink"
				@close-link-popover="closeLinkPopover"
				@print="printNotes"
				@toggle-rich="toggleRich"
			/>

			<!-- Rich contentEditable surface (desktop default). Seeded imperatively
			     via innerHTML built by the shared sanitising serialiser. -->
			<div
				v-show="showRich"
				ref="richEditorRef"
				:contenteditable="showRich"
				role="textbox"
				aria-multiline="true"
				:aria-label="t('pptx.presenter.speakerNotes')"
				class="pptx-vue-notes-rich box-border min-h-20 w-full resize-y overflow-auto rounded-md border border-border/50 bg-muted/60 p-2 text-[0.8125rem] leading-relaxed text-foreground focus:border-primary/50 focus:outline-none focus:ring-1 focus:ring-primary/30"
				@input="onRichInput"
				@keydown="onRichKeydown"
				@blur="onRichInput"
				@click="onEditorClick"
			/>

			<!-- Plain textarea fallback (mobile default / toggle / no slide). -->
			<textarea
				v-show="!showRich"
				ref="textareaRef"
				name="slide-notes"
				class="pptx-vue-notes-textarea box-border min-h-20 w-full resize-y rounded-md border border-border/50 bg-muted/60 p-2 text-[0.8125rem] leading-relaxed text-foreground transition-colors placeholder:text-muted-foreground focus:border-primary/50 focus:outline-none focus:ring-1 focus:ring-primary/30 disabled:cursor-not-allowed disabled:opacity-60"
				:disabled="!hasSlide"
				:placeholder="hasSlide ? t('pptx.notes.addSpeakerNotes') : t('pptx.notes.noSlide')"
				:aria-label="t('pptx.presenter.speakerNotes')"
				spellcheck="true"
				@change="onPlainCommit"
				@blur="onPlainCommit"
			/>
		</div>
	</section>
</template>

// packages/angular/src/viewer/notes-panel.component.ts
/**
 * notes-panel.component.ts: collapsible, editable speaker-notes panel.
 *
 * Ported from: packages/react/src/viewer/components/notes (rich editor) and the
 * earlier Vue/Angular plain-textarea panel.
 *
 * Renders the active slide's speaker notes. The default surface is a
 * contentEditable RICH editor (bold/italic/underline/strikethrough, bullet and
 * numbered lists, indent, hyperlinks, print), mirroring the React viewer. On a
 * mobile viewport it defaults to a plain `<textarea>` so the on-screen keyboard
 * and caret behave (the documented mobile rationale); the toolbar's rich/plain
 * toggle flips between the two on any device. All framework-agnostic logic lives
 * in `pptx-viewer-shared`; this component is the view layer + signal wiring.
 *
 * Framework-neutral e2e contract
 * ------------------------------
 * The body wrapper carries `id="slide-notes-content"` and the plain editor is a
 * `textarea[name="slide-notes"]` (kept in the DOM via `[hidden]`, not `@if`),
 * matching the React/Vue viewers so the shared Playwright specs run unchanged.
 *
 * Touch / focus correctness
 * -------------------------
 * Both surfaces are UNCONTROLLED: content is seeded imperatively (once per
 * slide, keyed by slide id) and never re-bound while the user types. Rich edits
 * are debounced; plain edits commit on `change` / `blur`. This keeps the host's
 * per-keystroke history-aware update from remounting the field mid-typing.
 */

import {
	afterNextRender,
	ChangeDetectionStrategy,
	Component,
	computed,
	effect,
	ElementRef,
	inject,
	input,
	output,
	signal,
	viewChild,
} from '@angular/core';
import { LucideChevronDown, LucideChevronRight } from '@lucide/angular';
import { TranslatePipe, TranslateService } from '@ngx-translate/core';
import type { PptxSlide, PptxTextStyleLevels, TextSegment } from 'pptx-viewer-core';

import type { NotesInlineCommand, NotesParagraphCommand } from '../internal/shared';
import {
	DEBOUNCE_MS,
	applyInlineCommand,
	applyParagraphCommand,
	buildNotesPrintHtml,
	createPlainNotesSegments,
	defaultRichEnabled,
	handleEditorAnchorClick,
	insertHyperlinkAtSelection,
	normalizeNotesLinkUrl,
	readEditorSegments,
	resolveNotesSegments,
	segmentsToEditorHtml,
	segmentsToPlainText,
} from '../internal/shared';
import { NotesToolbarComponent } from './notes-toolbar.component';

@Component({
	selector: 'pptx-notes-panel',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [NotesToolbarComponent, TranslatePipe, LucideChevronRight, LucideChevronDown],
	templateUrl: './notes-panel.component.html',
	styleUrl: './notes-panel.component.css',
})
export class NotesPanelComponent {
	private readonly translate = inject(TranslateService);

	/** The active slide whose notes are shown / edited. */
	readonly slide = input<PptxSlide | undefined>(undefined);

	/**
	 * Whether the notes body is expanded. When false the panel collapses to just
	 * its header strip (React parity: the notes footer is always present below
	 * the canvas, the body toggles). Host-controlled so the status-bar Notes
	 * button and the header chevron stay in sync.
	 */
	readonly expanded = input<boolean>(false);

	/**
	 * The deck's notes master `<p:notesStyle>` level defaults (`PptxData.
	 * notesMaster.notesStyle`), when the host has it. Fills in a notes
	 * segment's missing font/colour/indent from the authored defaults instead
	 * of a hardcoded look; see `resolveNotesSegments` / `buildNotesPrintHtml`.
	 */
	readonly notesStyle = input<PptxTextStyleLevels | undefined>(undefined);

	/** Emits the new plain-text notes on commit. */
	readonly update = output<string>();

	/** Emits when the header strip is clicked to expand / collapse the body. */
	readonly notesToggle = output<void>();

	readonly collapsed = computed<boolean>(() => !this.expanded());
	protected readonly isRichEnabled = signal<boolean>(defaultRichEnabled());
	protected readonly showLinkPopover = signal(false);
	protected readonly savedSelectionText = signal('');

	private readonly richEditor = viewChild<ElementRef<HTMLDivElement>>('richEditor');
	private readonly textarea = viewChild<ElementRef<HTMLTextAreaElement>>('textarea');

	/** Show the rich surface only when a slide is selected. */
	protected showRich(): boolean {
		return this.isRichEnabled() && this.slide() !== undefined;
	}

	private draftSegments: TextSegment[] = resolveNotesSegments(undefined, this.notesStyle());
	private draftText = '';
	private seededId: string | null = null;
	private debounceId: ReturnType<typeof setTimeout> | null = null;

	constructor() {
		// Re-seed the uncontrolled surface exactly once per slide (keyed by id), so
		// an in-progress edit is never overwritten on an unrelated change pass.
		effect(() => {
			const slide = this.slide();
			const id = slide?.id ?? null;
			if (id === this.seededId) {
				return;
			}
			this.seededId = id;
			this.draftSegments = resolveNotesSegments(slide, this.notesStyle());
			this.draftText = segmentsToPlainText(this.draftSegments);
			queueMicrotask(() => this.seedActiveSurface());
		});

		afterNextRender(() => this.seedActiveSurface());
	}

	private seedActiveSurface(): void {
		if (this.isRichEnabled()) {
			const el = this.richEditor()?.nativeElement;
			if (el) {
				// Built by the shared sanitising serialiser (text escaped, links/CSS
				// allow-listed), so assigning innerHTML here is safe.
				el.innerHTML = segmentsToEditorHtml(this.draftSegments);
			}
		} else {
			const el = this.textarea()?.nativeElement;
			if (el) {
				el.value = this.draftText;
			}
		}
	}

	private emitNow(text: string): void {
		if (this.debounceId) {
			clearTimeout(this.debounceId);
			this.debounceId = null;
		}
		this.update.emit(text);
	}

	private scheduleSave(text: string): void {
		if (this.debounceId) {
			clearTimeout(this.debounceId);
		}
		this.debounceId = setTimeout(() => {
			this.update.emit(text);
			this.debounceId = null;
		}, DEBOUNCE_MS);
	}

	toggle(): void {
		this.notesToggle.emit();
	}

	/* --- Rich editor --- */

	onRichInput(): void {
		const el = this.richEditor()?.nativeElement;
		if (!el) {
			return;
		}
		const next = readEditorSegments(el);
		this.draftSegments = next.segments;
		this.draftText = next.text;
		this.scheduleSave(next.text);
	}

	inlineCommand(command: NotesInlineCommand): void {
		applyInlineCommand(command);
		this.onRichInput();
		this.richEditor()?.nativeElement.focus();
	}

	paragraphCommand(command: NotesParagraphCommand): void {
		const el = this.richEditor()?.nativeElement;
		if (!el) {
			return;
		}
		const next = applyParagraphCommand(el, this.draftSegments, command);
		this.draftSegments = next.segments;
		this.draftText = next.text;
		// List/indent changes block structure, so re-seed the DOM.
		el.innerHTML = segmentsToEditorHtml(next.segments);
		this.scheduleSave(next.text);
		el.focus();
	}

	onRichKeydown(event: KeyboardEvent): void {
		event.stopPropagation();
		if (event.key === 'Enter' && (event.metaKey || event.ctrlKey)) {
			this.emitNow(this.draftText);
			this.richEditor()?.nativeElement.blur();
			return;
		}
		if (event.key === 'Tab') {
			event.preventDefault();
			this.paragraphCommand(event.shiftKey ? 'outdent' : 'indent');
		}
	}

	onEditorClick(event: MouseEvent): void {
		if (handleEditorAnchorClick(event.target, event.ctrlKey || event.metaKey)) {
			event.preventDefault();
		}
	}

	/* --- Hyperlink popover --- */

	openLinkPopover(): void {
		this.savedSelectionText.set(window.getSelection()?.toString() ?? '');
		this.showLinkPopover.set(true);
	}

	insertLink(link: { url: string; displayText: string }): void {
		this.showLinkPopover.set(false);
		const el = this.richEditor()?.nativeElement;
		if (!el) {
			return;
		}
		el.focus();
		const finalUrl = normalizeNotesLinkUrl(link.url);
		insertHyperlinkAtSelection(finalUrl, link.displayText || finalUrl);
		this.onRichInput();
	}

	/* --- Plain textarea --- */

	onPlainCommit(event: Event): void {
		const value = (event.target as HTMLTextAreaElement).value;
		this.draftText = value;
		this.draftSegments = createPlainNotesSegments(value);
		this.emitNow(value);
	}

	/* --- Toggle + print --- */

	toggleRich(): void {
		const richEl = this.richEditor()?.nativeElement;
		const plainEl = this.textarea()?.nativeElement;
		if (this.isRichEnabled() && richEl) {
			const next = readEditorSegments(richEl);
			this.draftSegments = next.segments;
			this.draftText = next.text;
		} else if (!this.isRichEnabled() && plainEl) {
			this.draftText = plainEl.value;
			this.draftSegments = createPlainNotesSegments(this.draftText);
		}
		this.isRichEnabled.update((v) => !v);
		queueMicrotask(() => this.seedActiveSurface());
	}

	printNotes(): void {
		const slide = this.slide();
		if (!slide || typeof document === 'undefined') {
			return;
		}
		const html = buildNotesPrintHtml(
			[slide],
			(n) => this.translate.instant('pptx.notes.slideN', { n }),
			this.notesStyle(),
		);
		const frame = document.createElement('iframe');
		frame.setAttribute('aria-hidden', 'true');
		frame.style.cssText = 'position:fixed;right:0;bottom:0;width:0;height:0;border:0';
		document.body.appendChild(frame);
		const doc = frame.contentWindow?.document;
		if (!doc) {
			frame.remove();
			return;
		}
		doc.open();
		doc.write(html);
		doc.close();
		setTimeout(() => {
			frame.contentWindow?.focus();
			frame.contentWindow?.print();
			setTimeout(() => frame.remove(), 1000);
		}, 200);
	}
}

<section class="pptx-ng-notes-panel" [attr.data-collapsed]="collapsed()">
	<button
		type="button"
		class="pptx-ng-notes-header"
		[attr.aria-expanded]="!collapsed()"
		(click)="toggle()"
	>
		<span class="pptx-ng-notes-label">{{ 'pptx.notes.speakerNotes' | translate }}</span>
		<span class="pptx-ng-notes-chevron" aria-hidden="true">
			@if (collapsed()) {
				<svg lucideChevronRight class="h-4 w-4"></svg>
			} @else {
				<svg lucideChevronDown class="h-4 w-4"></svg>
			}
		</span>
	</button>

	@if (!collapsed()) {
		<div id="slide-notes-content" class="pptx-ng-notes-body">
			@if (slide()) {
				<pptx-notes-toolbar
					[isRichEnabled]="isRichEnabled()"
					[showLinkPopover]="showLinkPopover()"
					[savedSelectionText]="savedSelectionText()"
					(inline)="inlineCommand($event)"
					(paragraph)="paragraphCommand($event)"
					(linkButtonClick)="openLinkPopover()"
					(insertLink)="insertLink($event)"
					(closeLinkPopover)="showLinkPopover.set(false)"
					(print)="printNotes()"
					(toggleRich)="toggleRich()"
				/>
			}

			<div
				#richEditor
				class="pptx-ng-notes-rich"
				[hidden]="!showRich()"
				[attr.contenteditable]="showRich() ? 'true' : 'false'"
				role="textbox"
				aria-multiline="true"
				[attr.aria-label]="'pptx.notes.speakerNotes' | translate"
				(input)="onRichInput()"
				(keydown)="onRichKeydown($event)"
				(blur)="onRichInput()"
				(click)="onEditorClick($event)"
			></div>

			<textarea
				#textarea
				name="slide-notes"
				class="pptx-ng-notes-textarea"
				[hidden]="showRich()"
				[disabled]="!slide()"
				[attr.placeholder]="
					(slide() ? 'pptx.notes.addSpeakerNotes' : 'pptx.notes.noSlide') | translate
				"
				[attr.aria-label]="'pptx.notes.speakerNotes' | translate"
				spellcheck="true"
				(change)="onPlainCommit($event)"
				(blur)="onPlainCommit($event)"
			></textarea>
		</div>
	}
</section>
