// packages/svelte/src/viewer/components/PresentationContextMenu.svelte
<script lang="ts">
	/**
	 * The slide-show right-click menu, shown while presenting when Options >
	 * Advanced > "Show menu on right mouse click" is on.
	 *
	 * Item order/grouping/i18n keys come from the shared
	 * `getPresentationContextMenuSections` (`pptx-viewer-shared`), the same
	 * source React's `PresentationContextMenu` and Vue's `PresentationMode`
	 * render from, so this menu cannot drift from theirs. The caller passes
	 * which capabilities are available (this binding has all of them) and a
	 * single `onaction` dispatch; it decides what each id does.
	 */
	import { getPresentationContextMenuSections } from 'pptx-viewer-shared';
	import type {
		PresentationContextMenuActionId,
		PresentationContextMenuCapabilities,
	} from 'pptx-viewer-shared';

	import { useTranslator } from '../../i18n/context';

	const {
		x,
		y,
		capabilities,
		onaction,
		onclose,
	}: {
		x: number;
		y: number;
		capabilities: PresentationContextMenuCapabilities;
		onaction: (id: PresentationContextMenuActionId) => void;
		onclose: () => void;
	} = $props();
	const t = useTranslator();

	const sections = $derived(getPresentationContextMenuSections(capabilities));

	function run(id: PresentationContextMenuActionId): void {
		onaction(id);
		onclose();
	}
</script>

<button class="scrim" type="button" aria-label={t('pptx.settings.close')} onclick={onclose} oncontextmenu={(event) => { event.preventDefault(); onclose(); }}></button>
<div class="menu" role="menu" tabindex="-1" data-pptx-presentation-menu style={`left:${x}px;top:${y}px`} oncontextmenu={(event) => event.preventDefault()}>
	{#each sections as section, sectionIndex (section.id)}
		{#if sectionIndex > 0}<hr />{/if}
		{#each section.items as item (item.id)}
			<button type="button" role="menuitem" data-item-id={item.id} onclick={() => run(item.id)}>{t(item.labelKey)}</button>
		{/each}
	{/each}
</div>

<style>
	.scrim { position: fixed; inset: 0; z-index: 95; border: 0; background: transparent; }
	.menu { position: fixed; z-index: 96; display: flex; min-width: 168px; flex-direction: column; border: 1px solid var(--pptx-border, #3f3f52); border-radius: 7px; background: var(--pptx-popover, #1e1e2e); box-shadow: 0 14px 28px #0008; padding: 4px; }
	.menu button { border: 0; border-radius: 4px; padding: 7px 12px; background: transparent; color: var(--pptx-popover-foreground, #e2e8f0); font: 12px system-ui, sans-serif; text-align: left; cursor: pointer; }
	.menu button:hover { background: var(--pptx-accent, #33334d); }
	hr { margin: 3px 4px; border: 0; border-top: 1px solid var(--pptx-border, #3f3f52); }
</style>

// packages/angular/src/viewer/presentation-context-menu.component.ts
/**
 * presentation-context-menu.component.ts: right-click menu shown while
 * presenting.
 *
 * Selector: `pptx-presentation-context-menu`
 *
 * Item order/grouping/i18n keys come from the shared
 * `getPresentationContextMenuSections` (`pptx-viewer-shared`), the same
 * source React's `PresentationContextMenu` and Vue's `PresentationMode`
 * render from, so this menu cannot drift from theirs. This component only
 * describes what capabilities are available (always all of them here: the
 * overlay already has next/prev, See All Slides, presenter view, pointer
 * tools, and the black/white blank screen) and routes a chosen action id
 * back to the overlay via a single output.
 *
 * Closes on Escape and on an outside pointerdown, matching
 * `EditorContextMenuComponent`.
 */

import {
	ChangeDetectionStrategy,
	Component,
	computed,
	ElementRef,
	HostListener,
	inject,
	input,
	output,
} from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';

import type {
	PresentationContextMenuActionId,
	PresentationContextMenuSection,
} from '../internal/shared';
import { getPresentationContextMenuSections } from '../internal/shared';
import { EDITOR_CONTEXT_MENU_STYLES } from './editor-context-menu.styles';

@Component({
	selector: 'pptx-presentation-context-menu',
	standalone: true,
	imports: [TranslatePipe],
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `
		<ul
			class="pptx-ctx__menu"
			data-pptx-presentation-menu="true"
			role="menu"
			(contextmenu)="$event.preventDefault()"
		>
			@for (section of sections(); track section.id; let sectionIndex = $index) {
				@if (sectionIndex > 0) {
					<li role="separator" class="pptx-ctx__divider"></li>
				}
				@for (item of section.items; track item.id) {
					<li role="none">
						<button type="button" class="pptx-ctx__item" role="menuitem" (click)="run(item.id)">
							{{ item.labelKey | translate }}
						</button>
					</li>
				}
			}
		</ul>
	`,
	styles: EDITOR_CONTEXT_MENU_STYLES,
	host: {
		'[style.--pptx-ctx-x]': 'x() + "px"',
		'[style.--pptx-ctx-y]': 'y() + "px"',
	},
})
export class PresentationContextMenuComponent {
	/** Horizontal viewport coordinate (px) of the top-left corner of the menu. */
	readonly x = input.required<number>();
	/** Vertical viewport coordinate (px) of the top-left corner of the menu. */
	readonly y = input.required<number>();

	/** Emitted when the menu should close (Escape, outside click, or after an action). */
	readonly closed = output<void>();
	/** The chosen action id; the overlay maps it onto its own navigator/annotations/etc. */
	readonly action = output<PresentationContextMenuActionId>();

	private readonly host = inject(ElementRef) as ElementRef<HTMLElement>;

	protected readonly sections = computed<PresentationContextMenuSection[]>(() =>
		getPresentationContextMenuSections({
			seeAllSlides: true,
			presenterView: true,
			pointerTools: true,
			eraseInk: true,
			blankBlack: true,
			blankWhite: true,
		}),
	);

	@HostListener('document:keydown.escape')
	onEscape(): void {
		this.closed.emit();
	}

	@HostListener('document:pointerdown', ['$event'])
	onDocumentPointerDown(event: PointerEvent): void {
		const target = event.target;
		if (!(target instanceof Node)) {
			return;
		}
		if (!this.host.nativeElement.contains(target)) {
			this.closed.emit();
		}
	}

	protected run(id: PresentationContextMenuActionId): void {
		this.action.emit(id);
		this.closed.emit();
	}
}
