// packages/vue/src/viewer/components/PresentationAnnotationOverlay.vue
<script setup lang="ts">
import { annotationOverlayZIndex, buildStrokePathD, cursorForTool } from 'pptx-viewer-shared';
import type { PresentationBlackout } from 'pptx-viewer-shared';
import type { CSSProperties } from 'vue';
import { computed, ref } from 'vue';

import type {
	AnnotationStroke,
	LaserPosition,
	PresentationTool,
} from '../composables/usePresentationAnnotations';
import type { CanvasSize } from '../types';

/**
 * PresentationAnnotationOverlay - transparent SVG overlay drawn on top of the
 * slide during presentation mode. Captures pointer events for the
 * pen/highlighter/eraser tools and renders the laser-pointer dot. Vue port of
 * the React `PresentationAnnotationOverlay`.
 *
 * Coordinate conversion divides client coordinates by `editorScale` so emitted
 * points are in the slide's unscaled coordinate space (matching
 * `usePresentationAnnotations`). Renders `null` (nothing) when the tool is
 * `'none'`.
 */
const props = withDefaults(
	defineProps<{
		canvasSize: CanvasSize;
		editorScale: number;
		presentationTool: PresentationTool;
		annotationStrokes: AnnotationStroke[];
		currentStroke: AnnotationStroke | null;
		laserPosition: LaserPosition | null;
		/**
		 * Presenter-snapshot blackout state. During a blackout the overlay is
		 * raised ABOVE the blackout sheet (shared `annotationOverlayZIndex`) so
		 * "blackboard" ink stays visible on the blank screen.
		 */
		blackout?: PresentationBlackout;
	}>(),
	{ blackout: 'none' },
);

const emit = defineEmits<{
	(e: 'pointer-down' | 'pointer-move' | 'laser-move' | 'erase', x: number, y: number): void;
	(e: 'pointer-up' | 'laser-leave'): void;
}>();

const svgRef = ref<SVGSVGElement | null>(null);
let isErasing = false;

function toSlideCoords(clientX: number, clientY: number): { x: number; y: number } | null {
	const svg = svgRef.value;
	if (!svg) {
		return null;
	}
	const rect = svg.getBoundingClientRect();
	return {
		x: (clientX - rect.left) / props.editorScale,
		y: (clientY - rect.top) / props.editorScale,
	};
}

function onPointerDown(event: PointerEvent): void {
	if (props.presentationTool === 'none') {
		return;
	}
	event.preventDefault();
	event.stopPropagation();
	const coords = toSlideCoords(event.clientX, event.clientY);
	if (!coords) {
		return;
	}
	if (props.presentationTool === 'eraser') {
		isErasing = true;
		emit('erase', coords.x, coords.y);
		return;
	}
	if (props.presentationTool === 'pen' || props.presentationTool === 'highlighter') {
		emit('pointer-down', coords.x, coords.y);
	}
}

function onPointerMove(event: PointerEvent): void {
	if (props.presentationTool === 'none') {
		return;
	}
	const coords = toSlideCoords(event.clientX, event.clientY);
	if (!coords) {
		return;
	}
	if (props.presentationTool === 'laser') {
		emit('laser-move', coords.x, coords.y);
		return;
	}
	if (props.presentationTool === 'eraser' && isErasing) {
		emit('erase', coords.x, coords.y);
		return;
	}
	if (props.presentationTool === 'pen' || props.presentationTool === 'highlighter') {
		emit('pointer-move', coords.x, coords.y);
	}
}

function onPointerUp(event: PointerEvent): void {
	if (props.presentationTool === 'none') {
		return;
	}
	event.preventDefault();
	if (props.presentationTool === 'eraser') {
		isErasing = false;
		return;
	}
	emit('pointer-up');
}

function onPointerLeave(): void {
	if (props.presentationTool === 'laser') {
		emit('laser-leave');
	}
	if (props.presentationTool === 'eraser') {
		isErasing = false;
	}
	emit('pointer-up');
}

const cursor = computed<string>(() => cursorForTool(props.presentationTool));

const allStrokes = computed<AnnotationStroke[]>(() =>
	props.currentStroke ? [...props.annotationStrokes, props.currentStroke] : props.annotationStrokes,
);

/**
 * Cursor + stacking level. The z-index is bound inline (scoped CSS is static):
 * 60 during a normal show, raised above the z-75 blackout sheet while the
 * screen is blanked, per the shared blackboard layering rules.
 */
const overlayStyle = computed<CSSProperties>(() => ({
	cursor: cursor.value,
	zIndex: annotationOverlayZIndex(props.blackout),
}));

const svgStyle = computed<CSSProperties>(() => ({
	position: 'absolute',
	width: `${props.canvasSize.width}px`,
	height: `${props.canvasSize.height}px`,
	transformOrigin: 'top left',
	transform: `scale(${props.editorScale})`,
}));

const laserStyle = computed<CSSProperties | undefined>(() => {
	if (props.presentationTool !== 'laser' || !props.laserPosition) {
		return undefined;
	}
	return {
		position: 'absolute',
		width: '24px',
		height: '24px',
		left: `${props.laserPosition.x * props.editorScale - 12}px`,
		top: `${props.laserPosition.y * props.editorScale - 12}px`,
		backgroundColor: 'rgba(255, 0, 0, 0.85)',
		boxShadow: '0 0 12px 6px rgba(255, 0, 0, 0.5), 0 0 24px 12px rgba(255, 0, 0, 0.25)',
		filter: 'drop-shadow(0 0 8px rgba(255, 0, 0, 0.7))',
		borderRadius: '50%',
		pointerEvents: 'none',
		zIndex: 70,
	};
});
</script>

<template>
	<div
		v-if="presentationTool !== 'none'"
		class="pptx-vue-annotation-overlay"
		data-pptx-annotation-overlay
		:style="overlayStyle"
	>
		<svg
			ref="svgRef"
			:style="svgStyle"
			:viewBox="`0 0 ${canvasSize.width} ${canvasSize.height}`"
			@pointerdown="onPointerDown"
			@pointermove="onPointerMove"
			@pointerup="onPointerUp"
			@pointerleave="onPointerLeave"
		>
			<path
				v-for="stroke in allStrokes"
				:key="stroke.id"
				:d="buildStrokePathD(stroke.points)"
				fill="none"
				:stroke="stroke.color"
				:stroke-width="stroke.width"
				:opacity="stroke.opacity"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
		</svg>
		<div v-if="laserStyle" class="pptx-vue-annotation-laser" :style="laserStyle" />
	</div>
</template>

<style scoped>
/* The z-index is bound inline (`overlayStyle`): it comes from the shared
   `annotationOverlayZIndex(blackout)` rule and a scoped stylesheet cannot see
   the blackout state. */
.pptx-vue-annotation-overlay {
	position: absolute;
	inset: 0;
	pointer-events: auto;
}
</style>

// packages/angular/src/viewer/presentation-annotation-overlay.component.ts
/**
 * presentation-annotation-overlay.component.ts: SVG overlay that captures
 * pointer events and renders ink strokes + laser dot during presentation mode.
 *
 * Ported from React:
 *   packages/react/src/viewer/components/PresentationAnnotationOverlay.tsx
 *
 * Selector: `pptx-presentation-annotation-overlay`
 *
 * This component is purely presentational: it calls out to
 * {@link PresentationAnnotationsService} for all state mutations, and
 * accepts `canvasSize` and `zoom` to correctly map pointer events from
 * screen space into slide space.
 *
 * When the tool is `'none'` the component renders nothing and sets
 * `pointer-events: none` on its host so click-to-advance still works.
 */

import { NgStyle } from '@angular/common';
import {
	ChangeDetectionStrategy,
	Component,
	ElementRef,
	computed,
	inject,
	input,
	viewChild,
} from '@angular/core';

import type { CanvasSize } from '../internal/shared';
import { buildPathD, cursorForTool } from './presentation-annotations-helpers';
import { PresentationAnnotationsService } from './presentation-annotations.service';

@Component({
	selector: 'pptx-presentation-annotation-overlay',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [NgStyle],
	styleUrl: './presentation-annotation-overlay.component.css',
	templateUrl: './presentation-annotation-overlay.component.html',
})
export class PresentationAnnotationOverlayComponent {
	// ------------------------------------------------------------------
	// Inputs
	// ------------------------------------------------------------------

	/** Logical canvas dimensions (the slide's authored size in pixels). */
	readonly canvasSize = input.required<CanvasSize>();

	/**
	 * The zoom factor currently applied to the slide stage.
	 * Pointer-event coordinates are divided by this value to obtain
	 * slide-space coordinates.
	 */
	readonly zoom = input<number>(1);

	// ------------------------------------------------------------------
	// Injected state
	// ------------------------------------------------------------------

	protected readonly service = inject(PresentationAnnotationsService);

	// ------------------------------------------------------------------
	// Template references
	// ------------------------------------------------------------------

	private readonly svgRef = viewChild<ElementRef<SVGSVGElement>>('svg');

	// ------------------------------------------------------------------
	// Eraser bookkeeping
	// ------------------------------------------------------------------

	/** True while a pointer-down is active in eraser mode. */
	private _isErasing = false;

	// ------------------------------------------------------------------
	// Derived signals
	// ------------------------------------------------------------------

	/** True when any tool other than 'none' is armed. */
	protected readonly isArmed = computed<boolean>(() => this.service.tool() !== 'none');

	/** SVG viewBox string that covers the full canvas. */
	protected readonly viewBox = computed<string>(() => {
		const { width, height } = this.canvasSize();
		return `0 0 ${width} ${height}`;
	});

	/** CSS cursor for the outer wrapper div. */
	protected readonly wrapperStyle = computed<Record<string, string>>(() => ({
		cursor: cursorForTool(this.service.tool()),
		'pointer-events': this.isArmed() ? 'auto' : 'none',
		'z-index': '60',
	}));

	/** Transform the SVG to match the slide's zoom level. */
	protected readonly svgStyle = computed<Record<string, string>>(() => ({
		transform: `scale(${this.zoom()})`,
	}));

	/** All strokes to render: committed + the live in-progress stroke. */
	protected readonly allStrokes = computed(() => {
		const committed = this.service.annotationStrokes();
		const live = this.service.currentStroke();
		return live ? [...committed, live] : committed;
	});

	// ------------------------------------------------------------------
	// Template helpers
	// ------------------------------------------------------------------

	protected strokePath(points: Array<{ x: number; y: number }>): string {
		return buildPathD(points);
	}

	protected laserDotStyle(x: number, y: number): Record<string, string> {
		const z = this.zoom();
		const dotSize = 24;
		return {
			width: `${dotSize}px`,
			height: `${dotSize}px`,
			left: `${x * z - dotSize / 2}px`,
			top: `${y * z - dotSize / 2}px`,
			'z-index': '70',
		};
	}

	// ------------------------------------------------------------------
	// Pointer event dispatch
	// ------------------------------------------------------------------

	protected onPointerDown(event: PointerEvent): void {
		const tool = this.service.tool();
		if (tool === 'none') {
			return;
		}
		event.preventDefault();
		event.stopPropagation();

		const coords = this._toSlideCoords(event.clientX, event.clientY);
		if (!coords) {
			return;
		}

		if (tool === 'eraser') {
			this._isErasing = true;
			this.service.beginErase(coords.x, coords.y);
			return;
		}
		if (tool === 'pen' || tool === 'highlighter') {
			this.service.beginStroke(coords.x, coords.y);
		}
	}

	protected onPointerMove(event: PointerEvent): void {
		const tool = this.service.tool();
		if (tool === 'none') {
			return;
		}

		const coords = this._toSlideCoords(event.clientX, event.clientY);
		if (!coords) {
			return;
		}

		if (tool === 'laser') {
			this.service.moveLaser(coords.x, coords.y);
			return;
		}
		if (tool === 'eraser' && this._isErasing) {
			this.service.continueErase(coords.x, coords.y);
			return;
		}
		if (tool === 'pen' || tool === 'highlighter') {
			this.service.extendStroke(coords.x, coords.y);
		}
	}

	protected onPointerUp(event: PointerEvent): void {
		const tool = this.service.tool();
		if (tool === 'none') {
			return;
		}
		event.preventDefault();

		if (tool === 'eraser') {
			this._isErasing = false;
			this.service.endErase();
			return;
		}
		this.service.endStroke();
	}

	protected onPointerLeave(_event: PointerEvent): void {
		const tool = this.service.tool();
		if (tool === 'laser') {
			this.service.hideLaser();
		}
		if (tool === 'eraser') {
			this._isErasing = false;
			this.service.endErase();
		}
		this.service.endStroke();
	}

	// ------------------------------------------------------------------
	// Coordinate mapping
	// ------------------------------------------------------------------

	/**
	 * Map a client-space pointer position to slide-space coordinates by
	 * subtracting the SVG element's bounding rect and dividing by the zoom.
	 * Returns `null` when the SVG ref is not yet available.
	 */
	private _toSlideCoords(clientX: number, clientY: number): { x: number; y: number } | null {
		const svgEl = this.svgRef()?.nativeElement;
		if (!svgEl) {
			return null;
		}
		const rect = svgEl.getBoundingClientRect();
		const z = this.zoom() || 1;
		return {
			x: (clientX - rect.left) / z,
			y: (clientY - rect.top) / z,
		};
	}
}

@if (isArmed()) {
	<div
		class="pptx-ng-anno-wrapper"
		[ngStyle]="wrapperStyle()"
		(pointerdown)="onPointerDown($event)"
		(pointermove)="onPointerMove($event)"
		(pointerup)="onPointerUp($event)"
		(pointerleave)="onPointerLeave($event)"
	>
		<svg
			#svg
			class="pptx-ng-anno-svg"
			[attr.width]="canvasSize().width"
			[attr.height]="canvasSize().height"
			[attr.viewBox]="viewBox()"
			[ngStyle]="svgStyle()"
		>
			@for (s of allStrokes(); track s.id) {
				<path
					[attr.d]="strokePath(s.points)"
					fill="none"
					[attr.stroke]="s.color"
					[attr.stroke-width]="s.width"
					stroke-linecap="round"
					stroke-linejoin="round"
					[attr.opacity]="s.opacity"
				/>
			}
		</svg>

		@if (service.tool() === 'laser' && service.laserPosition(); as lp) {
			<div class="pptx-ng-laser-dot" [ngStyle]="laserDotStyle(lp.x, lp.y)"></div>
		}
	</div>
}
