// packages/svelte/src/viewer/presentation/PresentationTransitionOverlay.svelte
<script lang="ts">
	/**
	 * PresentationTransitionOverlay: animates a slide change in presentation mode
	 * (Svelte port of the Vue overlay of the same name). It stacks two
	 * {@link SlideStage} layers, both scaled identically to the underlying
	 * presentation frame:
	 *   - the outgoing (old) slide as a snapshot layer, and
	 *   - the incoming (new) slide.
	 *
	 * The incoming slide's transition is mapped to CSS `animation` shorthands via
	 * the framework-agnostic {@link resolveSlideTransition}; each layer's z-index
	 * comes from `outgoingOnTop`. When the configured duration elapses it calls
	 * `ondone`, at which point the host drops the overlay and leaves the static
	 * incoming slide rendered by its main stage. The `@keyframes` themselves are
	 * injected once at document level (see `keyframes.ts`).
	 */
	import type { PptxSlide, PptxSlideTransition } from 'pptx-viewer-core';
	import {
		applySlideTransitionSound,
		buildMorphScopedCss,
		buildMorphTransitionPlan,
		MORPH_CROSSFADE_GROUP_CSS_TEXT,
		MORPH_CROSSFADE_HALF_BLEND_MODE,
		morphOptionToMode,
		resolveSlideTransition,
		resolveTransitionDurationMs,
	} from 'pptx-viewer-shared';
	import type { CanvasSize, CssStyleMap } from 'pptx-viewer-shared';
	import { onDestroy, onMount } from 'svelte';

	import { playAnimationSound, stopAnimationSound } from './animation-sound';
	import SlideStage from '../components/SlideStage.svelte';
	import { styleToString } from '../style';

	const {
		outgoingSlide,
		incomingSlide,
		canvasSize,
		mediaDataUrls,
		scale = 1,
		transition,
		ondone,
	}: {
		outgoingSlide: PptxSlide | undefined;
		incomingSlide: PptxSlide | undefined;
		canvasSize: CanvasSize;
		mediaDataUrls: Map<string, string>;
		scale?: number;
		transition: PptxSlideTransition | undefined;
		ondone: () => void;
	} = $props();

	const animations = $derived(resolveSlideTransition(transition));
	/** Effective duration (ms); `0` for instant (none/cut). */
	const durationMs = $derived(resolveTransitionDurationMs(transition));

	function layerStyle(animation: string, zIndex: number): CssStyleMap {
		const style: CssStyleMap = { zIndex };
		if (animation !== 'none') {
			style.animation = animation;
		}
		return style;
	}

	/**
	 * Morph moves individual shapes between the two slides rather than wiping the
	 * whole surface, so when it is active the incoming layer plays per-element
	 * keyframes (scoped by `data-pptx-morph-incoming`) and the outgoing layer
	 * animates each of its own shapes: gliding onto its counterpart (dissolving
	 * into it when its appearance changed) or fading out in place without one.
	 */
	const morphPlan = $derived(
		transition?.type === 'morph'
			? buildMorphTransitionPlan(
					outgoingSlide,
					incomingSlide,
					durationMs,
					morphOptionToMode(transition.morphOption),
				)
			: undefined,
	);

	const morphOutgoingSlide = $derived(
		morphPlan && outgoingSlide ? { ...outgoingSlide, elements: morphPlan.outgoingElements } : undefined,
	);

	/**
	 * The arriving shapes a ghost above them would otherwise hide for the whole
	 * morph, painted in their own layer over the departing one (issue #146).
	 * Their copy on the incoming layer is held invisible by the plan, so the two
	 * never composite with each other.
	 */
	const morphLiftedSlide = $derived(
		morphPlan && incomingSlide && morphPlan.overlayIncomingElements.length > 0
			? { ...incomingSlide, elements: morphPlan.overlayIncomingElements }
			: undefined,
	);

	/** One half of a grouped pair: blends additively, and carries the dissolve. */
	function halfStyle(animation: string | undefined): string {
		return `mix-blend-mode: ${MORPH_CROSSFADE_HALF_BLEND_MODE};${
			animation === undefined ? '' : ` animation: ${animation};`
		}`;
	}

	/**
	 * The pairs the overlay paints BOTH halves of, each as one isolated group so
	 * the halves are summed rather than stacked: two source-over fades leave the
	 * ink they share at 0.75 of full strength mid-transition, biting chunks out
	 * of glyphs that cross during a text dissolve, where PowerPoint's own blend
	 * keeps the two coefficients summing to 1.0 (issue #161).
	 */
	const morphCrossfadeGroups = $derived(
		morphPlan && outgoingSlide && incomingSlide
			? morphPlan.crossfadeGroups.map((group, index) => ({
					key: group.incoming.id,
					// `isolation` makes the group a stacking context, so it carries its
					// own z-index to stay above the ghosts its halves came from.
					style: `${MORPH_CROSSFADE_GROUP_CSS_TEXT} z-index: ${4 + index};`,
					// The dissolve rides these WRAPPERS, not the elements: a pair
					// dissolving in place never moves, and an animation on the small
					// element box gives it a compositing layer whose raster snaps to whole
					// device pixels, painting the wording a fraction of a pixel off the
					// live stage (issue #161).
					outgoingStyle: halfStyle(group.outgoingAnimation),
					incomingStyle: halfStyle(group.incomingAnimation),
					outgoing: { ...outgoingSlide, elements: [group.outgoing] },
					incoming: { ...incomingSlide, elements: [group.incoming] },
				}))
			: [],
	);

	const morphCss = $derived(
		morphPlan
			? [
					buildMorphScopedCss(morphPlan, 'data-pptx-morph-incoming', 'incoming'),
					buildMorphScopedCss(morphPlan, 'data-pptx-morph-outgoing', 'outgoing'),
					buildMorphScopedCss(morphPlan, 'data-pptx-morph-lifted', 'lifted'),
				].join('\n')
			: '',
	);

	// A layer-wide animation would drag every shape as one block and cancel the
	// morph, so the layers stay unanimated while a plan is active.
	const outgoingStyle = $derived(
		styleToString(layerStyle(morphPlan ? 'none' : animations.outgoing, morphPlan ? 2 : animations.outgoingOnTop ? 2 : 1)),
	);
	const incomingStyle = $derived(
		styleToString(layerStyle(morphPlan ? 'none' : animations.incoming, morphPlan ? 1 : animations.outgoingOnTop ? 1 : 2)),
	);
	const liftedStyle = styleToString(layerStyle('none', 3));

	/**
	 * Play or stop this transition's sound action (`p:sndAc/p:stSnd`/`p:endSnd`)
	 * the instant it starts. `transition.soundPath` is a raw in-archive path;
	 * `mediaDataUrls` is the same Blob-URL cache the load pipeline
	 * pre-populates for it (`collectAnimationSoundPaths`, extended to also
	 * collect a slide transition's own sound). Reuses the per-effect sound
	 * singleton (`animation-sound.ts`) so a transition sound and an animation
	 * sound cannot talk over each other, matching PowerPoint's "one sound
	 * plays at a time" behaviour. NOT stopped on this component's own
	 * destroy: a "Loop Until Next Sound" sound must keep playing across the
	 * static period between this overlay tearing down and the next
	 * transition's own sound action; the presentation controller stops it on
	 * leaving the show.
	 */
	$effect(() => {
		applySlideTransitionSound(transition, (soundPath) => mediaDataUrls.get(soundPath), {
			play: playAnimationSound,
			stop: stopAnimationSound,
		});
	});

	let timer: ReturnType<typeof setTimeout> | null = null;

	onMount(() => {
		// A small buffer past the animation duration lets the CSS `forwards` fill
		// settle before the host swaps back to the static slide.
		timer = setTimeout(
			() => {
				timer = null;
				ondone();
			},
			Math.max(0, durationMs) + 50,
		);
	});

	onDestroy(() => {
		if (timer !== null) {
			clearTimeout(timer);
			timer = null;
		}
	});
</script>

<div class="pptx-svelte-transition-overlay" data-pptx-transition-overlay>
	{#if morphPlan}
		<!-- eslint-disable-next-line svelte/no-at-html-tags -- generated keyframes, no user input -->
		{@html `<style>${morphCss}</style>`}
	{/if}
	<div
		class="pptx-svelte-transition-layer"
		data-pptx-transition-layer="outgoing"
		data-pptx-morph-outgoing={morphPlan ? 'true' : undefined}
		style={outgoingStyle}
	>
		<!-- transparentBackground during a morph: this layer sits ABOVE the
		     incoming slide and only carries the departing shapes, so painting the
		     outgoing slide's own (always opaque) background here would cover the
		     whole morph with a flat slab for its entire duration. -->
		<SlideStage
			slide={morphPlan ? morphOutgoingSlide : outgoingSlide}
			{canvasSize}
			{mediaDataUrls}
			{scale}
			transparentBackground={Boolean(morphPlan)}
		/>
	</div>
	<div
		class="pptx-svelte-transition-layer"
		data-pptx-transition-layer="incoming"
		data-pptx-morph-incoming={morphPlan ? 'true' : undefined}
		style={incomingStyle}
	>
		<SlideStage slide={incomingSlide} {canvasSize} {mediaDataUrls} {scale} />
	</div>
	{#if morphLiftedSlide}
		<!-- The arriving shapes that dissolve in ABOVE a departing one. They live
		     on the incoming slide, so the layer below draws them under the
		     departing layer, where nobody would see them. -->
		<div
			class="pptx-svelte-transition-layer"
			data-pptx-transition-layer="lifted"
			data-pptx-morph-lifted="true"
			style={liftedStyle}
		>
			<SlideStage slide={morphLiftedSlide} {canvasSize} {mediaDataUrls} {scale} transparentBackground />
		</div>
	{/if}
	<!-- A pair dissolving in place, painted as ONE isolated group whose two
	     halves sum instead of stacking (issue #161). -->
	{#each morphCrossfadeGroups as group (group.key)}
		<div data-pptx-morph-crossfade={group.key} style={group.style}>
			<div
				class="pptx-svelte-transition-layer"
				data-pptx-transition-layer="outgoing"
				data-pptx-morph-outgoing="true"
				style={group.outgoingStyle}
			>
				<SlideStage slide={group.outgoing} {canvasSize} {mediaDataUrls} {scale} transparentBackground />
			</div>
			<div
				class="pptx-svelte-transition-layer"
				data-pptx-transition-layer="lifted"
				data-pptx-morph-lifted="true"
				style={group.incomingStyle}
			>
				<SlideStage slide={group.incoming} {canvasSize} {mediaDataUrls} {scale} transparentBackground />
			</div>
		</div>
	{/each}
</div>

<style>
	.pptx-svelte-transition-overlay {
		position: absolute;
		inset: 0;
		overflow: hidden;
		pointer-events: none;
	}

	/* `inset: 0`, not `top/left: 0`: the stage inside scales with a CSS
	   `transform`, which never changes its laid-out box, so an auto-sized layer
	   measures the deck's NATIVE size (1280x720) while the stage paints the
	   display size (1920x1080). With `overflow: hidden` that cropped every
	   transition to a deck-sized top-left corner and the rest of the screen cut
	   straight to the next slide. Pinning to the overlay (already the frame's
	   scaled footprint) puts the clip on the slide edge, where it belongs. */
	.pptx-svelte-transition-layer {
		position: absolute;
		inset: 0;
		overflow: hidden;
		will-change: transform, opacity, clip-path, filter;
	}
</style>

// packages/angular/src/viewer/presentation-transition-overlay.component.ts
import { NgStyle } from '@angular/common';
import {
	ChangeDetectionStrategy,
	Component,
	DestroyRef,
	computed,
	effect,
	inject,
	input,
	output,
} from '@angular/core';
import type { PptxElement, PptxSlide, PptxSlideTransition } from 'pptx-viewer-core';

import type { CanvasSize, MorphTransitionPlan } from '../internal/shared';
import {
	applySlideTransitionSound,
	buildMorphScopedCss,
	buildMorphTransitionPlan,
	MORPH_CROSSFADE_GROUP_STYLE,
	MORPH_CROSSFADE_HALF_BLEND_MODE,
	morphOptionToMode,
	visibleTemplateElements as filterVisibleTemplateElements,
} from '../internal/shared';
import { playAnimationSound, stopAnimationSound } from './animation-sound';
import type { StyleMap } from './element-style';
import { SlideCanvasComponent } from './slide-canvas.component';
import {
	getSlideTransitionAnimations,
	resolveOverlayDurationMs,
	transitionSlideBoxSize,
} from './transition-helpers';
import type { SlideTransitionAnimations } from './transition-helpers';
import { ensureTransitionKeyframes } from './transition-keyframes';

/** Safety margin (ms) added to the animation duration before firing complete. */
const COMPLETE_MARGIN_MS = 50;

/**
 * The slide the incoming (arriving) layer paints for a CLASSIC transition, or
 * `undefined` when no such layer may exist.
 *
 * Without this layer the overlay painted only the outgoing slide: a wipe
 * (whose outgoing half is `none`) sat opaque for the whole duration and the
 * arriving slide - only ever the live stage beneath - popped in the instant
 * the overlay tore down ("takes the time, then instantly replaced"). Types
 * whose incoming half is `none` (the uncover family) deliberately reveal the
 * live stage and get no layer, and a morph paints its own halves.
 *
 * Exported and pure so it can be unit-tested: this package renders no component
 * under test (see `action-settings-panel.component.test.ts`).
 */
export function classicIncomingLayerSlide(
	isMorph: boolean,
	incomingAnimation: string,
	incomingSlide: PptxSlide | undefined,
	templateElements: readonly PptxElement[],
): PptxSlide | undefined {
	if (isMorph || incomingAnimation === 'none' || !incomingSlide) {
		return undefined;
	}
	const visible = filterVisibleTemplateElements(incomingSlide, templateElements);
	if (visible.length === 0) {
		return incomingSlide;
	}
	return { ...incomingSlide, elements: [...visible, ...incomingSlide.elements] };
}

/**
 * The slide the overlay paints ABOVE its ghosts, or `undefined` when a morph
 * has nothing to lift.
 *
 * A shape arriving inside a shape that persists is drawn on the live stage,
 * UNDER this overlay, so the persisting shape's opaque ghost hides it for the
 * whole transition (issue #146). `buildMorphTransitionPlan` names those few and
 * holds their stage copy invisible; this wraps them as a slide the component's
 * own `pptx-slide-canvas` can render.
 *
 * Exported and pure so it can be unit-tested: this package renders no component
 * under test (see `action-settings-panel.component.test.ts`).
 */
export function morphLiftedSlide(
	plan: MorphTransitionPlan | undefined,
	incomingSlide: PptxSlide | undefined,
): PptxSlide | undefined {
	if (!plan || !incomingSlide || plan.overlayIncomingElements.length === 0) {
		return undefined;
	}
	return { ...incomingSlide, elements: [...plan.overlayIncomingElements] };
}

/** One cross-dissolving pair, as the two single-element slides that paint it. */
export interface MorphCrossfadeGroupSlides {
	key: string;
	style: StyleMap;
	/**
	 * The departing half's layer style, carrying the dissolve itself.
	 *
	 * A pair dissolving in place never moves, and an animation on the small
	 * element box gives it a compositing layer whose raster snaps to whole device
	 * pixels - the wording is then painted a fraction of a pixel off the live
	 * stage and twitches as the overlay comes and goes (issue #161).
	 */
	outgoingStyle: StyleMap;
	/** The arriving half's layer style. @see MorphCrossfadeGroupSlides.outgoingStyle */
	incomingStyle: StyleMap;
	outgoing: PptxSlide;
	incoming: PptxSlide;
}

/**
 * The pairs the overlay paints BOTH halves of, as one isolated group each.
 *
 * Stacking the halves composites them source-over, which leaves the ink they
 * share at 0.75 of full strength halfway through instead of summing it, biting
 * chunks out of glyphs that cross during a text dissolve. PowerPoint's own
 * render holds the two blend coefficients at a sum of 1.0 for every frame
 * (issue #161), which `isolation: isolate` plus `mix-blend-mode: plus-lighter`
 * on the two halves reproduces.
 *
 * Exported and pure so it can be unit-tested: this package renders no component
 * under test (see `action-settings-panel.component.test.ts`).
 */
export function morphCrossfadeGroupSlides(
	plan: MorphTransitionPlan | undefined,
	outgoingSlide: PptxSlide | undefined,
	incomingSlide: PptxSlide | undefined,
): MorphCrossfadeGroupSlides[] {
	if (!plan || !outgoingSlide || !incomingSlide) {
		return [];
	}
	const half = (animation: string | undefined): StyleMap => ({
		'mix-blend-mode': MORPH_CROSSFADE_HALF_BLEND_MODE,
		...(animation === undefined ? {} : { animation }),
	});
	return plan.crossfadeGroups.map((group, index) => ({
		key: group.incoming.id,
		style: {
			...MORPH_CROSSFADE_GROUP_STYLE,
			// `isolation` makes the group a stacking context, so it carries a
			// z-index of its own to stay above the ghost layer (40) and the lifted
			// layer (41) its halves came from.
			'z-index': String(42 + index),
		},
		outgoingStyle: half(group.outgoingAnimation),
		incomingStyle: half(group.incomingAnimation),
		outgoing: { ...outgoingSlide, elements: [group.outgoing] },
		incoming: { ...incomingSlide, elements: [group.incoming] },
	}));
}

/**
 * PresentationTransitionOverlayComponent: plays a PowerPoint slide transition
 * over the presentation stage.
 *
 * Renders the *outgoing* (previous) slide as an absolutely-positioned layer
 * with the resolved CSS exit animation; the *incoming* slide is rendered by the
 * underlying stage (the existing `pptx-presentation-overlay`). The `outgoingOnTop`
 * descriptor controls whether the outgoing layer sits above or below the stage,
 * letting cover/uncover/push read correctly. Fires `complete` once the animation
 * finishes so the orchestrator can tear the overlay down.
 *
 * Selector: `pptx-presentation-transition-overlay`
 *
 * Inputs:
 *   - `outgoingSlide`    (required): the leaving slide to animate
 *   - `canvasSize`       (required): logical slide dimensions (px)
 *   - `transition`       (required): the transition definition (from the slide)
 *   - `templateElements`: master/layout elements behind the outgoing slide
 *   - `mediaDataUrls`   : data-URL map for media assets
 *   - `durationMs`      : explicit override; otherwise derived from `transition`
 *   - `zoom`            : the stage's live zoom, so the outgoing slide animates
 *                         at the same size as the incoming one
 *
 * Outputs:
 *   - `complete`: emits void when the transition animation completes
 *
 * Designed to compose with `PresentationOverlayComponent` WITHOUT editing it:
 * the orchestrator stacks this overlay on top of the stage while a transition
 * is in flight and removes it on `complete`.
 */
@Component({
	selector: 'pptx-presentation-transition-overlay',
	host: { 'data-pptx-transition-overlay': '' },
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [NgStyle, SlideCanvasComponent],
	styles: `
		:host {
			display: block;
			position: absolute;
			inset: 0;
			overflow: hidden;
			pointer-events: none;
		}

		.pptx-ng-transition-layer {
			position: absolute;
			inset: 0;
			display: flex;
			align-items: center;
			justify-content: center;
		}
	`,
	template: `
		@if (incomingLayerSlide(); as incoming) {
			<div
				class="pptx-ng-transition-layer"
				data-pptx-transition-layer="incoming"
				[ngStyle]="incomingLayerStyle()"
			>
				<div [ngStyle]="slideBoxStyle()">
					<pptx-slide-canvas
						[slide]="incoming"
						[canvasSize]="canvasSize()"
						[mediaDataUrls]="mediaDataUrls()"
						[zoom]="zoom()"
						[autoFit]="false"
						[interactive]="false"
					/>
				</div>
			</div>
		}

		<div
			class="pptx-ng-transition-layer"
			data-pptx-transition-layer="outgoing"
			[attr.data-pptx-morph-outgoing]="morphPlan() ? 'true' : null"
			[ngStyle]="layerStyle()"
		>
			<div [ngStyle]="slideBoxStyle()">
				<pptx-slide-canvas
					[slide]="layerSlide()"
					[canvasSize]="canvasSize()"
					[mediaDataUrls]="mediaDataUrls()"
					[zoom]="zoom()"
					[autoFit]="false"
					[interactive]="false"
					[transparentBackground]="isMorph()"
				/>
			</div>
		</div>

		<!-- The arriving shapes that dissolve in ABOVE a departing one. They are on
		     the live stage below this overlay, where the departing layer hides them
		     for the whole morph, so they are painted again here. -->
		@if (liftedSlide(); as lifted) {
			<div
				class="pptx-ng-transition-layer"
				data-pptx-transition-layer="lifted"
				data-pptx-morph-lifted="true"
				[ngStyle]="{ 'z-index': '41' }"
			>
				<div [ngStyle]="slideBoxStyle()">
					<pptx-slide-canvas
						[slide]="lifted"
						[canvasSize]="canvasSize()"
						[mediaDataUrls]="mediaDataUrls()"
						[zoom]="zoom()"
						[autoFit]="false"
						[interactive]="false"
						[transparentBackground]="true"
					/>
				</div>
			</div>
		}

		<!-- A pair dissolving in place, painted as ONE isolated group whose two
		     halves sum instead of stacking (issue #161). -->
		@for (group of crossfadeGroups(); track group.key) {
			<div [attr.data-pptx-morph-crossfade]="group.key" [ngStyle]="group.style">
				<div
					class="pptx-ng-transition-layer"
					data-pptx-transition-layer="outgoing"
					data-pptx-morph-outgoing="true"
					[ngStyle]="group.outgoingStyle"
				>
					<div [ngStyle]="slideBoxStyle()">
						<pptx-slide-canvas
							[slide]="group.outgoing"
							[canvasSize]="canvasSize()"
							[mediaDataUrls]="mediaDataUrls()"
							[zoom]="zoom()"
							[autoFit]="false"
							[interactive]="false"
							[transparentBackground]="true"
						/>
					</div>
				</div>
				<div
					class="pptx-ng-transition-layer"
					data-pptx-transition-layer="lifted"
					data-pptx-morph-lifted="true"
					[ngStyle]="group.incomingStyle"
				>
					<div [ngStyle]="slideBoxStyle()">
						<pptx-slide-canvas
							[slide]="group.incoming"
							[canvasSize]="canvasSize()"
							[mediaDataUrls]="mediaDataUrls()"
							[zoom]="zoom()"
							[autoFit]="false"
							[interactive]="false"
							[transparentBackground]="true"
						/>
					</div>
				</div>
			</div>
		}
	`,
})
export class PresentationTransitionOverlayComponent {
	// ------------------------------------------------------------------
	// Inputs
	// ------------------------------------------------------------------

	readonly outgoingSlide = input.required<PptxSlide>();
	readonly canvasSize = input.required<CanvasSize>();
	readonly transition = input.required<PptxSlideTransition>();
	readonly templateElements = input<readonly PptxElement[]>([]);
	readonly mediaDataUrls = input<Map<string, string>>(new Map());
	/** Explicit duration override (ms). When omitted, derived from `transition`. */
	readonly durationMs = input<number | undefined>(undefined);
	/**
	 * The stage's live zoom (the same value the underlying `pptx-slide-canvas`
	 * renders at). The outgoing layer MUST use it: left at 1 the leaving slide
	 * animates out at its intrinsic size over a full-screen incoming slide,
	 * which reads as the slide snapping small the instant a transition starts.
	 */
	readonly zoom = input<number>(1);
	/**
	 * The arriving slide. Required only for Morph, which has to match shapes
	 * across both slides; every other transition ignores it.
	 */
	readonly incomingSlide = input<PptxSlide | undefined>(undefined);

	// ------------------------------------------------------------------
	// Outputs
	// ------------------------------------------------------------------

	readonly complete = output<void>();

	// ------------------------------------------------------------------
	// Internal
	// ------------------------------------------------------------------

	private readonly destroyRef = inject(DestroyRef);
	/** Active completion timer handle, so re-running re-arms cleanly. */
	private completeTimer: ReturnType<typeof setTimeout> | null = null;
	/** Whether `complete` has already fired for the current run. */
	private fired = false;

	constructor() {
		ensureTransitionKeyframes();

		// Re-arm the completion timer + sound whenever the transition or its
		// resolved duration changes.
		effect(() => {
			const ms = this.resolvedDurationMs();
			this.applyTransitionSound(this.transition());
			this.armCompletion(ms);
		});

		// Morph keyframes + per-element rules. They must reach the LIVE stage,
		// which is a sibling component, so they are injected at document level.
		// Element ids embed their slide path, so unscoped rules cannot leak onto
		// another slide's elements.
		effect(() => {
			const plan = this.morphPlan();
			this.applyMorphStyle(
				plan
					? [
							buildMorphScopedCss(plan, '', 'incoming'),
							buildMorphScopedCss(plan, 'data-pptx-morph-outgoing', 'outgoing'),
							// Scoped, so it outranks the unscoped `incoming` rule that holds
							// the stage's copy of the same element invisible.
							buildMorphScopedCss(plan, 'data-pptx-morph-lifted', 'lifted'),
						].join('\n')
					: null,
			);
		});

		this.destroyRef.onDestroy(() => {
			this.clearTimer();
			stopAnimationSound();
			this.applyMorphStyle(null);
		});
	}

	/** Owned `<style>` element carrying the active morph rules, if any. */
	private morphStyle: HTMLStyleElement | null = null;

	private applyMorphStyle(css: string | null): void {
		if (typeof document === 'undefined') {
			return;
		}
		if (css === null) {
			this.morphStyle?.remove();
			this.morphStyle = null;
			return;
		}
		if (!this.morphStyle) {
			this.morphStyle = document.createElement('style');
			document.head.appendChild(this.morphStyle);
		}
		this.morphStyle.textContent = css;
	}

	// ------------------------------------------------------------------
	// Derived state
	// ------------------------------------------------------------------

	/** Effective transition duration (ms), floored/defaulted. */
	protected readonly resolvedDurationMs = computed<number>(() =>
		resolveOverlayDurationMs(this.durationMs(), this.transition()),
	);

	/** Resolved CSS animation descriptors for the outgoing/incoming layers. */
	protected readonly animations = computed<SlideTransitionAnimations>(() => {
		const tr = this.transition();
		return getSlideTransitionAnimations(
			tr.type,
			this.resolvedDurationMs(),
			tr.direction,
			tr.orient,
			tr.spokes,
		);
	});

	/**
	 * Active Morph plan, or `undefined` for every other transition.
	 *
	 * Morph travels individual shapes between the two slides rather than wiping
	 * the surface, so it changes what this overlay paints: a per-shape copy of
	 * the outgoing slide, each one gliding onto its counterpart (dissolving into
	 * it when its appearance changed) or fading out in place when it has none.
	 * The incoming halves are animated on the live stage by document-level rules
	 * (see `morphStyleEffect`).
	 */
	protected readonly morphPlan = computed(() =>
		this.transition().type === 'morph'
			? buildMorphTransitionPlan(
					this.outgoingSlide(),
					this.incomingSlide(),
					this.resolvedDurationMs(),
					morphOptionToMode(this.transition().morphOption),
				)
			: undefined,
	);

	/**
	 * Whether this overlay is playing a morph.
	 *
	 * A morph layer paints only the departing slide's paired shapes over the live
	 * incoming stage, so its stage background must be dropped
	 * (`transparentBackground`). Every other transition animates a whole slide
	 * surface out and keeps its own background.
	 */
	protected readonly isMorph = computed<boolean>(() => this.morphPlan() !== undefined);

	/** The slide rendered in the animated layer (outgoing + its template). */
	protected readonly layerSlide = computed<PptxSlide>(() => {
		const slide = this.outgoingSlide();
		const plan = this.morphPlan();
		if (plan) {
			return { ...slide, elements: [...plan.outgoingElements] };
		}
		const template = filterVisibleTemplateElements(slide, this.templateElements());
		if (template.length === 0) {
			return slide;
		}
		return { ...slide, elements: [...template, ...slide.elements] };
	});

	/**
	 * The arriving shapes the morph has to paint over its own ghosts, or
	 * `undefined` when there are none (issue #146). They sit on the live stage
	 * below this overlay, where the departing layer would hide them for the whole
	 * transition; the plan holds that copy invisible and hands them here instead.
	 */
	protected readonly liftedSlide = computed<PptxSlide | undefined>(() =>
		morphLiftedSlide(this.morphPlan(), this.incomingSlide()),
	);

	/**
	 * The cross-dissolving pairs this overlay paints both halves of, each in its
	 * own isolated group so the halves are summed rather than stacked.
	 */
	protected readonly crossfadeGroups = computed<MorphCrossfadeGroupSlides[]>(() =>
		morphCrossfadeGroupSlides(this.morphPlan(), this.outgoingSlide(), this.incomingSlide()),
	);

	/** Layer container style: animation + stacking relative to the stage. */
	protected readonly layerStyle = computed<StyleMap>(() => {
		const anims = this.animations();
		const plan = this.morphPlan();
		const style: StyleMap = {
			'z-index': plan ? '40' : anims.outgoingOnTop ? '40' : '20',
		};
		// A layer-wide animation would drag every shape as one block and cancel
		// the morph, so during a morph the layer itself stays still.
		if (!plan && anims.outgoing !== 'none') {
			style['animation'] = anims.outgoing;
		}
		return style;
	});

	/**
	 * The arriving slide rendered ABOVE the outgoing layer for a classic
	 * transition, carrying the incoming animation (wipe/cover/fade/push), or
	 * `undefined` for morphs and the uncover family (which reveal the live
	 * stage instead).
	 */
	protected readonly incomingLayerSlide = computed<PptxSlide | undefined>(() =>
		classicIncomingLayerSlide(
			this.isMorph(),
			this.animations().incoming,
			this.incomingSlide(),
			this.templateElements(),
		),
	);

	/** Style for that arriving layer: the incoming animation + its stacking. */
	protected readonly incomingLayerStyle = computed<StyleMap>(() => ({
		'z-index': this.animations().outgoingOnTop ? '30' : '25',
		animation: this.animations().incoming,
	}));

	/**
	 * Slide box sized to the ZOOMED slide footprint, matching the stage's own
	 * `pptx-slide-canvas`. The inner canvas renders at the same `zoom` with
	 * `autoFit` off, so the outgoing slide is pixel-for-pixel the size of the
	 * incoming one for the whole animation.
	 */
	protected readonly slideBoxStyle = computed<StyleMap>(() => {
		const box = transitionSlideBoxSize(this.canvasSize(), this.zoom());
		return {
			width: `${box.width}px`,
			height: `${box.height}px`,
			'transform-origin': 'center',
		};
	});

	// ------------------------------------------------------------------
	// Completion timing + sound
	// ------------------------------------------------------------------

	private armCompletion(durationMs: number): void {
		this.clearTimer();
		this.fired = false;
		if (typeof setTimeout === 'undefined') {
			return;
		}
		this.completeTimer = setTimeout(() => {
			this.completeTimer = null;
			if (this.fired) {
				return;
			}
			this.fired = true;
			this.complete.emit();
		}, durationMs + COMPLETE_MARGIN_MS);
	}

	private clearTimer(): void {
		if (this.completeTimer !== null) {
			clearTimeout(this.completeTimer);
			this.completeTimer = null;
		}
	}

	/**
	 * Play or stop this transition's sound action (`p:sndAc/p:stSnd`/`p:endSnd`).
	 *
	 * `transition.soundPath` is a raw in-archive path (e.g. `ppt/media/media3.wav`)
	 * that a bare `Audio` element constructed straight from it cannot fetch; it
	 * must be resolved through `mediaDataUrls()`, the same Blob-URL cache
	 * `load-content.service.ts`
	 * pre-populates via `collectAnimationSoundPaths` (extended to also collect
	 * `slide.transition?.soundPath` alongside per-effect animation sounds).
	 * Reuses the shared per-effect sound singleton (`animation-sound.ts`) rather
	 * than a private `Audio` element, so a transition sound and an animation
	 * sound cannot talk over each other, matching PowerPoint's "one sound plays
	 * at a time" behaviour.
	 */
	private applyTransitionSound(transition: PptxSlideTransition): void {
		applySlideTransitionSound(transition, (soundPath) => this.mediaDataUrls().get(soundPath), {
			play: playAnimationSound,
			stop: stopAnimationSound,
		});
	}
}
