// packages/vue/src/viewer/components/PrintDialog.vue
<script setup lang="ts">
/**
 * PrintDialog - full-featured print options dialog for the Vue viewer.
 *
 * Vue port of the React `PrintDialog.tsx`. Owns the print-settings state and,
 * on confirm, emits a resolved {@link PrintSettings} for the host to feed into
 * `usePrint().print(settings)`. Built on the reusable {@link ModalDialog} shell
 * and the {@link PrintSettingsPanel} fieldset; a lightweight live preview is
 * shown for the handout / notes layouts.
 *
 * Props:
 *  - `open`                  : visibility flag (host-owned).
 *  - `slides`                : the slides, for range bounds + outline preview.
 *  - `activeSlideIndex`      : current slide (for "current slide" range).
 *  - `defaultSlidesPerPage?` : seed from presentation props (clamped to valid).
 *  - `defaultFrameSlides?`   : seed from presentation props.
 *
 * Emits:
 *  - `print` : `PrintSettings`, the user confirmed; run the print flow.
 *  - `close` : the dialog was dismissed.
 */
import type { PptxSlide } from 'pptx-viewer-core';
import { DEFAULT_VIEWER_OPTIONS, resolveDefaultPrintSettings } from 'pptx-viewer-shared';
import { computed, inject, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';

import { ViewerOptionsKey } from '../composables/useViewerOptionsStore';
import ModalDialog from './ModalDialog.vue';
import {
	computePageCount,
	computeSlideCount,
	computeSlideIndices,
	effectiveOrientation,
	getHandoutGrid,
	resolveSlidesPerPage,
} from './print-dialog-types';
import type {
	HandoutSlidesPerPage,
	PrintColorMode,
	PrintOrientation,
	PrintSettings,
	PrintSlideRange,
	PrintWhat,
} from './print-dialog-types';
import PrintSettingsPanel from './PrintSettingsPanel.vue';

const props = defineProps<{
	open: boolean;
	slides: PptxSlide[];
	activeSlideIndex: number;
	defaultSlidesPerPage?: number;
	defaultFrameSlides?: boolean;
}>();

const emit = defineEmits<{
	print: [settings: PrintSettings];
	close: [];
}>();

const { t } = useI18n();

// File > Options > Advanced > Print. `undefined` (Options > "Use the most
// recently used print settings") keeps this dialog's own sticky in-session
// ref state below, since it is only reseeded when the dialog re-opens.
const injectedViewerOptions = inject(ViewerOptionsKey, undefined);
const printOptionDefaults = computed(() =>
	resolveDefaultPrintSettings(injectedViewerOptions?.value ?? DEFAULT_VIEWER_OPTIONS),
);

// ── State ──────────────────────────────────────────────────────────────
const printWhat = ref<PrintWhat>(printOptionDefaults.value?.printWhat ?? 'slides');
const orientation = ref<PrintOrientation>('landscape');
const colorMode = ref<PrintColorMode>(printOptionDefaults.value?.colorMode ?? 'color');
const frameSlides = ref<boolean>(
	printOptionDefaults.value?.frameSlides ?? props.defaultFrameSlides ?? false,
);
const slidesPerPage = ref<HandoutSlidesPerPage>(resolveSlidesPerPage(props.defaultSlidesPerPage));
const slideRange = ref<PrintSlideRange>('all');
const customFrom = ref<number>(1);
const customTo = ref<number>(props.slides.length);

/** Re-seed the form from the props each time the dialog opens. */
watch(
	() => props.open,
	(isOpen) => {
		if (isOpen) {
			const defaults = printOptionDefaults.value;
			printWhat.value = defaults?.printWhat ?? 'slides';
			orientation.value = 'landscape';
			colorMode.value = defaults?.colorMode ?? 'color';
			frameSlides.value = defaults?.frameSlides ?? props.defaultFrameSlides ?? false;
			slidesPerPage.value = resolveSlidesPerPage(props.defaultSlidesPerPage);
			slideRange.value = 'all';
			customFrom.value = 1;
			customTo.value = props.slides.length;
		}
	},
);

// ── Derived ────────────────────────────────────────────────────────────
const totalSlides = computed(() => props.slides.length);

const resolvedOrientation = computed<PrintOrientation>(() =>
	effectiveOrientation(printWhat.value, orientation.value),
);

const slideCount = computed(() =>
	computeSlideCount(slideRange.value, totalSlides.value, customFrom.value, customTo.value),
);

const pageCount = computed(() =>
	computePageCount(printWhat.value, slideCount.value, slidesPerPage.value),
);

const previewSlideIndices = computed(() =>
	computeSlideIndices(
		slideRange.value,
		props.activeSlideIndex,
		totalSlides.value,
		customFrom.value,
		customTo.value,
	),
);

const handoutGrid = computed(() => getHandoutGrid(slidesPerPage.value));

const showHandoutPreview = computed(() => printWhat.value === 'handouts');
const showNotesPreview = computed(() => printWhat.value === 'notes');

// ── Handlers ───────────────────────────────────────────────────────────
function close(): void {
	emit('close');
}

function confirmPrint(): void {
	emit('print', {
		printWhat: printWhat.value,
		orientation: resolvedOrientation.value,
		colorMode: colorMode.value,
		frameSlides: frameSlides.value,
		slidesPerPage: slidesPerPage.value,
		slideRange: slideRange.value,
		customRangeFrom: Math.max(1, Math.min(customFrom.value, totalSlides.value || 1)),
		customRangeTo: Math.max(1, Math.min(customTo.value, totalSlides.value || 1)),
		// Options > Advanced > "Print scale to fit"; no dialog control of its own
		// (PowerPoint keeps this an Options default, not a per-job choice).
		scaleToFit: printOptionDefaults.value?.scaleToFit ?? true,
	});
}
</script>

<template>
	<ModalDialog :open="open" :title="t('pptx.print.title')" @close="close">
		<div class="pptx-vue-print-body flex min-w-[480px] gap-5 max-md:min-w-0 max-md:flex-col">
			<PrintSettingsPanel
				:print-what="printWhat"
				:orientation="orientation"
				:color-mode="colorMode"
				:frame-slides="frameSlides"
				:slides-per-page="slidesPerPage"
				:slide-range="slideRange"
				:custom-from="customFrom"
				:custom-to="customTo"
				:total-slides="totalSlides"
				:active-slide-index="activeSlideIndex"
				@update:print-what="printWhat = $event"
				@update:orientation="orientation = $event"
				@update:color-mode="colorMode = $event"
				@update:frame-slides="frameSlides = $event"
				@update:slides-per-page="slidesPerPage = $event"
				@update:slide-range="slideRange = $event"
				@update:custom-from="customFrom = $event"
				@update:custom-to="customTo = $event"
			/>

			<!-- Lightweight preview for handout / notes layouts -->
			<div
				v-if="showHandoutPreview || showNotesPreview"
				class="pptx-vue-print-preview flex w-[180px] shrink-0 flex-col items-center gap-2.5 border-l border-border pl-4 max-md:w-full max-md:border-l-0 max-md:border-t max-md:pl-0 max-md:pt-4"
			>
				<span
					class="pptx-vue-print-preview-title text-[10px] uppercase tracking-wide text-muted-foreground"
				>
					{{ t('pptx.animations.preview') }}
				</span>

				<div
					v-if="previewSlideIndices.length === 0"
					class="pptx-vue-print-preview-empty flex h-full items-center justify-center text-xs text-muted-foreground"
				>
					{{ t('pptx.statusBar.noSlides') }}
				</div>

				<!-- Handout grid preview -->
				<div
					v-else-if="showHandoutPreview"
					class="pptx-vue-print-preview-page"
					:style="{
						display: 'grid',
						gridTemplateColumns: `repeat(${handoutGrid.columns}, 1fr)`,
						gridTemplateRows: `repeat(${handoutGrid.rows}, 1fr)`,
					}"
				>
					<div
						v-for="cellIndex in handoutGrid.rows * handoutGrid.columns"
						:key="cellIndex"
						class="pptx-vue-print-preview-cell"
						:class="{ 'pptx-vue-print-preview-cell--framed': frameSlides }"
					>
						<span v-if="previewSlideIndices[cellIndex - 1] !== undefined">
							{{ previewSlideIndices[cellIndex - 1] + 1 }}
						</span>
					</div>
				</div>

				<!-- Notes preview -->
				<div v-else class="pptx-vue-print-preview-notes-page">
					<div
						class="pptx-vue-print-preview-cell"
						:class="{ 'pptx-vue-print-preview-cell--framed': frameSlides }"
					>
						<span>{{ (previewSlideIndices[0] ?? 0) + 1 }}</span>
					</div>
					<div class="pptx-vue-print-preview-lines">
						<div v-for="line in 5" :key="line" class="pptx-vue-print-preview-line" />
					</div>
				</div>
			</div>
		</div>

		<template #footer>
			<span class="pptx-vue-print-estimate mr-auto text-xs text-muted-foreground">
				{{
					pageCount === 1
						? t('pptx.print.page', { count: pageCount })
						: t('pptx.print.pages', { count: pageCount })
				}}
				·
				{{
					slideCount === 1
						? t('pptx.print.slide', { count: slideCount })
						: t('pptx.print.slides', { count: slideCount })
				}}
			</span>
			<button
				type="button"
				class="pptx-vue-print-btn pptx-vue-print-btn--secondary rounded-lg border border-border px-4 py-2 text-sm text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
				@click="close"
			>
				{{ t('pptx.share.cancel') }}
			</button>
			<button
				type="button"
				class="pptx-vue-print-btn pptx-vue-print-btn--primary rounded-lg bg-primary px-4 py-2 text-sm text-white transition-colors hover:bg-primary/90"
				@click="confirmPrint"
			>
				{{ t('pptx.print.printButton') }}
			</button>
		</template>
	</ModalDialog>
</template>

<style scoped>
.pptx-vue-print-preview-page {
	width: 130px;
	height: 184px;
	gap: 4px;
	padding: 6px;
	background: #ffffff;
	border: 1px solid var(--pptx-vue-border, #e5e7eb);
	border-radius: 4px;
	box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
}

.pptx-vue-print-preview-notes-page {
	display: flex;
	flex-direction: column;
	gap: 6px;
	width: 130px;
	height: 184px;
	padding: 8px;
	background: #ffffff;
	border: 1px solid var(--pptx-vue-border, #e5e7eb);
	border-radius: 4px;
	box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
}

.pptx-vue-print-preview-notes-page .pptx-vue-print-preview-cell {
	height: 70px;
}

.pptx-vue-print-preview-cell {
	display: flex;
	align-items: center;
	justify-content: center;
	background: #f9fafb;
	border: 1px solid #d1d5db;
	border-radius: 2px;
	font-size: 9px;
	font-weight: 500;
	color: #9ca3af;
}

.pptx-vue-print-preview-cell--framed {
	border: 2px solid #1f2937;
}

.pptx-vue-print-preview-lines {
	display: flex;
	flex-direction: column;
	justify-content: space-evenly;
	flex: 1;
	padding: 0 2px;
}

.pptx-vue-print-preview-line {
	height: 0;
	border-bottom: 1px solid #d1d5db;
}
</style>

// packages/angular/src/viewer/print-dialog.component.ts
/**
 * print-dialog.component.ts: Full-featured print dialog for the PPTX viewer.
 *
 * Selector: `pptx-print-dialog`
 *
 * Mirrors React's `PrintDialog`: a modal with the settings panel, a live page
 * estimate in the footer, and Cancel / Print actions. The dialog owns the
 * authoritative {@link PrintSettings} as a signal, seeded from optional
 * presentation defaults, and emits the resolved settings on confirm.
 *
 * Usage:
 * ```html
 * @if (print.isDialogOpen()) {
 *   <pptx-print-dialog
 *     [slides]="loader.slides()"
 *     [activeSlideIndex]="activeIndex()"
 *     [defaultSlidesPerPage]="props.slidesPerPage"
 *     [defaultFrameSlides]="props.frameSlides"
 *     (print)="onPrint($event)"
 *     (cancel)="print.closeDialog()"
 *   />
 * }
 * ```
 */

import {
	ChangeDetectionStrategy,
	Component,
	HostListener,
	computed,
	effect,
	inject,
	input,
	output,
	signal,
} from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import type { PptxSlide } from 'pptx-viewer-core';

import { IsMobileService } from './is-mobile';
import {
	DEFAULT_PRINT_SETTINGS,
	computeSlideIndices,
	estimatePageCount,
	normalizeSlidesPerPage,
	validatePrintSettings,
} from './print-helpers';
import type { PrintSettings } from './print-helpers';
import { PrintSettingsPanelComponent } from './print-settings-panel.component';

/**
 * Map the mobile flag to the print-dialog panel class list. Pure (no Angular /
 * DOM) so it can be unit-tested without TestBed. On mobile the dialog gains the
 * `is-mobile` modifier that turns it into a full-width bottom sheet.
 */
export function printDialogClass(isMobile: boolean): string {
	return isMobile ? 'pptx-ng-print-dialog is-mobile' : 'pptx-ng-print-dialog';
}

@Component({
	selector: 'pptx-print-dialog',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [PrintSettingsPanelComponent, TranslatePipe],
	providers: [IsMobileService],
	template: `
		<div
			class="pptx-ng-print-dialog__backdrop"
			[class.is-mobile]="mobile.isMobile()"
			role="dialog"
			aria-modal="true"
			[attr.aria-label]="'pptx.print.title' | translate"
			(click)="onBackdropClick($event)"
		>
			<div [class]="dialogClass()">
				<!-- Header -->
				<div class="pptx-ng-print-dialog__header">
					<h2 class="pptx-ng-print-dialog__title">{{ 'pptx.print.title' | translate }}</h2>
					<button
						type="button"
						class="pptx-ng-print-dialog__icon-btn"
						[attr.aria-label]="'pptx.common.close' | translate"
						(click)="onCancel()"
					>
						&#10005;
					</button>
				</div>

				<!-- Body -->
				<div class="pptx-ng-print-dialog__body">
					<pptx-print-settings-panel
						[settings]="settings()"
						[totalSlides]="slides().length"
						[activeSlideIndex]="activeSlideIndex()"
						(settingsChange)="patch($event)"
					/>
				</div>

				<!-- Footer -->
				<div class="pptx-ng-print-dialog__footer">
					<span class="pptx-ng-print-dialog__estimate">
						{{
							'pptx.print.pageEstimate' | translate: { pages: pageCount(), slides: slideCount() }
						}}
					</span>
					<div class="pptx-ng-print-dialog__actions">
						<button type="button" class="pptx-ng-print-dialog__btn" (click)="onCancel()">
							{{ 'pptx.common.cancel' | translate }}
						</button>
						<button
							type="button"
							class="pptx-ng-print-dialog__btn pptx-ng-print-dialog__btn--primary"
							(click)="onConfirm()"
						>
							{{ 'pptx.print.printButton' | translate }}
						</button>
					</div>
				</div>
			</div>
		</div>
	`,
	styles: [
		`
			.pptx-ng-print-dialog__backdrop {
				position: fixed;
				inset: 0;
				z-index: 1200;
				display: flex;
				align-items: center;
				justify-content: center;
				background: rgba(0, 0, 0, 0.6);
				backdrop-filter: blur(2px);
			}

			.pptx-ng-print-dialog {
				display: flex;
				flex-direction: column;
				width: 780px;
				max-width: calc(100vw - 2rem);
				max-height: 90vh;
				border: 1px solid rgba(255, 255, 255, 0.12);
				border-radius: 0.75rem;
				background: #1e1e1e;
				color: #e5e5e5;
				box-shadow: 0 20px 60px rgba(0, 0, 0, 0.6);
			}

			.pptx-ng-print-dialog__header {
				display: flex;
				align-items: center;
				justify-content: space-between;
				padding: 1rem 1.25rem;
				border-bottom: 1px solid rgba(255, 255, 255, 0.1);
			}

			.pptx-ng-print-dialog__title {
				margin: 0;
				font-size: 0.875rem;
				font-weight: 600;
				color: #ffffff;
			}

			.pptx-ng-print-dialog__icon-btn {
				display: inline-flex;
				align-items: center;
				justify-content: center;
				width: 1.75rem;
				height: 1.75rem;
				padding: 0;
				border: 0;
				border-radius: 0.25rem;
				background: transparent;
				color: rgba(255, 255, 255, 0.6);
				font-size: 0.75rem;
				cursor: pointer;
				transition:
					background 0.12s,
					color 0.12s;
			}

			.pptx-ng-print-dialog__icon-btn:hover {
				background: rgba(255, 255, 255, 0.1);
				color: #ffffff;
			}

			.pptx-ng-print-dialog__body {
				flex: 1;
				overflow-y: auto;
				padding: 1rem 1.25rem;
			}

			.pptx-ng-print-dialog__footer {
				display: flex;
				align-items: center;
				justify-content: space-between;
				padding: 0.75rem 1.25rem;
				border-top: 1px solid rgba(255, 255, 255, 0.1);
			}

			.pptx-ng-print-dialog__estimate {
				font-size: 0.75rem;
				color: rgba(255, 255, 255, 0.5);
			}

			.pptx-ng-print-dialog__actions {
				display: flex;
				gap: 0.5rem;
			}

			.pptx-ng-print-dialog__btn {
				padding: 0.5rem 1rem;
				border: 1px solid rgba(255, 255, 255, 0.15);
				border-radius: 0.5rem;
				background: rgba(255, 255, 255, 0.04);
				color: rgba(255, 255, 255, 0.7);
				font-size: 0.8125rem;
				cursor: pointer;
				transition:
					background 0.12s,
					color 0.12s,
					border-color 0.12s;
			}

			.pptx-ng-print-dialog__btn:hover {
				background: rgba(255, 255, 255, 0.1);
				color: #ffffff;
			}

			.pptx-ng-print-dialog__btn--primary {
				border-color: #3b82f6;
				background: #3b82f6;
				color: #ffffff;
			}

			.pptx-ng-print-dialog__btn--primary:hover {
				background: #2f6fd6;
			}

			/*
			 * Mobile: dock the dialog full-width at the bottom as a sheet (rounded
			 * top, dvh-capped height with internal scroll, safe-area padding) so
			 * the 780px desktop card never overflows a phone. Driven by the
			 * .is-mobile class (IsMobileService 768px breakpoint) and mirrored by a
			 * media query as a no-JS fallback.
			 */
			.pptx-ng-print-dialog__backdrop.is-mobile {
				align-items: flex-end;
			}

			.pptx-ng-print-dialog.is-mobile {
				width: 100%;
				max-width: none;
				max-height: 88dvh;
				border-left: none;
				border-right: none;
				border-bottom: none;
				border-top-left-radius: 1rem;
				border-top-right-radius: 1rem;
				border-bottom-left-radius: 0;
				border-bottom-right-radius: 0;
				padding-bottom: max(env(safe-area-inset-bottom), 0px);
			}

			@media (max-width: 767px), (pointer: coarse) {
				.pptx-ng-print-dialog__backdrop {
					align-items: flex-end;
				}

				.pptx-ng-print-dialog {
					width: 100%;
					max-width: none;
					max-height: 88dvh;
					border-left: none;
					border-right: none;
					border-bottom: none;
					border-top-left-radius: 1rem;
					border-top-right-radius: 1rem;
					border-bottom-left-radius: 0;
					border-bottom-right-radius: 0;
					padding-bottom: max(env(safe-area-inset-bottom), 0px);
				}
			}
		`,
	],
})
export class PrintDialogComponent {
	// -------------------------------------------------------------------------
	// Inputs / outputs
	// -------------------------------------------------------------------------

	/** All slides in the current presentation. */
	readonly slides = input.required<PptxSlide[]>();

	/** Zero-based index of the active slide. */
	readonly activeSlideIndex = input.required<number>();

	/** Default slides-per-page from presentation properties. */
	readonly defaultSlidesPerPage = input<number | undefined>(undefined);

	/** Default frame-slides from presentation properties. */
	readonly defaultFrameSlides = input<boolean | undefined>(undefined);

	/**
	 * File > Options > Advanced > Print seed (`ViewerOptionsService.printDefaults`).
	 * `undefined` (Options > "Use the most recently used print settings") leaves
	 * `printWhat`/`colorMode`/`frameSlides` at their hardcoded defaults below.
	 */
	readonly defaultSettings = input<Partial<PrintSettings> | undefined>(undefined);

	/** Emits the resolved, validated settings when the user clicks Print. */
	readonly print = output<PrintSettings>();

	/** Emits when the dialog is dismissed (Cancel / Escape / backdrop). */
	readonly cancel = output<void>();

	/** Reactive viewport / pointer flags (drives the bottom-sheet layout). */
	protected readonly mobile = inject(IsMobileService);

	/**
	 * Dialog class list: gains the `is-mobile` bottom-sheet modifier under the
	 * mobile breakpoint. See {@link printDialogClass}.
	 */
	protected readonly dialogClass = computed(() => printDialogClass(this.mobile.isMobile()));

	// -------------------------------------------------------------------------
	// State
	// -------------------------------------------------------------------------

	/** Authoritative print settings, seeded from defaults. */
	readonly settings = signal<PrintSettings>({ ...DEFAULT_PRINT_SETTINGS });

	private _seeded = false;

	constructor() {
		// Seed settings from presentation defaults once, then leave user edits
		// untouched. Custom-range "to" defaults to the last slide.
		effect(() => {
			if (this._seeded) {
				return;
			}
			this._seeded = true;
			const total = this.slides().length;
			const optionDefaults = this.defaultSettings();
			this.settings.set({
				...DEFAULT_PRINT_SETTINGS,
				printWhat: optionDefaults?.printWhat ?? DEFAULT_PRINT_SETTINGS.printWhat,
				colorMode: optionDefaults?.colorMode ?? DEFAULT_PRINT_SETTINGS.colorMode,
				slidesPerPage: normalizeSlidesPerPage(this.defaultSlidesPerPage()),
				frameSlides: optionDefaults?.frameSlides ?? this.defaultFrameSlides() ?? false,
				scaleToFit: optionDefaults?.scaleToFit ?? DEFAULT_PRINT_SETTINGS.scaleToFit,
				customRangeFrom: 1,
				customRangeTo: Math.max(1, total),
			});
		});
	}

	// -------------------------------------------------------------------------
	// Derived
	// -------------------------------------------------------------------------

	/** Number of slides selected by the current range. */
	readonly slideCount = computed<number>(() => {
		const s = this.settings();
		return computeSlideIndices(
			s.slideRange,
			this.activeSlideIndex(),
			this.slides().length,
			s.customRangeFrom,
			s.customRangeTo,
		).length;
	});

	/** Estimated printed page count for the current settings. */
	readonly pageCount = computed<number>(() => {
		const s = this.settings();
		return estimatePageCount(s.printWhat, this.slideCount(), s.slidesPerPage);
	});

	// -------------------------------------------------------------------------
	// Handlers
	// -------------------------------------------------------------------------

	/** Apply a partial patch from the settings panel and re-validate. */
	patch(partial: Partial<PrintSettings>): void {
		const next = validatePrintSettings({ ...this.settings(), ...partial }, this.slides().length);
		this.settings.set(next);
	}

	onConfirm(): void {
		this.print.emit(validatePrintSettings(this.settings(), this.slides().length));
	}

	onCancel(): void {
		this.cancel.emit();
	}

	onBackdropClick(event: MouseEvent): void {
		// Only dismiss when the backdrop itself (not the dialog) is clicked.
		if (event.target === event.currentTarget) {
			this.onCancel();
		}
	}

	@HostListener('document:keydown', ['$event'])
	onKeydown(event: KeyboardEvent): void {
		if (event.key === 'Escape') {
			event.preventDefault();
			this.onCancel();
		}
	}
}
