// packages/vue/src/viewer/components/RemoteSelectionOverlay.vue
<script lang="ts">
/**
 * RemoteSelectionOverlay - presentational overlay that draws a coloured
 * rectangle around each element a remote collaborator has selected, labelled
 * with that peer's name in their colour (Google-Slides-style presence).
 *
 * Like {@link CollaborationCursors}, this component owns no Yjs/network logic.
 * The integrator supplies the reactive list of {@link RemotePresence} entries
 * (from the collaboration composable), the elements on the active slide, and
 * the active slide index. Only peers whose `activeSlide` matches
 * `activeSlideIndex` are drawn, and only for selected ids that resolve to an
 * element on the slide.
 *
 * Element `x`/`y`/`width`/`height` are *unscaled* slide coordinates (px) and
 * are used as-is: the overlay is mounted inside the scaled slide-stage host,
 * so the stage's CSS `transform: scale()` applies the zoom exactly once.
 * Multiplying by zoom here as well would double-apply the scale and shrink or
 * misplace the boxes at any zoom other than 100%.
 *
 * The overlay sets `pointer-events: none` so it never intercepts canvas input.
 */
import type { PptxElement } from 'pptx-viewer-core';

import type { RemotePresence } from '../composables/useCollaboration';

/** A single resolved remote selection box, in unscaled slide coordinates. */
export interface RemoteSelectionBox {
	/** Stable key (peer clientId + element id). */
	key: string;
	/** Id of the outlined element (framework-neutral e2e contract). */
	elementId: string;
	/** Peer display name shown in the label chip. */
	userName: string;
	/** Outline + chip colour. */
	color: string;
	/** Unscaled slide-space geometry of the selected element. */
	x: number;
	y: number;
	width: number;
	height: number;
}
</script>

<script setup lang="ts">
import type { CSSProperties } from 'vue';
import { computed } from 'vue';

const props = defineProps<{
	/** Remote collaborators' presence (cursor + selection + active slide). */
	presences: RemotePresence[];
	/** Elements on the active slide (used to resolve selected ids → geometry). */
	elements: PptxElement[];
	/** The current slide index: only peers on this slide are drawn. */
	activeSlideIndex: number;
	/**
	 * @deprecated Unused. The scaled slide-stage host already applies the zoom
	 * via its CSS transform, so selection geometry is rendered as-is.
	 */
	zoom?: number;
}>();

/** Build a quick id → element lookup for the active slide. */
const elementMap = computed(() => {
	const map = new Map<string, PptxElement>();
	for (const el of props.elements) {
		map.set(el.id, el);
	}
	return map;
});

/** Resolve every remote peer's selection on this slide into drawable boxes. */
const boxes = computed<RemoteSelectionBox[]>(() => {
	const result: RemoteSelectionBox[] = [];
	for (const peer of props.presences) {
		if (peer.activeSlide !== props.activeSlideIndex) {
			continue;
		}
		for (const id of peer.selectionIds) {
			const el = elementMap.value.get(id);
			if (!el) {
				continue;
			}
			result.push({
				key: `${peer.clientId}-${id}`,
				elementId: id,
				userName: peer.userName,
				color: peer.color,
				x: el.x,
				y: el.y,
				width: el.width,
				height: el.height,
			});
		}
	}
	return result;
});

/** Clamp/format the label so very long names don't overflow the chip. */
const MAX_LABEL_CHARS = 20;
function labelFor(userName: string): string {
	return userName.length > MAX_LABEL_CHARS
		? `${userName.slice(0, MAX_LABEL_CHARS - 1)}…`
		: userName;
}

/** Absolute position + size for a box, in raw slide-space pixels. */
function boxStyle(box: RemoteSelectionBox): CSSProperties {
	return {
		transform: `translate(${box.x}px, ${box.y}px)`,
		width: `${box.width}px`,
		height: `${box.height}px`,
		borderColor: box.color,
	};
}
</script>

<template>
	<div class="pptx-vue-remote-selections" aria-hidden="true" data-export-ignore="true">
		<div
			v-for="box in boxes"
			:key="box.key"
			class="pptx-vue-remote-selection"
			:data-element-id="box.key"
			:data-pptx-remote-selection="box.elementId"
			:style="boxStyle(box)"
		>
			<span class="pptx-vue-remote-selection-label" :style="{ backgroundColor: box.color }">
				{{ labelFor(box.userName) }}
			</span>
		</div>
	</div>
</template>

<style scoped>
.pptx-vue-remote-selections {
	position: absolute;
	inset: 0;
	pointer-events: none;
	overflow: visible;
	z-index: 9997;
}

.pptx-vue-remote-selection {
	position: absolute;
	top: 0;
	left: 0;
	box-sizing: border-box;
	border: 2px solid currentcolor;
	border-radius: 2px;
	pointer-events: none;
	will-change: transform;
	transition: transform 90ms linear;
}

.pptx-vue-remote-selection-label {
	position: absolute;
	top: -18px;
	left: -2px;
	max-width: 150px;
	padding: 1px 5px;
	border-radius: 3px;
	color: #ffffff;
	font-family: system-ui, sans-serif;
	font-size: 9px;
	font-weight: 500;
	line-height: 1.3;
	white-space: nowrap;
	overflow: hidden;
	text-overflow: ellipsis;
}
</style>

// packages/angular/src/viewer/remote-selection-overlay.component.ts
/**
 * remote-selection-overlay.component.ts: Angular port of the Vue
 * `RemoteSelectionOverlay.vue` / React `RemoteSelectionOverlay.tsx`.
 *
 * Selector: `pptx-remote-selection-overlay`
 *
 * Draws a coloured rectangle around each element a remote collaborator has
 * selected, labelled with that peer's name in their colour (Google-Slides-style
 * presence). Purely presentational: the host supplies the reactive presence
 * list (from `CollaborationService.presence`), the elements on the active slide,
 * the active slide index, and the current `zoom`. Only peers whose
 * `activeSlideIndex` matches are drawn, and only for a selected id that resolves
 * to an element on the slide.
 *
 * Element geometry is in unscaled slide coordinates (px) and is rendered as-is:
 * the overlay is projected into the scaled slide stage, so the stage's CSS
 * `transform: scale()` applies the on-screen scale exactly once. Multiplying by
 * zoom here as well would double-apply the scale and misplace the boxes. It
 * sets `pointer-events: none` so it never intercepts canvas input.
 */

import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import type { PptxElement } from 'pptx-viewer-core';

import { MAX_LABEL_CHARS, formatCursorLabel } from './collaboration-helpers';
import type { RemotePresence } from './collaboration-helpers';
import { resolveRemoteSelectionBoxes } from './collaboration-overlay-geometry';

/** A drawable box: the resolved geometry turned into a CSS transform. */
interface PositionedSelectionBox {
	key: string;
	elementId: string;
	label: string;
	color: string;
	transform: string;
	width: number;
	height: number;
}

@Component({
	selector: 'pptx-remote-selection-overlay',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	styles: `
		:host {
			position: absolute;
			inset: 0;
			pointer-events: none;
			overflow: visible;
			z-index: 9997;
		}

		.pptx-ng-remote-selection {
			position: absolute;
			top: 0;
			left: 0;
			box-sizing: border-box;
			border: 2px solid currentcolor;
			border-radius: 2px;
			pointer-events: none;
			will-change: transform;
			transition: transform 90ms linear;
		}

		.pptx-ng-remote-selection-label {
			position: absolute;
			top: -18px;
			left: -2px;
			max-width: 150px;
			padding: 1px 5px;
			border-radius: 3px;
			color: #ffffff;
			font-family: system-ui, sans-serif;
			font-size: 9px;
			font-weight: 500;
			line-height: 1.3;
			white-space: nowrap;
			overflow: hidden;
			text-overflow: ellipsis;
		}
	`,
	template: `
		<div aria-hidden="true" data-export-ignore="true">
			@for (box of boxes(); track box.key) {
				<div
					class="pptx-ng-remote-selection"
					[attr.data-element-id]="box.key"
					[attr.data-pptx-remote-selection]="box.elementId"
					[style.transform]="box.transform"
					[style.width.px]="box.width"
					[style.height.px]="box.height"
					[style.color]="box.color"
				>
					<span class="pptx-ng-remote-selection-label" [style.background-color]="box.color">
						{{ box.label }}
					</span>
				</div>
			}
		</div>
	`,
})
export class RemoteSelectionOverlayComponent {
	/** Remote collaborators' presence (cursor + selection + active slide). */
	readonly presences = input<RemotePresence[]>([]);
	/** Elements on the active slide (used to resolve selected ids -> geometry). */
	readonly elements = input<readonly PptxElement[]>([]);
	/** The current slide index: only peers on this slide are drawn. */
	readonly activeSlideIndex = input<number>(0);
	/**
	 * @deprecated Unused. The scaled slide stage this overlay is projected into
	 * already applies the zoom via its CSS transform, so selection geometry is
	 * rendered in raw slide coordinates.
	 */
	readonly zoom = input<number>(1);

	protected readonly boxes = computed<PositionedSelectionBox[]>(() =>
		resolveRemoteSelectionBoxes(
			this.presences(),
			this.elements(),
			this.activeSlideIndex(),
			(userName) => formatCursorLabel(userName, MAX_LABEL_CHARS),
		).map((box) => ({
			key: box.key,
			elementId: box.elementId,
			label: box.label,
			color: box.color,
			transform: `translate(${box.x}px, ${box.y}px)`,
			width: box.width,
			height: box.height,
		})),
	);
}
