// packages/vue/src/viewer/components/ShareDialog.vue
<script setup lang="ts">
import type { CollaborationConfig } from 'pptx-viewer-shared';
import {
	buildActiveSessionUsers,
	buildCollaborationShareUrl,
	buildCreateCollaborationConfig,
	buildJoinCollaborationConfig,
	resolveTransportForServerUrl,
} from 'pptx-viewer-shared';
import { computed, inject, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';

import type { UseCollaborationResult } from '../composables/useCollaboration';
import { ViewerOptionsKey } from '../composables/useViewerOptionsStore';
import ModalDialog from './ModalDialog.vue';

/**
 * ShareDialog - Vue port of the React `ShareDialog`.
 *
 * Configures and starts a real-time collaboration session (room id, display
 * name, server URL), or stops an active one. Field defaults are supplied by
 * the host application via the `defaults` prop. When `active` is `true` the
 * form is replaced by the active-session view: status, a copyable share link,
 * room/server details, and the connected-users list built by shared's
 * `buildActiveSessionUsers` from `collab`'s live presence state.
 */
const props = defineProps<{
	/** Whether the dialog is visible. */
	open: boolean;
	/** Prefilled values for the form fields. */
	defaults?: { roomId?: string; userName?: string; serverUrl?: string };
	/** Whether a collaboration session is currently active. */
	active?: boolean;
	/** Live collaboration session state (status/count/remote users). */
	collab?: UseCollaborationResult;
	/** The config the active session was started with; null while stopped. */
	activeCollaboration?: CollaborationConfig | null;
}>();

const viewerOptions = inject(ViewerOptionsKey, undefined);

const emit = defineEmits<{
	/** Fired with the assembled config when the user starts sharing. */
	start: [config: CollaborationConfig];
	/** Fired when the user stops an active session. */
	stop: [];
	/** Fired when the dialog is dismissed. */
	close: [];
}>();

const { t } = useI18n();

const roomId = ref('');
const userName = ref('');
const serverUrl = ref('');
const mode = ref<'create' | 'join'>('create');
const invitation = ref('');

function resetFromDefaults(): void {
	roomId.value = props.defaults?.roomId ?? '';
	userName.value = props.defaults?.userName ?? '';
	serverUrl.value = props.defaults?.serverUrl ?? '';
}

// Re-seed the form from defaults whenever the dialog (re)opens.
watch(
	() => props.open,
	(open) => {
		if (open) {
			resetFromDefaults();
		}
	},
	{ immediate: true },
);

// A blank server URL is valid: it selects serverless peer-to-peer (webrtc).
const pendingConfig = computed(() =>
	mode.value === 'join'
		? buildJoinCollaborationConfig({
				invitation: invitation.value,
				userName: userName.value,
				serverUrl: serverUrl.value,
			})
		: buildCreateCollaborationConfig({
				roomId: roomId.value,
				userName: userName.value,
				serverUrl: serverUrl.value,
			}),
);
const canStart = computed(() => pendingConfig.value !== null);

// True when the current server field selects serverless peer-to-peer mode.
const isPeerToPeer = computed(() => resolveTransportForServerUrl(serverUrl.value) === 'webrtc');

// ── Active-session view ──────────────────────────────────────────────────

const status = computed(() => props.collab?.status.value ?? 'disconnected');
const connectedCount = computed(() => props.collab?.connectedCount.value ?? 0);
const activeIsPeerToPeer = computed(
	() => resolveTransportForServerUrl(props.activeCollaboration?.serverUrl ?? '') === 'webrtc',
);
const activeShareUrl = computed(() => {
	if (!props.activeCollaboration || typeof window === 'undefined') {
		return '';
	}
	return buildCollaborationShareUrl(props.activeCollaboration, {
		origin: window.location.origin,
		pathname: window.location.pathname,
	});
});
const sessionUsers = computed(() => {
	if (!props.collab || !props.activeCollaboration) {
		return [];
	}
	return buildActiveSessionUsers({
		localUserName: props.activeCollaboration.userName,
		localUserInitials: viewerOptions?.value.general.userInitials,
		localUserColor: props.activeCollaboration.userColor,
		remoteUsers: props.collab.remotePresences.value.map((peer) => ({
			clientId: peer.clientId,
			userName: peer.userName,
			userColor: peer.color,
			activeSlideIndex: peer.activeSlide,
		})),
	});
});

const copied = ref(false);
function onCopyLink(): void {
	if (!activeShareUrl.value || typeof navigator === 'undefined' || !navigator.clipboard) {
		return;
	}
	void navigator.clipboard.writeText(activeShareUrl.value).then(() => {
		copied.value = true;
		window.setTimeout(() => {
			copied.value = false;
		}, 2000);
		return undefined;
	});
}

function handleStart(): void {
	if (pendingConfig.value) {
		emit('start', pendingConfig.value);
	}
}

function handleStop(): void {
	emit('stop');
}
</script>

<template>
	<ModalDialog
		:open="open"
		:title="active ? t('pptx.share.collaborationActive') : t('pptx.toolbar.share')"
		@close="emit('close')"
	>
		<div v-if="active" class="pptx-vue-share-active flex flex-col gap-4">
			<!-- Status -->
			<div class="flex items-center gap-2">
				<span
					class="inline-block h-2 w-2 rounded-full"
					:class="{
						'bg-green-400': status === 'connected',
						'bg-yellow-400': status === 'connecting',
						'bg-red-400': status !== 'connected' && status !== 'connecting',
					}"
				/>
				<span class="text-[13px] font-medium capitalize text-foreground">{{ status }}</span>
				<span class="ml-auto text-[12px] text-muted-foreground">
					{{ t('pptx.collaboration.userCount', { count: connectedCount }) }}
				</span>
			</div>

			<!-- Share URL -->
			<div v-if="activeShareUrl" class="pptx-vue-share-field flex flex-col gap-1.5">
				<label class="text-[12px] font-medium text-foreground">{{
					t('pptx.share.shareLink')
				}}</label>
				<div class="flex items-center gap-2">
					<div
						class="flex-1 select-all truncate rounded border border-border bg-background px-3 py-1.5 font-mono text-[11px] text-foreground"
					>
						{{ activeShareUrl }}
					</div>
					<button
						type="button"
						class="shrink-0 rounded border border-border bg-muted px-2.5 py-1.5 text-[12px] text-foreground transition-colors hover:bg-accent"
						:title="t('pptx.share.copyLink')"
						@click="onCopyLink"
					>
						{{ copied ? t('pptx.share.copied') : t('pptx.share.copyUrl') }}
					</button>
				</div>
				<p class="text-[11px] text-muted-foreground">{{ t('pptx.share.shareHint') }}</p>
			</div>

			<!-- Session details -->
			<div
				v-if="activeCollaboration"
				class="flex items-center gap-3 text-[11px] text-muted-foreground"
			>
				<span>
					{{ t('pptx.share.room') }}
					<code class="font-mono text-foreground">{{ activeCollaboration.roomId }}</code>
				</span>
				<span>
					{{ t('pptx.share.server') }}
					<code class="font-mono text-foreground">
						{{
							activeIsPeerToPeer ? t('pptx.share.p2pServerValue') : activeCollaboration.serverUrl
						}}
					</code>
				</span>
			</div>
			<p
				v-else-if="isPeerToPeer"
				class="pptx-vue-share-server-value text-[12px] text-muted-foreground"
			>
				{{ t('pptx.share.p2pServerValue') }}
			</p>

			<!-- Connected users -->
			<div v-if="sessionUsers.length > 0" class="pptx-vue-share-field flex flex-col gap-1.5">
				<label class="text-[12px] font-medium text-foreground">{{
					t('pptx.share.connectedUsers')
				}}</label>
				<div
					class="max-h-[140px] divide-y divide-border overflow-y-auto rounded border border-border bg-background"
				>
					<div
						v-for="user in sessionUsers"
						:key="user.id"
						class="flex items-center gap-2 px-3 py-2"
					>
						<div
							class="flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-[9px] font-semibold text-white"
							:style="{ backgroundColor: user.color }"
						>
							<img
								v-if="user.avatarUrl"
								:src="user.avatarUrl"
								alt=""
								class="h-full w-full rounded-full object-cover"
							/>
							<template v-else>{{ user.initials }}</template>
						</div>
						<span class="truncate text-[12px] text-foreground">{{ user.name }}</span>
						<span class="ml-auto text-[10px] text-muted-foreground">
							{{
								user.isLocal ? t('pptx.share.you') : t('pptx.notes.slideN', { n: user.slideNumber })
							}}
						</span>
					</div>
				</div>
			</div>

			<button
				type="button"
				class="pptx-vue-share-stop w-full rounded border border-red-500/30 bg-red-500/10 px-3 py-2 text-[12px] font-medium text-red-400 transition-colors hover:bg-red-500/20"
				@click="handleStop"
			>
				{{ t('pptx.share.stopSharing') }}
			</button>
		</div>

		<div v-else class="pptx-vue-share-form flex flex-col gap-4">
			<div class="grid grid-cols-2 gap-1 rounded-lg bg-muted p-1" role="tablist">
				<button
					v-for="candidate in ['create', 'join'] as const"
					:key="candidate"
					type="button"
					role="tab"
					:aria-selected="mode === candidate"
					class="rounded-md px-3 py-1.5 text-[12px] font-medium transition-colors"
					:class="
						mode === candidate ? 'bg-background text-foreground shadow-sm' : 'text-muted-foreground'
					"
					@click="mode = candidate"
				>
					{{ t(candidate === 'create' ? 'pptx.share.createSession' : 'pptx.share.joinSession') }}
				</button>
			</div>
			<p class="pptx-vue-share-desc text-[13px] leading-relaxed text-muted-foreground">
				{{ t(mode === 'join' ? 'pptx.share.joinDescription' : 'pptx.share.formDescription') }}
			</p>

			<div v-if="mode === 'join'" class="pptx-vue-share-field flex flex-col gap-1.5">
				<label for="pptx-vue-share-invitation" class="text-[12px] font-medium text-foreground">
					{{ t('pptx.share.invitationLabel') }}
				</label>
				<input
					id="pptx-vue-share-invitation"
					v-model="invitation"
					type="text"
					class="pptx-vue-share-input w-full rounded border border-border bg-background px-3 py-1.5 text-[13px] text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary"
					:placeholder="t('pptx.share.invitationPlaceholder')"
				/>
				<p class="text-[11px] text-muted-foreground">{{ t('pptx.share.invitationHint') }}</p>
			</div>

			<div v-else class="pptx-vue-share-field flex flex-col gap-1.5">
				<label
					for="pptx-vue-share-room"
					class="pptx-vue-share-label text-[12px] font-medium text-foreground"
				>
					{{ t('pptx.share.roomId') }}
				</label>
				<input
					id="pptx-vue-share-room"
					v-model="roomId"
					type="text"
					class="pptx-vue-share-input w-full rounded border border-border bg-background px-3 py-1.5 text-[13px] text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary"
					:placeholder="t('pptx.share.roomIdPlaceholder')"
				/>
			</div>

			<div class="pptx-vue-share-field flex flex-col gap-1.5">
				<label
					for="pptx-vue-share-name"
					class="pptx-vue-share-label text-[12px] font-medium text-foreground"
				>
					{{ t('pptx.share.yourName') }}
				</label>
				<input
					id="pptx-vue-share-name"
					v-model="userName"
					type="text"
					class="pptx-vue-share-input w-full rounded border border-border bg-background px-3 py-1.5 text-[13px] text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary"
					:placeholder="t('pptx.share.yourNamePlaceholder')"
				/>
			</div>

			<div class="pptx-vue-share-field flex flex-col gap-1.5">
				<label
					for="pptx-vue-share-server"
					class="pptx-vue-share-label text-[12px] font-medium text-foreground"
				>
					{{ t('pptx.share.serverUrl') }}
				</label>
				<input
					id="pptx-vue-share-server"
					v-model="serverUrl"
					type="text"
					class="pptx-vue-share-input w-full rounded border border-border bg-background px-3 py-1.5 text-[13px] text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary"
					:placeholder="t('pptx.share.serverPlaceholder')"
				/>
				<p v-if="isPeerToPeer" class="pptx-vue-share-p2p-hint text-[11px] text-muted-foreground">
					{{ t('pptx.share.p2pHint') }}
				</p>
			</div>
		</div>

		<template #footer>
			<button
				type="button"
				class="pptx-vue-share-btn rounded bg-muted px-3 py-1.5 text-[12px] text-foreground transition-colors hover:bg-accent"
				@click="emit('close')"
			>
				{{ active ? t('pptx.share.close') : t('pptx.share.cancel') }}
			</button>
			<button
				v-if="!active"
				type="button"
				class="pptx-vue-share-btn pptx-vue-share-btn-primary rounded bg-primary px-3 py-1.5 text-[12px] text-white transition-colors hover:bg-primary/90 disabled:cursor-not-allowed disabled:opacity-40"
				:disabled="!canStart"
				@click="handleStart"
			>
				{{ t(mode === 'join' ? 'pptx.share.joinSession' : 'pptx.share.startSharing') }}
			</button>
		</template>
	</ModalDialog>
</template>

// packages/angular/src/viewer/share-dialog.component.ts
/**
 * share-dialog.component.ts: Start / stop a real-time collaboration session.
 *
 * Selector: `pptx-share-dialog`
 *
 * Angular port of the Vue `ShareDialog.vue`. Configures and starts a
 * collaboration session (room id, display name, server URL), or stops an
 * active one. Field defaults are supplied by the host via `defaults`. When
 * `active` is `true` the form is replaced by a "Stop sharing" action.
 *
 * Composes {@link ModalDialogComponent}. Pure validation / config-assembly
 * logic lives in `./share-helpers`.
 */

import {
	ChangeDetectionStrategy,
	Component,
	computed,
	effect,
	input,
	output,
	signal,
} from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';

import type { ActiveSessionUserDescriptor, CollaborationConfig } from '../internal/shared';
import { buildCreateCollaborationConfig, buildJoinCollaborationConfig } from '../internal/shared';
import { canUseClipboard } from './broadcast-helpers';
import { ModalDialogComponent } from './modal-dialog.component';
import { seedShareFields } from './share-helpers';
import type { ShareDefaults } from './share-helpers';

@Component({
	selector: 'pptx-share-dialog',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [ModalDialogComponent, TranslatePipe],
	templateUrl: './share-dialog.component.html',
	styleUrl: './share-dialog.component.css',
})
export class ShareDialogComponent {
	/** Whether the dialog is visible. */
	readonly open = input<boolean>(false);

	/** Prefilled values for the form fields. */
	readonly defaults = input<ShareDefaults>();

	/** Whether a collaboration session is currently active (provider constructed). */
	readonly active = input<boolean>(false);

	/** Whether the websocket has reported a `connected` status. */
	readonly connected = input<boolean>(false);

	/** Total connected participants (self + remote peers). */
	readonly userCount = input<number>(0);

	/** Shareable join link surfaced while the session is active. */
	readonly shareUrl = input<string>('');

	/** Whether the active session is peer-to-peer (serverless webrtc). */
	readonly p2p = input<boolean>(false);

	/** Room id of the active session, for the room/server detail line. */
	readonly activeRoomId = input<string>('');

	/** Server URL of the active session (ignored when `p2p` is true). */
	readonly activeServerUrl = input<string>('');

	/** Connected-users list (local user first, then remote peers). */
	readonly users = input<ActiveSessionUserDescriptor[]>([]);

	/** Fired with the assembled config when the user starts sharing. */
	readonly start = output<CollaborationConfig>();

	/** Fired when the user stops an active session. */
	readonly stop = output<void>();

	/** Fired when the dialog is dismissed. */
	readonly close = output<void>();

	readonly roomId = signal('');
	readonly userName = signal('');
	readonly serverUrl = signal('');
	readonly invitation = signal('');
	readonly mode = signal<'create' | 'join'>('create');
	readonly copied = signal(false);

	readonly pendingConfig = computed(() =>
		this.mode() === 'join'
			? buildJoinCollaborationConfig({
					invitation: this.invitation(),
					userName: this.userName(),
					serverUrl: this.serverUrl(),
				})
			: buildCreateCollaborationConfig({
					roomId: this.roomId(),
					userName: this.userName(),
					serverUrl: this.serverUrl(),
				}),
	);
	readonly canStart = computed(() => this.pendingConfig() !== null);

	/** Blank server URL selects the serverless peer-to-peer (webrtc) transport. */
	readonly isP2p = computed(() => this.serverUrl().trim().length === 0);

	readonly canCopy = computed(() =>
		canUseClipboard(typeof navigator !== 'undefined' ? navigator : undefined),
	);

	constructor() {
		// Re-seed the form from defaults whenever the dialog (re)opens.
		effect(() => {
			if (this.open()) {
				const fields = seedShareFields(this.defaults());
				this.roomId.set(fields.roomId);
				this.userName.set(fields.userName);
				this.serverUrl.set(fields.serverUrl);
				this.invitation.set('');
			}
		});
	}

	asValue(event: Event): string {
		return (event.target as HTMLInputElement).value;
	}

	selectAll(event: Event): void {
		(event.target as HTMLInputElement).select();
	}

	onCopyLink(): void {
		const url = this.shareUrl();
		if (!url || !this.canCopy()) {
			return;
		}
		void Promise.resolve(navigator.clipboard.writeText(url)).then(() => {
			this.copied.set(true);
			window.setTimeout(() => {
				this.copied.set(false);
			}, 2000);
			return undefined;
		});
	}

	handleStart(): void {
		const config = this.pendingConfig();
		if (config) {
			this.start.emit(config);
		}
	}

	handleStop(): void {
		this.stop.emit();
	}
}

<pptx-modal-dialog
	[open]="open()"
	[title]="(active() ? 'pptx.share.activeTitle' : 'pptx.toolbar.share') | translate"
	(close)="close.emit()"
>
	@if (active()) {
		<div class="pptx-ng-share-active">
			<div class="pptx-ng-share-status-row">
				<span class="pptx-ng-share-status-dot" [class.is-on]="connected()"></span>
				<span class="pptx-ng-share-status-text">
					{{
						(connected() ? 'pptx.collaboration.status.connected' : 'pptx.share.connecting')
							| translate
					}}
				</span>
				<span class="pptx-ng-share-count">
					{{ userCount() }}
					{{
						(userCount() === 1 ? 'pptx.share.participantSingular' : 'pptx.share.participantPlural')
							| translate
					}}
				</span>
			</div>

			@if (activeRoomId()) {
				<div class="pptx-ng-share-details-row">
					<span>
						{{ 'pptx.share.room' | translate }}
						<code>{{ activeRoomId() }}</code>
					</span>
					<span>
						{{ 'pptx.share.server' | translate }}
						<code>{{ p2p() ? ('pptx.share.p2pServerValue' | translate) : activeServerUrl() }}</code>
					</span>
				</div>
			} @else if (p2p()) {
				<div class="pptx-ng-share-status-row">
					<span class="pptx-ng-share-count" style="margin-left: 0">
						{{ 'pptx.share.p2pServerValue' | translate }}
					</span>
				</div>
			}

			@if (shareUrl()) {
				<div class="pptx-ng-share-field">
					<label class="pptx-ng-share-label">{{ 'pptx.share.shareLink' | translate }}</label>
					<div class="pptx-ng-share-link-row">
						<input
							class="pptx-ng-share-input"
							type="text"
							readonly
							[value]="shareUrl()"
							(focus)="selectAll($event)"
						/>
						<button
							type="button"
							class="pptx-ng-share-btn"
							[disabled]="!canCopy()"
							(click)="onCopyLink()"
						>
							{{ (copied() ? 'pptx.share.copied' : 'pptx.share.copyLinkButton') | translate }}
						</button>
					</div>
					<p class="pptx-ng-share-hint">{{ 'pptx.share.shareHint' | translate }}</p>
				</div>
			}

			@if (users().length > 0) {
				<div class="pptx-ng-share-field">
					<label class="pptx-ng-share-label">{{ 'pptx.share.connectedUsers' | translate }}</label>
					<div class="pptx-ng-share-users">
						@for (user of users(); track user.id) {
							<div class="pptx-ng-share-user">
								<span class="pptx-ng-share-user-avatar" [style.background-color]="user.color">
									@if (user.avatarUrl) {
										<img [src]="user.avatarUrl" alt="" />
									} @else {
										<ng-container>{{ user.initials }}</ng-container>
									}
								</span>
								<span class="pptx-ng-share-user-name">{{ user.name }}</span>
								<span class="pptx-ng-share-user-meta">
									{{
										user.isLocal
											? ('pptx.share.you' | translate)
											: ('pptx.notes.slideN' | translate: { n: user.slideNumber })
									}}
								</span>
							</div>
						}
					</div>
				</div>
			}

			<button type="button" class="pptx-ng-share-stop" (click)="handleStop()">
				{{ 'pptx.share.stopSharing' | translate }}
			</button>
		</div>
	} @else {
		<div class="pptx-ng-share-form">
			<div class="pptx-ng-share-tabs" role="tablist">
				<button
					type="button"
					role="tab"
					[attr.aria-selected]="mode() === 'create'"
					(click)="mode.set('create')"
				>
					{{ 'pptx.share.createSession' | translate }}
				</button>
				<button
					type="button"
					role="tab"
					[attr.aria-selected]="mode() === 'join'"
					(click)="mode.set('join')"
				>
					{{ 'pptx.share.joinSession' | translate }}
				</button>
			</div>
			<p class="pptx-ng-share-desc">
				{{
					(mode() === 'join' ? 'pptx.share.joinDescription' : 'pptx.share.formDescription')
						| translate
				}}
			</p>

			@if (mode() === 'join') {
				<div class="pptx-ng-share-field">
					<label for="pptx-ng-share-invitation" class="pptx-ng-share-label">{{
						'pptx.share.invitationLabel' | translate
					}}</label>
					<input
						id="pptx-ng-share-invitation"
						type="text"
						class="pptx-ng-share-input"
						[attr.placeholder]="'pptx.share.invitationPlaceholder' | translate"
						[value]="invitation()"
						(input)="invitation.set(asValue($event))"
					/>
					<p class="pptx-ng-share-hint">{{ 'pptx.share.invitationHint' | translate }}</p>
				</div>
			} @else {
				<div class="pptx-ng-share-field">
					<label for="pptx-ng-share-room" class="pptx-ng-share-label">{{
						'pptx.share.roomId' | translate
					}}</label>
					<input
						id="pptx-ng-share-room"
						type="text"
						class="pptx-ng-share-input"
						[attr.placeholder]="'pptx.share.roomIdPlaceholder' | translate"
						[value]="roomId()"
						(input)="roomId.set(asValue($event))"
					/>
				</div>
			}

			<div class="pptx-ng-share-field">
				<label for="pptx-ng-share-name" class="pptx-ng-share-label">{{
					'pptx.share.yourName' | translate
				}}</label>
				<input
					id="pptx-ng-share-name"
					type="text"
					class="pptx-ng-share-input"
					[attr.placeholder]="'pptx.share.yourNamePlaceholder' | translate"
					[value]="userName()"
					(input)="userName.set(asValue($event))"
				/>
			</div>

			<div class="pptx-ng-share-field">
				<label for="pptx-ng-share-server" class="pptx-ng-share-label">{{
					'pptx.share.serverUrl' | translate
				}}</label>
				<input
					id="pptx-ng-share-server"
					type="text"
					class="pptx-ng-share-input"
					[attr.placeholder]="'pptx.share.serverPlaceholder' | translate"
					[value]="serverUrl()"
					(input)="serverUrl.set(asValue($event))"
				/>
				@if (isP2p()) {
					<p class="pptx-ng-share-hint">{{ 'pptx.share.p2pHint' | translate }}</p>
				}
			</div>
		</div>
	}

	<div footer>
		<button type="button" class="pptx-ng-share-btn" (click)="close.emit()">
			{{ (active() ? 'pptx.common.close' : 'pptx.common.cancel') | translate }}
		</button>
		@if (!active()) {
			<button
				type="button"
				class="pptx-ng-share-btn pptx-ng-share-btn-primary"
				[disabled]="!canStart()"
				(click)="handleStart()"
			>
				{{ (mode() === 'join' ? 'pptx.share.joinSession' : 'pptx.share.startSharing') | translate }}
			</button>
		}
	</div>
</pptx-modal-dialog>
