// packages/svelte/src/viewer/components/SlideSorterOverlay.svelte
<script lang="ts">
	import ChevronLeft from '@lucide/svelte/icons/chevron-left';
	import ChevronRight from '@lucide/svelte/icons/chevron-right';
	import X from '@lucide/svelte/icons/x';
	import type { PptxSlide } from 'pptx-viewer-core'; import { HIDDEN_SLIDE_DIM_OPACITY, HIDDEN_SLIDE_LABEL_KEY, HIDDEN_SLIDE_SLASH_GRADIENT, hiddenSlideCue, isEditorTextInputTarget, mapSlideSorterKey } from 'pptx-viewer-shared'; import type { CanvasSize } from 'pptx-viewer-shared'; import { useTranslator } from '../../i18n/context'; import SlideStage from './SlideStage.svelte';

	const { slides, canvasSize, mediaDataUrls, current, canEdit = false, onselect, onmove, ondelete, onduplicate, ontogglehidden, onclose }: { slides: PptxSlide[]; canvasSize: CanvasSize; mediaDataUrls: Map<string,string>; current: number; canEdit?: boolean; onselect: (index:number)=>void; onmove:(from:number,to:number)=>void; ondelete?:(index:number)=>void; onduplicate?:(index:number)=>void; ontogglehidden?:(index:number)=>void; onclose:()=>void } = $props(); const t=useTranslator(); const scale=$derived(180/canvasSize.width);

	/**
	 * Right-click context menu (duplicate / hide-show / delete a slide), the
	 * Svelte port of Vue's `SlideSorter.vue` `ContextMenu` wiring. Previously
	 * this overlay had no mouse path to any of the three: delete/duplicate
	 * only fired via keyboard and only ever targeted `current`, never an
	 * arbitrary right-clicked slide, and hide/show had no path here at all.
	 */
	let contextMenu = $state<{ x: number; y: number; index: number } | null>(null);

	function oncontextmenu(event: MouseEvent, index: number): void {
		if (!canEdit) {
			return;
		}
		event.preventDefault();
		contextMenu = { x: event.clientX, y: event.clientY, index };
	}

	function closeContextMenu(): void {
		contextMenu = null;
	}

	function menuDuplicate(): void {
		if (contextMenu) {
			onduplicate?.(contextMenu.index);
		}
		closeContextMenu();
	}

	function menuToggleHidden(): void {
		if (contextMenu) {
			ontogglehidden?.(contextMenu.index);
		}
		closeContextMenu();
	}

	function menuDelete(): void {
		if (contextMenu) {
			ondelete?.(contextMenu.index);
		}
		closeContextMenu();
	}

	// The sorter keymap is shared (`mapSlideSorterKey`), so this overlay answers
	// the same keys as the other four bindings' sorters. Svelte had no sorter
	// keyboard at all before: Escape did not even close it. Only the commands
	// this overlay can perform are dispatched; it has no slide clipboard, no
	// multi-selection and no thumbnail zoom, so those chords reach the host.
	function onkeydown(event: KeyboardEvent): void {
		if (contextMenu) {
			closeContextMenu();
		}
		const { action } = mapSlideSorterKey(event, { canEdit, isTextInputTarget: isEditorTextInputTarget(event.target) });
		if (action === 'close') { event.stopPropagation(); onclose(); return; }
		if (action === 'delete') { event.preventDefault(); ondelete?.(current); return; }
		if (action === 'duplicate') { event.preventDefault(); onduplicate?.(current); }
	}
</script>
<svelte:window {onkeydown} />
<div class="overlay"><header><h2>{t('pptx.view.slideSorter')}</h2><button aria-label={t('pptx.slideSorter.close')} onclick={onclose}><X size={16} aria-hidden="true" /></button></header><main>{#each slides as slide,index}{@const cue = hiddenSlideCue(slide.hidden, 'sorter', index)}<article class:active={current===index} data-pptx-slide-hidden={cue.marker} oncontextmenu={(event) => oncontextmenu(event, index)}><button class="preview" style={cue.hidden ? `opacity: ${HIDDEN_SLIDE_DIM_OPACITY}` : undefined} aria-label={t('pptx.compare.slideNumber', { number: index + 1 })} aria-describedby={cue.labelId} onclick={() => { onselect(index); onclose(); }}><SlideStage {slide} {canvasSize} {mediaDataUrls} {scale} presenting={false} /></button><footer><span class="meta"><span class="num" style={cue.hidden ? `background-image: ${HIDDEN_SLIDE_SLASH_GRADIENT}` : undefined}>{index+1}</span>{#if cue.hidden}<span class="hidden-label" id={cue.labelId}>{t(HIDDEN_SLIDE_LABEL_KEY)}</span>{/if}</span><button aria-label={t('pptx.animations.moveEarlier')} disabled={index===0} onclick={() => onmove(index,index-1)}><ChevronLeft size={14} aria-hidden="true" /></button><button aria-label={t('pptx.animations.moveLater')} disabled={index===slides.length-1} onclick={() => onmove(index,index+1)}><ChevronRight size={14} aria-hidden="true" /></button></footer></article>{/each}</main>{#if contextMenu}{@const hidden = slides[contextMenu.index]?.hidden ?? false}<button class="menu-backdrop" aria-label={t('pptx.overflow.closeMenu')} onclick={closeContextMenu} oncontextmenu={(event) => { event.preventDefault(); closeContextMenu(); }}></button><div class="context-menu" style={`left:${contextMenu.x}px;top:${contextMenu.y}px`} role="menu"><button role="menuitem" onclick={menuDuplicate}>{t('pptx.slideMenu.duplicate')}</button><button role="menuitem" onclick={menuToggleHidden}>{hidden ? t('pptx.slideMenu.show') : t('pptx.slideMenu.hide')}</button><div class="sep"></div><button role="menuitem" class="danger" onclick={menuDelete}>{t('pptx.slideMenu.delete')}</button></div>{/if}</div>
<style>.overlay{position:absolute;inset:0;z-index:70;overflow:auto;background:var(--pptx-background,#11111b)}header{position:sticky;z-index:2;top:0;display:flex;align-items:center;justify-content:space-between;padding:12px 18px;border-bottom:1px solid var(--pptx-border,#3f3f52);background:var(--pptx-card,#1e1e2e)}h2{margin:0;font-size:14px}header button{display:inline-flex;align-items:center;justify-content:center;border:0;background:transparent;color:inherit}main{display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:18px;padding:24px}article{display:grid;justify-content:center;gap:6px;padding:9px;border:2px solid transparent;border-radius:8px;background:var(--pptx-card,#1e1e2e)}article.active{border-color:var(--pptx-primary,#c43b32)}.preview{width:180px;height:calc(180px * 9 / 16);overflow:hidden;border:0;padding:0;background:#fff;text-align:left}article footer{display:flex;align-items:center;gap:5px;font-size:11px}article footer .meta{display:flex;flex:1;align-items:center;gap:5px}article footer .num{display:inline-block;padding:0 3px}article footer .hidden-label{font-size:9px;text-transform:uppercase;letter-spacing:.05em;color:var(--pptx-muted-foreground,#94a3b8)}article footer button{display:inline-flex;align-items:center;justify-content:center;border:1px solid var(--pptx-border,#3f3f52);border-radius:4px;background:var(--pptx-muted,#2a2a3d);color:inherit}article footer button:disabled{opacity:.4}.menu-backdrop{position:fixed;inset:0;z-index:79;border:0;padding:0;background:transparent;cursor:default}.context-menu{position:fixed;z-index:80;min-width:160px;padding:4px;border:1px solid var(--pptx-border,#3f3f52);border-radius:6px;background:var(--pptx-card,#1e1e2e);box-shadow:0 8px 24px rgba(0,0,0,.4)}.context-menu button{display:block;width:100%;padding:6px 10px;border:0;border-radius:4px;background:transparent;color:inherit;text-align:left;font-size:12px;cursor:pointer}.context-menu button:hover{background:var(--pptx-muted,#2a2a3d)}.context-menu button.danger{color:#f87171}.context-menu .sep{margin:4px 2px;border-top:1px solid var(--pptx-border,#3f3f52)}</style>

// packages/angular/src/viewer/slide-sorter-overlay.component.ts
import { NgStyle } from '@angular/common';
import {
	ChangeDetectionStrategy,
	Component,
	HostListener,
	computed,
	input,
	output,
	signal,
} from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import type { PptxSlide } from 'pptx-viewer-core';

import {
	HIDDEN_SLIDE_LABEL_KEY,
	HIDDEN_SLIDE_SLASH_GRADIENT,
	hiddenSlideCue,
	isEditorTextInputTarget,
	mapSlideSorterKey,
} from '../internal/shared';
import type { CanvasSize, HiddenSlideCue } from '../internal/shared';
import { SlideCanvasComponent } from './slide-canvas.component';
import { thumbnailHeight, thumbnailZoom } from './slide-sorter-overlay-helpers';

/** Pixel width of each thumbnail cell (the clipping box, not the canvas). */
const THUMB_W = 200;

/** Gap between grid cells in pixels. */
const GRID_GAP = 16;

/**
 * SlideSorterOverlayComponent: Angular port of the React `SlideSorterOverlay`.
 *
 * Renders a fixed full-screen modal overlay containing a responsive grid of
 * scaled slide previews. Clicking a thumbnail emits `select(index)`; pressing
 * Escape or clicking the ✕ button emits `closed`. Right-clicking a thumbnail
 * (when `canEdit`) opens a small context menu (Duplicate / Hide-Show /
 * Delete), matching React's `SorterContextMenu` and Vue's `ContextMenu`
 * wiring: this overlay previously had no mouse path to any of the three, and
 * no path to hide/show at all (mouse or keyboard).
 *
 * Viewer-first scope: no drag-reorder, no section grouping.
 *
 * Usage:
 * ```html
 * <pptx-slide-sorter-overlay
 *   [slides]="slides()"
 *   [canvasSize]="canvasSize()"
 *   [mediaDataUrls]="mediaDataUrls()"
 *   [activeIndex]="activeSlideIndex()"
 *   (select)="goTo($event)"
 *   (closed)="showSorter.set(false)"
 * />
 * ```
 */
@Component({
	selector: 'pptx-slide-sorter-overlay',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [NgStyle, SlideCanvasComponent, TranslatePipe],
	templateUrl: './slide-sorter-overlay.component.html',
	styleUrl: './slide-sorter-overlay.component.css',
})
export class SlideSorterOverlayComponent {
	/** Full list of slides to display. */
	readonly slides = input.required<PptxSlide[]>();

	/** Natural (100 %) canvas dimensions, passed through to SlideCanvasComponent. */
	readonly canvasSize = input.required<CanvasSize>();

	/** Media asset lookup table, forwarded to each SlideCanvasComponent. */
	readonly mediaDataUrls = input<Map<string, string>>(new Map());

	/** Zero-based index of the currently active slide (highlighted in blue). */
	readonly activeIndex = input<number>(0);

	/** Whether the host allows edits; gates the deck-writing shortcuts. */
	readonly canEdit = input<boolean>(false);

	/** Emits the zero-based index of the thumbnail the user clicked. */
	readonly select = output<number>();

	/** Emits when the user closes the overlay (✕ button or Escape key). */
	readonly closed = output<void>();

	/** Delete the active slide (Delete / Backspace). */
	readonly deleteSlide = output<number>();

	/** Duplicate the active slide (Ctrl/Cmd+D). */
	readonly duplicateSlide = output<number>();

	/** Toggle the hidden flag on a slide (context-menu only, no keyboard chord). */
	readonly toggleHiddenSlide = output<number>();

	// -------------------------------------------------------------------------
	// Derived display values
	// -------------------------------------------------------------------------

	/** Zoom level that fits the full canvas width into THUMB_W pixels. */
	readonly thumbZoom = computed(() => thumbnailZoom(this.canvasSize().width, THUMB_W));

	/** Pixel height of the clipping box (aspect-correct). */
	readonly thumbH = computed(() =>
		thumbnailHeight(this.canvasSize().width, this.canvasSize().height, THUMB_W),
	);

	/** ngStyle object for the thumbnail clipping box. */
	readonly clipStyle = computed<Record<string, string>>(() => ({
		width: `${THUMB_W}px`,
		height: `${this.thumbH()}px`,
	}));

	/** ngStyle object for the grid: responsive auto-fill columns. */
	readonly gridStyle = computed<Record<string, string>>(() => ({
		'grid-template-columns': `repeat(auto-fill, minmax(${THUMB_W + GRID_GAP * 2 + 4}px, 1fr))`,
	}));

	// -------------------------------------------------------------------------
	// Event handlers
	// -------------------------------------------------------------------------

	/**
	 * Keyboard handler, resolved by the shared sorter keymap.
	 *
	 * This used to test for `Escape` and nothing else, so the sorter's Delete and
	 * Ctrl+D were dead in Angular alone. Only the commands this overlay can
	 * perform are dispatched: there is no slide clipboard, no multi-selection and
	 * no thumbnail zoom here, so those chords are left to the host instead of
	 * being swallowed by a branch that would do nothing.
	 */
	@HostListener('document:keydown', ['$event'])
	onKeydown(event: KeyboardEvent): void {
		if (this.contextMenu()) {
			this.closeContextMenu();
		}
		const { action } = mapSlideSorterKey(event, {
			canEdit: this.canEdit(),
			isTextInputTarget: isEditorTextInputTarget(event.target),
		});
		if (action === 'close') {
			event.preventDefault();
			this.closed.emit();
			return;
		}
		if (action === 'delete') {
			event.preventDefault();
			this.deleteSlide.emit(this.activeIndex());
			return;
		}
		if (action === 'duplicate') {
			event.preventDefault();
			this.duplicateSlide.emit(this.activeIndex());
		}
	}

	/** Clicking the backdrop (outside the panel) closes the overlay. */
	onBackdropClick(event: MouseEvent): void {
		// Only close when the click target IS the backdrop element itself.
		if (event.target === event.currentTarget) {
			this.closed.emit();
		}
	}

	/** Clicking a thumbnail selects the slide. */
	onThumbClick(index: number): void {
		this.select.emit(index);
	}

	// -------------------------------------------------------------------------
	// Context menu (right-click a thumbnail)
	// -------------------------------------------------------------------------

	/** Open state + screen position of the context menu, or null when closed. */
	readonly contextMenu = signal<{ x: number; y: number; index: number } | null>(null);

	/**
	 * Right-clicking a thumbnail opens the menu for THAT slide.
	 *
	 * Deliberately does not also emit `select`: the host's `select` handler
	 * closes the whole overlay (it navigates the canvas and dismisses the
	 * sorter), so doing that here would tear down the menu before a single
	 * mouse action against it was reachable.
	 */
	onThumbContextMenu(event: MouseEvent, index: number): void {
		if (!this.canEdit()) {
			return;
		}
		event.preventDefault();
		this.contextMenu.set({ x: event.clientX, y: event.clientY, index });
	}

	closeContextMenu(): void {
		this.contextMenu.set(null);
	}

	/** Whether the context menu's target slide is currently hidden. */
	contextMenuTargetHidden(): boolean {
		const menu = this.contextMenu();
		return menu ? (this.slides()[menu.index]?.hidden ?? false) : false;
	}

	menuDuplicate(): void {
		const menu = this.contextMenu();
		if (menu) {
			this.duplicateSlide.emit(menu.index);
		}
		this.closeContextMenu();
	}

	menuToggleHidden(): void {
		const menu = this.contextMenu();
		if (menu) {
			this.toggleHiddenSlide.emit(menu.index);
		}
		this.closeContextMenu();
	}

	menuDelete(): void {
		const menu = this.contextMenu();
		if (menu) {
			this.deleteSlide.emit(menu.index);
		}
		this.closeContextMenu();
	}

	// -------------------------------------------------------------------------
	// Utilities
	// -------------------------------------------------------------------------

	/** Returns true when a slide has been marked as hidden in the presentation. */
	isHiddenSlide(slide: PptxSlide): boolean {
		// PptxSlide carries a `hidden` boolean when the slide is set to hidden in
		// the OpenXML package. Cast via unknown to avoid accessing a field that
		// may not exist on all versions of the core type.
		const s = slide as unknown as Record<string, unknown>;
		return s['hidden'] === true;
	}

	/** Dictionary key for the word shown and announced on a hidden slide's cell. */
	readonly hiddenLabelKey = HIDDEN_SLIDE_LABEL_KEY;

	/** Shared slash mark, bound inline so a stylesheet copy cannot drift. */
	readonly slashGradient = HIDDEN_SLIDE_SLASH_GRADIENT;

	/**
	 * The shared cue for one cell. The dim already came off `.is-hidden`, but
	 * opacity is a colour-only signal and said nothing to a screen reader, so
	 * this adds the number slash, the word, and the neutral marker attribute.
	 */
	hiddenCue(slide: PptxSlide, index: number): HiddenSlideCue {
		return hiddenSlideCue(this.isHiddenSlide(slide), 'sorter', index);
	}
}

<!-- Backdrop -->
<div class="pptx-ng-sorter-backdrop" (click)="onBackdropClick($event)">
	<!-- Modal panel -->
	<div class="pptx-ng-sorter-panel" (click)="$event.stopPropagation()">
		<!-- Header -->
		<header class="pptx-ng-sorter-header">
			<h2 class="pptx-ng-sorter-title">{{ 'pptx.slideSorter.title' | translate }}</h2>
			<span class="pptx-ng-sorter-count">{{
				'pptx.slideSorter.slideCount' | translate: { count: slides().length }
			}}</span>
			<button
				type="button"
				class="pptx-ng-sorter-close"
				[attr.aria-label]="'pptx.slideSorter.close' | translate"
				(click)="closed.emit()"
			>
				<svg
					xmlns="http://www.w3.org/2000/svg"
					width="16"
					height="16"
					viewBox="0 0 24 24"
					fill="none"
					stroke="currentColor"
					stroke-width="2"
					stroke-linecap="round"
					stroke-linejoin="round"
					aria-hidden="true"
				>
					<line x1="18" y1="6" x2="6" y2="18" />
					<line x1="6" y1="6" x2="18" y2="18" />
				</svg>
			</button>
		</header>

		<!-- Scrollable grid -->
		<div class="pptx-ng-sorter-grid-scroll">
			<div class="pptx-ng-sorter-grid" [ngStyle]="gridStyle()">
				@for (slide of slides(); track slide.id; let i = $index) {
					@let hidden = hiddenCue(slide, i);
					<button
						type="button"
						class="pptx-ng-sorter-cell"
						[class.is-active]="i === activeIndex()"
						[class.is-hidden]="hidden.hidden"
						[attr.data-pptx-slide-hidden]="hidden.marker ?? null"
						[attr.aria-label]="'pptx.notes.slideN' | translate: { n: i + 1 }"
						[attr.aria-describedby]="hidden.labelId ?? null"
						[attr.aria-current]="i === activeIndex() ? 'true' : null"
						(click)="onThumbClick(i)"
						(contextmenu)="onThumbContextMenu($event, i)"
					>
						<!-- Thumbnail clipping wrapper -->
						<div class="pptx-ng-sorter-thumb-clip" [ngStyle]="clipStyle()">
							<pptx-slide-canvas
								[slide]="slide"
								[canvasSize]="canvasSize()"
								[mediaDataUrls]="mediaDataUrls()"
								[zoom]="thumbZoom()"
								[autoFit]="false"
								[interactive]="false"
								[exposeElementIds]="false"
							/>
						</div>
						<!-- Slide number badge, struck through with the shared diagonal
						     slash when hidden (PowerPoint's own cue). -->
						<span
							class="pptx-ng-sorter-index"
							aria-hidden="true"
							[style.background-image]="hidden.hidden ? slashGradient : null"
							>{{ i + 1 }}</span
						>
						@if (hidden.hidden) {
							<span class="pptx-ng-sorter-hidden" [id]="hidden.labelId">{{
								hiddenLabelKey | translate
							}}</span>
						}
					</button>
				}
			</div>
		</div>
	</div>

	@if (contextMenu(); as menu) {
		<button
			type="button"
			class="pptx-ng-sorter-menu-backdrop"
			[attr.aria-label]="'pptx.overflow.closeMenu' | translate"
			(click)="closeContextMenu()"
			(contextmenu)="$event.preventDefault(); closeContextMenu()"
		></button>
		<div
			class="pptx-ng-sorter-context-menu"
			[style.left.px]="menu.x"
			[style.top.px]="menu.y"
			role="menu"
		>
			<button type="button" role="menuitem" (click)="menuDuplicate()">
				{{ 'pptx.slideMenu.duplicate' | translate }}
			</button>
			<button type="button" role="menuitem" (click)="menuToggleHidden()">
				{{
					(contextMenuTargetHidden() ? 'pptx.slideMenu.show' : 'pptx.slideMenu.hide') | translate
				}}
			</button>
			<div class="pptx-ng-sorter-context-menu-sep"></div>
			<button type="button" role="menuitem" class="is-danger" (click)="menuDelete()">
				{{ 'pptx.slideMenu.delete' | translate }}
			</button>
		</div>
	}
</div>
