// packages/react/src/viewer/components/toolbar/TitleBar.tsx
import {
	filterCommands,
	resolveTitleBarStatusKey,
	TITLE_BAR_CLASSES as TB,
	TITLE_BAR_DEFAULT_FILE_KEY,
} from 'pptx-viewer-shared';
import type { CommandSearchEntry, ToolbarActionId } from 'pptx-viewer-shared';
import React, { useCallback, useEffect, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { LuRedo, LuSave, LuSearch, LuUndo } from 'react-icons/lu';

import type { AutosaveStatus } from '../../hooks/useAutosave';
import { useToolbarVisibility } from '../../hooks/useToolbarVisibility';
import type { ViewerMode } from '../../types';
import { cn } from '../../utils';
import { useViewerOptionsContext } from '../viewer-options-context';
import { TitleBarQuickExtras } from './TitleBarQuickExtras';

export interface TitleBarProps {
	mode: ViewerMode;
	canEdit: boolean;
	/** Display name of the open document (host-supplied). */
	fileName?: string;
	isDirty: boolean;
	autosaveStatus?: AutosaveStatus;
	autosaveEnabled: boolean;
	onToggleAutosave: () => void;
	canUndo: boolean;
	canRedo: boolean;
	undoLabel?: string | null;
	redoLabel?: string | null;
	onUndo: () => void;
	onRedo: () => void;
	/** Quick-access save (downloads the .pptx). */
	onSave?: () => void;
	findReplaceOpen: boolean;
	onToggleFindReplace: () => void;
	/** Dispatch a command from the search palette. */
	onCommandSearch?: (command: string) => void;
	/** Host-supplied list of toolbar buttons/ribbon tabs to hide. */
	hiddenActions?: readonly ToolbarActionId[];
	/**
	 * Run a Quick Access command that is not one of the dedicated
	 * Save/Undo/Redo buttons (`presentFromStart`, `print`, ...), by catalog id.
	 */
	onQuickCommand?: (id: string) => void;
}

/**
 * PowerPoint-style title bar: AutoSave toggle, quick-access Save/Undo/Redo,
 * file name + save-location status, and a centred search box that opens the
 * Find & Replace panel. Rendered above (outside) the ribbon toolbar.
 */
export function TitleBar(p: TitleBarProps): React.ReactElement {
	const { t } = useTranslation();
	const editing = (p.mode === 'edit' || p.mode === 'master') && p.canEdit;
	const { isHidden } = useToolbarVisibility(p.hiddenActions);
	const quickAccess = useViewerOptionsContext().quickAccess;

	const [searchQuery, setSearchQuery] = useState('');
	const [searchFocused, setSearchFocused] = useState(false);
	const searchRef = useRef<HTMLDivElement>(null);

	const commandResults = filterCommands(searchQuery, t);

	const handleCommandSelect = useCallback(
		(entry: CommandSearchEntry) => {
			p.onCommandSearch?.(entry.command);
			setSearchQuery('');
			setSearchFocused(false);
		},
		[p],
	);

	const handleSearchKeyDown = useCallback(
		(e: React.KeyboardEvent) => {
			if (e.key === 'Enter' && searchQuery.trim()) {
				if (commandResults.length > 0) {
					handleCommandSelect(commandResults[0]);
				} else {
					p.onToggleFindReplace();
					setSearchFocused(false);
				}
			} else if (e.key === 'Escape') {
				setSearchQuery('');
				setSearchFocused(false);
			}
		},
		[searchQuery, commandResults, handleCommandSelect, p],
	);

	useEffect(() => {
		const handler = (e: MouseEvent) => {
			if (searchRef.current && !searchRef.current.contains(e.target as Node)) {
				setSearchFocused(false);
			}
		};
		document.addEventListener('mousedown', handler);
		return () => document.removeEventListener('mousedown', handler);
	}, []);

	const statusKey = resolveTitleBarStatusKey({
		autosaveState: p.autosaveStatus?.state ?? 'idle',
		isDirty: p.isDirty,
		autosaveEnabled: p.autosaveEnabled,
		disabledReason: p.autosaveStatus?.state === 'disabled' ? p.autosaveStatus.reason : undefined,
	});

	return (
		<div className={TB.container} data-pptx-title-bar=''>
			<span className={TB.logo} aria-hidden='true'>
				P
			</span>

			{editing && (
				<>
					<span className={TB.autosaveGroup}>
						<span className={TB.autosaveLabel}>{t('pptx.titleBar.autoSave')}</span>
						<button
							type='button'
							role='switch'
							aria-checked={p.autosaveEnabled}
							onClick={p.onToggleAutosave}
							className={cn(
								TB.toggleTrack,
								p.autosaveEnabled ? TB.toggleTrackOn : TB.toggleTrackOff,
							)}
							title={t('pptx.titleBar.toggleAutoSave')}
							aria-label={t('pptx.titleBar.toggleAutoSave')}
						>
							<span
								className={cn(
									TB.toggleKnob,
									p.autosaveEnabled ? TB.toggleKnobOn : TB.toggleKnobOff,
								)}
							/>
						</button>
						<span className={TB.autosaveLabel}>
							{t(p.autosaveEnabled ? 'pptx.titleBar.autoSaveOn' : 'pptx.titleBar.autoSaveOff')}
						</span>
					</span>

					<div className={TB.separator} />

					{p.onSave && (
						<button
							type='button'
							onClick={p.onSave}
							className={TB.quickButton}
							title={t('pptx.titleBar.save')}
							aria-label={t('pptx.titleBar.save')}
						>
							<LuSave className='w-3.5 h-3.5' />
						</button>
					)}
					{!isHidden('undo') && (
						<button
							type='button'
							onClick={p.onUndo}
							disabled={!p.canUndo}
							className={TB.quickButton}
							title={
								p.undoLabel
									? t('pptx.toolbar.undoAction', { action: p.undoLabel })
									: t('pptx.toolbar.undo')
							}
							aria-label={t('pptx.toolbar.undo')}
						>
							<LuUndo className='w-3.5 h-3.5' />
						</button>
					)}
					{!isHidden('redo') && (
						<button
							type='button'
							onClick={p.onRedo}
							disabled={!p.canRedo}
							className={TB.quickButton}
							title={
								p.redoLabel
									? t('pptx.toolbar.redoAction', { action: p.redoLabel })
									: t('pptx.toolbar.redo')
							}
							aria-label={t('pptx.toolbar.redo')}
						>
							<LuRedo className='w-3.5 h-3.5' />
						</button>
					)}
					{/*
					 * Everything else File > Options > Quick Access Toolbar asks for, in
					 * configured order. Without this the strip was hardcoded to the three
					 * buttons above and silently ignored the options model, so it showed
					 * three commands where the shared default (and Angular) had four.
					 *
					 * Suppressed here when position is "below": the same commands then
					 * render in a row under the ribbon (`Toolbar`'s own
					 * `TitleBarQuickExtras` usage) instead, so they show in exactly one
					 * place. The dedicated Save/Undo/Redo trio above always stays here,
					 * matching Angular's `belowRibbonQuickAccess`.
					 */}
					{quickAccess.position !== 'below' && (
						<TitleBarQuickExtras quickAccess={quickAccess} onCommand={p.onQuickCommand} />
					)}

					<div className={TB.separator} />
				</>
			)}

			<span className={TB.fileGroup}>
				<span className={TB.fileName}>{p.fileName || t(TITLE_BAR_DEFAULT_FILE_KEY)}</span>
				{editing && (
					<>
						<span className={TB.statusDot} aria-hidden='true'>
							&bull;
						</span>
						<span
							className={cn(
								TB.statusText,
								p.autosaveStatus?.state === 'error' && p.autosaveEnabled && TB.statusError,
								p.autosaveStatus?.state === 'saving' && p.autosaveEnabled && TB.statusSaving,
							)}
						>
							{t(statusKey)}
						</span>
					</>
				)}
			</span>

			<span className={TB.searchWrap}>
				{(p.mode === 'edit' || p.mode === 'master') && (
					<div ref={searchRef} className='relative w-full max-w-md'>
						<div
							className={cn(
								TB.searchBox,
								(searchFocused || p.findReplaceOpen) && 'text-foreground bg-background',
							)}
						>
							<LuSearch className={TB.searchIcon} />
							<input
								type='text'
								value={searchQuery}
								onChange={(e) => setSearchQuery(e.target.value)}
								onFocus={() => setSearchFocused(true)}
								onKeyDown={handleSearchKeyDown}
								placeholder={t('pptx.titleBar.searchPlaceholder')}
								className='flex-1 bg-transparent text-[11px] outline-none placeholder:text-muted-foreground/60'
								aria-label={t('pptx.titleBar.search')}
							/>
						</div>
						{searchFocused && searchQuery.trim() && (
							<div className='absolute left-0 right-0 top-full z-50 mt-1 rounded-lg border border-border bg-popover shadow-xl max-h-64 overflow-y-auto'>
								{commandResults.length > 0 ? (
									<>
										<div className='px-3 py-1.5 text-[10px] font-semibold text-muted-foreground uppercase tracking-wider'>
											{t('pptx.titleBar.searchCommands')}
										</div>
										{commandResults.slice(0, 8).map((entry) => (
											<button
												key={entry.command}
												type='button'
												className='flex w-full items-center gap-2 px-3 py-1.5 text-xs text-foreground hover:bg-accent transition-colors'
												onMouseDown={() => handleCommandSelect(entry)}
											>
												<span className='truncate'>{t(entry.labelKey)}</span>
												<span className='ml-auto text-[10px] text-muted-foreground capitalize'>
													{entry.category}
												</span>
											</button>
										))}
									</>
								) : (
									<div className='px-3 py-2 text-xs text-muted-foreground'>
										{t('pptx.titleBar.searchNoResults')}
									</div>
								)}
								<div className='border-t border-border/60'>
									<button
										type='button'
										className='flex w-full items-center gap-2 px-3 py-1.5 text-xs text-foreground hover:bg-accent transition-colors'
										onMouseDown={() => {
											p.onToggleFindReplace();
											setSearchFocused(false);
											setSearchQuery('');
										}}
									>
										<LuSearch className='w-3 h-3 shrink-0' />
										<span>
											{t('pptx.titleBar.searchContent')} &ldquo;{searchQuery}&rdquo;
										</span>
									</button>
								</div>
							</div>
						)}
					</div>
				)}
			</span>

			{/* Right block mirrors the left visually; kept minimal. */}
			<span className={TB.rightSpacer} />
		</div>
	);
}

// packages/angular/src/viewer/title-bar.component.ts
/**
 * title-bar.component.ts: PowerPoint-style top chrome row for the Angular
 * editor, at parity with React's `viewer/components/toolbar/TitleBar.tsx`.
 *
 * Renders (left to right): the square "P" app mark, an AutoSave label + switch
 * toggle + On/Off text, quick-access Save/Undo/Redo icon buttons, the open
 * document's name + a save-location status (resolved via the shared
 * {@link resolveTitleBarStatusKey}), and a centred search button that opens
 * Find & Replace. Rendered ABOVE and OUTSIDE the ribbon's `role="toolbar"`
 * container so the toolbar height stays measurable for the e2e parity spec.
 * Purely presentational + `OnPush`: every action is an `output()` the
 * {@link PowerPointViewerComponent} already has handlers for. Class tokens come
 * verbatim from the shared {@link TITLE_BAR_CLASSES} so the three bindings stay
 * pixel-identical. The host is a plain block (no `display:contents`) so the row
 * renders as one 36px flex strip.
 *
 * The search box and its command palette live in
 * {@link TitleBarSearchComponent}: they are the only stateful part of this row,
 * and keeping them here pushed the file past the repo's 300 LOC ceiling.
 */
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';
import { LucideRedo, LucideSave, LucideUndo } from '@lucide/angular';
import { TranslatePipe } from '@ngx-translate/core';

import {
	DEFAULT_VIEWER_OPTIONS,
	extraQuickAccessCommands,
	resolveTitleBarStatusKey,
	TITLE_BAR_CLASSES,
	TITLE_BAR_DEFAULT_FILE_KEY,
} from '../internal/shared';
import type { ToolbarActionId, ViewerQuickAccessOptions } from '../internal/shared';
import type { AutosaveStatus } from './autosave.service';
import { QuickAccessStripComponent } from './quick-access-strip.component';
import { TitleBarSearchComponent } from './title-bar-search.component';
import { toolbarVisibility } from './toolbar-visibility';

/**
 * Narrow the Quick Access options to the commands rendered BEYOND the dedicated
 * Save/Undo/Redo buttons (which keep their own gating + labels), so the
 * remainder can be handed to {@link QuickAccessStripComponent} as-is.
 *
 * Exported (and pure) because this package has no TestBed: the template's
 * `@if (extraQat().commandIds.length > 0)` is exactly this list, so asserting
 * it asserts what the strip renders.
 */
export function narrowToExtraQuickAccess(
	options: ViewerQuickAccessOptions,
): ViewerQuickAccessOptions {
	return {
		...options,
		commandIds: options.visible
			? extraQuickAccessCommands(options.commandIds).map((entry) => entry.id)
			: [],
	};
}

/**
 * The below-ribbon strip's options, or `null` when nothing renders there:
 * hidden, position `above`, or no commands beyond the dedicated trio.
 *
 * Single source of truth for BOTH sides of the "below the ribbon" placement:
 * {@link PowerPointViewerComponent} renders the strip precisely when this is
 * non-null, and this component's own inline strip below suppresses itself
 * under the identical condition, so the two can never disagree about where
 * the configured commands show up.
 */
export function resolveBelowRibbonQuickAccess(
	options: ViewerQuickAccessOptions,
): ViewerQuickAccessOptions | null {
	if (!options.visible || options.position !== 'below') {
		return null;
	}
	const narrowed = narrowToExtraQuickAccess(options);
	return narrowed.commandIds.length > 0 ? narrowed : null;
}

@Component({
	selector: 'pptx-title-bar',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [
		NgClass,
		TranslatePipe,
		LucideSave,
		LucideUndo,
		LucideRedo,
		QuickAccessStripComponent,
		TitleBarSearchComponent,
	],
	template: `
		<div [class]="tb.container" data-pptx-title-bar>
			<span [class]="tb.logo" aria-hidden="true">P</span>

			@if (canEdit()) {
				<span [class]="tb.autosaveGroup">
					<span [class]="tb.autosaveLabel">{{ 'pptx.titleBar.autoSave' | translate }}</span>
					<button
						type="button"
						role="switch"
						[attr.aria-checked]="autosaveEnabled()"
						[class]="tb.toggleTrack"
						[ngClass]="autosaveEnabled() ? tb.toggleTrackOn : tb.toggleTrackOff"
						[title]="'pptx.titleBar.toggleAutoSave' | translate"
						[attr.aria-label]="'pptx.titleBar.toggleAutoSave' | translate"
						(click)="toggleAutosave.emit()"
					>
						<span
							[class]="tb.toggleKnob"
							[ngClass]="autosaveEnabled() ? tb.toggleKnobOn : tb.toggleKnobOff"
						></span>
					</button>
					<span [class]="tb.autosaveLabel">{{
						(autosaveEnabled() ? 'pptx.titleBar.autoSaveOn' : 'pptx.titleBar.autoSaveOff')
							| translate
					}}</span>
				</span>

				<div [class]="tb.separator"></div>

				@if (qat().visible) {
					<button
						type="button"
						[class]="tb.quickButton"
						[title]="'pptx.titleBar.save' | translate"
						[attr.aria-label]="'pptx.titleBar.save' | translate"
						(click)="save.emit()"
					>
						<svg lucideSave class="h-3.5 w-3.5"></svg>
					</button>
					@if (!toolbar.isHidden('undo')) {
						<button
							type="button"
							[class]="tb.quickButton"
							[disabled]="!canUndo()"
							[title]="
								undoLabel()
									? ('pptx.toolbar.undoAction' | translate: { action: undoLabel() })
									: ('pptx.toolbar.undo' | translate)
							"
							[attr.aria-label]="'pptx.toolbar.undo' | translate"
							(click)="undo.emit()"
						>
							<svg lucideUndo class="h-3.5 w-3.5"></svg>
						</button>
					}
					@if (!toolbar.isHidden('redo')) {
						<button
							type="button"
							[class]="tb.quickButton"
							[disabled]="!canRedo()"
							[title]="
								redoLabel()
									? ('pptx.toolbar.redoAction' | translate: { action: redoLabel() })
									: ('pptx.toolbar.redo' | translate)
							"
							[attr.aria-label]="'pptx.toolbar.redo' | translate"
							(click)="redo.emit()"
						>
							<svg lucideRedo class="h-3.5 w-3.5"></svg>
						</button>
					}
					@if (extraQat().commandIds.length > 0 && !belowRibbonActive()) {
						<pptx-quick-access-strip
							[quickAccess]="extraQat()"
							(command)="onQuickCommand($event)"
						/>
					}
				}

				<div [class]="tb.separator"></div>
			}

			<span [class]="tb.fileGroup">
				<span [class]="tb.fileName">{{ fileName() || (defaultFileKey | translate) }}</span>
				@if (canEdit()) {
					<span [class]="tb.statusDot" aria-hidden="true">&bull;</span>
					<span [class]="tb.statusText" [ngClass]="statusStateClass()">{{
						statusKey() | translate
					}}</span>
				}
			</span>

			<span [class]="tb.searchWrap">
				@if (canEdit()) {
					<pptx-title-bar-search
						[findReplaceOpen]="findReplaceOpen()"
						(commandSearch)="commandSearch.emit($event)"
						(toggleFindReplace)="toggleFindReplace.emit()"
					/>
				}
			</span>

			<span [class]="tb.rightSpacer"></span>
		</div>
	`,
})
export class TitleBarComponent {
	/** Whether the deck is editable (gates the autosave/quick-access/search chrome). */
	readonly canEdit = input<boolean>(false);
	/** Display name of the open document (host-supplied). */
	readonly fileName = input<string | undefined>(undefined);
	/** Whether the document has unsaved changes. */
	readonly isDirty = input<boolean>(false);
	/** Current autosave engine status (drives the save-location text). */
	readonly autosaveStatus = input<AutosaveStatus | undefined>(undefined);
	/** Whether the AutoSave toggle is on. */
	readonly autosaveEnabled = input<boolean>(true);
	readonly canUndo = input<boolean>(false);
	readonly canRedo = input<boolean>(false);
	readonly undoLabel = input<string | undefined>(undefined);
	readonly redoLabel = input<string | undefined>(undefined);
	/** Whether the Find & Replace panel is open (search-button active state). */
	readonly findReplaceOpen = input<boolean>(false);
	/** Toolbar buttons the host wants hidden (gates Undo/Redo independently). */
	readonly hiddenActions = input<ToolbarActionId[]>([]);
	/** Live Quick Access Toolbar options (File > Options > Quick Access). */
	readonly quickAccess = input<ViewerQuickAccessOptions | null>(null);

	readonly toggleAutosave = output<void>();
	readonly save = output<void>();
	readonly undo = output<void>();
	readonly redo = output<void>();
	/** A configured Quick Access command was pressed (catalog id). */
	readonly quickCommand = output<string>();
	readonly toggleFindReplace = output<void>();
	readonly commandSearch = output<string>();

	protected readonly tb = TITLE_BAR_CLASSES;
	protected readonly defaultFileKey = TITLE_BAR_DEFAULT_FILE_KEY;
	protected readonly toolbar = toolbarVisibility(this.hiddenActions);

	/** Resolved Quick Access options (host-supplied, or the default trio+). */
	protected readonly qat = computed<ViewerQuickAccessOptions>(
		() => this.quickAccess() ?? DEFAULT_VIEWER_OPTIONS.quickAccess,
	);

	/**
	 * The Quick Access options narrowed to the commands beyond the dedicated
	 * save/undo/redo buttons. Reusing {@link QuickAccessStripComponent} for the
	 * remainder means those buttons carry real icons rather than a letter glyph.
	 */
	protected readonly extraQat = computed(() => narrowToExtraQuickAccess(this.qat()));

	/**
	 * Whether the below-ribbon strip is the one rendering the configured extra
	 * commands right now, so this component's OWN inline strip stands down
	 * instead of showing the same commands twice.
	 */
	protected readonly belowRibbonActive = computed(
		() => resolveBelowRibbonQuickAccess(this.qat()) !== null,
	);

	/**
	 * Route a Quick Access press: keep the dedicated save/undo/redo outputs
	 * (existing host wiring, `hiddenActions` gating) and forward everything
	 * else through the generic {@link quickCommand} output.
	 */
	protected onQuickCommand(id: string): void {
		if (id === 'save') {
			this.save.emit();
		} else if (id === 'undo' && !this.toolbar.isHidden('undo')) {
			this.undo.emit();
		} else if (id === 'redo' && !this.toolbar.isHidden('redo')) {
			this.redo.emit();
		} else if (id !== 'undo' && id !== 'redo') {
			this.quickCommand.emit(id);
		}
	}

	/** The i18n key for the save-location status text (next to the file name). */
	protected readonly statusKey = computed(() => {
		const status = this.autosaveStatus();
		return resolveTitleBarStatusKey({
			autosaveState: status?.state ?? 'idle',
			isDirty: this.isDirty(),
			autosaveEnabled: this.autosaveEnabled(),
			disabledReason: status?.state === 'disabled' ? status.reason : undefined,
		});
	});

	/** Colour override for the status text on saving/error (when autosave is on). */
	protected readonly statusStateClass = computed(() => {
		const state = this.autosaveStatus()?.state;
		if (!this.autosaveEnabled()) {
			return '';
		}
		if (state === 'error') {
			return this.tb.statusError;
		}
		if (state === 'saving') {
			return this.tb.statusSaving;
		}
		return '';
	});
}
