// packages/react/src/viewer/components/CompatibilityToasts.tsx
import type { CompatibilityWarningToast } from 'pptx-viewer-shared';
import { useTranslation } from 'react-i18next';

/**
 * CompatibilityToasts: load-diagnostic toast stack for
 * `getCompatibilityWarnings()`-shaped warnings (deck + slide), computed via
 * the shared `compatibilityWarningToasts`. These do not auto-hide (they are
 * diagnostics, not transient notifications) and are cleared wholesale on the
 * next load.
 */
export interface CompatibilityToastsProps {
	toasts: CompatibilityWarningToast[];
	onDismiss: (id: string) => void;
	onDismissAll: () => void;
}

export function CompatibilityToasts({ toasts, onDismiss, onDismissAll }: CompatibilityToastsProps) {
	const { t } = useTranslation();

	if (toasts.length === 0) {
		return null;
	}

	return (
		<div
			data-testid='pptx-compat-toasts'
			className='absolute bottom-3 right-3 z-50 flex max-h-[60%] w-80 flex-col gap-2 overflow-y-auto'
		>
			<div className='flex items-center justify-between px-1'>
				<span className='text-[11px] font-medium uppercase tracking-wide text-muted-foreground'>
					{t('pptx.compatibility.toastTitle')}
				</span>
				{toasts.length > 1 && (
					<button
						type='button'
						data-testid='pptx-compat-toasts-dismiss-all'
						onClick={onDismissAll}
						className='text-[11px] text-muted-foreground underline-offset-2 hover:underline'
					>
						{t('pptx.compatibility.dismissAll')}
					</button>
				)}
			</div>
			{toasts.map((toast) => (
				<div
					key={toast.id}
					data-testid='pptx-compat-toast'
					data-code={toast.code}
					data-severity={toast.severity}
					className='flex items-start gap-2 rounded border border-border bg-card p-2 text-[11px] shadow-md'
				>
					<span className='flex-1 min-w-0'>{t(toast.messageKey, toast.params)}</span>
					<button
						type='button'
						data-testid='pptx-compat-toast-dismiss'
						onClick={() => onDismiss(toast.id)}
						aria-label={t('pptx.compatibility.dismiss')}
						className='shrink-0 text-muted-foreground hover:text-foreground'
					>
						×
					</button>
				</div>
			))}
		</div>
	);
}

// packages/svelte/src/viewer/components/CompatibilityToasts.svelte
<script lang="ts">
	/**
	 * CompatibilityToasts: the bottom-right load-diagnostic stack for
	 * `PptxCompatibilityWarning`s (unmodelled markup, an external image
	 * reference, a chart workbook writeback that failed, and so on). Every
	 * warning already flows through the shared `compatibilityWarningToasts`
	 * decision function (`CompatToastsState`); this component only renders the
	 * list it returns. Svelte port of Vue's `CompatibilityToasts.vue`.
	 *
	 * Unlike a transient toast, these do not auto-hide: they are diagnostics
	 * about the LOADED document, so they persist until the user dismisses them
	 * (or the next load resets the stack).
	 */
	import type { CompatibilityWarningToast } from 'pptx-viewer-shared';

	import { useTranslator } from '../../i18n/context';

	const {
		toasts,
		overflowCount,
		ondismiss,
		ondismissall,
	}: {
		toasts: readonly CompatibilityWarningToast[];
		overflowCount: number;
		ondismiss: (id: string) => void;
		ondismissall: () => void;
	} = $props();

	const t = useTranslator();
</script>

{#if toasts.length > 0}
	<div
		class="pptx-svelte-compat-toasts pointer-events-none fixed bottom-4 right-4 z-[900] flex w-80 max-w-[90vw] flex-col gap-2"
		data-testid="pptx-compat-toasts"
	>
		<div class="pointer-events-auto flex items-center justify-between">
			<span class="text-[11px] font-semibold text-muted-foreground">{t('pptx.compatibility.toastTitle')}</span>
			<button
				type="button"
				data-testid="pptx-compat-toasts-dismiss-all"
				class="text-[11px] font-medium text-muted-foreground underline-offset-2 hover:underline"
				onclick={ondismissall}
			>
				{t('pptx.compatibility.dismissAll')}
			</button>
		</div>

		{#each toasts as toast (toast.id)}
			<div
				class="pptx-svelte-compat-toast pointer-events-auto flex items-start gap-2 rounded-md border border-border bg-popover p-2.5 text-xs shadow-lg"
				data-testid="pptx-compat-toast"
				data-code={toast.code}
				data-severity={toast.severity}
			>
				<span class="mt-0.5 shrink-0" aria-hidden="true">{toast.severity === 'warning' ? '⚠️' : 'ℹ️'}</span>
				<p class="flex-1 text-foreground">{t(toast.messageKey, toast.params)}</p>
				<button
					type="button"
					data-testid="pptx-compat-toast-dismiss"
					aria-label={t('pptx.compatibility.dismiss')}
					class="shrink-0 rounded p-0.5 text-muted-foreground hover:bg-muted hover:text-foreground"
					onclick={() => ondismiss(toast.id)}
				>
					&#10005;
				</button>
			</div>
		{/each}

		{#if overflowCount > 0}
			<p class="pointer-events-auto text-center text-[11px] text-muted-foreground">+{overflowCount}</p>
		{/if}
	</div>
{/if}
