// packages/vue/src/viewer/components/PresentationEndScreen.vue
<script setup lang="ts">
/**
 * PresentationEndScreen - the black "End of slide show" screen shown once the
 * show has run past its last slide, when Options > Advanced > "End with black
 * slide" is on. A click (or the next forward advance) exits the presentation.
 *
 * Without it the end-of-show state was invisible: the deck kept painting its
 * last slide, a backward press was silently swallowed and the next forward
 * press ended the show with no warning (issue #106). Vue port of React's
 * `PresentationEndOverlay`.
 */
import { useI18n } from 'vue-i18n';

defineEmits<{ (e: 'exit'): void }>();

const { t } = useI18n();
</script>

<template>
	<button
		type="button"
		class="pptx-vue-presentation-end absolute inset-0 z-[90] flex cursor-default items-start bg-black text-left"
		data-pptx-end-of-show
		@click.stop="$emit('exit')"
	>
		<span class="px-4 py-3 text-[12px] text-white/70">
			{{ t('pptx.presentation.endOfSlideShow') }}
		</span>
	</button>
</template>

// packages/svelte/src/viewer/components/PresentationEndScreen.svelte
<script lang="ts">
	/**
	 * The "End of slide show" black screen shown past the last slide when
	 * Options > Advanced > "End with black slide" is on. Any click (or
	 * Enter/Space via the button semantics) exits the presentation.
	 */
	import { useTranslator } from '../../i18n/context';

	const { onexit }: { onexit: () => void } = $props();
	const t = useTranslator();
</script>

<button type="button" class="pptx-svelte-presentation-end" data-pptx-end-of-show onclick={onexit}>
	{t('pptx.presentation.endOfSlideShow')}
</button>

<style>
	.pptx-svelte-presentation-end {
		position: absolute;
		inset: 0;
		z-index: 80;
		display: grid;
		place-items: center;
		border: 0;
		background: #000;
		color: #9ca3af;
		font: 14px system-ui, sans-serif;
		cursor: pointer;
	}
</style>
