// packages/react/src/viewer/components/ReadOnlyBanner.tsx
import type { ReadOnlyRecommendation } from 'pptx-viewer-shared';
import { useTranslation } from 'react-i18next';

/**
 * ReadOnlyBanner: shown above the canvas (under the ribbon/toolbar) when a
 * loaded deck recommends opening read-only (`p:modifyVerifier` or "Mark as
 * Final", via the shared `readOnlyRecommendation`). "Edit anyway" lifts the
 * lock this banner represents; "Dismiss" only hides the banner, the deck
 * stays locked.
 */
export interface ReadOnlyBannerProps {
	recommendation: ReadOnlyRecommendation;
	onEditAnyway: () => void;
	onDismiss: () => void;
}

export function ReadOnlyBanner({ recommendation, onEditAnyway, onDismiss }: ReadOnlyBannerProps) {
	const { t } = useTranslation();

	return (
		<div
			data-testid='pptx-readonly-banner'
			data-kind={recommendation.kind ?? undefined}
			className='flex items-center gap-3 px-3 py-1.5 bg-amber-600/10 border-b border-amber-600/30 text-[12px] text-amber-900 dark:text-amber-200'
		>
			<span className='flex-1 min-w-0'>{t(recommendation.messageKey)}</span>
			<button
				type='button'
				data-testid='pptx-readonly-edit-anyway'
				onClick={onEditAnyway}
				className='shrink-0 rounded-sm bg-amber-600/90 px-2 py-0.5 text-[11px] text-amber-50 transition-colors hover:bg-amber-600'
			>
				{t('pptx.readOnly.editAnyway')}
			</button>
			<button
				type='button'
				data-testid='pptx-readonly-dismiss'
				onClick={onDismiss}
				aria-label={t('pptx.readOnly.dismiss')}
				className='shrink-0 rounded-sm px-1.5 py-0.5 text-[11px] text-amber-900/80 transition-colors hover:bg-amber-600/20 dark:text-amber-200/80'
			>
				{t('pptx.readOnly.dismiss')}
			</button>
		</div>
	);
}

// packages/svelte/src/viewer/components/ReadOnlyBanner.svelte
<script lang="ts">
	/**
	 * ReadOnlyBanner: shown above the canvas (under the ribbon/toolbar) when the
	 * loaded deck recommends opening read-only (`p:modifyVerifier` or "Mark as
	 * Final"). Mirrors this binding's existing Protected View banner's look
	 * (`ViewerChrome.svelte`); the recommendation itself is a pure shared
	 * decision (`readOnlyRecommendation`, `pptx-viewer-shared`) computed by
	 * `ReadOnlyRecommendationState`, this component only renders it.
	 */
	import type { ReadOnlyRecommendationKind } from 'pptx-viewer-shared';

	import { useTranslator } from '../../i18n/context';

	const {
		kind,
		messageKey,
		oneditanyway,
		ondismiss,
	}: {
		kind: ReadOnlyRecommendationKind;
		messageKey: string;
		oneditanyway: () => void;
		ondismiss: () => void;
	} = $props();

	const t = useTranslator();
</script>

{#if kind}
	<div
		class="pptx-svelte-readonly-banner flex items-center gap-3 border-b border-amber-700/30 bg-amber-900/20 px-4 py-2"
		role="status"
		data-testid="pptx-readonly-banner"
		data-kind={kind}
	>
		<span class="h-4 w-4 shrink-0 text-amber-400" aria-hidden="true">&#128274;</span>
		<p class="flex-1 text-xs text-amber-200">
			<strong>{t('pptx.readOnly.bannerTitle')}</strong>: {t(messageKey)}
		</p>
		<button
			type="button"
			data-testid="pptx-readonly-edit-anyway"
			class="shrink-0 rounded border border-amber-600/50 px-3 py-1 text-xs font-medium text-amber-100 transition-colors hover:bg-amber-700/30"
			onclick={oneditanyway}
		>
			{t('pptx.readOnly.editAnyway')}
		</button>
		<button
			type="button"
			data-testid="pptx-readonly-dismiss"
			class="shrink-0 rounded px-2 py-1 text-xs font-medium text-amber-200/80 transition-colors hover:bg-amber-700/20"
			onclick={ondismiss}
		>
			{t('pptx.readOnly.dismiss')}
		</button>
	</div>
{/if}
