// packages/vue/src/viewer/components/MobileMenuSheet.vue
<script setup lang="ts">
/**
 * MobileMenuSheet - Vue port of React's
 * `components/mobile/MobileMenuSheet.tsx`.
 *
 * Drawer-style sheet that exposes every ribbon section (File / Home / Insert /
 * Text / Draw / Arrange / Design / Transitions / Animations / Slide Show /
 * Review / View) in a single mobile-friendly scroll. Tapping a section chip
 * selects it; the matching desktop ribbon section component is then rendered
 * below in a wrapping, larger-touch-target layout. The section SFCs are reused
 * verbatim (same prop contract as `RibbonToolbar.vue`), so behaviour matches
 * the desktop ribbon.
 *
 * The host (`PowerPointViewer.vue`) passes the same aggregate `RibbonProps`
 * bundle it already assembles for the desktop ribbon, plus `open` + a `close`
 * emit, exactly like React threads `ToolbarProps` through.
 */
import { TOOLBAR_TABS } from 'pptx-viewer-shared';
import type { ToolbarTabId } from 'pptx-viewer-shared';
import { computed, ref } from 'vue';
import { useI18n } from 'vue-i18n';

import { cn } from '../../utils';
import { useToolbarVisibility } from '../composables/useToolbarVisibility';
import MobileSheet from './MobileSheet.vue';
import AnimationsSection from './ribbon/AnimationsSection.vue';
import ArrangeSection from './ribbon/ArrangeSection.vue';
import { toCustomShowsControlsProps } from './ribbon/custom-show-controls-props';
import DesignSection from './ribbon/DesignSection.vue';
import DrawSection from './ribbon/DrawSection.vue';
import FileSection from './ribbon/FileSection.vue';
import HomeSection from './ribbon/HomeSection.vue';
import InsertSection from './ribbon/InsertSection.vue';
import { MOBILE_MENU_ITEMS } from './ribbon/mobile-menu-items';
import type { MobileMenuKey } from './ribbon/mobile-menu-items';
import ReviewSection from './ribbon/ReviewSection.vue';
import type { RibbonProps } from './ribbon/ribbon-types';
import SlideShowSection from './ribbon/SlideShowSection.vue';
import TextSection from './ribbon/TextSection.vue';
import TransitionsSection from './ribbon/TransitionsSection.vue';
import ViewSection from './ribbon/ViewSection.vue';

interface Props extends RibbonProps {
	open: boolean;
}

const props = defineProps<Props>();
const emit = defineEmits<{ close: [] }>();

const { t } = useI18n();
const { isHidden } = useToolbarVisibility(() => props.hiddenActions);

/** Ribbon-tab ids among the menu chips (draw/home/insert/... but not text/arrange, which aren't tabs). */
const TAB_KEYS = new Set<string>(TOOLBAR_TABS.map((tab) => tab.id));

/** Chips resolved with their label, minus any hidden ribbon tabs. */
const MENU_ITEMS = computed(() =>
	MOBILE_MENU_ITEMS.filter(
		(item) => !TAB_KEYS.has(item.key) || !isHidden(item.key as ToolbarTabId),
	).map((item) => ({ key: item.key, label: t(item.labelKey), icon: item.icon })),
);

const active = ref<MobileMenuKey | null>('home');
function toggle(key: MobileMenuKey): void {
	active.value = active.value === key ? null : key;
}

/** Wrapping, larger-touch-target body layout (React's `wrap`). */
const WRAP = 'flex flex-wrap items-center gap-2';
</script>

<template>
	<MobileSheet :open="props.open" :title="t('pptx.mobileMenu.title')" @close="emit('close')">
		<div class="flex flex-col">
			<!-- Section chips: wrap so every section stays reachable without
			     horizontal scrolling (mirrors React's wrapping chip row). -->
			<div class="sticky top-0 z-10 border-b border-border bg-background">
				<div class="flex flex-wrap gap-1.5 px-3 py-2">
					<button
						v-for="item in MENU_ITEMS"
						:key="item.key"
						type="button"
						:class="
							cn(
								'inline-flex shrink-0 items-center gap-1.5 rounded-full border px-3 py-2 text-[12px] font-medium transition-colors min-h-[36px]',
								active === item.key
									? 'border-primary bg-primary text-white'
									: 'border-border text-muted-foreground hover:bg-accent/40 hover:text-foreground',
							)
						"
						@click="toggle(item.key)"
					>
						<component :is="item.icon" class="h-4 w-4" />
						{{ item.label }}
					</button>
				</div>
			</div>

			<!-- Active section body: reuses the desktop ribbon section SFCs. -->
			<div class="p-3">
				<div v-if="active === 'home'" :class="WRAP">
					<HomeSection
						:can-edit="props.canEdit"
						:clipboard-payload="props.clipboardPayload"
						:format-painter-active="props.formatPainterActive"
						:can-activate-format-painter="props.canActivateFormatPainter"
						:on-copy="props.onCopy"
						:on-cut="props.onCut"
						:on-paste="props.onPaste"
						:on-toggle-format-painter="props.onToggleFormatPainter"
						:layout-options="props.layoutOptions"
						:on-insert-slide-from-layout="props.onInsertSlideFromLayout"
						:on-insert-slide-from-template="props.onInsertSlideFromTemplate"
						:template-scheme="props.templateScheme"
						:selected-element="props.selectedElement"
						:on-update-text-style="props.onUpdateTextStyle"
					/>
				</div>

				<div v-else-if="active === 'insert'" :class="WRAP">
					<InsertSection
						:can-edit="props.canEdit"
						:new-shape-type="props.newShapeType"
						:on-set-new-shape-type="props.onSetNewShapeType"
						:on-add-text-box="props.onAddTextBox"
						:on-add-shape="props.onAddShape"
						:on-add-table="props.onAddTable"
						:on-add-chart="props.onAddChart"
						:on-add-smart-art="props.onAddSmartArt"
						:on-add-equation="props.onAddEquation"
						:on-add-action-button="props.onAddActionButton"
						:on-insert-field="props.onInsertField"
						:on-open-image-picker="props.onOpenImagePicker"
						:on-open-media-picker="props.onOpenMediaPicker"
						:has-selection="Boolean(props.selectedElement)"
						:on-open-hyperlink-dialog="props.onOpenHyperlinkDialog"
					/>
				</div>

				<div v-else-if="active === 'text'" :class="WRAP">
					<TextSection
						:can-edit="props.canEdit"
						:selected-element="props.selectedElement"
						:table-editor-state="props.tableEditorState"
						:on-update-text-style="props.onUpdateTextStyle"
						:on-transform-text-case="props.onTransformTextCase"
					/>
				</div>

				<div v-else-if="active === 'draw'" :class="WRAP">
					<DrawSection
						:active-tool="props.activeTool"
						:drawing-color="props.drawingColor"
						:drawing-width="props.drawingWidth"
						:on-set-active-tool="props.onSetActiveTool"
						:on-set-drawing-color="props.onSetDrawingColor"
						:on-set-drawing-width="props.onSetDrawingWidth"
					/>
				</div>

				<div v-else-if="active === 'arrange'" :class="WRAP">
					<ArrangeSection
						:can-edit="props.canEdit"
						:selected-element="props.selectedElement"
						:selected-count="props.selectedCount"
						:selection-groupable="props.selectionGroupable"
						:on-align-elements="props.onAlignElements"
						:on-distribute-elements="props.onDistributeElements"
						:can-distribute="props.canDistribute"
						:on-flip="props.onFlip"
						:on-move-layer="props.onMoveLayer"
						:on-move-layer-to-edge="props.onMoveLayerToEdge"
						:on-group-elements="props.onGroupElements"
						:on-ungroup-element="props.onUngroupElement"
						:on-update-element-style="props.onUpdateElementStyle"
						:on-duplicate="props.onDuplicate"
						:on-delete="props.onDelete"
						:format-painter-active="props.formatPainterActive"
						:on-toggle-format-painter="props.onToggleFormatPainter"
						:can-activate-format-painter="props.canActivateFormatPainter"
					/>
				</div>

				<div v-else-if="active === 'design'" :class="WRAP">
					<DesignSection
						:can-edit="props.canEdit"
						:on-toggle-theme-gallery="props.onToggleThemeGallery"
						:is-theme-gallery-open="props.isThemeGalleryOpen"
						:on-toggle-theme-editor="props.onToggleThemeEditor"
						:is-theme-editor-open="props.isThemeEditorOpen"
						:on-open-document-properties="props.onOpenDocumentProperties"
						:on-open-slide-size="props.onOpenSlideSize"
						:on-toggle-inspector="props.onToggleInspector"
						:is-inspector-pane-open="props.isInspectorPaneOpen"
					/>
				</div>

				<div v-else-if="active === 'transitions'" :class="WRAP">
					<TransitionsSection
						:is-inspector-pane-open="props.isInspectorPaneOpen"
						:on-toggle-inspector="props.onToggleInspector"
						:can-edit="props.canEdit"
						:active-slide="props.activeSlide"
						:on-transition-change="props.onTransitionChange"
						:on-apply-transition-to-all="props.onApplyTransitionToAll"
					/>
				</div>

				<div v-else-if="active === 'animations'" :class="WRAP">
					<AnimationsSection
						:can-edit="props.canEdit"
						:selected-element="props.selectedElement"
						:is-inspector-pane-open="props.isInspectorPaneOpen"
						:on-toggle-inspector="props.onToggleInspector"
						:on-open-animation-panel="props.onOpenAnimationPanel"
						:on-add-animation="props.onAddAnimation"
						:on-remove-animation="props.onRemoveAnimation"
					/>
				</div>

				<div v-else-if="active === 'slideShow'" :class="WRAP">
					<SlideShowSection
						:on-present="() => props.onSetMode('present')"
						:on-present-from-beginning="props.onPresentFromBeginning"
						:on-enter-presenter-view="props.onEnterPresenterView ?? (() => {})"
						:on-enter-rehearsal-mode="props.onEnterRehearsalMode ?? (() => {})"
						:on-open-set-up-slide-show="props.onOpenSetUpSlideShow ?? (() => {})"
						:on-toggle-hide-slide="props.onToggleHideSlide ?? (() => {})"
						:active-slide-hidden="props.activeSlideHidden ?? false"
						:on-open-broadcast-dialog="props.onOpenBroadcastDialog ?? (() => {})"
						:on-toggle-subtitles="props.onToggleSubtitles ?? (() => {})"
						:show-subtitles="props.showSubtitles ?? false"
						:custom-show-controls="toCustomShowsControlsProps(props)"
						:hidden-actions="props.hiddenActions"
					/>
				</div>

				<div v-else-if="active === 'review'" :class="WRAP">
					<ReviewSection
						:can-edit="props.canEdit"
						:spell-check-enabled="props.spellCheckEnabled"
						:on-set-spell-check-enabled="props.onSetSpellCheckEnabled"
						:on-toggle-comments="props.onToggleComments"
						:is-comments-panel-open="props.isCommentsPanelOpen"
						:slide-comment-count="props.slideCommentCount"
						:on-compare="props.onCompare"
						:on-set-language="props.onOpenSettings"
						:on-open-accessibility-check="props.onRunAccessibilityCheck"
					/>
				</div>

				<div v-else-if="active === 'view'" :class="WRAP">
					<ViewSection
						:can-edit="props.canEdit"
						:edit-template-mode="props.editTemplateMode"
						:on-set-edit-template-mode="props.onSetEditTemplateMode"
						:spell-check-enabled="props.spellCheckEnabled"
						:on-set-spell-check-enabled="props.onSetSpellCheckEnabled"
						:show-grid="props.showGrid"
						:show-rulers="props.showRulers"
						:show-guides="props.showGuides"
						:snap-to-grid="props.snapToGrid"
						:snap-to-shape="props.snapToShape"
						:on-set-show-grid="props.onSetShowGrid"
						:on-set-show-rulers="props.onSetShowRulers"
						:on-set-show-guides="props.onSetShowGuides"
						:on-set-snap-to-grid="props.onSetSnapToGrid"
						:on-set-snap-to-shape="props.onSetSnapToShape"
						:on-add-guide="props.onAddGuide"
						:on-zoom-to-fit="props.onZoomToFit"
						:on-enter-master-view="props.onEnterMasterView"
						:is-selection-pane-open="props.isSelectionPaneOpen"
						:on-toggle-selection-pane="props.onToggleSelectionPane"
						:eyedropper-active="props.eyedropperActive"
						:on-toggle-eyedropper="props.onToggleEyedropper"
						:on-open-reading-view="props.onOpenReadingView"
					/>
				</div>

				<div v-else-if="active === 'file'" :class="WRAP">
					<FileSection
						:file-name="props.fileName"
						:on-close="() => emit('close')"
						:on-create-presentation="props.onCreatePresentation"
						:on-open-file="props.onOpenFile"
						:on-open-recent-file="props.onOpenRecentFile"
						:on-export-png="props.onExportPng"
						:on-export-pdf="props.onExportPdf"
						:on-export-video="props.onExportVideo"
						:on-export-gif="props.onExportGif"
						:on-export-json="props.onExportJson"
						:on-save-as-pptx="props.onSaveAsPptx"
						:on-save-as-ppsx="props.onSaveAsPpsx"
						:on-save-as-pptm="props.onSaveAsPptm"
						:has-macros="props.hasMacros"
						:on-copy-slide-as-image="props.onCopySlideAsImage"
						:on-print="props.onPrint"
						:on-open-settings="props.onOpenSettings"
						:on-open-share-dialog="props.onOpenShareDialog"
						:on-open-document-properties="props.onOpenDocumentProperties"
						:on-open-password-protection="props.onOpenPasswordProtection"
						:on-open-font-embedding="props.onOpenFontEmbedding"
						:on-open-digital-signatures="props.onOpenDigitalSignatures"
						:on-open-version-history="props.onToggleVersionHistory"
						:hidden-actions="props.hiddenActions"
						:recent-presentations-count="props.recentPresentationsCount"
					/>
				</div>

				<p v-else class="py-8 text-center text-sm text-muted-foreground">
					{{ t('pptx.mobileMenu.selectSection') }}
				</p>
			</div>
		</div>
	</MobileSheet>
</template>

// packages/react/src/viewer/components/mobile/MobileMenuSheet.tsx
import React, { useState } from 'react';
import { useTranslation } from 'react-i18next';
import {
	LuChevronRight,
	LuClipboardCopy,
	LuFile,
	LuLayoutGrid,
	LuPaintbrush,
	LuPlus,
	LuPresentation,
	LuSettings,
	LuShapes,
	LuSparkles,
	LuTextCursorInput,
	LuType,
	LuWand,
} from 'react-icons/lu';

import { useToolbarVisibility } from '../../hooks/useToolbarVisibility';
import { cn } from '../../utils';
import { AnimationsSection } from '../toolbar/AnimationsSection';
import { ArrangeSection } from '../toolbar/ArrangeSection';
import { DesignSection, TransitionsSection } from '../toolbar/DesignTransitionsReviewSection';
import { DrawSection } from '../toolbar/DrawSection';
import { FileSection } from '../toolbar/FileSection';
import { HomeSection } from '../toolbar/HomeSection';
import { InsertSection } from '../toolbar/InsertSection';
import { ReviewSection } from '../toolbar/ReviewSection';
import { SlideShowSection } from '../toolbar/SlideShowSection';
import { TextSection } from '../toolbar/TextSection';
import type { ToolbarProps } from '../toolbar/toolbar-types';
import { ViewSection } from '../toolbar/ViewSection';
import { MobileSheet } from './MobileSheet';

type MenuKey =
	| null
	| 'home'
	| 'insert'
	| 'text'
	| 'draw'
	| 'arrange'
	| 'design'
	| 'transitions'
	| 'animations'
	| 'slideShow'
	| 'review'
	| 'view'
	| 'file';

interface MenuItemDef {
	key: Exclude<MenuKey, null>;
	label: string;
	icon: React.ComponentType<{ className?: string }>;
}

const MENU_ITEMS: MenuItemDef[] = [
	{ key: 'home', label: 'pptx.ribbon.tab.home', icon: LuClipboardCopy },
	{ key: 'insert', label: 'pptx.ribbon.tab.insert', icon: LuPlus },
	{ key: 'text', label: 'pptx.ribbon.tab.text', icon: LuType },
	{ key: 'draw', label: 'pptx.ribbon.tab.draw', icon: LuPaintbrush },
	{ key: 'arrange', label: 'pptx.ribbon.tab.arrange', icon: LuShapes },
	{ key: 'design', label: 'pptx.ribbon.tab.design', icon: LuLayoutGrid },
	{ key: 'transitions', label: 'pptx.ribbon.tab.transitions', icon: LuSparkles },
	{ key: 'animations', label: 'pptx.ribbon.tab.animations', icon: LuWand },
	{ key: 'slideShow', label: 'pptx.ribbon.tab.slideShow', icon: LuPresentation },
	{ key: 'review', label: 'pptx.ribbon.tab.review', icon: LuTextCursorInput },
	{ key: 'view', label: 'pptx.ribbon.tab.view', icon: LuSettings },
	{ key: 'file', label: 'pptx.ribbon.tab.file', icon: LuFile },
];

export interface MobileMenuSheetProps extends ToolbarProps {
	open: boolean;
	onClose: () => void;
}

/**
 * Drawer-style sheet exposing every ribbon section in a single mobile-friendly
 * scroll. Tapping a section title expands it inline; the existing section
 * components are reused so functionality is identical to desktop.
 */
export function MobileMenuSheet(props: MobileMenuSheetProps): React.ReactElement {
	const { t } = useTranslation();
	const { open, onClose } = props;
	const [active, setActive] = useState<MenuKey>('home');
	const { isTabVisible } = useToolbarVisibility(props.hiddenActions);

	return (
		<MobileSheet open={open} onClose={onClose} autoHeight title={t('pptx.mobileToolbar.menu')}>
			<div className='flex flex-col'>
				{/* Section selector: chips wrap so every section stays reachable
				    without horizontal scrolling (which hid the trailing sections). */}
				<div className='sticky top-0 z-10 bg-background border-b border-border'>
					<div className='flex flex-wrap gap-1.5 px-3 py-2'>
						{MENU_ITEMS.filter(({ key }) => isTabVisible(key)).map(({ key, label, icon: Icon }) => (
							<button
								key={key}
								type='button'
								onClick={() => setActive(active === key ? null : key)}
								className={cn(
									'inline-flex items-center gap-1.5 shrink-0 px-3 py-2 rounded-full text-[12px] font-medium border transition-colors min-h-[36px]',
									active === key
										? 'bg-primary text-white border-primary'
										: 'border-border text-muted-foreground hover:text-foreground hover:bg-accent/40',
								)}
							>
								<Icon className='w-4 h-4' />
								{t(label)}
							</button>
						))}
					</div>
				</div>

				{/* Active section body */}
				<div className='p-3'>
					<MobileSectionBody active={active} {...props} />
				</div>
			</div>
		</MobileSheet>
	);
}

function MobileSectionBody({
	active,
	...p
}: { active: MenuKey } & ToolbarProps): React.ReactElement | null {
	// Re-use the desktop section components inside a vertical mobile layout.
	// The wrapper applies `flex-wrap` and larger touch targets through
	// global overrides in toolbar-constants `pill` / `ic` are already styled,
	// but here we let them flow and wrap.
	const wrap = 'flex flex-wrap items-center gap-2';

	switch (active) {
		case 'home':
			return (
				<div className={wrap}>
					<HomeSection
						canEdit={p.canEdit}
						clipboardPayload={p.clipboardPayload}
						formatPainterActive={p.formatPainterActive}
						canActivateFormatPainter={p.canActivateFormatPainter}
						onCopy={p.onCopy}
						onCut={p.onCut}
						onPaste={p.onPaste}
						onToggleFormatPainter={p.onToggleFormatPainter}
						layoutOptions={p.layoutOptions}
						onInsertSlideFromLayout={p.onInsertSlideFromLayout}
						onInsertSlideFromTemplate={p.onInsertSlideFromTemplate}
						templateScheme={p.templateScheme}
						selectedElement={p.selectedElement}
						onUpdateTextStyle={p.onUpdateTextStyle}
					/>
				</div>
			);
		case 'insert':
			return (
				<div className={wrap}>
					<InsertSection
						canEdit={p.canEdit}
						newShapeType={p.newShapeType}
						onSetNewShapeType={p.onSetNewShapeType}
						onAddTextBox={p.onAddTextBox}
						onAddShape={p.onAddShape}
						onAddTable={p.onAddTable}
						onAddChart={p.onAddChart}
						onAddSmartArt={p.onAddSmartArt}
						onAddEquation={p.onAddEquation}
						onAddActionButton={p.onAddActionButton}
						onInsertField={p.onInsertField}
						onOpenImagePicker={p.onOpenImagePicker}
						onOpenMediaPicker={p.onOpenMediaPicker}
						hasSelection={Boolean(p.selectedElement)}
						onOpenHyperlinkDialog={p.onOpenHyperlinkDialog}
					/>
				</div>
			);
		case 'text':
			return (
				<div className={wrap}>
					<TextSection
						canEdit={p.canEdit}
						selectedElement={p.selectedElement}
						tableEditorState={p.tableEditorState}
						onUpdateTextStyle={p.onUpdateTextStyle}
						onTransformTextCase={p.onTransformTextCase}
					/>
				</div>
			);
		case 'draw':
			return (
				<div className={wrap}>
					<DrawSection
						activeTool={p.activeTool}
						drawingColor={p.drawingColor}
						drawingWidth={p.drawingWidth}
						onSetActiveTool={p.onSetActiveTool}
						onSetDrawingColor={p.onSetDrawingColor}
						onSetDrawingWidth={p.onSetDrawingWidth}
					/>
				</div>
			);
		case 'arrange':
			return (
				<div className={wrap}>
					<ArrangeSection
						canEdit={p.canEdit}
						selectedElement={p.selectedElement}
						selectedCount={p.selectedCount}
						selectionGroupable={p.selectionGroupable}
						onAlignElements={p.onAlignElements}
						onDistributeElements={p.onDistributeElements}
						canDistribute={p.canDistribute}
						onFlip={p.onFlip}
						onMoveLayer={p.onMoveLayer}
						onMoveLayerToEdge={p.onMoveLayerToEdge}
						onGroupElements={p.onGroupElements}
						onUngroupElement={p.onUngroupElement}
						onUpdateElementStyle={p.onUpdateElementStyle}
						onDuplicate={p.onDuplicate}
						onDelete={p.onDelete}
						formatPainterActive={p.formatPainterActive}
						onToggleFormatPainter={p.onToggleFormatPainter}
						canActivateFormatPainter={p.canActivateFormatPainter}
					/>
				</div>
			);
		case 'design':
			return (
				<div className={wrap}>
					<DesignSection
						canEdit={p.canEdit}
						onToggleThemeGallery={p.onToggleThemeGallery}
						isThemeGalleryOpen={p.isThemeGalleryOpen}
						onToggleThemeEditor={p.onToggleThemeEditor}
						isThemeEditorOpen={p.isThemeEditorOpen}
						onOpenDocumentProperties={p.onOpenDocumentProperties}
						onOpenSlideSize={p.onOpenSlideSize}
						onToggleInspector={p.onToggleInspector}
						isInspectorPaneOpen={p.isInspectorPaneOpen}
					/>
				</div>
			);
		case 'transitions':
			return (
				<div className={wrap}>
					<TransitionsSection
						isInspectorPaneOpen={p.isInspectorPaneOpen}
						onToggleInspector={p.onToggleInspector}
						canEdit={p.canEdit}
						activeSlide={p.activeSlide}
						onTransitionChange={p.onTransitionChange}
						onApplyTransitionToAll={p.onApplyTransitionToAll}
					/>
				</div>
			);
		case 'animations':
			return (
				<div className={wrap}>
					<AnimationsSection
						canEdit={p.canEdit}
						selectedElement={p.selectedElement}
						isInspectorPaneOpen={p.isInspectorPaneOpen}
						onToggleInspector={p.onToggleInspector}
						onOpenAnimationPanel={p.onOpenAnimationPanel}
						onAddAnimation={p.onAddAnimation}
						onRemoveAnimation={p.onRemoveAnimation}
					/>
				</div>
			);
		case 'slideShow':
			return (
				<div className={wrap}>
					<SlideShowSection
						onPresent={() => p.onSetMode('present')}
						onPresentFromBeginning={p.onPresentFromBeginning}
						onEnterPresenterView={p.onEnterPresenterView ?? (() => {})}
						onEnterRehearsalMode={p.onEnterRehearsalMode ?? (() => {})}
						onOpenSetUpSlideShow={p.onOpenSetUpSlideShow ?? (() => {})}
						onToggleHideSlide={p.onToggleHideSlide ?? (() => {})}
						activeSlideHidden={p.activeSlideHidden ?? false}
						onOpenBroadcastDialog={p.onOpenBroadcastDialog ?? (() => {})}
						onToggleSubtitles={p.onToggleSubtitles ?? (() => {})}
						showSubtitles={p.showSubtitles ?? false}
						onSetMode={p.onSetMode}
						customShowControls={p}
						hiddenActions={p.hiddenActions}
					/>
				</div>
			);
		case 'review':
			return (
				<div className={wrap}>
					<ReviewSection
						canEdit={p.canEdit}
						spellCheckEnabled={p.spellCheckEnabled}
						onSetSpellCheckEnabled={p.onSetSpellCheckEnabled}
						onToggleComments={p.onToggleComments}
						isCommentsPanelOpen={p.isCommentsPanelOpen}
						slideCommentCount={p.slideCommentCount}
						onCompare={p.onCompare}
					/>
				</div>
			);
		case 'view':
			return (
				<div className={wrap}>
					<ViewSection
						canEdit={p.canEdit}
						editTemplateMode={p.editTemplateMode}
						onSetEditTemplateMode={p.onSetEditTemplateMode}
						spellCheckEnabled={p.spellCheckEnabled}
						onSetSpellCheckEnabled={p.onSetSpellCheckEnabled}
						showGrid={p.showGrid}
						showRulers={p.showRulers}
						showGuides={p.showGuides}
						onSetShowGuides={p.onSetShowGuides}
						snapToGrid={p.snapToGrid}
						snapToShape={p.snapToShape}
						onSetShowGrid={p.onSetShowGrid}
						onSetShowRulers={p.onSetShowRulers}
						onSetSnapToGrid={p.onSetSnapToGrid}
						onSetSnapToShape={p.onSetSnapToShape}
						onAddGuide={p.onAddGuide}
						onEnterMasterView={p.onEnterMasterView}
						isSelectionPaneOpen={p.isSelectionPaneOpen}
						onToggleSelectionPane={p.onToggleSelectionPane}
						eyedropperActive={p.eyedropperActive}
						onToggleEyedropper={p.onToggleEyedropper}
						onToggleSlideSorter={p.onToggleSlideSorter}
						onOpenReadingView={p.onOpenReadingView}
					/>
				</div>
			);
		case 'file':
			return (
				<div className={wrap}>
					<FileSection
						fileName={p.fileName}
						onClose={() => p.onSetToolbarSection('home')}
						onCreatePresentation={p.onCreatePresentation}
						onOpenFile={p.onOpenFile}
						onOpenRecentFile={p.onOpenRecentFile}
						onExportPng={p.onExportPng}
						onExportPdf={p.onExportPdf}
						onExportVideo={p.onExportVideo}
						onExportGif={p.onExportGif}
						onExportJson={p.onExportJson}
						onSaveAsPptx={p.onSaveAsPptx}
						onSaveAsPpsx={p.onSaveAsPpsx}
						onSaveAsPptm={p.onSaveAsPptm}
						hasMacros={p.hasMacros}
						onCopySlideAsImage={p.onCopySlideAsImage}
						onPrint={p.onPrint}
						onOpenSettings={p.onOpenSettings}
						onOpenShareDialog={p.onOpenShareDialog}
						onOpenDocumentProperties={p.onOpenDocumentProperties}
						onOpenPasswordProtection={p.onOpenPasswordProtection}
						onOpenFontEmbedding={p.onOpenFontEmbedding}
						onOpenDigitalSignatures={p.onOpenDigitalSignatures}
						onOpenVersionHistory={p.onToggleVersionHistory}
						hiddenActions={p.hiddenActions}
						recentPresentationsCount={p.recentPresentationsCount}
					/>
				</div>
			);
		default:
			return (
				<div className='text-center text-sm text-muted-foreground py-8'>
					<LuChevronRight className='w-5 h-5 inline-block opacity-50' />
					{' Select a section above'}
				</div>
			);
	}
}
