// packages/angular/src/viewer/comments-panel.component.ts
/**
 * comments-panel.component.ts: Side panel listing the active slide's comments.
 *
 * Selector: `pptx-comments-panel`
 *
 * Presentational only: it renders the supplied `comments` (already filtered to
 * the active slide by the host, nested replies included) and surfaces
 * add / remove / resolve / reply intents via outputs. The host owns state and
 * commits history-aware comment-array writes.
 *
 * Timestamps are formatted with the core `formatCommentTimestamp` helper so the
 * Angular binding matches the React/Vue formatting exactly.
 *
 * Usage:
 * ```html
 * <pptx-comments-panel
 *   [comments]="slideComments()"
 *   [authorName]="userName()"
 *   (add)="onAddComment($event)"
 *   (remove)="onRemoveComment($event)"
 *   (resolve)="onResolveComment($event)"
 *   (reply)="onReplyComment($event)"
 * />
 * ```
 */

import {
	ChangeDetectionStrategy,
	Component,
	computed,
	inject,
	input,
	output,
	signal,
} from '@angular/core';
import { TranslatePipe, TranslateService } from '@ngx-translate/core';
import type { PptxComment, PptxCommentMention, PptxModernCommentAuthor } from 'pptx-viewer-core';
import { formatCommentTimestamp } from 'pptx-viewer-core';

import { CommentBodyComponent } from './comment-body.component';
import { CommentMentionTextareaComponent } from './comment-mention-textarea.component';

/** The trimmed text plus the mention spans an add/reply submit carries. */
export interface CommentSubmission {
	text: string;
	mentions: PptxCommentMention[];
}

@Component({
	selector: 'pptx-comments-panel',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [TranslatePipe, CommentBodyComponent, CommentMentionTextareaComponent],
	templateUrl: './comments-panel.component.html',
	styleUrl: './comments-panel.component.css',
})
export class CommentsPanelComponent {
	// -------------------------------------------------------------------------
	// Inputs / outputs
	// -------------------------------------------------------------------------

	/** The active slide's comments (already filtered to the active slide). */
	readonly comments = input<PptxComment[]>([]);

	private readonly translate = inject(TranslateService);

	/** Display name shown in the compose label ("Commenting as …"). */
	readonly authorName = input<string>(this.translate.instant('pptx.comments.defaultAuthorName'));

	/** Office 2021 modern comment authors, for the `@`-mention typeahead. */
	readonly modernCommentAuthors = input<readonly PptxModernCommentAuthor[]>([]);

	/** Emits the trimmed comment text (+ mentions) the user wants to add. */
	readonly add = output<CommentSubmission>();

	/** Emits the id of a comment the user wants to remove. */
	readonly remove = output<string>();

	/** Emits the id of a comment whose resolved flag should toggle. */
	readonly resolve = output<string>();

	/** Emits the parent comment id + trimmed text (+ mentions) of a threaded reply. */
	readonly reply = output<{ parentId: string } & CommentSubmission>();

	// -------------------------------------------------------------------------
	// Draft state
	// -------------------------------------------------------------------------

	/** Current text typed into the compose textarea. */
	readonly draft = signal('');
	/** `@`-mentions recorded in {@link draft} so far. */
	readonly draftMentions = signal<PptxCommentMention[]>([]);

	/** Whether the draft has non-whitespace content (enables the submit button). */
	readonly canAdd = computed<boolean>(() => this.draft().trim().length > 0);

	/** Id of the comment whose reply composer is open (one at a time). */
	readonly replyingTo = signal<string | null>(null);

	/** Current text typed into the open reply composer. */
	readonly replyDraft = signal('');
	/** `@`-mentions recorded in {@link replyDraft} so far. */
	readonly replyMentions = signal<PptxCommentMention[]>([]);

	/** Whether the reply draft has content (enables the reply submit button). */
	readonly canReply = computed<boolean>(() => this.replyDraft().trim().length > 0);

	// -------------------------------------------------------------------------
	// Event handlers
	// -------------------------------------------------------------------------

	submit(event: Event): void {
		event.preventDefault();
		const text = this.draft().trim();
		if (text.length === 0) {
			return;
		}
		this.add.emit({ text, mentions: this.draftMentions() });
		this.draft.set('');
		this.draftMentions.set([]);
	}

	/** Localized reply-composer placeholder ("Reply to <author>..."). */
	replyPlaceholder(comment: PptxComment): string {
		return this.translate.instant('pptx.comments.replyPlaceholder', {
			author: comment.author || this.translate.instant('pptx.comments.unknownAuthor'),
		});
	}

	/** Open the reply composer under `parentId` (closing any other composer). */
	startReply(parentId: string): void {
		this.replyingTo.set(parentId);
		this.replyDraft.set('');
		this.replyMentions.set([]);
	}

	cancelReply(): void {
		this.replyingTo.set(null);
		this.replyDraft.set('');
		this.replyMentions.set([]);
	}

	submitReply(parentId: string): void {
		const text = this.replyDraft().trim();
		if (text.length === 0) {
			return;
		}
		this.reply.emit({ parentId, text, mentions: this.replyMentions() });
		this.cancelReply();
	}

	formatTimestamp(value: string | undefined): string {
		return formatCommentTimestamp(value);
	}
}

<aside class="pptx-ng-comments" [attr.aria-label]="'pptx.comments.slideComments' | translate">
	<header class="pptx-ng-comments__header">
		<h2 class="pptx-ng-comments__title">{{ 'pptx.toolbar.comments' | translate }}</h2>
		<span class="pptx-ng-comments__count" data-testid="comment-count">
			{{ comments().length }}
		</span>
	</header>

	@if (comments().length > 0) {
		<ul class="pptx-ng-comments__list">
			@for (comment of comments(); track comment.id) {
				<li
					class="pptx-ng-comments__item"
					[class.pptx-ng-comments__item--resolved]="comment.resolved"
					[attr.data-comment-id]="comment.id"
				>
					<div class="pptx-ng-comments__meta">
						<span class="pptx-ng-comments__author">{{
							comment.author || ('pptx.comments.unknownAuthor' | translate)
						}}</span>
						@if (formatTimestamp(comment.createdAt); as ts) {
							<time class="pptx-ng-comments__time">{{ ts }}</time>
						}
					</div>
					<p class="pptx-ng-comments__text">
						<pptx-comment-body [text]="comment.text" [mentions]="comment.mentions" />
					</p>

					<!-- Threaded replies, nested inside the parent card -->
					@if (comment.replies && comment.replies.length > 0) {
						<ul class="pptx-ng-comments__replies">
							@for (replyItem of comment.replies; track replyItem.id) {
								<li class="pptx-ng-comments__reply" [attr.data-comment-id]="replyItem.id">
									<div class="pptx-ng-comments__meta">
										<span class="pptx-ng-comments__reply-author">{{
											replyItem.author || ('pptx.comments.unknownAuthor' | translate)
										}}</span>
										@if (formatTimestamp(replyItem.createdAt); as replyTs) {
											<time class="pptx-ng-comments__time">{{ replyTs }}</time>
										}
									</div>
									<p class="pptx-ng-comments__reply-text">
										<pptx-comment-body [text]="replyItem.text" [mentions]="replyItem.mentions" />
									</p>
								</li>
							}
						</ul>
					}

					<div class="pptx-ng-comments__actions">
						<button
							type="button"
							class="pptx-ng-comments__action"
							[attr.data-comment-id]="comment.id"
							[attr.aria-pressed]="comment.resolved ? 'true' : 'false'"
							(click)="resolve.emit(comment.id)"
						>
							{{
								(comment.resolved ? 'pptx.comments.reopen' : 'pptx.comments.resolve') | translate
							}}
						</button>
						<button
							type="button"
							class="pptx-ng-comments__action"
							[attr.data-comment-id]="comment.id"
							(click)="startReply(comment.id)"
						>
							{{ 'pptx.comments.reply' | translate }}
						</button>
						<button
							type="button"
							class="pptx-ng-comments__action pptx-ng-comments__action--danger"
							[attr.data-comment-id]="comment.id"
							[attr.aria-label]="'pptx.comments.removeComment' | translate"
							(click)="remove.emit(comment.id)"
						>
							{{ 'pptx.comments.remove' | translate }}
						</button>
					</div>

					<!-- Reply composer -->
					@if (replyingTo() === comment.id) {
						<div class="pptx-ng-comments__reply-compose">
							<pptx-comment-mention-textarea
								[text]="replyDraft()"
								[mentions]="replyMentions()"
								[authors]="modernCommentAuthors()"
								textareaClass="pptx-ng-comments__reply-textarea"
								[rows]="2"
								[placeholder]="replyPlaceholder(comment)"
								[ariaLabel]="'pptx.comments.reply' | translate"
								(textChange)="replyDraft.set($event)"
								(mentionsChange)="replyMentions.set($event)"
							/>
							<div class="pptx-ng-comments__reply-actions">
								<button type="button" class="pptx-ng-comments__action" (click)="cancelReply()">
									{{ 'pptx.comments.cancel' | translate }}
								</button>
								<button
									type="button"
									class="pptx-ng-comments__reply-submit"
									[disabled]="!canReply()"
									(click)="submitReply(comment.id)"
								>
									{{ 'pptx.comments.reply' | translate }}
								</button>
							</div>
						</div>
					}
				</li>
			}
		</ul>
	} @else {
		<p class="pptx-ng-comments__empty" data-testid="comments-empty">
			{{ 'pptx.comments.noneOnSlide' | translate }}
		</p>
	}

	<form class="pptx-ng-comments__compose" (submit)="submit($event)">
		<label
			class="pptx-ng-comments__compose-label"
			[title]="'pptx.comments.commentingAs' | translate: { name: authorName() }"
		>
			{{ 'pptx.comments.addComment' | translate }}
		</label>
		<pptx-comment-mention-textarea
			[text]="draft()"
			[mentions]="draftMentions()"
			[authors]="modernCommentAuthors()"
			textareaClass="pptx-ng-comments__textarea"
			[rows]="3"
			[placeholder]="'pptx.comments.writePlaceholder' | translate"
			[ariaLabel]="'pptx.comments.addComment' | translate"
			(textChange)="draft.set($event)"
			(mentionsChange)="draftMentions.set($event)"
		/>
		<button
			type="submit"
			class="pptx-ng-comments__submit"
			[disabled]="!canAdd()"
			data-testid="add-comment"
		>
			{{ 'pptx.comments.addComment' | translate }}
		</button>
	</form>
</aside>

// packages/vue/src/viewer/components/CommentsPanel.vue
<script setup lang="ts">
import type { PptxComment, PptxCommentMention, PptxModernCommentAuthor } from 'pptx-viewer-core';
import { formatCommentTimestamp } from 'pptx-viewer-core';
import { computed, ref } from 'vue';
import { useI18n } from 'vue-i18n';

import CommentBody from './CommentBody.vue';
import CommentMentionTextarea from './CommentMentionTextarea.vue';

/**
 * CommentsPanel: side panel listing the active slide's comments.
 *
 * Presentational only: it renders the supplied `comments` (already filtered to
 * the active slide by the host) and surfaces add / remove / resolve intents via
 * emits. The host owns state and commits history-aware comment-array writes.
 *
 * Timestamps are formatted with the core `formatCommentTimestamp` helper so the
 * Vue binding matches the React/Angular formatting exactly.
 */
const props = defineProps<{
	comments: PptxComment[];
	authorName: string;
	/**
	 * True when hosted inside a chrome that already renders its own title +
	 * close button (the mobile `MobileSheet`). Suppresses the internal
	 * `<header>` so mobile doesn't show "Comments" twice stacked.
	 */
	embedded?: boolean;
	/** Modern comment authors (`ppt/commentAuthors.xml`), for the `@`-mention typeahead. */
	modernCommentAuthors?: PptxModernCommentAuthor[];
}>();

const emit = defineEmits<{
	add: [payload: { text: string; mentions?: PptxCommentMention[] }];
	remove: [id: string];
	resolve: [id: string];
	reply: [payload: { parentId: string; text: string; mentions?: PptxCommentMention[] }];
}>();

const { t } = useI18n();

const mentionAuthors = computed(() => props.modernCommentAuthors ?? []);

const draft = ref('');
const draftMentions = ref<PptxCommentMention[]>([]);

// Which comment currently has its reply box open, plus per-comment draft text
// and mentions. Only one reply box is open at a time, so a flat record keyed
// by comment id (rather than a single pair) just keeps a cancelled draft's
// mentions from leaking onto the next comment's reply box.
const replyingTo = ref<string | null>(null);
const replyDrafts = ref<Record<string, string>>({});
const replyMentions = ref<Record<string, PptxCommentMention[]>>({});

function startReply(id: string): void {
	replyingTo.value = id;
	if (!(id in replyDrafts.value)) {
		replyDrafts.value = { ...replyDrafts.value, [id]: '' };
		replyMentions.value = { ...replyMentions.value, [id]: [] };
	}
}

function submitReply(id: string): void {
	const text = (replyDrafts.value[id] ?? '').trim();
	if (text.length === 0) {
		return;
	}
	emit('reply', { parentId: id, text, mentions: replyMentions.value[id] });
	const nextDrafts = { ...replyDrafts.value };
	delete nextDrafts[id];
	replyDrafts.value = nextDrafts;
	const nextMentions = { ...replyMentions.value };
	delete nextMentions[id];
	replyMentions.value = nextMentions;
	replyingTo.value = null;
}

const canAdd = computed<boolean>(() => draft.value.trim().length > 0);

const submit = (): void => {
	const text = draft.value.trim();
	if (text.length === 0) {
		return;
	}
	emit('add', { text, mentions: draftMentions.value });
	draft.value = '';
	draftMentions.value = [];
};

const formatTimestamp = (value: string | undefined): string => formatCommentTimestamp(value);
</script>

<template>
	<aside
		class="pptx-comments-panel flex h-full min-h-0 w-full flex-col border-l border-border bg-card text-foreground"
		:aria-label="t('pptx.comments.slideComments')"
	>
		<header
			v-if="!embedded"
			class="pptx-comments-panel__header flex items-center justify-between border-b border-border px-4 py-3"
		>
			<h2 class="pptx-comments-panel__title m-0 text-sm font-semibold">
				{{ t('pptx.toolbar.comments') }}
			</h2>
			<span
				class="pptx-comments-panel__count text-xs text-muted-foreground"
				data-testid="comment-count"
			>
				{{ props.comments.length }}
			</span>
		</header>

		<ul
			v-if="props.comments.length > 0"
			class="pptx-comments-panel__list m-0 min-h-0 flex-1 list-none overflow-y-auto p-2"
		>
			<li
				v-for="comment in props.comments"
				:key="comment.id"
				class="pptx-comments-panel__item mb-2 rounded-lg border border-border px-3 py-2.5"
				:class="{ 'pptx-comments-panel__item--resolved opacity-60': comment.resolved }"
				:data-comment-id="comment.id"
			>
				<div class="pptx-comments-panel__meta mb-1 flex items-baseline justify-between gap-2">
					<span class="pptx-comments-panel__author text-[13px] font-semibold">{{
						comment.author || t('pptx.comments.unknownAuthor')
					}}</span>
					<time
						v-if="formatTimestamp(comment.createdAt)"
						class="pptx-comments-panel__time text-[11px] text-muted-foreground"
					>
						{{ formatTimestamp(comment.createdAt) }}
					</time>
				</div>
				<p class="pptx-comments-panel__text m-0 mb-2 whitespace-pre-wrap break-words text-[13px]">
					<CommentBody :text="comment.text" :mentions="comment.mentions" />
				</p>

				<!-- Threaded replies -->
				<ul
					v-if="comment.replies && comment.replies.length > 0"
					class="pptx-comments-panel__replies m-0 mb-2 list-none border-l-2 border-border pl-3"
				>
					<li
						v-for="reply in comment.replies"
						:key="reply.id"
						class="pptx-comments-panel__reply mb-1.5"
						:data-comment-id="reply.id"
					>
						<div class="mb-0.5 flex items-baseline justify-between gap-2">
							<span class="text-[12px] font-semibold">{{
								reply.author || t('pptx.comments.unknownAuthor')
							}}</span>
							<time
								v-if="formatTimestamp(reply.createdAt)"
								class="text-[11px] text-muted-foreground"
							>
								{{ formatTimestamp(reply.createdAt) }}
							</time>
						</div>
						<p class="m-0 whitespace-pre-wrap break-words text-[12px]">
							<CommentBody :text="reply.text" :mentions="reply.mentions" />
						</p>
					</li>
				</ul>

				<div class="pptx-comments-panel__actions flex gap-2">
					<button
						type="button"
						class="pptx-comments-panel__action cursor-pointer rounded-md border border-border bg-transparent px-2 py-1 text-xs text-foreground hover:bg-muted"
						:data-comment-id="comment.id"
						:aria-pressed="comment.resolved ? 'true' : 'false'"
						@click="emit('resolve', comment.id)"
					>
						{{ comment.resolved ? t('pptx.comments.reopen') : t('pptx.comments.resolve') }}
					</button>
					<button
						type="button"
						class="pptx-comments-panel__action cursor-pointer rounded-md border border-border bg-transparent px-2 py-1 text-xs text-foreground hover:bg-muted"
						:data-comment-id="comment.id"
						@click="startReply(comment.id)"
					>
						{{ t('pptx.comments.reply') }}
					</button>
					<button
						type="button"
						class="pptx-comments-panel__action pptx-comments-panel__action--danger cursor-pointer rounded-md border border-border bg-transparent px-2 py-1 text-xs text-red-400 hover:bg-muted"
						:data-comment-id="comment.id"
						:aria-label="t('pptx.comments.removeComment')"
						@click="emit('remove', comment.id)"
					>
						{{ t('pptx.comments.remove') }}
					</button>
				</div>

				<!-- Reply composer -->
				<div v-if="replyingTo === comment.id" class="mt-2 flex flex-col gap-1.5">
					<CommentMentionTextarea
						:model-value="replyDrafts[comment.id] ?? ''"
						:mentions="replyMentions[comment.id] ?? []"
						:authors="mentionAuthors"
						textarea-class="w-full resize-y rounded-md border border-border bg-background p-2 text-[12px] text-foreground"
						:rows="2"
						:placeholder="t('pptx.comments.replyPlaceholder')"
						:aria-label="t('pptx.comments.reply')"
						@update:model-value="replyDrafts[comment.id] = $event"
						@update:mentions="replyMentions[comment.id] = $event"
					/>
					<div class="flex justify-end gap-2">
						<button
							type="button"
							class="cursor-pointer rounded-md border border-border bg-transparent px-2 py-1 text-xs text-foreground hover:bg-muted"
							@click="replyingTo = null"
						>
							{{ t('pptx.comments.cancel') }}
						</button>
						<button
							type="button"
							class="cursor-pointer rounded-md border-none bg-primary px-2.5 py-1 text-xs text-primary-foreground disabled:cursor-not-allowed disabled:opacity-50"
							:disabled="(replyDrafts[comment.id] ?? '').trim().length === 0"
							@click="submitReply(comment.id)"
						>
							{{ t('pptx.comments.reply') }}
						</button>
					</div>
				</div>
			</li>
		</ul>

		<p
			v-else
			class="pptx-comments-panel__empty flex-1 p-4 text-[13px] text-muted-foreground"
			data-testid="comments-empty"
		>
			{{ t('pptx.comments.noneOnSlide') }}
		</p>

		<form
			class="pptx-comments-panel__compose flex flex-col gap-2 border-t border-border px-4 py-3"
			@submit.prevent="submit"
		>
			<label
				class="pptx-comments-panel__compose-label text-xs font-semibold"
				:title="t('pptx.comments.commentingAs', { name: props.authorName })"
			>
				{{ t('pptx.comments.addComment') }}
			</label>
			<CommentMentionTextarea
				v-model="draft"
				:mentions="draftMentions"
				:authors="mentionAuthors"
				textarea-class="pptx-comments-panel__textarea w-full resize-y rounded-md border border-border bg-background p-2 text-[13px] text-foreground"
				:rows="3"
				:placeholder="t('pptx.comments.addCommentPlaceholder')"
				:aria-label="t('pptx.comments.addComment')"
				@update:mentions="draftMentions = $event"
			/>
			<button
				type="submit"
				class="pptx-comments-panel__submit cursor-pointer self-end rounded-md border-none bg-primary px-3.5 py-1.5 text-[13px] text-primary-foreground disabled:cursor-not-allowed disabled:opacity-50"
				:disabled="!canAdd"
				data-testid="add-comment"
			>
				{{ t('pptx.comments.addComment') }}
			</button>
		</form>
	</aside>
</template>
