// packages/angular/src/viewer/mobile-presenter-view.component.ts
import { NgStyle } from '@angular/common';
import {
	ChangeDetectionStrategy,
	Component,
	DestroyRef,
	computed,
	inject,
	input,
	output,
	signal,
} from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import type { PptxElement, PptxSlide } from 'pptx-viewer-core';

import type { AuthoredSlideRange, CanvasSize, ShowOrderCustomShow } from '../internal/shared';
import {
	formatMobileElapsed,
	mobileElapsedSince,
	mobileNextThumbSize,
	mobileSlideCounter,
	presenterNextDisabled,
	presenterPrevDisabled,
} from '../internal/shared';
import { currentSlideAt, nextSlideAfter, resolvePresenterNotes } from './presenter-view-helpers';
import { SlideCanvasComponent } from './slide-canvas.component';

/** Clock tick interval (ms) for the elapsed-timer display. */
const CLOCK_TICK_MS = 1000;

/**
 * MobilePresenterViewComponent: single-column phone layout for presenter /
 * speaker view, shown instead of the desktop split-screen
 * `PresenterViewComponent` when the speaker enters presenter mode on a small
 * screen (the orchestrator branches on `IsMobileService.isMobile()`). The
 * desktop layout is left unchanged; only the layout differs.
 *
 * Top to bottom: header (elapsed timer + slide counter + exit), the current
 * slide large, a small next-slide thumbnail, scrollable speaker notes, and
 * prev/next controls; all offset by the device safe-area insets. Pure geometry
 * / labels / time formatting come from `pptx-viewer-shared` (`presenter-mobile`,
 * re-exported via `../internal/shared`). Slide rendering reuses
 * `pptx-slide-canvas` like the desktop presenter.
 *
 * Selector: `pptx-mobile-presenter-view`. Keyboard navigation is owned by the
 * orchestrator; this component registers no document keydown listener.
 */
@Component({
	selector: 'pptx-mobile-presenter-view',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [NgStyle, SlideCanvasComponent, TranslatePipe],
	styleUrl: './mobile-presenter-view.component.css',
	templateUrl: './mobile-presenter-view.component.html',
})
export class MobilePresenterViewComponent {
	// ------------------------------------------------------------------
	// Inputs
	// ------------------------------------------------------------------

	readonly slides = input.required<PptxSlide[]>();
	readonly currentSlideIndex = input.required<number>();
	/**
	 * The running custom show, or null for the whole deck. The "next slide"
	 * preview MUST honour it: while a show is playing, the slide the next
	 * forward press lands on is the show's next member, not `index + 1`.
	 */
	readonly activeCustomShow = input<ShowOrderCustomShow | null>(null);
	/**
	 * The deck's authored `p:showPr/p:sldRg` slide-range restriction, or null
	 * for the whole deck. The next-slide preview must honour it the same way it
	 * honours {@link activeCustomShow}.
	 */
	readonly authoredRange = input<AuthoredSlideRange | null>(null);
	readonly canvasSize = input.required<CanvasSize>();
	readonly templateElements = input<readonly PptxElement[]>([]);
	readonly mediaDataUrls = input<Map<string, string>>(new Map());
	readonly presentationStartTime = input<number | null>(null);

	// ------------------------------------------------------------------
	// Outputs
	// ------------------------------------------------------------------

	readonly movePresentationSlide = output<1 | -1>();
	readonly exit = output<void>();

	// ------------------------------------------------------------------
	// Internal state
	// ------------------------------------------------------------------

	/** Live wall-clock (epoch ms), advanced once per second. */
	private readonly now = signal(Date.now());

	constructor() {
		if (typeof setInterval !== 'undefined') {
			const handle = setInterval(() => this.now.set(Date.now()), CLOCK_TICK_MS);
			inject(DestroyRef).onDestroy(() => clearInterval(handle));
		}
	}

	// ------------------------------------------------------------------
	// Derived signals
	// ------------------------------------------------------------------

	protected readonly currentSlide = computed<PptxSlide | undefined>(() =>
		currentSlideAt(this.slides(), this.currentSlideIndex()),
	);

	protected readonly nextSlide = computed<PptxSlide | undefined>(() =>
		nextSlideAfter(
			this.slides(),
			this.currentSlideIndex(),
			this.activeCustomShow(),
			this.authoredRange(),
		),
	);

	protected readonly currentPreviewSlide = computed<PptxSlide | undefined>(() =>
		this.withTemplate(this.currentSlide()),
	);

	protected readonly nextPreviewSlide = computed<PptxSlide | undefined>(() =>
		this.withTemplate(this.nextSlide()),
	);

	protected readonly notes = computed(() => resolvePresenterNotes(this.currentSlide()));

	protected readonly elapsedLabel = computed<string>(() =>
		formatMobileElapsed(mobileElapsedSince(this.presentationStartTime(), this.now())),
	);

	protected readonly counterLabel = computed<string>(() =>
		mobileSlideCounter(this.currentSlideIndex(), this.slides().length),
	);

	// The desktop console's rules, not a phone-sized copy of them: Next stays live
	// on the last slide so the presenter can reach the end-of-show screen and
	// finish, exactly as the split-screen console does.
	protected readonly prevDisabled = computed<boolean>(() =>
		presenterPrevDisabled(this.currentSlideIndex()),
	);

	protected readonly nextDisabled = computed<boolean>(() => presenterNextDisabled());

	/** Next-slide thumbnail box (CSS px); width drives the slide-canvas autoFit. */
	protected readonly thumbStyle = computed(() => {
		const size = this.canvasSize();
		const thumb = mobileNextThumbSize(size.width, size.height);
		return { width: `${thumb.width}px`, height: `${thumb.height}px` };
	});

	// ------------------------------------------------------------------
	// Helpers
	// ------------------------------------------------------------------

	private withTemplate(slide: PptxSlide | undefined): PptxSlide | undefined {
		if (!slide) {
			return undefined;
		}
		const template = this.templateElements();
		if (template.length === 0) {
			return slide;
		}
		return { ...slide, elements: [...template, ...slide.elements] };
	}
}

@if (currentSlide(); as current) {
	<!-- Header: elapsed + counter + exit -->
	<div class="pptx-ng-mpresenter-header">
		<div>
			<div class="pptx-ng-mpresenter-label">{{ 'pptx.presenter.elapsed' | translate }}</div>
			<div class="pptx-ng-mpresenter-elapsed">{{ elapsedLabel() }}</div>
		</div>
		<span class="pptx-ng-mpresenter-counter">{{ counterLabel() }}</span>
		<button
			type="button"
			class="pptx-ng-mpresenter-exit"
			(click)="exit.emit()"
			[attr.aria-label]="'pptx.presenter.endPresentation' | translate"
			[title]="'pptx.presenter.endPresentation' | translate"
		>
			&#x2715;
		</button>
	</div>

	<!-- Current slide (large) -->
	<div class="pptx-ng-mpresenter-main">
		<div class="pptx-ng-mpresenter-main-stage">
			<pptx-slide-canvas
				[slide]="currentPreviewSlide()"
				[canvasSize]="canvasSize()"
				[mediaDataUrls]="mediaDataUrls()"
				[zoom]="1"
				[interactive]="false"
			/>
		</div>
	</div>

	<!-- Next thumbnail -->
	<div class="pptx-ng-mpresenter-next">
		<span class="pptx-ng-mpresenter-label">{{
			'pptx.presenter.nextSlidePreview' | translate
		}}</span>
		@if (nextPreviewSlide(); as next) {
			<div class="pptx-ng-mpresenter-thumb" [ngStyle]="thumbStyle()">
				<pptx-slide-canvas
					[slide]="next"
					[canvasSize]="canvasSize()"
					[mediaDataUrls]="mediaDataUrls()"
					[zoom]="1"
					[interactive]="false"
				/>
			</div>
		} @else {
			<div class="pptx-ng-mpresenter-next-empty">
				{{ 'pptx.presenter.endOfPresentation' | translate }}
			</div>
		}
	</div>

	<!-- Speaker notes (scrollable) -->
	<div class="pptx-ng-mpresenter-notes">
		<div class="pptx-ng-mpresenter-label">{{ 'pptx.presenter.speakerNotes' | translate }}</div>
		<div class="pptx-ng-mpresenter-notes-body">
			@if (notes().hasRichNotes) {
				@for (seg of notes().segments; track seg.key) {
					@if (seg.isBreak) {
						<br />
					} @else {
						<span [ngStyle]="seg.style">{{ seg.text }}</span>
					}
				}
			} @else if (notes().hasAnyNotes) {
				{{ notes().plainText }}
			} @else {
				<span class="pptx-ng-mpresenter-notes-empty">{{
					'pptx.presenter.noNotes' | translate
				}}</span>
			}
		</div>
	</div>

	<!-- Prev / Next controls -->
	<div class="pptx-ng-mpresenter-ctl">
		<button
			type="button"
			class="pptx-ng-mpresenter-navbtn"
			data-pptx-presenter-control="prev"
			(click)="movePresentationSlide.emit(-1)"
			[disabled]="prevDisabled()"
			[attr.aria-label]="'pptx.presenter.previousSlide' | translate"
			[title]="'pptx.presenter.previousSlide' | translate"
		>
			&#x2039; {{ 'pptx.presenter.prev' | translate }}
		</button>
		<button
			type="button"
			class="pptx-ng-mpresenter-navbtn"
			data-pptx-presenter-control="next"
			(click)="movePresentationSlide.emit(1)"
			[disabled]="nextDisabled()"
			[attr.aria-label]="'pptx.presenter.nextSlide' | translate"
			[title]="'pptx.presenter.nextSlide' | translate"
		>
			{{ 'pptx.presenter.next' | translate }} &#x203A;
		</button>
	</div>
} @else {
	<div class="pptx-ng-mpresenter-empty">{{ 'pptx.presenter.noSlides' | translate }}</div>
}

// packages/vue/src/viewer/components/MobilePresenterView.vue
<script setup lang="ts">
import { ChevronLeft, ChevronRight, X } from 'lucide-vue-next';
import type { PptxSlide } from 'pptx-viewer-core';
import type { AuthoredSlideRange } from 'pptx-viewer-shared';
import {
	formatMobileElapsed,
	mobileElapsedSince,
	mobileNextThumbSize,
	mobileSlideCounter,
	nextPresentedSlide,
	presenterNextDisabled,
	presenterPrevDisabled,
} from 'pptx-viewer-shared';
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';
import { useI18n } from 'vue-i18n';

import { notesSegmentsToSpans } from '../composables/presenter-view-utils';
import type { CanvasSize } from '../types';
import SlideStage from './SlideStage.vue';

/**
 * MobilePresenterView - single-column phone layout for presenter/speaker view.
 *
 * Shown instead of the desktop split-screen `PresenterView` when the speaker
 * enters presenter mode on a small screen (the host `PresentationMode` branches
 * on `useIsMobile`). The desktop layout is left unchanged; only the layout
 * differs. Pure geometry / labels / time formatting come from
 * `pptx-viewer-shared` (`presenter-mobile`).
 *
 * Top to bottom: header (elapsed timer + counter + exit), the current slide
 * large, a small next-slide thumbnail, scrollable speaker notes, and prev/next
 * controls; all offset by the device safe-area insets.
 */
const props = defineProps<{
	slides: PptxSlide[];
	currentSlideIndex: number;
	canvasSize: CanvasSize;
	mediaDataUrls: Map<string, string>;
	/** Timestamp (ms) the presentation started, or `null`. */
	presentationStartTime: number | null;
	/** Membership of the running custom show, when one is playing. */
	activeCustomShow?: { slideRIds: string[] } | null;
	/** `p:showPr/p:sldRg`, resolved to deck indexes; `null`/`undefined` for no range. */
	authoredRange?: AuthoredSlideRange | null;
}>();

const emit = defineEmits<{
	(e: 'move', direction: 1 | -1): void;
	(e: 'exit'): void;
}>();

const { t } = useI18n();

// -- Live elapsed timer (1 Hz tick) -----------------------------------------
const now = ref(Date.now());
let clockId: ReturnType<typeof setInterval> | null = null;

onMounted(() => {
	clockId = setInterval(() => {
		now.value = Date.now();
	}, 1000);
});

onBeforeUnmount(() => {
	if (clockId !== null) {
		clearInterval(clockId);
		clockId = null;
	}
});

const elapsedText = computed(() =>
	formatMobileElapsed(mobileElapsedSince(props.presentationStartTime, now.value)),
);

// -- Slide data -------------------------------------------------------------
const currentSlide = computed<PptxSlide | undefined>(() => props.slides[props.currentSlideIndex]);
// The preview must be the slide the next advance really lands on, so it runs
// the shared show-order rule: it skips slides the author hid, and follows the
// running custom show's order rather than the deck's.
const nextSlide = computed<PptxSlide | undefined>(() =>
	nextPresentedSlide(
		props.slides,
		props.currentSlideIndex,
		props.activeCustomShow,
		props.authoredRange,
	),
);

const counterText = computed(() =>
	mobileSlideCounter(props.currentSlideIndex, props.slides.length),
);
// The desktop console's rules, not a phone-sized copy of them: Next stays live
// on the last slide so the presenter can reach the end-of-show screen and
// finish, exactly as the split-screen console does.
const prevDisabled = computed(() => presenterPrevDisabled(props.currentSlideIndex));
const nextDisabled = computed(() => presenterNextDisabled());

const notesText = computed(() => currentSlide.value?.notes ?? '');
const notesSpans = computed(() => {
	const segments = currentSlide.value?.notesSegments;
	return segments && segments.length > 0 ? notesSegmentsToSpans(segments) : null;
});
const hasPlainNotes = computed(() => notesText.value.trim().length > 0);

// -- Main-stage scaling: fit the slide into the column width (a notional box;
// the flex layout + overflow clipping handle the rest).
const MAIN_FIT_WIDTH = 640;
const mainScale = computed(() => {
	const { width } = props.canvasSize;
	return width > 0 ? MAIN_FIT_WIDTH / width : 1;
});
const mainFrameStyle = computed(() => ({
	width: `${props.canvasSize.width * mainScale.value}px`,
	height: `${props.canvasSize.height * mainScale.value}px`,
}));

// -- Next-slide thumbnail geometry (shared) ---------------------------------
const thumb = computed(() => mobileNextThumbSize(props.canvasSize.width, props.canvasSize.height));
const thumbFrameStyle = computed(() => ({
	width: `${thumb.value.width}px`,
	height: `${thumb.value.height}px`,
}));
</script>

<template>
	<div
		v-if="!currentSlide"
		class="pptx-vue-mpresenter pptx-vue-mpresenter--empty absolute inset-0 z-50 flex items-center justify-center bg-card text-muted-foreground"
	>
		{{ t('pptx.mpresenter.noSlides') }}
	</div>
	<div
		v-else
		class="pptx-vue-mpresenter absolute inset-0 z-50 flex flex-col bg-card text-foreground"
	>
		<!-- Header: elapsed + counter + exit -->
		<div
			class="pptx-vue-mpresenter-header flex items-center justify-between gap-2 border-b border-border/60 px-4 py-2"
		>
			<div class="flex flex-col">
				<span class="text-[10px] uppercase tracking-wider text-muted-foreground">{{
					t('pptx.mpresenter.elapsed')
				}}</span>
				<span class="font-mono text-lg tabular-nums text-primary">{{ elapsedText }}</span>
			</div>
			<span class="font-mono text-sm tabular-nums text-foreground">{{ counterText }}</span>
			<button
				type="button"
				class="pptx-vue-mpresenter-exit flex h-11 w-11 items-center justify-center rounded text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
				:title="t('pptx.presenter.endPresentation')"
				:aria-label="t('pptx.presenter.endPresentation')"
				@click="emit('exit')"
			>
				<X class="w-5 h-5" aria-hidden="true" />
			</button>
		</div>

		<!-- Current slide (large) -->
		<div class="pptx-vue-mpresenter-main flex items-center justify-center bg-black px-3 py-3">
			<div class="relative overflow-hidden" :style="mainFrameStyle">
				<SlideStage
					:slide="currentSlide"
					:canvas-size="canvasSize"
					:media-data-urls="mediaDataUrls"
					:scale="mainScale"
				/>
			</div>
		</div>

		<!-- Next thumbnail -->
		<div
			class="pptx-vue-mpresenter-next flex items-center gap-3 border-b border-border/60 px-4 py-2"
		>
			<span class="whitespace-nowrap text-[10px] uppercase tracking-wider text-muted-foreground">{{
				t('pptx.presenter.nextSlidePreview')
			}}</span>
			<div
				v-if="nextSlide"
				class="relative flex-shrink-0 overflow-hidden rounded border border-border/30"
				:style="thumbFrameStyle"
			>
				<SlideStage
					:slide="nextSlide"
					:canvas-size="canvasSize"
					:media-data-urls="mediaDataUrls"
					:scale="thumb.scale"
				/>
			</div>
			<div
				v-else
				class="flex h-12 flex-1 items-center justify-center rounded border border-border/30 bg-muted/40 text-[10px] italic text-muted-foreground"
			>
				{{ t('pptx.mpresenter.endOfPresentation') }}
			</div>
		</div>

		<!-- Speaker notes (scrollable) -->
		<div class="pptx-vue-mpresenter-notes flex flex-1 min-h-0 flex-col px-4 py-2">
			<div class="mb-1 text-[10px] uppercase tracking-wider text-muted-foreground">
				{{ t('pptx.presenter.speakerNotes') }}
			</div>
			<div
				class="flex-1 overflow-y-auto whitespace-pre-wrap rounded border border-border/30 bg-muted/40 px-3 py-2 text-[15px] leading-relaxed text-foreground"
			>
				<template v-if="notesSpans">
					<template v-for="span in notesSpans" :key="span.key">
						<br v-if="span.kind === 'break'" />
						<span v-else :style="span.style">{{ span.text }}</span>
					</template>
				</template>
				<template v-else-if="hasPlainNotes">{{ notesText }}</template>
				<span v-else class="italic text-muted-foreground">{{ t('pptx.mpresenter.noNotes') }}</span>
			</div>
		</div>

		<!-- Prev / Next controls -->
		<div
			class="pptx-vue-mpresenter-ctl flex items-center justify-between gap-3 border-t border-border/60 px-4 py-2"
		>
			<button
				type="button"
				class="inline-flex h-11 flex-1 items-center justify-center gap-1.5 rounded bg-muted text-sm transition-colors hover:bg-accent disabled:cursor-not-allowed disabled:opacity-40"
				data-pptx-presenter-control="prev"
				:disabled="prevDisabled"
				:title="t('pptx.presenter.previousSlide')"
				:aria-label="t('pptx.presenter.previousSlide')"
				@click="emit('move', -1)"
			>
				<ChevronLeft class="w-5 h-5" aria-hidden="true" />
				{{ t('pptx.mpresenter.prev') }}
			</button>
			<button
				type="button"
				class="inline-flex h-11 flex-1 items-center justify-center gap-1.5 rounded bg-muted text-sm transition-colors hover:bg-accent disabled:cursor-not-allowed disabled:opacity-40"
				data-pptx-presenter-control="next"
				:disabled="nextDisabled"
				:title="t('pptx.presenter.nextSlide')"
				:aria-label="t('pptx.presenter.nextSlide')"
				@click="emit('move', 1)"
			>
				{{ t('pptx.mpresenter.next') }}
				<ChevronRight class="w-5 h-5" aria-hidden="true" />
			</button>
		</div>
	</div>
</template>

<style scoped>
.pptx-vue-mpresenter {
	padding-top: env(safe-area-inset-top, 0px);
	padding-bottom: env(safe-area-inset-bottom, 0px);
	padding-left: env(safe-area-inset-left, 0px);
	padding-right: env(safe-area-inset-right, 0px);
}
</style>
