// packages/angular/src/viewer/mobile-bottom-bar.component.ts
/**
 * mobile-bottom-bar.component.ts: Persistent mobile bottom action bar.
 *
 * Ported from: packages/react/src/viewer/components/mobile/MobileBottomBar.tsx
 *
 * A fixed-to-bottom bar exposing the five primary per-selection / per-slide
 * actions for mobile editing, mirroring React's slot set:
 *
 *   Slides · Insert · Format · Comments · Notes
 *
 * Each slot either opens a bottom sheet/panel (slides / format / comments /
 * notes) or triggers an action (insert). The Menu, Undo/Redo and Present
 * controls live in the compact top toolbar (`MobileToolbarComponent`).
 *
 * The host renders a `<nav aria-label="Editor actions">` so it matches the
 * framework-neutral accessibility contract the e2e specs assert against
 * (`getByRole('navigation', { name: 'Editor actions' })`).
 *
 * Icons and colours come from the same Lucide glyphs and `--pptx-*` theme
 * tokens React uses. Each input/output is documented on its declaration below.
 */

import { ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';
import {
	LucideLayers,
	LucideMessageSquare,
	LucidePlus,
	LucideSettings2,
	LucideStickyNote,
} from '@lucide/angular';
import { TranslatePipe } from '@ngx-translate/core';

import { buildBarActions } from './mobile-chrome-helpers';

/** Which mobile sheet/panel is currently active (highlights its button). */
export type MobileBarSheet = 'slides' | 'inspector' | 'comments' | 'notes' | null;

/** Internal action descriptor used to build the bar. */
interface BarAction {
	key: NonNullable<MobileBarSheet> | 'insert';
	labelKey: string;
	ariaLabelKey?: string;
	disabled: boolean;
	active: boolean;
	badge?: number;
	emit: () => void;
}

@Component({
	selector: 'pptx-mobile-bottom-bar',
	standalone: true,
	imports: [
		LucideLayers,
		LucideMessageSquare,
		LucidePlus,
		LucideSettings2,
		LucideStickyNote,
		TranslatePipe,
	],
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `
		<nav class="pptx-ng-mbar" [attr.aria-label]="'pptx.mobileBar.ariaLabel' | translate">
			@for (action of actions(); track action.key) {
				<button
					type="button"
					class="pptx-ng-mbar-btn"
					[class.is-active]="action.active"
					[attr.aria-pressed]="action.active ? true : null"
					[attr.aria-label]="action.ariaLabelKey ?? action.labelKey | translate"
					[disabled]="action.disabled"
					(click)="action.emit()"
				>
					@switch (action.key) {
						@case ('slides') {
							<svg lucideLayers class="pptx-ng-mbar-icon" aria-hidden="true"></svg>
						}
						@case ('insert') {
							<svg lucidePlus class="pptx-ng-mbar-icon" aria-hidden="true"></svg>
						}
						@case ('inspector') {
							<svg lucideSettings2 class="pptx-ng-mbar-icon" aria-hidden="true"></svg>
						}
						@case ('comments') {
							<svg lucideMessageSquare class="pptx-ng-mbar-icon" aria-hidden="true"></svg>
						}
						@case ('notes') {
							<svg lucideStickyNote class="pptx-ng-mbar-icon" aria-hidden="true"></svg>
						}
					}
					<span class="pptx-ng-mbar-label">{{ action.labelKey | translate }}</span>
					@if (action.badge && action.badge > 0) {
						<span class="pptx-ng-mbar-badge" aria-hidden="true">
							{{ action.badge > 99 ? '99+' : action.badge }}
						</span>
					}
					@if (action.active) {
						<span class="pptx-ng-mbar-indicator" aria-hidden="true"></span>
					}
				</button>
			}
		</nav>
	`,
	styles: [
		`
			:host {
				display: block;
			}

			/* ── Navigation bar ── */

			/*
			 * Themed chrome: the same semantic tokens React's MobileBottomBar
			 * resolves through Tailwind (bg-secondary/80, dropping to /60 when
			 * backdrop-filter is supported, plus border-border), so a ViewerTheme
			 * preset restyles the bar instead of leaving it on a hardcoded
			 * near-black that clashes with the rest of the chrome.
			 */
			.pptx-ng-mbar {
				display: flex;
				align-items: stretch;
				justify-content: space-around;
				background: color-mix(in srgb, var(--pptx-secondary, #1f2937) 80%, transparent);
				border-top: 1px solid var(--pptx-border, #374151);
				padding-bottom: max(env(safe-area-inset-bottom, 0px), 0px);
			}

			@supports ((backdrop-filter: blur(12px)) or (-webkit-backdrop-filter: blur(12px))) {
				.pptx-ng-mbar {
					background: color-mix(in srgb, var(--pptx-secondary, #1f2937) 60%, transparent);
					backdrop-filter: blur(12px);
					-webkit-backdrop-filter: blur(12px);
				}
			}

			/* ── Individual button ── */

			.pptx-ng-mbar-btn {
				position: relative;
				display: flex;
				flex-direction: column;
				align-items: center;
				justify-content: center;
				gap: 0.125rem;
				flex: 1;
				min-height: 56px;
				padding: 0.375rem 0.25rem;
				border: none;
				background: transparent;
				color: var(--pptx-muted-foreground, #9ca3af);
				font-size: 0.625rem;
				font-weight: 500;
				cursor: pointer;
				touch-action: manipulation;
				transition:
					color 0.12s,
					transform 0.08s;
				-webkit-tap-highlight-color: transparent;
			}

			.pptx-ng-mbar-btn:active:not([disabled]) {
				transform: scale(0.92);
			}

			.pptx-ng-mbar-btn.is-active {
				color: var(--pptx-primary, #6366f1);
			}

			.pptx-ng-mbar-btn:hover:not([disabled]):not(.is-active) {
				color: var(--pptx-foreground, #f3f4f6);
			}

			.pptx-ng-mbar-btn[disabled] {
				opacity: 0.35;
				cursor: not-allowed;
			}

			/* ── Icon ── */

			.pptx-ng-mbar-icon {
				width: 1.25rem;
				height: 1.25rem;
				flex-shrink: 0;
			}

			/* ── Label ── */

			.pptx-ng-mbar-label {
				line-height: 1;
				white-space: nowrap;
			}

			/* ── Badge (numeric count) ── */

			.pptx-ng-mbar-badge {
				position: absolute;
				top: 0.25rem;
				right: calc(50% - 1.25rem);
				display: flex;
				align-items: center;
				justify-content: center;
				min-width: 1rem;
				height: 1rem;
				padding: 0 0.25rem;
				border-radius: 9999px;
				background: var(--pptx-primary, #6366f1);
				color: var(--pptx-primary-foreground, #ffffff);
				font-size: 0.5625rem;
				font-weight: 600;
				line-height: 1;
			}

			/* ── Active indicator stripe ── */

			.pptx-ng-mbar-indicator {
				position: absolute;
				top: 0;
				left: 50%;
				transform: translateX(-50%);
				width: 2rem;
				height: 0.1875rem;
				border-radius: 9999px;
				background: var(--pptx-primary, #6366f1);
			}
		`,
	],
})
export class MobileBottomBarComponent {
	// ── Inputs ────────────────────────────────────────────────────────────────

	/** Total number of slides in the presentation. */
	readonly slideCount = input<number>(0);

	/** Number of comments on the active slide (for the badge). */
	readonly commentCount = input<number>(0);

	/** Currently-active sheet/panel (highlights its button). */
	readonly activeSheet = input<MobileBarSheet>(null);

	// ── Outputs ───────────────────────────────────────────────────────────────

	/** User tapped the Slides thumbnail strip button. */
	readonly openSlides = output<void>();
	/** User tapped the Insert button. */
	readonly insert = output<void>();
	/** User tapped the Format (inspector) button. */
	readonly openFormat = output<void>();
	/** User tapped the Comments button. */
	readonly openComments = output<void>();
	/** User tapped the Notes button. */
	readonly notes = output<void>();

	// ── Derived action list ───────────────────────────────────────────────────

	// Shared `buildBarActions` decides which slots are disabled (no slides
	// loaded); this binding only maps the resulting descriptor's `key` and
	// `disabled` onto its own labels, icons and outputs.
	readonly actions = computed<BarAction[]>(() => {
		const active = this.activeSheet(),
			disabledByKey = new Map(
				buildBarActions({ slideCount: this.slideCount() }).map((descriptor) => [
					descriptor.key,
					descriptor.disabled,
				]),
			);
		return [
			{
				key: 'slides',
				labelKey: 'pptx.sections.slides',
				disabled: disabledByKey.get('slides') ?? false,
				active: active === 'slides',
				emit: () => this.openSlides.emit(),
			},
			{
				key: 'insert',
				labelKey: 'pptx.editorToolbar.insert',
				disabled: disabledByKey.get('insert') ?? false,
				active: false,
				emit: () => this.insert.emit(),
			},
			{
				key: 'inspector',
				labelKey: 'pptx.arrange.format',
				disabled: disabledByKey.get('inspector') ?? false,
				active: active === 'inspector',
				emit: () => this.openFormat.emit(),
			},
			{
				key: 'comments',
				labelKey: 'pptx.toolbar.comments',
				disabled: disabledByKey.get('comments') ?? false,
				active: active === 'comments',
				badge: this.commentCount(),
				emit: () => this.openComments.emit(),
			},
			{
				key: 'notes',
				labelKey: 'pptx.notes.title',
				ariaLabelKey: 'pptx.statusBar.toggleNotes',
				disabled: disabledByKey.get('notes') ?? false,
				active: active === 'notes',
				emit: () => this.notes.emit(),
			},
		];
	});
}

// packages/vue/src/viewer/components/MobileBottomBar.vue
<script setup lang="ts">
/**
 * MobileBottomBar - the Vue port of React's mobile bottom navigation
 * (`packages/react/src/viewer/components/mobile/MobileBottomBar.tsx`).
 *
 * Five labelled destination tabs - Slides / Insert / Format / Comments / Notes -
 * each opening a bottom sheet (or, for Insert, quick-inserting a text box),
 * matching the navigation pattern of Office Mobile and Google Slides. The active
 * tab is tinted and carries a top pill indicator.
 *
 * Slide navigation is a horizontal swipe and zoom is a pinch (both handled on the
 * canvas), so this bar carries no prev/next or zoom controls; Present, Save and
 * the section menu live in the top `MobileToolbar`. That division mirrors React,
 * whose mobile StatusBar is hidden and whose bottom bar is purely these five
 * targets.
 *
 * Conventions vs. React: function-prop callbacks become emits. The Vue package
 * has a Tailwind build (see `src/styles/pptx-vue-viewer.css`), so the utility
 * classes are used directly, like React, rather than hand-written scoped CSS.
 */
import { Layers, MessageSquare, Plus, Settings2, StickyNote } from 'lucide-vue-next';
import type { ActionDescriptor } from 'pptx-viewer-shared';
import { buildBarActions } from 'pptx-viewer-shared';
import type { FunctionalComponent } from 'vue';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import type { MobileActiveSheet } from '../composables/useMobileChrome';

const { t } = useI18n();

const props = withDefaults(
	defineProps<{
		/** Total number of slides in the presentation; every tab disables at 0. */
		slideCount?: number;
		/** The currently-open sheet, so its tab renders active. */
		activeSheet?: MobileActiveSheet;
		/** Number of comments on the active slide (renders a badge, capped at 99+). */
		commentCount?: number;
		/**
		 * CSS pixels the on-screen keyboard covers. When > 0 the fixed bar lifts by
		 * this amount so it stays above the keyboard instead of under it.
		 */
		keyboardInset?: number;
	}>(),
	{ slideCount: 0 },
);

const emit = defineEmits<{
	slides: [];
	insert: [];
	format: [];
	comments: [];
	notes: [];
}>();

type TabKey = 'slides' | 'insert' | 'format' | 'comments' | 'notes';

interface Tab {
	/** Sheet key; `insert` is a fire action and never renders active. */
	key: TabKey;
	labelKey: string;
	icon: FunctionalComponent;
	/** Overrides the visible label as the accessible name (React does this for Notes). */
	ariaLabelKey?: string;
	badge?: number;
	disabled: boolean;
}

/**
 * Per-tab display metadata, plus the shared `buildBarActions` key each tab
 * maps from (the shared vocabulary calls the format tab `inspector`).
 */
const TAB_META: Record<
	TabKey,
	{ labelKey: string; icon: FunctionalComponent; sharedKey: ActionDescriptor['key'] }
> = {
	slides: { labelKey: 'pptx.sections.slides', icon: Layers, sharedKey: 'slides' },
	insert: { labelKey: 'pptx.mobileBar.insert', icon: Plus, sharedKey: 'insert' },
	format: { labelKey: 'pptx.field.format', icon: Settings2, sharedKey: 'inspector' },
	comments: { labelKey: 'pptx.toolbar.comments', icon: MessageSquare, sharedKey: 'comments' },
	notes: { labelKey: 'pptx.notes.title', icon: StickyNote, sharedKey: 'notes' },
};

// Shared `buildBarActions` decides which tabs are disabled (no slides
// loaded); this binding only maps the resulting descriptor onto its own
// icons, labels and click handlers.
const tabs = computed<Tab[]>(() => {
	const disabledBySharedKey = new Map(
		buildBarActions({ slideCount: props.slideCount ?? 0 }).map((descriptor) => [
			descriptor.key,
			descriptor.disabled,
		]),
	);
	return (Object.keys(TAB_META) as TabKey[]).map((key) => {
		const meta = TAB_META[key];
		return {
			key,
			labelKey: meta.labelKey,
			icon: meta.icon,
			ariaLabelKey: key === 'notes' ? 'pptx.statusBar.toggleNotes' : undefined,
			badge: key === 'comments' ? props.commentCount : undefined,
			disabled: disabledBySharedKey.get(meta.sharedKey) ?? false,
		};
	});
});

/**
 * Fire the emit for a tapped tab. Vue's typed `emit` is an overload set that
 * rejects a union argument, so dispatch each event name as a literal.
 */
function onTab(key: TabKey): void {
	switch (key) {
		case 'slides':
			emit('slides');
			break;
		case 'insert':
			emit('insert');
			break;
		case 'format':
			emit('format');
			break;
		case 'comments':
			emit('comments');
			break;
		case 'notes':
			emit('notes');
			break;
	}
}

/** Comment-count badge text, capped at "99+" like the React mobile bar. */
function badgeText(count: number | undefined): string | null {
	if (count === undefined || count <= 0) {
		return null;
	}
	return count > 99 ? '99+' : String(count);
}

/** Translate the fixed bar up above the on-screen keyboard, if one is open. */
const barStyle = computed(() => {
	const inset = props.keyboardInset ?? 0;
	if (inset <= 0) {
		return undefined;
	}
	return {
		transform: `translateY(-${inset}px)`,
		transition: 'transform 150ms ease-out',
		willChange: 'transform',
	};
});
</script>

<template>
	<nav
		class="pptx-vue-mobile-bar fixed bottom-0 left-0 right-0 z-40 flex items-stretch justify-around border-t border-border bg-secondary/80 backdrop-blur supports-[backdrop-filter]:bg-secondary/60 pb-[max(env(safe-area-inset-bottom),0px)]"
		:style="barStyle"
		:aria-label="t('pptx.mobileBar.ariaLabel')"
	>
		<button
			v-for="tab in tabs"
			:key="tab.key"
			type="button"
			class="pptx-vue-mobile-tab relative flex flex-col items-center justify-center gap-0.5 flex-1 min-h-[56px] py-1.5 text-[10px] font-medium transition-colors active:scale-95 disabled:opacity-40 disabled:cursor-not-allowed"
			:class="
				activeSheet === tab.key ? 'text-primary' : 'text-muted-foreground hover:text-foreground'
			"
			:disabled="tab.disabled"
			:aria-pressed="activeSheet === tab.key"
			:aria-label="tab.ariaLabelKey ? t(tab.ariaLabelKey) : undefined"
			@click="onTab(tab.key)"
		>
			<component :is="tab.icon" class="w-5 h-5" aria-hidden="true" />
			<span>{{ t(tab.labelKey) }}</span>
			<span
				v-if="badgeText(tab.badge)"
				class="pptx-vue-mobile-badge absolute top-1 right-1/4 flex items-center justify-center min-w-[16px] h-4 px-1 rounded-full bg-primary text-[9px] font-semibold text-white"
				aria-hidden="true"
				>{{ badgeText(tab.badge) }}</span
			>
			<span
				v-if="activeSheet === tab.key"
				class="absolute top-0 left-1/2 -translate-x-1/2 w-8 h-0.5 rounded-full bg-primary"
				aria-hidden="true"
			/>
		</button>
	</nav>
</template>
