// packages/angular/src/viewer/pie-chart-3d-renderer.component.ts
import { NgStyle } from '@angular/common';
import {
	afterNextRender,
	ChangeDetectionStrategy,
	Component,
	computed,
	effect,
	ElementRef,
	input,
	OnDestroy,
	output,
	signal,
	viewChild,
} from '@angular/core';
import type { PptxElement } from 'pptx-viewer-core';

import { buildPieChart3DDataForElement } from '../internal/shared';
import type { ChartPartRef, PieChart3DHandle, PieChart3DSceneOptions } from '../internal/shared';
// Type-only import of the shared scene controller; the implementation (which
// pulls the optional `three` peer) is loaded lazily via dynamic import so it
// never lands in the main bundle.
import type {
	mountPieChart3D as MountPieChart3D,
	PieChart3DInteraction,
} from '../internal/shared-src/render/pie-chart-3d-scene';
import { Chart3DSceneMount } from './chart-3d-scene-mount';
import { ChartRendererComponent } from './chart-renderer.component';

type MountFn = typeof MountPieChart3D;

/**
 * PieChart3DRendererComponent: Angular interactive 3D pie3D-chart view.
 *
 * When the chart resolves to a plottable wedge-mesh layout (see
 * {@link buildPieChart3DDataForElement}) and the optional `three` peer
 * dependency is installed, this mounts the shared, framework-agnostic
 * vanilla-three controller ({@link MountPieChart3D} from
 * `pptx-viewer-shared`) into a container `<div>` for a camera-orbitable
 * wedge scene (OrbitControls: drag to rotate, scroll to zoom). The
 * controller's scene runtime (and `three`) is imported lazily via dynamic
 * `import()` so it never lands in the main bundle.
 *
 * Falls back to the plain SVG `<pptx-chart-renderer>` when:
 *  - the chart has no plottable series,
 *  - `three` is not installed (`mountPieChart3D` resolves to the `ok: false`
 *    sentinel),
 *  - or the scene fails to load.
 *
 * Wedges are click-to-select (`partSelect`, mirroring the 2D chart's
 * `ChartPartSelectionService` wiring one level up in
 * `ChartElementViewComponent`) and drag-to-value (`valueDragPreview`/
 * `valueDragCommit`) via the shared `PieChart3DInteraction` wiring: dragging
 * sweeps a wedge's trailing edge around the pie's centre, renormalising every
 * other slice's angle live, exactly like the flat SVG pie/doughnut's own
 * on-canvas editing. The scene draws no axis labels, so unlike
 * bar3D/line3D/area3D/surface3D there is no `textStyle` input. `selectedPart`
 * re-applies the wedge-emissive highlight when the selection changes from
 * outside this scene (inspector, keyboard).
 */
@Component({
	selector: 'pptx-pie-chart-3d-renderer',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [NgStyle, ChartRendererComponent],
	template: `
		@if (showScene()) {
			<div #scene class="pptx-ng-pie-chart-3d-scene" [ngStyle]="sceneStyle()"></div>
		} @else {
			<pptx-chart-renderer [element]="element()" />
		}
	`,
	styles: `
		.pptx-ng-pie-chart-3d-scene {
			width: 100%;
			height: 100%;
			display: block;
		}
	`,
})
export class PieChart3DRendererComponent implements OnDestroy {
	readonly element = input.required<PptxElement>();
	/** The part selected elsewhere (inspector, keyboard), or null. Applied to the live scene. */
	readonly selectedPart = input<ChartPartRef | null>(null);

	/** Emitted when a wedge (or empty space, `null`) is clicked. */
	readonly partSelect = output<ChartPartRef | null>();
	/** Emitted continuously while dragging a wedge's value around the pie (live preview). */
	readonly valueDragPreview = output<{ part: ChartPartRef; value: number }>();
	/** Emitted once on release with the final dragged value. */
	readonly valueDragCommit = output<{ part: ChartPartRef; value: number }>();

	private readonly sceneRef = viewChild<ElementRef<HTMLDivElement>>('scene');

	/** Pure wedge-mesh layout for the current element, or `null` when not plottable. */
	private readonly options = computed<PieChart3DSceneOptions | null>(() =>
		buildPieChart3DDataForElement(this.element(), {
			width: this.element().width,
			height: this.element().height,
		}),
	);

	protected readonly sceneStyle = computed(() => ({
		width: `${this.element().width}px`,
		height: `${this.element().height}px`,
	}));

	/** Lazily-loaded shared mount fn; `null` until the scene runtime resolves. */
	private readonly mountFn = signal<MountFn | null>(null);

	/** `true` once a series is mountable and the runtime has not failed. */
	readonly showScene = computed<boolean>(() => this.options() !== null && !this.failed());

	/** Set when `three` is missing or the scene failed to load: forces the SVG fallback. */
	private readonly failed = signal(false);

	/** Mount / supersede / teardown state (see `chart-3d-scene-mount.ts`);
	 * `scene.handle()` is the live handle, `null` while unmounted/loading. */
	private readonly scene = new Chart3DSceneMount<PieChart3DSceneOptions, PieChart3DHandle>({
		onFailed: () => this.failed.set(true),
	});

	constructor() {
		afterNextRender(() => void this.loadScene());

		// Mount when the scene container exists, the runtime has loaded, and we
		// have (new) wedge-mesh data. Re-mounts when the underlying data changes; an
		// in-flight mount for the same data is left alone (`ensure`).
		effect(() => {
			const container = this.sceneRef()?.nativeElement;
			const fn = this.mountFn();
			const opts = this.options();
			if (!container || !fn || !opts) {
				return;
			}
			this.scene.ensure(
				opts,
				() => fn(container, opts, this.buildInteraction()),
				(handle) => {
					handle.setSelectedPart(this.selectedPart());
				},
			);
		});

		// Push size changes to the live handle without re-mounting.
		effect(() => {
			const opts = this.options();
			if (opts) {
				this.scene.handle()?.resize(opts.width, opts.height);
			}
		});

		// Re-apply the selected-part highlight when the external selection (or
		// the live handle) changes.
		effect(() => {
			this.scene.handle()?.setSelectedPart(this.selectedPart());
		});
	}

	private async loadScene(): Promise<void> {
		if (!this.options()) {
			return; // No plottable series: stay on the SVG fallback.
		}
		try {
			const mod = await import('../internal/shared-src/render/pie-chart-3d-scene');
			this.mountFn.set(mod.mountPieChart3D);
		} catch {
			this.failed.set(true);
		}
	}

	private buildInteraction(): PieChart3DInteraction {
		return {
			onSelect: (part) => this.partSelect.emit(part),
			onValueDragPreview: (part, value) => this.valueDragPreview.emit({ part, value }),
			onValueDragCommit: (part, value) => this.valueDragCommit.emit({ part, value }),
		};
	}

	ngOnDestroy(): void {
		this.scene.teardown();
	}
}

// packages/vue/src/viewer/components/PieChart3DRenderer.vue
<script setup lang="ts">
import type { PptxChartData, PptxElement } from 'pptx-viewer-core';
import type { ChartViewModel } from 'pptx-viewer-shared';
import { buildPieChart3DDataForElement } from 'pptx-viewer-shared';
import { computed, ref } from 'vue';

import { usePieChart3dScene } from '../composables/usePieChart3dScene';
import ChartEditOverlays from './chart/ChartEditOverlays.vue';
import ChartViewModelSvg from './chart/ChartViewModelSvg.vue';
import Chart3DLoading from './Chart3DLoading.vue';

/**
 * PieChart3DRenderer - Vue interactive 3D pie-chart view.
 *
 * When the chart resolves to a plottable wedge-mesh layout (see
 * `buildPieChart3DDataForElement`) and the optional `three` peer dependency
 * is installed, this mounts the shared, framework-agnostic vanilla-three
 * controller (`mountPieChart3D` from `pptx-viewer-shared`) into a container
 * div for a camera-orbitable set of real 3D wedge meshes (OrbitControls: drag
 * to rotate, scroll to zoom; click a wedge to select it, drag a wedge to
 * change its value). The mount lifecycle, including the bridge to the SAME
 * chart-part selection + commit path the 2D SVG mark interaction uses, lives
 * in {@link usePieChart3dScene}; this SFC stays thin presentation. Mirrors
 * `Bar3DChartRenderer.vue` exactly.
 *
 * Falls back to the plain SVG `ChartViewModelSvg` (rendered with the same
 * `viewModel`/`preserveAspectRatio` the parent `ChartRenderer` already built,
 * i.e. the flat oblique-projection pie3D illusion) when there is no
 * plottable series, `three` is not installed, or the scene fails to mount.
 *
 * Dragging a wedge sweeps its trailing edge around the pie's centre,
 * renormalising every other slice's angle live, exactly like the flat SVG
 * pie/doughnut's own on-canvas editing. Pie3D draws no axis labels, so unlike
 * its bar/line/area/surface siblings it carries no text-style emphasis
 * wiring.
 */
const props = defineProps<{
	element: PptxElement;
	/** The parent's already-built SVG view-model, used as the fallback render. */
	viewModel: ChartViewModel;
	preserveAspectRatio?: 'none' | 'xMidYMid meet';
}>();

const options = computed(() =>
	buildPieChart3DDataForElement(props.element, {
		width: props.element.width,
		height: props.element.height,
	}),
);

const chartData = computed<PptxChartData | undefined>(() =>
	props.element.type === 'chart' ? props.element.chartData : undefined,
);

const sceneContainer = ref<HTMLElement | null>(null);

const { mounted, loading, dragLabel } = usePieChart3dScene({
	container: sceneContainer,
	options,
	elementId: () => props.element.id,
	chartData: () => chartData.value,
});

/** Show the SVG fallback once loading has settled without a mounted scene. */
const showFallback = computed(() => !mounted.value && !loading.value);
/** Show the spinner while a mount attempt is still in flight. */
const showLoading = computed(() => !mounted.value && loading.value);
</script>

<template>
	<!--
		Always present so the scene can mount into it (v-show, not v-if, keeps
		the ref attached). Hidden while the loading spinner or SVG fallback is
		showing.
	-->
	<div
		v-show="mounted"
		ref="sceneContainer"
		class="pptx-vue-pie-chart-3d-scene"
		:style="{ width: `${element.width}px`, height: `${element.height}px` }"
	/>
	<Chart3DLoading v-if="showLoading" :width="element.width" :height="element.height" />
	<ChartViewModelSvg
		v-else-if="showFallback"
		:element-id="element.id"
		:vm="viewModel"
		:preserve-aspect-ratio="preserveAspectRatio"
	/>
	<!-- Mid-drag value badge for a live value drag on a wedge mesh -->
	<ChartEditOverlays v-if="mounted" :drag-label="dragLabel" :title-draft="null" />
</template>

<style scoped>
.pptx-vue-pie-chart-3d-scene {
	will-change: transform;
}
</style>
