// packages/svelte/src/viewer/presentation/PresentationTransitionOverlay.svelte
<script lang="ts">
	/**
	 * PresentationTransitionOverlay: animates a slide change in presentation mode
	 * (Svelte port of the Vue overlay of the same name). It stacks two
	 * {@link SlideStage} layers, both scaled identically to the underlying
	 * presentation frame:
	 *   - the outgoing (old) slide as a snapshot layer, and
	 *   - the incoming (new) slide.
	 *
	 * The incoming slide's transition is mapped to CSS `animation` shorthands via
	 * the framework-agnostic {@link resolveSlideTransition}; each layer's z-index
	 * comes from `outgoingOnTop`. When the configured duration elapses it calls
	 * `ondone`, at which point the host drops the overlay and leaves the static
	 * incoming slide rendered by its main stage. The `@keyframes` themselves are
	 * injected once at document level (see `keyframes.ts`).
	 */
	import type { PptxSlide, PptxSlideTransition } from 'pptx-viewer-core';
	import {
		applySlideTransitionSound,
		buildMorphScopedCss,
		buildMorphTransitionPlan,
		MORPH_CROSSFADE_GROUP_CSS_TEXT,
		MORPH_CROSSFADE_HALF_BLEND_MODE,
		morphOptionToMode,
		resolveSlideTransition,
		resolveTransitionDurationMs,
	} from 'pptx-viewer-shared';
	import type { CanvasSize, CssStyleMap } from 'pptx-viewer-shared';
	import { onDestroy, onMount } from 'svelte';

	import { playAnimationSound, stopAnimationSound } from './animation-sound';
	import SlideStage from '../components/SlideStage.svelte';
	import { styleToString } from '../style';

	const {
		outgoingSlide,
		incomingSlide,
		canvasSize,
		mediaDataUrls,
		scale = 1,
		transition,
		ondone,
	}: {
		outgoingSlide: PptxSlide | undefined;
		incomingSlide: PptxSlide | undefined;
		canvasSize: CanvasSize;
		mediaDataUrls: Map<string, string>;
		scale?: number;
		transition: PptxSlideTransition | undefined;
		ondone: () => void;
	} = $props();

	const animations = $derived(resolveSlideTransition(transition));
	/** Effective duration (ms); `0` for instant (none/cut). */
	const durationMs = $derived(resolveTransitionDurationMs(transition));

	function layerStyle(animation: string, zIndex: number): CssStyleMap {
		const style: CssStyleMap = { zIndex };
		if (animation !== 'none') {
			style.animation = animation;
		}
		return style;
	}

	/**
	 * Morph moves individual shapes between the two slides rather than wiping the
	 * whole surface, so when it is active the incoming layer plays per-element
	 * keyframes (scoped by `data-pptx-morph-incoming`) and the outgoing layer
	 * animates each of its own shapes: gliding onto its counterpart (dissolving
	 * into it when its appearance changed) or fading out in place without one.
	 */
	const morphPlan = $derived(
		transition?.type === 'morph'
			? buildMorphTransitionPlan(
					outgoingSlide,
					incomingSlide,
					durationMs,
					morphOptionToMode(transition.morphOption),
				)
			: undefined,
	);

	const morphOutgoingSlide = $derived(
		morphPlan && outgoingSlide ? { ...outgoingSlide, elements: morphPlan.outgoingElements } : undefined,
	);

	/**
	 * The arriving shapes a ghost above them would otherwise hide for the whole
	 * morph, painted in their own layer over the departing one (issue #146).
	 * Their copy on the incoming layer is held invisible by the plan, so the two
	 * never composite with each other.
	 */
	const morphLiftedSlide = $derived(
		morphPlan && incomingSlide && morphPlan.overlayIncomingElements.length > 0
			? { ...incomingSlide, elements: morphPlan.overlayIncomingElements }
			: undefined,
	);

	/** One half of a grouped pair: blends additively, and carries the dissolve. */
	function halfStyle(animation: string | undefined): string {
		return `mix-blend-mode: ${MORPH_CROSSFADE_HALF_BLEND_MODE};${
			animation === undefined ? '' : ` animation: ${animation};`
		}`;
	}

	/**
	 * The pairs the overlay paints BOTH halves of, each as one isolated group so
	 * the halves are summed rather than stacked: two source-over fades leave the
	 * ink they share at 0.75 of full strength mid-transition, biting chunks out
	 * of glyphs that cross during a text dissolve, where PowerPoint's own blend
	 * keeps the two coefficients summing to 1.0 (issue #161).
	 */
	const morphCrossfadeGroups = $derived(
		morphPlan && outgoingSlide && incomingSlide
			? morphPlan.crossfadeGroups.map((group, index) => ({
					key: group.incoming.id,
					// `isolation` makes the group a stacking context, so it carries its
					// own z-index to stay above the ghosts its halves came from.
					style: `${MORPH_CROSSFADE_GROUP_CSS_TEXT} z-index: ${4 + index};`,
					// The dissolve rides these WRAPPERS, not the elements: a pair
					// dissolving in place never moves, and an animation on the small
					// element box gives it a compositing layer whose raster snaps to whole
					// device pixels, painting the wording a fraction of a pixel off the
					// live stage (issue #161).
					outgoingStyle: halfStyle(group.outgoingAnimation),
					incomingStyle: halfStyle(group.incomingAnimation),
					outgoing: { ...outgoingSlide, elements: [group.outgoing] },
					incoming: { ...incomingSlide, elements: [group.incoming] },
				}))
			: [],
	);

	const morphCss = $derived(
		morphPlan
			? [
					buildMorphScopedCss(morphPlan, 'data-pptx-morph-incoming', 'incoming'),
					buildMorphScopedCss(morphPlan, 'data-pptx-morph-outgoing', 'outgoing'),
					buildMorphScopedCss(morphPlan, 'data-pptx-morph-lifted', 'lifted'),
				].join('\n')
			: '',
	);

	// A layer-wide animation would drag every shape as one block and cancel the
	// morph, so the layers stay unanimated while a plan is active.
	const outgoingStyle = $derived(
		styleToString(layerStyle(morphPlan ? 'none' : animations.outgoing, morphPlan ? 2 : animations.outgoingOnTop ? 2 : 1)),
	);
	const incomingStyle = $derived(
		styleToString(layerStyle(morphPlan ? 'none' : animations.incoming, morphPlan ? 1 : animations.outgoingOnTop ? 1 : 2)),
	);
	const liftedStyle = styleToString(layerStyle('none', 3));

	/**
	 * Play or stop this transition's sound action (`p:sndAc/p:stSnd`/`p:endSnd`)
	 * the instant it starts. `transition.soundPath` is a raw in-archive path;
	 * `mediaDataUrls` is the same Blob-URL cache the load pipeline
	 * pre-populates for it (`collectAnimationSoundPaths`, extended to also
	 * collect a slide transition's own sound). Reuses the per-effect sound
	 * singleton (`animation-sound.ts`) so a transition sound and an animation
	 * sound cannot talk over each other, matching PowerPoint's "one sound
	 * plays at a time" behaviour. NOT stopped on this component's own
	 * destroy: a "Loop Until Next Sound" sound must keep playing across the
	 * static period between this overlay tearing down and the next
	 * transition's own sound action; the presentation controller stops it on
	 * leaving the show.
	 */
	$effect(() => {
		applySlideTransitionSound(transition, (soundPath) => mediaDataUrls.get(soundPath), {
			play: playAnimationSound,
			stop: stopAnimationSound,
		});
	});

	let timer: ReturnType<typeof setTimeout> | null = null;

	onMount(() => {
		// A small buffer past the animation duration lets the CSS `forwards` fill
		// settle before the host swaps back to the static slide.
		timer = setTimeout(
			() => {
				timer = null;
				ondone();
			},
			Math.max(0, durationMs) + 50,
		);
	});

	onDestroy(() => {
		if (timer !== null) {
			clearTimeout(timer);
			timer = null;
		}
	});
</script>

<div class="pptx-svelte-transition-overlay" data-pptx-transition-overlay>
	{#if morphPlan}
		<!-- eslint-disable-next-line svelte/no-at-html-tags -- generated keyframes, no user input -->
		{@html `<style>${morphCss}</style>`}
	{/if}
	<div
		class="pptx-svelte-transition-layer"
		data-pptx-transition-layer="outgoing"
		data-pptx-morph-outgoing={morphPlan ? 'true' : undefined}
		style={outgoingStyle}
	>
		<!-- transparentBackground during a morph: this layer sits ABOVE the
		     incoming slide and only carries the departing shapes, so painting the
		     outgoing slide's own (always opaque) background here would cover the
		     whole morph with a flat slab for its entire duration. -->
		<SlideStage
			slide={morphPlan ? morphOutgoingSlide : outgoingSlide}
			{canvasSize}
			{mediaDataUrls}
			{scale}
			transparentBackground={Boolean(morphPlan)}
		/>
	</div>
	<div
		class="pptx-svelte-transition-layer"
		data-pptx-transition-layer="incoming"
		data-pptx-morph-incoming={morphPlan ? 'true' : undefined}
		style={incomingStyle}
	>
		<SlideStage slide={incomingSlide} {canvasSize} {mediaDataUrls} {scale} />
	</div>
	{#if morphLiftedSlide}
		<!-- The arriving shapes that dissolve in ABOVE a departing one. They live
		     on the incoming slide, so the layer below draws them under the
		     departing layer, where nobody would see them. -->
		<div
			class="pptx-svelte-transition-layer"
			data-pptx-transition-layer="lifted"
			data-pptx-morph-lifted="true"
			style={liftedStyle}
		>
			<SlideStage slide={morphLiftedSlide} {canvasSize} {mediaDataUrls} {scale} transparentBackground />
		</div>
	{/if}
	<!-- A pair dissolving in place, painted as ONE isolated group whose two
	     halves sum instead of stacking (issue #161). -->
	{#each morphCrossfadeGroups as group (group.key)}
		<div data-pptx-morph-crossfade={group.key} style={group.style}>
			<div
				class="pptx-svelte-transition-layer"
				data-pptx-transition-layer="outgoing"
				data-pptx-morph-outgoing="true"
				style={group.outgoingStyle}
			>
				<SlideStage slide={group.outgoing} {canvasSize} {mediaDataUrls} {scale} transparentBackground />
			</div>
			<div
				class="pptx-svelte-transition-layer"
				data-pptx-transition-layer="lifted"
				data-pptx-morph-lifted="true"
				style={group.incomingStyle}
			>
				<SlideStage slide={group.incoming} {canvasSize} {mediaDataUrls} {scale} transparentBackground />
			</div>
		</div>
	{/each}
</div>

<style>
	.pptx-svelte-transition-overlay {
		position: absolute;
		inset: 0;
		overflow: hidden;
		pointer-events: none;
	}

	/* `inset: 0`, not `top/left: 0`: the stage inside scales with a CSS
	   `transform`, which never changes its laid-out box, so an auto-sized layer
	   measures the deck's NATIVE size (1280x720) while the stage paints the
	   display size (1920x1080). With `overflow: hidden` that cropped every
	   transition to a deck-sized top-left corner and the rest of the screen cut
	   straight to the next slide. Pinning to the overlay (already the frame's
	   scaled footprint) puts the clip on the slide edge, where it belongs. */
	.pptx-svelte-transition-layer {
		position: absolute;
		inset: 0;
		overflow: hidden;
		will-change: transform, opacity, clip-path, filter;
	}
</style>

// packages/vue/src/viewer/components/PresentationTransitionOverlay.vue
<script setup lang="ts">
import type { PptxSlide, PptxSlideTransition } from 'pptx-viewer-core';
import {
	applySlideTransitionSound,
	buildMorphScopedCss,
	buildMorphTransitionPlan,
	MORPH_CROSSFADE_GROUP_STYLE,
	MORPH_CROSSFADE_HALF_BLEND_MODE,
	morphOptionToMode,
} from 'pptx-viewer-shared';
import type { CSSProperties } from 'vue';
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue';

import { playAnimationSound, stopAnimationSound } from '../composables/animation-sound';
import {
	resolveSlideTransition,
	resolveTransitionDurationMs,
	SLIDE_TRANSITION_KEYFRAMES_CSS,
} from '../composables/slide-transition-css';
import type { CanvasSize } from '../types';
import SlideStage from './SlideStage.vue';

/**
 * PresentationTransitionOverlay - animates a slide change in presentation mode.
 *
 * It stacks two {@link SlideStage} layers, both scaled-to-fit identically to the
 * underlying presentation frame:
 *   - the **outgoing** (old) slide as a snapshot layer, and
 *   - the **incoming** (new) slide.
 *
 * The active slide's {@link PptxSlideTransition} is mapped to CSS `animation`
 * shorthands (via {@link resolveSlideTransition}); each layer's `z-index` is set
 * from `outgoingOnTop`. When the configured duration elapses the overlay emits
 * `done`, at which point the host should drop the overlay and leave the static
 * incoming slide rendered by its main stage.
 *
 * `PresentationMode` is expected to mount this **only while a transition is
 * playing** (between the outgoing and incoming slides), render nothing of its
 * own animated stage during that window, and remove it on `@done`.
 */
const props = withDefaults(
	defineProps<{
		/** The outgoing (previous) slide rendered in the exit layer. */
		outgoingSlide: PptxSlide | undefined;
		/** The incoming (new) slide rendered in the entrance layer. */
		incomingSlide: PptxSlide | undefined;
		/** Slide surface dimensions (px). */
		canvasSize: CanvasSize;
		/** Resolved media data URLs, threaded to each {@link SlideStage}. */
		mediaDataUrls: Map<string, string>;
		/** Fit-to-viewport scale (same value the host applies to its main stage). */
		scale?: number;
		/** The transition definition from the incoming slide. */
		transition: PptxSlideTransition | undefined;
	}>(),
	{ scale: 1 },
);

const emit = defineEmits<{
	(e: 'done'): void;
}>();

// ---------------------------------------------------------------------------
// Resolved animation pieces
// ---------------------------------------------------------------------------

const animations = computed(() => resolveSlideTransition(props.transition));

/** Effective duration (ms); `0` for instant (none/cut). */
const durationMs = computed(() => resolveTransitionDurationMs(props.transition));

// ---------------------------------------------------------------------------
// Morph
// ---------------------------------------------------------------------------

/**
 * Morph is not a whole-slide wipe: individual shapes travel from where they sat
 * on the outgoing slide to where they sit on the incoming one. So when the
 * transition is `morph` the two stacked layers are re-purposed - the incoming
 * layer plays per-element keyframes (scoped by `data-pptx-morph-incoming`), and
 * the outgoing layer paints a moving copy of the outgoing slide, each shape
 * gliding onto its counterpart (dissolving into it when its appearance changed)
 * or fading out in place when it has none.
 */
const morphPlan = computed(() =>
	props.transition?.type === 'morph'
		? buildMorphTransitionPlan(
				props.outgoingSlide,
				props.incomingSlide,
				durationMs.value,
				morphOptionToMode(props.transition.morphOption),
			)
		: undefined,
);

/** The outgoing slide's shapes, rendered as the morph's departing layer. */
const morphOutgoingSlide = computed<PptxSlide | undefined>(() => {
	const plan = morphPlan.value;
	if (!plan || !props.outgoingSlide) {
		return undefined;
	}
	return { ...props.outgoingSlide, elements: plan.outgoingElements };
});

/**
 * The arriving shapes a ghost above them would otherwise hide for the whole
 * morph, painted in their own layer over the departing one (issue #146). Their
 * copy on the incoming layer is held invisible by the plan, so the two never
 * composite with each other.
 */
const morphLiftedSlide = computed<PptxSlide | undefined>(() => {
	const plan = morphPlan.value;
	if (!plan || !props.incomingSlide || plan.overlayIncomingElements.length === 0) {
		return undefined;
	}
	return { ...props.incomingSlide, elements: plan.overlayIncomingElements };
});

/** Both halves of a grouped pair blend additively, and only with each other. */
const crossfadeHalfStyle: CSSProperties = { mixBlendMode: MORPH_CROSSFADE_HALF_BLEND_MODE };

/**
 * The pairs whose two halves the overlay paints itself, as one isolated group
 * each so they can be SUMMED rather than stacked.
 *
 * Two source-over fades leave the ink the halves share dipped toward the
 * backdrop (0.75 of full strength at the midpoint), which bites chunks out of
 * glyphs crossing during a text dissolve; PowerPoint's own render holds the two
 * coefficients at a sum of 1.0 throughout (issue #161).
 */
const morphCrossfadeGroups = computed(() => {
	const plan = morphPlan.value;
	if (!plan || !props.outgoingSlide || !props.incomingSlide) {
		return [];
	}
	const outgoing = props.outgoingSlide;
	const incoming = props.incomingSlide;
	return plan.crossfadeGroups.map((group, index) => ({
		key: group.incoming.id,
		// `isolation` makes the group a stacking context, so it needs its own
		// z-index to stay above the ghosts its halves used to sit among.
		style: { ...MORPH_CROSSFADE_GROUP_STYLE, zIndex: 4 + index } as CSSProperties,
		// The dissolve rides these WRAPPERS, not the elements: a pair dissolving
		// in place never moves, and an animation on the small element box gives it
		// a compositing layer whose raster snaps to whole device pixels, painting
		// the wording a fraction of a pixel off the live stage (issue #161).
		outgoingStyle: { ...crossfadeHalfStyle, animation: group.outgoingAnimation } as CSSProperties,
		incomingStyle: { ...crossfadeHalfStyle, animation: group.incomingAnimation } as CSSProperties,
		outgoingSlide: { ...outgoing, elements: [group.outgoing] },
		incomingSlide: { ...incoming, elements: [group.incoming] },
	}));
});

const morphCss = computed(() => {
	const plan = morphPlan.value;
	if (!plan) {
		return '';
	}
	return [
		buildMorphScopedCss(plan, 'data-pptx-morph-incoming', 'incoming'),
		buildMorphScopedCss(plan, 'data-pptx-morph-outgoing', 'outgoing'),
		buildMorphScopedCss(plan, 'data-pptx-morph-lifted', 'lifted'),
	].join('\n');
});

const outgoingZIndex = computed(() => (animations.value.outgoingOnTop ? 2 : 1));
const incomingZIndex = computed(() => (animations.value.outgoingOnTop ? 1 : 2));

const outgoingLayerStyle = computed<CSSProperties>(() => ({
	zIndex: morphPlan.value ? 2 : outgoingZIndex.value,
	// Morph animates each shape individually; a layer-wide animation on top of
	// that would drag the whole slide and cancel the effect.
	animation: morphPlan.value
		? undefined
		: animations.value.outgoing !== 'none'
			? animations.value.outgoing
			: undefined,
}));

const liftedLayerStyle = computed<CSSProperties>(() => ({ zIndex: 3 }));

const incomingLayerStyle = computed<CSSProperties>(() => ({
	zIndex: morphPlan.value ? 1 : incomingZIndex.value,
	animation: morphPlan.value
		? undefined
		: animations.value.incoming !== 'none'
			? animations.value.incoming
			: undefined,
}));

// ---------------------------------------------------------------------------
// Sound (`p:sndAc/p:stSnd`/`p:endSnd`)
// ---------------------------------------------------------------------------

/**
 * Play or stop this transition's sound action the instant it starts.
 *
 * `transition.soundPath` is a raw in-archive path; `mediaDataUrls` is the
 * same Blob-URL cache the load pipeline pre-populates for it (via
 * `collectAnimationSoundPaths`, extended to also collect a slide transition's
 * own sound alongside per-effect animation sounds). Reuses the per-effect
 * sound singleton (`animation-sound.ts`) so a transition sound and an
 * animation sound cannot talk over each other, matching PowerPoint's "one
 * sound plays at a time" behaviour.
 */
watch(
	() => props.transition,
	(transition) => {
		applySlideTransitionSound(transition, (soundPath) => props.mediaDataUrls.get(soundPath), {
			play: playAnimationSound,
			stop: stopAnimationSound,
		});
	},
	{ immediate: true },
);

// ---------------------------------------------------------------------------
// Completion timer
// ---------------------------------------------------------------------------

let timer: ReturnType<typeof setTimeout> | null = null;

function clearTimer(): void {
	if (timer !== null) {
		clearTimeout(timer);
		timer = null;
	}
}

onMounted(() => {
	// A small buffer past the animation duration ensures the CSS `forwards`
	// fill has settled before the host swaps to the static slide.
	const wait = Math.max(0, durationMs.value) + 50;
	timer = setTimeout(() => {
		timer = null;
		emit('done');
	}, wait);
});

// NOT stopped here: a "Loop Until Next Sound" transition sound must keep
// playing across the (much longer) static period between this overlay
// tearing down and the NEXT transition's own sound action, exactly as
// PowerPoint does. `PresentationMode.vue` stops it on leaving the show.
onBeforeUnmount(clearTimer);
</script>

<template>
	<div class="pptx-vue-transition-overlay" data-pptx-transition-overlay>
		<!-- Inject the transition @keyframes once for this overlay. -->
		<component :is="'style'">{{ SLIDE_TRANSITION_KEYFRAMES_CSS }}</component>
		<component :is="'style'" v-if="morphPlan">{{ morphCss }}</component>

		<!-- Outgoing (old) slide snapshot. During a morph this carries only the
		     shapes with no incoming counterpart, so the ones that persist stay
		     visible on the incoming layer while they travel - and it must stay
		     BACKGROUND-FREE, or the departing layer's opaque slide fill covers the
		     morph underneath it for the whole transition. -->
		<div
			class="pptx-vue-transition-layer"
			data-pptx-transition-layer="outgoing"
			:data-pptx-morph-outgoing="morphPlan ? 'true' : undefined"
			:style="outgoingLayerStyle"
		>
			<SlideStage
				:slide="morphPlan ? morphOutgoingSlide : outgoingSlide"
				:canvas-size="canvasSize"
				:media-data-urls="mediaDataUrls"
				:scale="scale"
				:preserve-element-ids="Boolean(morphPlan)"
				:transparent-background="Boolean(morphPlan)"
			/>
		</div>

		<!-- Incoming (new) slide. -->
		<div
			class="pptx-vue-transition-layer"
			data-pptx-transition-layer="incoming"
			:data-pptx-morph-incoming="morphPlan ? 'true' : undefined"
			:style="incomingLayerStyle"
		>
			<SlideStage
				:slide="incomingSlide"
				:canvas-size="canvasSize"
				:media-data-urls="mediaDataUrls"
				:scale="scale"
				:preserve-element-ids="Boolean(morphPlan)"
			/>
		</div>

		<!-- The arriving shapes that dissolve in ABOVE a departing one. They live
		     on the incoming slide, so the layer below draws them under the
		     departing layer, where nobody would see them. -->
		<div
			v-if="morphLiftedSlide"
			class="pptx-vue-transition-layer"
			data-pptx-transition-layer="lifted"
			data-pptx-morph-lifted="true"
			:style="liftedLayerStyle"
		>
			<SlideStage
				:slide="morphLiftedSlide"
				:canvas-size="canvasSize"
				:media-data-urls="mediaDataUrls"
				:scale="scale"
				preserve-element-ids
				transparent-background
			/>
		</div>

		<!-- A pair dissolving in place, painted as ONE isolated group whose two
		     halves sum instead of stacking (issue #161). -->
		<div
			v-for="group in morphCrossfadeGroups"
			:key="group.key"
			:data-pptx-morph-crossfade="group.key"
			:style="group.style"
		>
			<div
				class="pptx-vue-transition-layer"
				data-pptx-transition-layer="outgoing"
				data-pptx-morph-outgoing="true"
				:style="group.outgoingStyle"
			>
				<SlideStage
					:slide="group.outgoingSlide"
					:canvas-size="canvasSize"
					:media-data-urls="mediaDataUrls"
					:scale="scale"
					preserve-element-ids
					transparent-background
				/>
			</div>
			<div
				class="pptx-vue-transition-layer"
				data-pptx-transition-layer="lifted"
				data-pptx-morph-lifted="true"
				:style="group.incomingStyle"
			>
				<SlideStage
					:slide="group.incomingSlide"
					:canvas-size="canvasSize"
					:media-data-urls="mediaDataUrls"
					:scale="scale"
					preserve-element-ids
					transparent-background
				/>
			</div>
		</div>
	</div>
</template>

<style scoped>
.pptx-vue-transition-overlay {
	position: absolute;
	inset: 0;
	overflow: hidden;
	pointer-events: none;
}

/*
 * The layer must FILL the overlay, not shrink-wrap its child.
 *
 * `SlideStage` scales with `transform`, which never changes its laid-out box, so
 * an auto-sized absolute layer measures the deck's NATIVE size (e.g. 1280x720)
 * while the stage paints at `canvasSize * scale`. Combined with `overflow:
 * hidden` that cropped every transition to the top-left native-size corner of
 * the show whenever the display was bigger than the deck: on a 1920x1080 screen
 * a 1280x720 deck lost the outer third of the animation and the morph read as a
 * hard-edged slab rather than a transition. `inset: 0` pins the layer to the
 * overlay (itself the frame's scaled footprint), so the clip lands exactly on
 * the slide edge, as intended.
 */
.pptx-vue-transition-layer {
	position: absolute;
	inset: 0;
	overflow: hidden;
	will-change: transform, opacity, clip-path, filter;
}
</style>
