// packages/svelte/src/viewer/components/RulerStrips.svelte
<script lang="ts">
	/**
	 * RulerStrips: the horizontal + vertical rulers behind View > Rulers.
	 *
	 * Svelte port of React's `Ruler` / `RulerStrips`. Drawn as a sibling of the
	 * scaled stage (NOT inside it) so the stage's CSS transform never scales the
	 * tick strokes or the labels: the strips receive `scale` and lay their ticks
	 * out in already-scaled screen px instead, which is what makes the ruler
	 * track zoom while staying legible at every zoom level.
	 *
	 * Tick geometry comes from `pptx-viewer-shared` (`generateTicks`), the same
	 * generator React and Vue use, so all three agree on unit, subdivision
	 * density and label thinning. Dragging off a strip drops a guide, resolved by
	 * the shared `rulerDragToGuidePosition` rules.
	 */
	import { generateTicks, RULER_FONT_SIZE, RULER_THICKNESS, rulerDragToGuidePosition } from 'pptx-viewer-shared';

	import type { RulerStripsProps } from './viewer-body-props';

	const {
		canvasSize,
		scale,
		unit = 'inches',
		selectedBounds = null,
		oncreateguide,
	}: RulerStripsProps = $props();

	const T = RULER_THICKNESS;
	const FS = RULER_FONT_SIZE;

	const scaledWidth = $derived(canvasSize.width * scale);
	const scaledHeight = $derived(canvasSize.height * scale);
	const hTicks = $derived(generateTicks(canvasSize.width, scale, unit));
	const vTicks = $derived(generateTicks(canvasSize.height, scale, unit));

	/** Selected-element extent, in scaled px, highlighted on each strip. */
	const hHighlight = $derived(
		selectedBounds
			? { start: selectedBounds.x * scale, span: Math.max(selectedBounds.width * scale, 1) }
			: null,
	);
	const vHighlight = $derived(
		selectedBounds
			? { start: selectedBounds.y * scale, span: Math.max(selectedBounds.height * scale, 1) }
			: null,
	);

	// A guide is created on pointer-UP, not pointer-down, so a stray click on the
	// ruler cannot drop a guide the user never dragged out (React does the same).
	// eslint-disable-next-line prefer-const
	let dragAxis = $state<'h' | 'v' | null>(null);

	function startDrag(axis: 'h' | 'v', event: PointerEvent): void {
		if (!oncreateguide) {
			return;
		}
		event.preventDefault();
		(event.currentTarget as Element | null)?.setPointerCapture?.(event.pointerId);
		dragAxis = axis;
	}

	function endDrag(event: PointerEvent): void {
		const axis = dragAxis;
		dragAxis = null;
		if (!axis || !oncreateguide) {
			return;
		}
		const strip = event.currentTarget as Element | null;
		if (!strip) {
			return;
		}
		try {
			strip.releasePointerCapture?.(event.pointerId);
		} catch {
			// Capture may already have been released by the browser.
		}
		const rect = strip.getBoundingClientRect();
		const offset = axis === 'h' ? event.clientY - rect.top : event.clientX - rect.left;
		const position = rulerDragToGuidePosition(
			offset,
			scale,
			axis === 'h' ? canvasSize.height : canvasSize.width,
		);
		if (position !== null) {
			oncreateguide(axis, position);
		}
	}
</script>

<!-- Corner square where the two strips meet. -->
<div class="pptx-svelte-ruler-corner" style={`width:${T}px;height:${T}px`} aria-hidden="true"></div>

<!-- Horizontal ruler: spans the top of the stage; drag down for an h-guide. -->
<svg
	class="pptx-svelte-ruler pptx-svelte-ruler-h"
	class:pptx-svelte-ruler-draggable={Boolean(oncreateguide)}
	style={`left:${T}px;width:${scaledWidth}px;height:${T}px`}
	width={scaledWidth}
	height={T}
	data-pptx-ruler="h"
	role="presentation"
	onpointerdown={(event) => startDrag('h', event)}
	onpointerup={endDrag}
>
	<rect width={scaledWidth} height={T} class="pptx-svelte-ruler-bg" />
	{#if hHighlight}
		<rect x={hHighlight.start} y={0} width={hHighlight.span} height={T} class="pptx-svelte-ruler-highlight" />
	{/if}
	{#each hTicks as tick, index (index)}
		<line
			x1={tick.position}
			y1={T}
			x2={tick.position}
			y2={T - (tick.isMajor ? T * 0.6 : T * 0.3)}
			class="pptx-svelte-ruler-tick"
			stroke-width={tick.isMajor ? 1 : 0.5}
		/>
		{#if tick.label}
			<text x={tick.position + 2} y={FS + 1} font-size={FS} class="pptx-svelte-ruler-label">{tick.label}</text>
		{/if}
	{/each}
	<line x1={0} y1={T - 0.5} x2={scaledWidth} y2={T - 0.5} class="pptx-svelte-ruler-edge" stroke-width="1" />
</svg>

<!-- Vertical ruler: spans the left of the stage; drag right for a v-guide. -->
<svg
	class="pptx-svelte-ruler pptx-svelte-ruler-v"
	class:pptx-svelte-ruler-draggable={Boolean(oncreateguide)}
	style={`top:${T}px;width:${T}px;height:${scaledHeight}px`}
	width={T}
	height={scaledHeight}
	data-pptx-ruler="v"
	role="presentation"
	onpointerdown={(event) => startDrag('v', event)}
	onpointerup={endDrag}
>
	<rect width={T} height={scaledHeight} class="pptx-svelte-ruler-bg" />
	{#if vHighlight}
		<rect x={0} y={vHighlight.start} width={T} height={vHighlight.span} class="pptx-svelte-ruler-highlight" />
	{/if}
	{#each vTicks as tick, index (index)}
		<line
			x1={T}
			y1={tick.position}
			x2={T - (tick.isMajor ? T * 0.6 : T * 0.3)}
			y2={tick.position}
			class="pptx-svelte-ruler-tick"
			stroke-width={tick.isMajor ? 1 : 0.5}
		/>
		{#if tick.label}
			<text x={2} y={tick.position + FS + 2} font-size={FS} class="pptx-svelte-ruler-label">{tick.label}</text>
		{/if}
	{/each}
	<line x1={T - 0.5} y1={0} x2={T - 0.5} y2={scaledHeight} class="pptx-svelte-ruler-edge" stroke-width="1" />
</svg>

<style>
	.pptx-svelte-ruler-corner {
		position: absolute;
		top: 0;
		left: 0;
		z-index: 51;
		background: var(--pptx-muted, #f1f5f9);
		border-right: 1px solid var(--pptx-border, #cbd5e1);
		border-bottom: 1px solid var(--pptx-border, #cbd5e1);
	}

	.pptx-svelte-ruler {
		position: absolute;
		z-index: 50;
		display: block;
		user-select: none;
		touch-action: none;
	}

	.pptx-svelte-ruler-h {
		top: 0;
	}

	.pptx-svelte-ruler-v {
		left: 0;
	}

	.pptx-svelte-ruler-h.pptx-svelte-ruler-draggable {
		cursor: row-resize;
	}

	.pptx-svelte-ruler-v.pptx-svelte-ruler-draggable {
		cursor: col-resize;
	}

	.pptx-svelte-ruler-bg {
		fill: var(--pptx-muted, #f1f5f9);
	}

	.pptx-svelte-ruler-edge {
		stroke: var(--pptx-border, #cbd5e1);
	}

	.pptx-svelte-ruler-tick {
		stroke: var(--pptx-muted-foreground, #94a3b8);
	}

	.pptx-svelte-ruler-highlight {
		fill: var(--pptx-primary, #2563eb);
		opacity: 0.2;
	}

	.pptx-svelte-ruler-label {
		fill: var(--pptx-muted-foreground, #94a3b8);
		font-family: system-ui, sans-serif;
	}
</style>

// packages/vue/src/viewer/components/RulerStrips.vue
<script setup lang="ts">
/**
 * RulerStrips - horizontal + vertical rulers (View > Rulers), drawn along the
 * top and left edges of the slide. Vue port of React's `Ruler` / `RulerStrips`,
 * kept in step with the Svelte `RulerStrips.svelte`.
 *
 * Tick geometry comes from the shared `generateTicks` (scaled px from the slide
 * origin), so every binding agrees on unit, subdivision density and label
 * thinning. The strips are positioned just OUTSIDE the slide wrapper (negative
 * offsets) rather than inside the scaled stage, because a ruler inside the
 * stage would have its strokes and labels scaled by the zoom transform instead
 * of tracking it.
 *
 * The strips are interactive: dragging off one drops a guide, resolved by the
 * shared `rulerDragToGuidePosition` rules. They were previously
 * `pointer-events: none`, which silently disabled the gesture React, Angular
 * and Svelte all offer.
 */
import { computed, ref } from 'vue';

import {
	generateTicks,
	RULER_FONT_SIZE,
	RULER_THICKNESS,
	rulerDragToGuidePosition,
} from '../composables/ruler-utils';
import type { RulerUnit } from '../composables/ruler-utils';
import type { CanvasSize } from '../types';

/** Bounding box (unscaled slide px) highlighted on the strips. */
interface SelectedBounds {
	x: number;
	y: number;
	width: number;
	height: number;
}

const props = withDefaults(
	defineProps<{
		canvasSize: CanvasSize;
		scale: number;
		unit?: RulerUnit;
		/** Selected element extent, highlighted on both strips as PowerPoint does. */
		selectedBounds?: SelectedBounds | null;
		/** Enable the drag-out-a-guide gesture (editing only). */
		draggable?: boolean;
	}>(),
	{ unit: 'inches', selectedBounds: null, draggable: false },
);

const emit = defineEmits<{ createGuide: [axis: 'h' | 'v', position: number] }>();

const stripW = computed(() => props.canvasSize.width * props.scale);
const stripH = computed(() => props.canvasSize.height * props.scale);
const hTicks = computed(() => generateTicks(props.canvasSize.width, props.scale, props.unit));
const vTicks = computed(() => generateTicks(props.canvasSize.height, props.scale, props.unit));
const T = RULER_THICKNESS;
const FS = RULER_FONT_SIZE;

const hHighlight = computed(() =>
	props.selectedBounds
		? {
				start: props.selectedBounds.x * props.scale,
				span: Math.max(props.selectedBounds.width * props.scale, 1),
			}
		: null,
);
const vHighlight = computed(() =>
	props.selectedBounds
		? {
				start: props.selectedBounds.y * props.scale,
				span: Math.max(props.selectedBounds.height * props.scale, 1),
			}
		: null,
);

// A guide is created on pointer-UP, not pointer-down, so a stray click on a
// strip cannot drop a guide the user never dragged out (React/Svelte agree).
const dragAxis = ref<'h' | 'v' | null>(null);

function startDrag(axis: 'h' | 'v', event: PointerEvent): void {
	if (!props.draggable) {
		return;
	}
	// The canvas' own pointerdown clears the selection and starts a marquee, so
	// a ruler drag must not bubble into it.
	event.stopPropagation();
	event.preventDefault();
	(event.currentTarget as Element | null)?.setPointerCapture?.(event.pointerId);
	dragAxis.value = axis;
}

function endDrag(event: PointerEvent): void {
	const axis = dragAxis.value;
	dragAxis.value = null;
	const strip = event.currentTarget as Element | null;
	if (!axis || !props.draggable || !strip) {
		return;
	}
	try {
		strip.releasePointerCapture?.(event.pointerId);
	} catch {
		// Capture may already have been released by the browser.
	}
	const rect = strip.getBoundingClientRect();
	const offset = axis === 'h' ? event.clientY - rect.top : event.clientX - rect.left;
	const position = rulerDragToGuidePosition(
		offset,
		props.scale,
		axis === 'h' ? props.canvasSize.height : props.canvasSize.width,
	);
	if (position !== null) {
		emit('createGuide', axis, position);
	}
}
</script>

<template>
	<!-- Corner -->
	<div
		class="absolute bg-secondary border-r border-b border-border"
		:style="{ top: `-${T}px`, left: `-${T}px`, width: `${T}px`, height: `${T}px` }"
		aria-hidden="true"
	/>
	<!-- Horizontal ruler: drag down onto the slide for a horizontal guide -->
	<svg
		class="absolute bg-secondary border-b border-border text-muted-foreground select-none touch-none"
		:class="draggable ? 'cursor-row-resize' : ''"
		:style="{ top: `-${T}px`, left: '0px' }"
		:width="stripW"
		:height="T"
		data-pptx-ruler="h"
		role="presentation"
		@pointerdown="startDrag('h', $event)"
		@pointerup="endDrag"
	>
		<rect
			v-if="hHighlight"
			:x="hHighlight.start"
			:y="0"
			:width="hHighlight.span"
			:height="T"
			class="fill-primary/20"
		/>
		<template v-for="(t, i) in hTicks" :key="i">
			<line
				:x1="t.position"
				:x2="t.position"
				:y1="t.isMajor ? T - T * 0.6 : T - T * 0.3"
				:y2="T"
				stroke="currentColor"
				:stroke-width="t.isMajor ? 1 : 0.5"
			/>
			<text v-if="t.label" :x="t.position + 2" :y="FS + 1" :font-size="FS" fill="currentColor">
				{{ t.label }}
			</text>
		</template>
	</svg>
	<!-- Vertical ruler: drag right onto the slide for a vertical guide -->
	<svg
		class="absolute bg-secondary border-r border-border text-muted-foreground select-none touch-none"
		:class="draggable ? 'cursor-col-resize' : ''"
		:style="{ top: '0px', left: `-${T}px` }"
		:width="T"
		:height="stripH"
		data-pptx-ruler="v"
		role="presentation"
		@pointerdown="startDrag('v', $event)"
		@pointerup="endDrag"
	>
		<rect
			v-if="vHighlight"
			:x="0"
			:y="vHighlight.start"
			:width="T"
			:height="vHighlight.span"
			class="fill-primary/20"
		/>
		<template v-for="(t, i) in vTicks" :key="i">
			<line
				:y1="t.position"
				:y2="t.position"
				:x1="t.isMajor ? T - T * 0.6 : T - T * 0.3"
				:x2="T"
				stroke="currentColor"
				:stroke-width="t.isMajor ? 1 : 0.5"
			/>
			<text v-if="t.label" :x="2" :y="t.position + FS + 2" :font-size="FS" fill="currentColor">
				{{ t.label }}
			</text>
		</template>
	</svg>
</template>
