// packages/angular/src/viewer/smart-art-3d-renderer.component.ts
import { NgStyle } from '@angular/common';
import {
	afterNextRender,
	ChangeDetectionStrategy,
	Component,
	computed,
	effect,
	ElementRef,
	inject,
	Injector,
	input,
	OnDestroy,
	signal,
	viewChild,
} from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import type { PptxElement } from 'pptx-viewer-core';

import type { SmartArt3DModel, TextStyleAnimationDescriptor } from '../internal/shared';
// Type-only import of the scene runtime; the implementation (which pulls the
// optional `three` peer) is loaded lazily via dynamic import so it never lands
// in the main bundle.
import type { mountSmartArt3D as MountSmartArt3D } from '../internal/shared-src/smartart-3d/index';
import { EditorStateService } from './editor-state.service';
import { getContainerStyle } from './element-style';
import type { StyleMap } from './element-style';
import { SLIDE_CONTEXT } from './slide-context';
import {
	buildSmartArt3DModelForElement,
	computeNode3DEditBox,
	findSmartArtNodeElementAtPoint,
	getSmartArtData,
} from './smart-art-3d-renderer-helpers';
import { commitNodeText, findOwningSlideIndex } from './smart-art-inline-edit';
import type { InlineEditState } from './smart-art-inline-edit';
import { SmartArtRendererComponent } from './smart-art-renderer.component';

type MountFn = typeof MountSmartArt3D;
type SceneHandle = ReturnType<MountFn>;

/**
 * SmartArt3DRendererComponent: Angular Three.js SmartArt renderer.
 *
 * Builds the pure 3D model from the shared layout engine (no `three` import),
 * then lazily imports the vanilla scene runtime from the vendored
 * `pptx-viewer-shared/smartart-3d` and mounts it on a canvas. `three` is an
 * optional peer dependency: when it is missing, the diagram has no geometry, or
 * the scene errors, the component falls back to the SVG SmartArt renderer.
 *
 * When `canEdit` is true and the 3D scene is active, an invisible
 * `<pptx-smart-art-renderer>` overlay is stacked over the canvas. Double-clicking
 * on the overlay uses `document.elementsFromPoint` to locate the `<g>` bearing
 * `data-smartart-node-id`, then opens an inline textarea editor over that node
 * (same commit path as the SVG renderer: `EditorStateService.updateElement`).
 */
@Component({
	selector: 'pptx-smart-art-3d-renderer',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [NgStyle, SmartArtRendererComponent, TranslatePipe],
	templateUrl: './smart-art-3d-renderer.component.html',
	styleUrl: './smart-art-3d-renderer.component.css',
})
export class SmartArt3DRendererComponent implements OnDestroy {
	readonly element = input.required<PptxElement>();
	readonly zIndex = input<number>(0);
	/** When true and the 3D scene is active, enables inline node text editing. */
	readonly canEdit = input<boolean>(false);
	/**
	 * Emit the neutral element marker (`data-pptx-element="true"`) on the node
	 * that also carries `data-element-id`: the 3D scene's root, or the box the
	 * SVG fallback branch is drawn into. Set only by the main interactive canvas.
	 */
	readonly markElement = input<boolean>(false);
	/**
	 * Active font-style emphasis override (Bold Flash, Bold Reveal, Underline,
	 * Change Font Style/Size) for every node's caption, driven by native-
	 * animation playback. Mirrors `ChartElementViewComponent`'s `textStyle`
	 * threading for the 3D chart scenes: a canvas-texture caption has no DOM
	 * text node the CSS-injection path (`buildTextStyleOverrideCss`) can reach,
	 * so the scene's own `setTextStyle` handle method is the only way in.
	 */
	readonly textStyle = input<TextStyleAnimationDescriptor | undefined>(undefined);

	private readonly canvas = viewChild<ElementRef<HTMLCanvasElement>>('canvas');
	private readonly containerEl = viewChild<ElementRef<HTMLElement>>('container3d');
	private readonly nodeEditor3d = viewChild<ElementRef<HTMLTextAreaElement>>('nodeEditor3d');

	/** `true` until the 3D scene is known to be mountable; renders the SVG fallback. */
	readonly useFallback = signal(true);

	private readonly mountFn = signal<MountFn | null>(null);
	/** The live mounted handle, or `null` while unmounted. A signal so
	 * `setTextStyle` re-applies as soon as it (or the input) changes. */
	private readonly handle = signal<SceneHandle | null>(null);

	protected readonly editState = signal<InlineEditState | null>(null);
	/** Live draft text, updated on every input event. */
	protected draftText = '';
	/** Guards against a cancel-triggered DOM-removal blur committing the edit. */
	private editSettled = false;

	private readonly editor = inject(EditorStateService, { optional: true });
	/** The hosting canvas's slide, for resolving template (master/layout) SmartArt. */
	private readonly slideContext = inject(SLIDE_CONTEXT, { optional: true });
	private readonly injector = inject(Injector);

	readonly containerStyle = computed<StyleMap>(() =>
		getContainerStyle(this.element(), this.zIndex()),
	);

	private readonly smartArtData = computed(() => getSmartArtData(this.element()));

	private readonly model = computed<SmartArt3DModel | null>(() =>
		buildSmartArt3DModelForElement(this.element()),
	);

	constructor() {
		afterNextRender(() => void this.loadScene());

		// Mount once the canvas exists and the scene runtime has loaded.
		effect(() => {
			const canvasEl = this.canvas()?.nativeElement;
			const fn = this.mountFn();
			const m = this.model();
			if (!canvasEl || !fn || !m || this.handle()) {
				return;
			}
			try {
				const el = this.element();
				this.handle.set(fn(canvasEl, m, el.width, el.height, { textStyle: this.textStyle() }));
			} catch {
				this.useFallback.set(true);
			}
		});

		// Resize without re-mounting.
		effect(() => {
			const el = this.element();
			this.handle()?.resize(el.width, el.height);
		});

		// Apply/clear the node-caption text-style override when it (or the live
		// handle) changes.
		effect(() => {
			this.handle()?.setTextStyle(this.textStyle());
		});

		// Auto-focus the textarea when the editor opens.
		effect(() => {
			if (this.editState()) {
				afterNextRender(
					() => {
						const el = this.nodeEditor3d()?.nativeElement;
						if (el) {
							el.focus();
							el.select();
						}
					},
					{ injector: this.injector },
				);
			}
		});
	}

	private async loadScene(): Promise<void> {
		const m = this.model();
		if (!m || m.meshes.length === 0) {
			return; // No geometry: stay on the SVG fallback.
		}
		try {
			const mod = await import('../internal/shared-src/smartart-3d/index');
			this.mountFn.set(mod.mountSmartArt3D);
			this.useFallback.set(false);
		} catch {
			this.useFallback.set(true);
		}
	}

	/**
	 * Locate the SmartArt node at the click position using `elementsFromPoint`
	 * (which includes pointer-events:none SVG elements) and open the inline editor.
	 */
	onOverlayDblClick(event: MouseEvent): void {
		const container = this.containerEl()?.nativeElement;
		const data = this.smartArtData();
		if (!container || !data) {
			return;
		}
		// elementsFromPoint includes pointer-events:none nodes, so this finds the
		// <g data-smartart-node-id="..."> in the invisible overlay SVG.
		const nodeEl = findSmartArtNodeElementAtPoint(
			document.elementsFromPoint(event.clientX, event.clientY),
		);
		const nodeId = nodeEl?.getAttribute('data-smartart-node-id');
		if (!nodeEl || !nodeId) {
			return;
		}
		const currentText = data.nodes.find((n) => n.id === nodeId)?.text ?? '';
		this.draftText = currentText;
		this.editSettled = false;
		this.editState.set({
			nodeId,
			box: computeNode3DEditBox(nodeEl.getBoundingClientRect(), container.getBoundingClientRect()),
			text: currentText,
		});
	}

	/** Update the live draft text on each keystroke. */
	updateDraft(event: Event): void {
		this.draftText = (event.target as HTMLTextAreaElement).value;
	}

	/** Enter commits (via blur); Escape cancels. Propagation always stopped. */
	onEditorKeydown(event: KeyboardEvent): void {
		event.stopPropagation();
		if (event.key === 'Enter' && !event.shiftKey) {
			event.preventDefault();
			// Commit via blur so the single commit path runs once.
			(event.target as HTMLTextAreaElement).blur();
		} else if (event.key === 'Escape') {
			event.preventDefault();
			this.cancelEdit();
		}
	}

	/** Commit the current draft through EditorStateService (blur handler). */
	commitEdit(): void {
		if (this.editSettled) {
			this.editSettled = false;
			return;
		}
		const edit = this.editState();
		if (!edit) {
			return;
		}
		const text = this.draftText;
		this.editState.set(null);
		this.applyCommit(edit.nodeId, text);
	}

	/** Discard the current edit without committing. */
	cancelEdit(): void {
		// Mark as settled so the DOM-removal blur does not commit the cancelled edit.
		this.editSettled = true;
		this.editState.set(null);
	}

	private applyCommit(nodeId: string, text: string): void {
		const data = this.smartArtData();
		if (!data || !this.editor) {
			return;
		}
		const next = commitNodeText(data, nodeId, text);
		if (next === data) {
			return;
		} // no-op: text unchanged
		const slideIndex = findOwningSlideIndex(
			this.editor.slides(),
			this.element().id,
			this.slideContext?.slideId() ?? null,
		);
		if (slideIndex < 0) {
			return;
		}
		this.editor.updateElement(slideIndex, this.element().id, {
			smartArtData: next,
		} as Partial<PptxElement>);
	}

	ngOnDestroy(): void {
		this.handle()?.dispose();
		this.handle.set(null);
	}
}

@if (useFallback()) {
	<!--
		The SVG renderer only fills a box, so the positioned, id-bearing,
		marked element node has to be drawn here.
	-->
	<div
		class="pptx-ng-element pptx-ng-smartart"
		[ngStyle]="containerStyle()"
		[attr.data-element-id]="element().id"
		[attr.data-pptx-element]="markElement() ? 'true' : null"
	>
		<pptx-smart-art-renderer [element]="element()" />
	</div>
} @else {
	<div
		#container3d
		class="pptx-ng-element pptx-ng-smartart-3d"
		[ngStyle]="containerStyle()"
		[attr.data-element-id]="element().id"
		[attr.data-pptx-element]="markElement() ? 'true' : null"
	>
		<canvas #canvas class="pptx-ng-smartart-3d-canvas"></canvas>
		@if (canEdit()) {
			<!-- Invisible SVG overlay: provides data-smartart-node-id hit targets -->
			<div class="pptx-ng-smartart-3d-hittest" (dblclick)="onOverlayDblClick($event)">
				<pptx-smart-art-renderer [element]="element()" [editable]="false" />
			</div>
			@if (editState()) {
				<textarea
					#nodeEditor3d
					class="pptx-ng-smartart-3d-node-editor"
					[style.left.px]="editState()!.box.x"
					[style.top.px]="editState()!.box.y"
					[style.width.px]="editState()!.box.width"
					[style.height.px]="editState()!.box.height"
					[value]="editState()!.text"
					spellcheck="false"
					[attr.aria-label]="'pptx.smartArt.editNodeText' | translate"
					(input)="updateDraft($event)"
					(blur)="commitEdit()"
					(keydown)="onEditorKeydown($event)"
					(mousedown)="$event.stopPropagation()"
					(click)="$event.stopPropagation()"
					(dblclick)="$event.stopPropagation()"
				></textarea>
			}
		}
	</div>
}

// packages/vue/src/viewer/components/SmartArt3DRenderer.vue
<script setup lang="ts">
/**
 * SmartArt3DRenderer - Vue Three.js SmartArt renderer.
 *
 * Builds the pure 3D model from the shared layout engine (no `three` import),
 * then lazily imports the vanilla scene runtime from
 * `pptx-viewer-shared/smartart-3d` and mounts it on a canvas. `three` is an
 * optional peer dependency: when it is missing, the diagram has no geometry, or
 * the scene errors, the component transparently falls back to the SVG
 * `SmartArtRenderer`.
 *
 * When the host provides a SmartArtNodeEditKey injection (edit mode), an
 * invisible SmartArtHitTestWrapper overlay is stacked over the 3D canvas.
 * Double-clicking it walks up from the click target to the nearest
 * `[data-node-id]` SVG group, projects its screen rect into container-local
 * coordinates, and opens an inline textarea editor for that node. Commits flow
 * through the same injection context the 2D renderer uses (undo/redo + save).
 */
import type {
	PptxElement,
	PptxSmartArtChrome,
	SmartArtColorScheme,
	SmartArtStyle,
} from 'pptx-viewer-core';
import {
	buildSmartArt3DModel,
	collectCoherent3DOffNodeIds,
	computeSmartArtElementLayout,
	shouldCommitSmartArtNodeText,
} from 'pptx-viewer-shared';
import type { SmartArt3DModel, TextStyleAnimationDescriptor } from 'pptx-viewer-shared';
import { computed, nextTick, ref, toRef } from 'vue';
import type { CSSProperties } from 'vue';
import { useI18n } from 'vue-i18n';

import { getContainerStyle } from '../composables/element-style';
import { inlineEditorRect, useSmartArtInlineEditState } from '../composables/smartart-inline-edit';
import { injectSmartArtNodeEdit } from '../composables/smartart-node-edit';
import { useSmartArt3DScene } from '../composables/useSmartArt3DScene';
import SmartArtHitTestWrapper from './SmartArtHitTestWrapper.vue';
import SmartArtRenderer from './SmartArtRenderer.vue';

const props = defineProps<{
	element: PptxElement;
	mediaDataUrls?: Map<string, string>;
	zIndex: number;
	/**
	 * Active font-style emphasis override (Bold Flash, Bold Reveal, Underline,
	 * Change Font Style/Size), applied to every node caption via the mounted
	 * handle's `setTextStyle`. The parent `ElementRenderer`'s DOM CSS override
	 * (`buildTextStyleOverrideCss`) cannot reach a canvas-texture caption, so
	 * this scene-native path is the only one that reaches it; the fallback
	 * SVG `SmartArtRenderer` below still takes the CSS override directly.
	 */
	textStyle?: TextStyleAnimationDescriptor;
	/** Forwarded to the fallback SVG `SmartArtRenderer` (see `textStyle` above). */
	textStyleOverrideCss?: string;
}>();

const { t } = useI18n();

const PALETTES: Record<SmartArtColorScheme, string[]> = {
	colorful1: ['#3b82f6', '#22c55e', '#f97316', '#eab308', '#a855f7', '#ec4899'],
	colorful2: ['#6366f1', '#14b8a6', '#f59e0b', '#ef4444', '#8b5cf6', '#06b6d4'],
	colorful3: ['#0ea5e9', '#84cc16', '#f43e5e', '#a855f7', '#f97316', '#10b981'],
	monochromatic1: ['#3b82f6', '#60a5fa', '#93c5fd', '#bfdbfe', '#2563eb', '#1d4ed8'],
	monochromatic2: ['#6366f1', '#818cf8', '#a5b4fc', '#c7d2fe', '#4f46e5', '#4338ca'],
};

const smartArtData = computed(() =>
	props.element.type === 'smartArt' ? props.element.smartArtData : undefined,
);

const palette = computed<string[]>(() => {
	const data = smartArtData.value;
	const ctFills = data?.colorTransform?.fillColors;
	if (ctFills && ctFills.length > 0) {
		return ctFills;
	}
	return PALETTES[data?.colorScheme ?? 'colorful1'] ?? PALETTES.colorful1;
});

const style = computed<SmartArtStyle>(() => smartArtData.value?.style ?? 'flat');
const chrome = computed<PptxSmartArtChrome | undefined>(() => smartArtData.value?.chrome);

const model = computed<SmartArt3DModel | null>(() => {
	const data = smartArtData.value;
	if (!data || data.nodes.length === 0) {
		return null;
	}
	const layout = computeSmartArtElementLayout(
		data,
		data.nodes,
		{ width: props.element.width, height: props.element.height },
		palette.value,
		style.value,
		props.element.id,
	);
	return buildSmartArt3DModel(layout, {
		background: chrome.value?.backgroundColor,
		spatial: true,
		coherent3DOffNodeIds: collectCoherent3DOffNodeIds(data.nodes),
	});
});

const canvasRef = ref<HTMLCanvasElement | null>(null);
const containerRef = ref<HTMLElement | null>(null);
const editorEl = ref<HTMLTextAreaElement | null>(null);

/** Opt-in interactive WebGL scene; falls back to the SVG renderer when it cannot mount. */
const { useFallback } = useSmartArt3DScene({
	canvas: canvasRef,
	model: () => model.value,
	width: () => props.element.width,
	height: () => props.element.height,
	textStyle: toRef(props, 'textStyle'),
});

const containerStyle = computed<CSSProperties>(() =>
	getContainerStyle(props.element, props.zIndex),
);

// ── Inline editing (injection-based, mirrors SmartArtRenderer.vue) ──────────

const nodeEdit = injectSmartArtNodeEdit();
const canEdit = computed(() => Boolean(nodeEdit?.canEdit()));

const editState = useSmartArtInlineEditState();

/** Walk up from an event target to find the nearest element with data-node-id. */
function findNodeEl(target: EventTarget | null): Element | null {
	let el = target instanceof Element ? target : null;
	while (el) {
		if (el.hasAttribute('data-node-id')) {
			return el;
		}
		el = el.parentElement;
	}
	return null;
}

function onOverlayDblClick(e: MouseEvent): void {
	const nodeEl = findNodeEl(e.target);
	const container = containerRef.value;
	if (!nodeEl || !container) {
		return;
	}
	const nodeId = nodeEl.getAttribute('data-node-id');
	if (!nodeId || !nodeEdit) {
		return;
	}
	const data = smartArtData.value;
	if (!data) {
		return;
	}
	const currentText = data.nodes.find((n) => n.id === nodeId)?.text ?? '';
	const rect = inlineEditorRect(nodeEl.getBoundingClientRect(), container.getBoundingClientRect());
	editState.begin(nodeId, currentText, rect);
	void nextTick(() => {
		editorEl.value?.focus();
		editorEl.value?.select();
	});
}

function commitEdit(): void {
	const nodeId = editState.editingNodeId.value;
	const data = smartArtData.value;
	if (
		nodeId &&
		data &&
		nodeEdit &&
		shouldCommitSmartArtNodeText(data, nodeId, editState.draft.value)
	) {
		nodeEdit.commit(props.element.id, nodeId, editState.draft.value);
	}
	editState.cancel();
}
</script>

<template>
	<SmartArtRenderer
		v-if="useFallback"
		:element="element"
		:media-data-urls="mediaDataUrls"
		:z-index="zIndex"
		:text-style-override-css="textStyleOverrideCss"
	/>
	<div
		v-else
		ref="containerRef"
		class="pptx-vue-element pptx-vue-smartart-3d"
		:style="containerStyle"
		:data-element-id="element.id"
	>
		<canvas ref="canvasRef" class="pptx-vue-smartart-3d-canvas" />

		<template v-if="canEdit">
			<!-- Invisible SVG overlay: data-node-id groups are pointer-events hit targets -->
			<div class="pptx-vue-smartart-3d-hittest" @dblclick.stop="onOverlayDblClick">
				<SmartArtHitTestWrapper :element="element" :zIndex="0" />
			</div>

			<!-- Inline node text editor, positioned over the clicked node -->
			<textarea
				v-if="editState.isEditing.value && editState.rect.value"
				ref="editorEl"
				v-model="editState.draft.value"
				class="pptx-vue-smartart-3d-editor"
				spellcheck="false"
				:aria-label="t('pptx.smartArt.editNodeText')"
				:style="{
					left: `${editState.rect.value.left}px`,
					top: `${editState.rect.value.top}px`,
					width: `${editState.rect.value.width}px`,
					height: `${editState.rect.value.height}px`,
				}"
				@mousedown.stop
				@click.stop
				@dblclick.stop
				@blur="commitEdit"
				@keydown.enter.prevent="commitEdit"
				@keydown.esc.prevent="editState.cancel()"
				@keydown.stop
			/>
		</template>
	</div>
</template>

<style scoped>
.pptx-vue-smartart-3d-canvas {
	width: 100%;
	height: 100%;
	display: block;
}

/* Invisible hit-test overlay: fills the canvas area, captures dblclicks.
   opacity:0 makes it invisible while keeping it in the layout + event flow. */
.pptx-vue-smartart-3d-hittest {
	position: absolute;
	inset: 0;
	opacity: 0;
}

/* Force pointer-events:auto on SmartArt node groups within the hit-test overlay.
   SmartArtRenderer sets pointer-events:none on its <svg> element; groups only
   get pointer-events:auto when editable=true, which is disabled in the wrapper.
   This rule re-enables them so the dblclick target is the <g> element (carrying
   data-node-id) rather than the overlay div, enabling correct node resolution. */
.pptx-vue-smartart-3d-hittest :deep([data-node-id]) {
	pointer-events: auto;
}

.pptx-vue-smartart-3d-editor {
	position: absolute;
	z-index: 20;
	margin: 0;
	padding: 2px;
	box-sizing: border-box;
	border: 1px solid #2563eb;
	border-radius: 3px;
	resize: none;
	overflow: hidden;
	font: inherit;
	font-size: 12px;
	line-height: 1.2;
	text-align: center;
	color: #111;
	background: rgba(255, 255, 255, 0.95);
	outline: none;
	box-shadow: 0 2px 6px rgba(0, 0, 0, 0.15);
}
</style>
