// packages/angular/src/viewer/smart-art-renderer.component.ts
import { NgStyle } from '@angular/common';
import {
	afterNextRender,
	ChangeDetectionStrategy,
	Component,
	computed,
	DestroyRef,
	effect,
	ElementRef,
	inject,
	Injector,
	input,
	signal,
	viewChild,
} from '@angular/core';
import { TranslatePipe, TranslateService } from '@ngx-translate/core';
import type { PptxElement, PptxSmartArtData } from 'pptx-viewer-core';
import { setSmartArtNodeStyle } from 'pptx-viewer-core';

import {
	buildSmartArtA11y,
	computeInlineEditorRect,
	computeSmartArtElementLayout,
	flattenNodes,
	rebuildDrawingShapesIfCleared,
	resolveDrawingShapeNodeId,
	revealedSmartArtNodeCount,
} from '../internal/shared';
import type {
	ElementAnimationState,
	InlineEditRect,
	RenderedNode,
	SmartArtA11y,
	SmartArtConnectorPaint,
	SmartArtLayoutResult,
	SmartArtNodeLabel,
} from '../internal/shared';
import { EditorStateService } from './editor-state.service';
import type { StyleMap } from './element-style';
import { SLIDE_CONTEXT } from './slide-context';
import {
	buildChromeStyle,
	computeDrawingViewBox,
	projectDrawingShapes,
	resolvePalette,
	styleShadowFilter,
} from './smart-art-drawing';
import type { DrawingViewBox, RenderedShape } from './smart-art-drawing';
import {
	beginNodeEdit,
	canEditSmartArtNodes,
	commitNodeText,
	findOwningSlideIndex,
} from './smart-art-inline-edit';
import type { InlineEditState } from './smart-art-inline-edit';
import {
	layoutConnectorPaints,
	layoutNodeLabels,
	narrowToCircle,
	narrowToPolygon,
	narrowToRect,
} from './smart-art-renderer-helpers';

/**
 * SmartArtRendererComponent: Angular SmartArt renderer.
 *
 * Data path mirrors the Vue `SmartArtRenderer.vue` and the React renderer:
 *  1. **Drawing shapes** (`smartArtData.drawingShapes`) -- the preferred path
 *     when the core extracted per-shape geometry from `ppt/diagrams/drawing*.xml`.
 *  2. **Shared SVG-fallback engine** (`computeSmartArtLayout`) -- when no drawing
 *     shapes exist, the framework-agnostic engine in `pptx-viewer-shared`
 *     positions/styles the node tree across all 10 layout families (list /
 *     process / cycle / hierarchy / matrix / radial / pyramid / venn / funnel /
 *     target), returning `RenderedNode[]` (rect / circle / polygon) +
 *     `RenderedConnector[]` view-models. Every binding renders the same
 *     geometry; this maps those view-models to SVG exactly as Vue does.
 *  3. **Placeholder** -- when there is neither data nor any nodes/shapes.
 *
 * Positioning is NOT this component's job: its chrome root fills the positioned,
 * element-id bearing box its host draws (the element dispatcher, the 3D
 * renderer's fallback branch, or a preview stage), the same contract the chart
 * and table renderers follow. Owning `left`/`top` here too offset the diagram
 * twice, and stamping the element id on this root hid the host's marked node
 * from anything reading the element contract by id.
 */
@Component({
	selector: 'pptx-smart-art-renderer',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [NgStyle, TranslatePipe],
	templateUrl: './smart-art-renderer.component.html',
	styleUrl: './smart-art-renderer.component.css',
})
export class SmartArtRendererComponent {
	/** The smartArt element to render. Must be `type === 'smartArt'`. */
	readonly element = input.required<PptxElement>();

	/**
	 * Whether inline on-canvas node-text editing is enabled. False in
	 * presentation / read-only / thumbnail contexts (mirrors the table renderer's
	 * `editable` input). Double-clicking a node only enters edit mode when true.
	 */
	readonly editable = input<boolean>(false);

	/**
	 * Native-animation playback state. A staged diagram build
	 * (`build.kind === 'diagram'`) reveals the leading nodes / drawing shapes for
	 * the current progress; absent or non-diagram state renders every node. The
	 * view box is still computed from the FULL shape set so the diagram does not
	 * rescale as it builds. Mirrors the Vue `SmartArtRenderer`'s reveal slice.
	 */
	readonly animationState = input<ElementAnimationState | undefined>(undefined);

	/**
	 * The editor state layer. Optional: the renderer is also used outside the
	 * editing viewer (thumbnails, export), where this service is not provided.
	 * Inline editing commits through `updateElement` here, the exact channel the
	 * inspector's SmartArt panel uses, so undo/redo + save round-trip are shared.
	 */
	private readonly editor = inject(EditorStateService, { optional: true });
	/** The hosting canvas's slide, for resolving template (master/layout) SmartArt. */
	private readonly slideContext = inject(SLIDE_CONTEXT, { optional: true });
	private readonly injector = inject(Injector);
	private readonly translate = inject(TranslateService);

	/** The node currently being edited on the canvas, or null. */
	protected readonly editState = signal<InlineEditState | null>(null);

	/** The mounted `<textarea>` for the active node edit, if any. */
	private readonly nodeEditor = viewChild<ElementRef<HTMLTextAreaElement>>('nodeEditor');

	/** Container div ref used to project hover rects into local coordinates. */
	private readonly smartartContainer = viewChild<ElementRef>('smartartContainer');

	/**
	 * The mounted style-bar popover, if any. Mousemove events landing inside it
	 * must not clear hover state, or the popover would unmount as soon as the
	 * pointer reaches the swatches it needs to be clicked.
	 */
	private readonly styleBar = viewChild<ElementRef>('styleBar');

	/** Pending "leave" timeout: grace period for the pointer to reach the style bar. */
	private hideTimeout: ReturnType<typeof setTimeout> | null = null;

	/**
	 * Guards against a cancel-triggered DOM-removal blur committing the edit.
	 * Set to true before programmatic cancellation; reset to false on each new edit.
	 */
	private editSettled = false;

	/** Whether node double-click / Enter enters inline edit (editable + has editor). */
	readonly canEditNodes = computed(() =>
		canEditSmartArtNodes(this.editable(), this.editor !== null, this.element()),
	);

	constructor() {
		inject(DestroyRef).onDestroy(() => this.cancelPendingHide());
		// Focus + select-all the editor as soon as it mounts (mirrors the table
		// renderer's cell-input effect).
		effect(() => {
			if (this.editState()) {
				afterNextRender(
					() => {
						const el = this.nodeEditor()?.nativeElement;
						if (el) {
							el.focus();
							el.select();
						}
					},
					{ injector: this.injector },
				);
			}
		});
	}

	private readonly smartArtData = computed(() => {
		const el = this.element();
		return el.type === 'smartArt' ? el.smartArtData : undefined;
	});

	readonly chromeStyle = computed<StyleMap>(() => buildChromeStyle(this.smartArtData()?.chrome));

	readonly palette = computed<string[]>(() => resolvePalette(this.smartArtData()));

	readonly artStyle = computed(() => this.smartArtData()?.style ?? 'flat');

	readonly nodes = computed(() => this.smartArtData()?.nodes ?? []);

	readonly shadowFilter = computed<string | undefined>(() => styleShadowFilter(this.artStyle()));

	private readonly rawDrawingShapes = computed(() => this.smartArtData()?.drawingShapes ?? []);

	readonly hasDrawingShapes = computed(() => this.rawDrawingShapes().length > 0);

	// ── Staged diagram build (p:bldDgm) reveal ──────────────────────────────
	//
	// When an active native animation carries a staged diagram build, reveal only
	// the leading nodes / drawing shapes for the current progress; the view box is
	// still computed from the FULL shape set so the diagram does not rescale.

	private readonly diagramBuild = computed(() => {
		const build = this.animationState()?.build;
		return build?.kind === 'diagram' ? build : undefined;
	});

	private readonly shownNodeCount = computed(() => {
		const build = this.diagramBuild();
		return build ? revealedSmartArtNodeCount(this.nodes(), build) : this.nodes().length;
	});

	private readonly isPartialBuild = computed(
		() => this.diagramBuild() !== undefined && this.shownNodeCount() < this.nodes().length,
	);

	/** Leading node prefix revealed so far (full list when no partial build). */
	private readonly revealedNodes = computed(() =>
		this.isPartialBuild() ? this.nodes().slice(0, this.shownNodeCount()) : this.nodes(),
	);

	/** Leading drawing-shape prefix revealed so far (proportional to nodes). */
	private readonly revealedShapeList = computed(() => {
		const shapes = this.rawDrawingShapes();
		if (!this.isPartialBuild() || shapes.length === 0) {
			return shapes;
		}
		const count = Math.ceil(
			(this.shownNodeCount() / Math.max(this.nodes().length, 1)) * shapes.length,
		);
		return shapes.slice(0, count);
	});

	private readonly viewBox = computed<DrawingViewBox>(() =>
		computeDrawingViewBox(this.rawDrawingShapes()),
	);

	/** `viewBox` attribute string for the drawing-shapes `<svg>`. */
	readonly svgViewBox = computed<string>(() => {
		const vb = this.viewBox();
		return `0 0 ${vb.width} ${vb.height}`;
	});

	readonly renderedShapes = computed<RenderedShape[]>(() =>
		projectDrawingShapes(
			this.element().id,
			this.revealedShapeList(),
			this.viewBox(),
			this.palette(),
			this.artStyle(),
		),
	);

	/**
	 * Node id for each drawing shape (index-aligned with `renderedShapes`).
	 * Used to tag `<g>` elements with `data-smartart-node-id` so the 3D
	 * renderer's hit-test overlay can resolve a click to a node.
	 */
	readonly drawingShapeNodeIds = computed<(string | undefined)[]>(() => {
		const shapes = this.rawDrawingShapes();
		const nodes = this.nodes();
		return shapes.map((shape, i) => resolveDrawingShapeNodeId(shape, i, shapes, nodes));
	});

	// ── Shared SVG-fallback engine (no drawing shapes) ──────────────────────

	readonly layout = computed<SmartArtLayoutResult>(() => {
		const el = this.element();
		const data = this.smartArtData();
		return computeSmartArtElementLayout(
			data ?? {},
			this.revealedNodes(),
			{ width: Math.max(el.width, 1), height: Math.max(el.height, 1) },
			this.palette(),
			this.artStyle(),
			el.id,
		);
	});

	readonly hasLayout = computed(() => this.layout().nodes.length > 0);

	// ── Fallback-layout label / connector paint (shared decisions) ──────────
	//
	// `RenderedNode` / `RenderedConnector` carry OPTIONAL paint and placement
	// fields (per-node font colour / weight / style, off-centre label anchors,
	// per-connector stroke / width / opacity / dash). This template used to
	// hardcode `fill="white"` and park circle labels on `cx`/`cy`, so target
	// leader captions, gear legend rows and timeline captions all sat on the
	// node centre. Both descriptors below are resolved once per layout by the
	// shared decision functions; the template binds them and computes nothing.

	/** Label descriptors, index-aligned with `layout().nodes`. */
	readonly layoutLabels = computed<SmartArtNodeLabel[]>(() => layoutNodeLabels(this.layout()));

	/** Connector paint, index-aligned with `layout().connectors`. */
	readonly layoutConnectors = computed<SmartArtConnectorPaint[]>(() =>
		layoutConnectorPaints(this.layout()),
	);

	// ── Accessibility view-model (shared) ───────────────────────────────────

	/**
	 * Screen-reader metadata for the whole diagram, derived by the shared
	 * `buildSmartArtA11y`. The container SVG gets `role="img"` + this `label`;
	 * each node gets a per-node `aria-label` + `<title>` resolved by node id.
	 */
	readonly a11y = computed<SmartArtA11y | undefined>(() => {
		const data = this.smartArtData();
		return data ? buildSmartArtA11y(data) : undefined;
	});

	/** Map of node id -> accessibility label (for per-node `<title>` lookup). */
	private readonly a11yLabelById = computed<Map<string, string>>(() => {
		const map = new Map<string, string>();
		for (const node of this.a11y()?.nodes ?? []) {
			map.set(node.id, node.label);
		}
		return map;
	});

	/**
	 * Source node ids in fallback render order, index-aligned with
	 * `layout().nodes`. The layout engine walks the node tree depth-first, so
	 * flattening it is the mapping every binding uses.
	 *
	 * This component used to parse the id back out of the rendered node's `key`
	 * instead, which broke on any family whose key carries an extra segment: the
	 * gear legend's `<id>-gear-extra-<nodeId>-<i>` resolved to `extra-<nodeId>`,
	 * so its `data-smartart-node-id` did not match any model node and an inline
	 * edit on a legend row committed nowhere.
	 */
	readonly layoutNodeIds = computed<(string | undefined)[]>(() =>
		flattenNodes(this.revealedNodes()).map((node) => node.id),
	);

	/**
	 * Data-model node id for the rendered node at `index` (or `null`). Exposed
	 * as a method so the template can use it: Angular AOT templates can only
	 * call component members, not imported functions.
	 */
	nodeIdAt(index: number): string | null {
		return this.layoutNodeIds()[index] ?? null;
	}

	/** Resolve the accessibility label for the rendered node at `index`. */
	nodeAriaLabel(index: number): string | null {
		const nodeId = this.nodeIdAt(index);
		if (nodeId === null) {
			return null;
		}
		return this.a11yLabelById().get(nodeId) ?? null;
	}

	/**
	 * Polite live-region message announcing the most recent node-text commit.
	 * Empty between commits so assistive tech only speaks on change.
	 */
	readonly liveMessage = signal<string>('');

	protected readonly hoveredNodeId = signal<string | null>(null);
	protected readonly hoveredNodeRect = signal<InlineEditRect | null>(null);

	/** Narrowing helpers bound as class properties for template type-checking. */
	protected readonly asCircle = narrowToCircle;
	protected readonly asPolygon = narrowToPolygon;
	protected readonly asRect = narrowToRect;

	// ── Inline node-text editing ───────────────────────────────────────────

	/** Double-click a node enters inline edit mode (when editable). */
	onNodeDblClick(event: Event, node: RenderedNode, index: number): void {
		if (!this.canEditNodes()) {
			return;
		}
		event.stopPropagation();
		this.enterEdit(node, index);
	}

	/** Enter / F2 on a focused node enters inline edit mode (when editable). */
	onNodeKeydown(event: KeyboardEvent, node: RenderedNode, index: number): void {
		if (!this.canEditNodes() || (event.key !== 'Enter' && event.key !== 'F2')) {
			return;
		}
		event.preventDefault();
		event.stopPropagation();
		this.enterEdit(node, index);
	}

	/** Commit the current edit (called on blur). */
	commitEdit(event: Event): void {
		if (this.editSettled) {
			this.editSettled = false;
			return;
		}
		const edit = this.editState();
		if (!edit) {
			return;
		}
		const value = (event.target as HTMLTextAreaElement).value;
		this.editState.set(null);
		this.applyCommit(edit.nodeId, value);
	}

	/** Enter commits (Shift+Enter inserts a newline); Escape cancels. */
	onEditorKeydown(event: KeyboardEvent): void {
		event.stopPropagation();
		if (event.key === 'Enter' && !event.shiftKey) {
			event.preventDefault();
			// Commit via blur so the single commit path runs once.
			(event.target as HTMLTextAreaElement).blur();
		} else if (event.key === 'Escape') {
			event.preventDefault();
			// Mark as settled so the DOM-removal blur does not commit the cancelled edit.
			this.editSettled = true;
			this.editState.set(null);
		}
	}

	/** Resolve the node id + geometry and open the editor seeded with full text. */
	private enterEdit(node: RenderedNode, index: number): void {
		this.editSettled = false;
		const nodeId = this.nodeIdAt(index);
		const seed = beginNodeEdit(node, this.element().id, this.rawNodeText(node, index), nodeId);
		if (seed) {
			this.editState.set(seed);
		}
	}

	/** The node's full (untruncated) data-model text, falling back to rendered text. */
	private rawNodeText(node: RenderedNode, index: number): string {
		const nodeId = this.nodeIdAt(index);
		if (nodeId === null) {
			return node.text;
		}
		const match = flattenNodes(this.nodes()).find((n) => n.id === nodeId);
		return match ? match.text : node.text;
	}

	/** Commit edited text through the shared editor state (one history entry). */
	private applyCommit(nodeId: string, text: string): void {
		const data = this.smartArtData();
		const editor = this.editor;
		if (!data || !editor) {
			return;
		}
		const next = commitNodeText(data, nodeId, text);
		if (next === data) {
			return;
		}
		const slideIndex = findOwningSlideIndex(
			editor.slides(),
			this.element().id,
			this.slideContext?.slideId() ?? null,
		);
		if (slideIndex < 0) {
			return;
		}
		editor.updateElement(slideIndex, this.element().id, {
			smartArtData: this.reflow(next),
		} as Partial<PptxElement>);
		// Announce the commit to assistive technology via the polite live region.
		this.liveMessage.set(
			text.trim().length > 0
				? this.translate.instant('pptx.smartart.nodeUpdated', { text: text.trim() })
				: this.translate.instant('pptx.smartart.nodeCleared'),
		);
	}

	// ── Style bar & hover tracking ────────────────────────────────────────

	/** Approximate rendered size of the style bar (6 swatches + padding/border). */
	private static readonly STYLE_BAR_WIDTH = 168;
	private static readonly STYLE_BAR_HEIGHT = 40;

	/** Grace period (ms) before clearing hover state once the pointer leaves the
	 * node, so it can cross the small visual gap to the style bar. */
	private static readonly HIDE_GRACE_MS = 150;

	protected readonly styleBarStyle = computed<Record<string, string> | null>(() => {
		const rect = this.hoveredNodeRect();
		const cnt = this.smartartContainer()?.nativeElement as HTMLElement | undefined;
		if (!rect || !cnt) {
			return null;
		}
		const maxLeft = Math.max(0, cnt.clientWidth - SmartArtRendererComponent.STYLE_BAR_WIDTH);
		const maxTop = Math.max(0, cnt.clientHeight - SmartArtRendererComponent.STYLE_BAR_HEIGHT);
		return {
			position: 'absolute',
			left: `${Math.min(maxLeft, Math.max(0, rect.left + rect.width - SmartArtRendererComponent.STYLE_BAR_WIDTH))}px`,
			top: `${Math.min(maxTop, Math.max(0, rect.top - 22))}px`,
			'z-index': '25',
		};
	});

	protected onMouseMove(event: MouseEvent): void {
		if (!this.canEditNodes()) {
			return;
		}
		const nodeEl = this.findNodeEl(event.target as EventTarget);
		const cnt = this.smartartContainer()?.nativeElement as HTMLElement | undefined;
		if (nodeEl && cnt) {
			this.cancelPendingHide();
			const id = nodeEl.getAttribute('data-smartart-node-id');
			this.hoveredNodeId.set(id);
			this.hoveredNodeRect.set(
				id
					? computeInlineEditorRect(nodeEl.getBoundingClientRect(), cnt.getBoundingClientRect())
					: null,
			);
			return;
		}
		// Pointer may be over the style-bar popover anchored to the currently
		// hovered node (not the node itself) - keep the hover state so the
		// popover doesn't unmount out from under the pointer.
		const styleBarEl = this.styleBar()?.nativeElement as HTMLElement | undefined;
		if (styleBarEl && event.target instanceof Node && styleBarEl.contains(event.target)) {
			this.cancelPendingHide();
			return;
		}
		this.cancelPendingHide();
		this.hideTimeout = setTimeout(() => {
			this.hoveredNodeId.set(null);
			this.hoveredNodeRect.set(null);
			this.hideTimeout = null;
		}, SmartArtRendererComponent.HIDE_GRACE_MS);
	}

	protected onMouseLeave(): void {
		this.cancelPendingHide();
		this.hoveredNodeId.set(null);
		this.hoveredNodeRect.set(null);
	}

	private cancelPendingHide(): void {
		if (this.hideTimeout !== null) {
			clearTimeout(this.hideTimeout);
			this.hideTimeout = null;
		}
	}

	private findNodeEl(target: EventTarget | null): Element | null {
		let el = target instanceof Element ? target : null;
		while (el) {
			if (el.hasAttribute('data-smartart-node-id')) {
				return el;
			}
			el = el.parentElement;
		}
		return null;
	}

	protected handleChangeNodeStyle(nodeId: string, fill: string): void {
		const data = this.smartArtData();
		if (!data || !this.editor) {
			return;
		}
		const next = setSmartArtNodeStyle(data, nodeId, { fillColor: fill });
		if (next === data) {
			return;
		}
		const slideIndex = findOwningSlideIndex(
			this.editor.slides(),
			this.element().id,
			this.slideContext?.slideId() ?? null,
		);
		if (slideIndex < 0) {
			return;
		}
		this.editor.updateElement(slideIndex, this.element().id, {
			smartArtData: this.reflow(next),
		} as Partial<PptxElement>);
	}

	/**
	 * Reflow `drawingShapes` back from the shared layout engine when an edit op
	 * cleared them (every text/style edit does) -- otherwise the renderer falls
	 * back to the generic SVG layout for every node, not just the edited one.
	 */
	private reflow(data: PptxSmartArtData): PptxSmartArtData {
		const el = this.element();
		return rebuildDrawingShapesIfCleared(
			data,
			data.layout,
			resolvePalette(data),
			data.style ?? 'flat',
			el.id,
			{ width: el.width, height: el.height },
		);
	}

	// ── Empty / no-data state ──────────────────────────────────────────────

	readonly isEmpty = computed(() => this.nodes().length === 0 && !this.hasDrawingShapes());
}

// Re-export helper types used in the template so template type-checking works.
export type { DrawingViewBox, RenderedShape };

<div
	#smartartContainer
	class="pptx-ng-smartart-chrome"
	[ngStyle]="chromeStyle()"
	[attr.role]="a11y() ? a11y()!.role : null"
	[attr.aria-label]="a11y()?.label ?? null"
	(mousemove)="onMouseMove($event)"
	(mouseleave)="onMouseLeave()"
>
	@if (isEmpty()) {
		<div class="pptx-ng-smartart-placeholder">
			{{ 'pptx.smartArt.placeholder' | translate }}
		</div>
	} @else if (hasDrawingShapes()) {
		<svg
			class="pptx-ng-smartart-svg"
			data-testid="smartart-drawing-shapes"
			[attr.viewBox]="svgViewBox()"
			preserveAspectRatio="xMidYMid meet"
		>
			@for (shape of renderedShapes(); track shape.key; let i = $index) {
				<g
					[ngStyle]="shadowFilter() ? { filter: shadowFilter() } : {}"
					[attr.data-smartart-node-id]="drawingShapeNodeIds()[i] ?? null"
					[class.pptx-ng-smartart-node--editable]="canEditNodes() && !!drawingShapeNodeIds()[i]"
				>
					@if (shape.gradient) {
						<defs>
							@if (shape.gradient!.kind === 'radial') {
								<radialGradient
									[attr.id]="shape.gradient!.id"
									[attr.cx]="shape.gradient!.cx"
									[attr.cy]="shape.gradient!.cy"
									[attr.r]="shape.gradient!.r"
								>
									@for (stop of shape.gradient!.stops; track $index) {
										<stop
											[attr.offset]="stop.offset"
											[attr.stop-color]="stop.color"
											[attr.stop-opacity]="stop.opacity ?? null"
										/>
									}
								</radialGradient>
							} @else {
								<linearGradient
									[attr.id]="shape.gradient!.id"
									[attr.x1]="shape.gradient!.x1"
									[attr.y1]="shape.gradient!.y1"
									[attr.x2]="shape.gradient!.x2"
									[attr.y2]="shape.gradient!.y2"
								>
									@for (stop of shape.gradient!.stops; track $index) {
										<stop
											[attr.offset]="stop.offset"
											[attr.stop-color]="stop.color"
											[attr.stop-opacity]="stop.opacity ?? null"
										/>
									}
								</linearGradient>
							}
						</defs>
					}
					@if (shape.kind === 'image') {
						<image
							[attr.x]="shape.x"
							[attr.y]="shape.y"
							[attr.width]="shape.width"
							[attr.height]="shape.height"
							[attr.href]="shape.imageUrl"
							preserveAspectRatio="xMidYMid meet"
							[attr.transform]="shape.transform ?? null"
						/>
					} @else if (shape.kind === 'ellipse') {
						<ellipse
							[attr.cx]="shape.cx"
							[attr.cy]="shape.cy"
							[attr.rx]="shape.width / 2"
							[attr.ry]="shape.height / 2"
							[attr.fill]="shape.fill"
							[attr.stroke]="shape.stroke"
							[attr.stroke-width]="shape.strokeWidth"
							[attr.transform]="shape.transform ?? null"
						/>
					} @else if (shape.kind === 'path') {
						<path
							[attr.d]="shape.pathData"
							[attr.fill]="shape.fill"
							[attr.stroke]="shape.stroke"
							[attr.stroke-width]="shape.strokeWidth"
							[attr.transform]="shape.pathTransform ?? null"
						/>
					} @else {
						<rect
							[attr.x]="shape.x"
							[attr.y]="shape.y"
							[attr.width]="shape.width"
							[attr.height]="shape.height"
							[attr.rx]="shape.rx"
							[attr.fill]="shape.fill"
							[attr.stroke]="shape.stroke"
							[attr.stroke-width]="shape.strokeWidth"
							[attr.transform]="shape.transform ?? null"
						/>
					}
					@if (shape.textLines.length > 0) {
						<text
							[attr.x]="shape.textX"
							text-anchor="middle"
							dominant-baseline="central"
							[attr.fill]="shape.fontColor"
							[attr.font-family]="shape.fontFamily ?? null"
							[attr.font-weight]="shape.fontWeight ?? null"
							[attr.font-style]="shape.fontStyle ?? null"
							[attr.font-size]="shape.fontSize"
						>
							@for (line of shape.textLines; track $index) {
								<tspan [attr.x]="shape.textX" [attr.y]="line.y">
									{{ line.text }}
								</tspan>
							}
						</text>
					}
				</g>
			}
		</svg>
	} @else if (hasLayout()) {
		<svg
			class="pptx-ng-smartart-svg"
			[attr.data-testid]="'smartart-' + layout().family"
			[attr.viewBox]="layout().viewBox"
			preserveAspectRatio="xMidYMid meet"
			[attr.data-layout-family]="layout().family"
		>
			@for (conn of layout().connectors; track conn.key; let ci = $index) {
				<path
					[attr.d]="layoutConnectors()[ci]!.d"
					fill="none"
					[attr.stroke]="layoutConnectors()[ci]!.stroke"
					[attr.stroke-width]="layoutConnectors()[ci]!.strokeWidth"
					[attr.opacity]="layoutConnectors()[ci]!.opacity"
					[attr.stroke-dasharray]="layoutConnectors()[ci]!.dash ?? null"
				/>
			}
			@for (node of layout().nodes; track node.key; let ni = $index) {
				<g
					[ngStyle]="shadowFilter() ? { filter: shadowFilter() } : {}"
					[class.pptx-ng-smartart-node--editable]="canEditNodes()"
					[attr.tabindex]="canEditNodes() ? 0 : null"
					[attr.role]="canEditNodes() ? 'button' : 'img'"
					[attr.aria-label]="nodeAriaLabel(ni) ?? node.text"
					[attr.data-smartart-node-id]="nodeIdAt(ni)"
					(dblclick)="onNodeDblClick($event, node, ni)"
					(keydown)="onNodeKeydown($event, node, ni)"
				>
					@if (nodeAriaLabel(ni); as title) {
						<title>{{ title }}</title>
					}
					@if (asCircle(node); as c) {
						<circle
							[attr.cx]="c.cx"
							[attr.cy]="c.cy"
							[attr.r]="c.r"
							[attr.fill]="c.fill"
							[attr.stroke]="c.stroke"
							[attr.stroke-width]="c.strokeWidth"
							[attr.opacity]="c.opacity"
						/>
					} @else if (asPolygon(node); as p) {
						<polygon
							[attr.points]="p.points"
							[attr.fill]="p.fill"
							[attr.stroke]="p.stroke"
							[attr.stroke-width]="p.strokeWidth"
							[attr.opacity]="p.opacity"
						/>
					} @else if (asRect(node); as r) {
						<rect
							[attr.x]="r.x"
							[attr.y]="r.y"
							[attr.width]="r.width"
							[attr.height]="r.height"
							[attr.rx]="r.rx"
							[attr.fill]="r.fill"
							[attr.stroke]="r.stroke"
							[attr.stroke-width]="r.strokeWidth"
							[attr.opacity]="r.opacity"
						/>
					}
					<!--
						Node label. Placement, colour, weight and baseline arrive
						already decided from the shared `smartArtNodeLabel`, so an
						off-centre caption (target leader, gear legend row, timeline
						caption above / below the axis) lands beside its node.
					-->
					@if (layoutLabels()[ni]!.visible) {
						<text
							[attr.x]="layoutLabels()[ni]!.x"
							[attr.text-anchor]="layoutLabels()[ni]!.textAnchor"
							[attr.dominant-baseline]="layoutLabels()[ni]!.dominantBaseline"
							[attr.fill]="layoutLabels()[ni]!.fill"
							[attr.font-size]="layoutLabels()[ni]!.fontSize"
							[attr.font-weight]="layoutLabels()[ni]!.fontWeight ?? null"
							[attr.font-style]="layoutLabels()[ni]!.fontStyle ?? null"
						>
							@for (line of layoutLabels()[ni]!.lines; track $index) {
								<tspan [attr.x]="layoutLabels()[ni]!.x" [attr.y]="line.y">
									{{ line.text }}
								</tspan>
							}
						</text>
					}
				</g>
			}
		</svg>
	} @else {
		<div class="pptx-ng-smartart-placeholder">
			{{ 'pptx.smartArt.placeholder' | translate }}
		</div>
	}

	@if (canEditNodes() && hoveredNodeId() && !editState() && styleBarStyle()) {
		<div
			#styleBar
			class="pptx-ng-smartart-style-bar"
			[ngStyle]="styleBarStyle()!"
			(mousedown)="$event.stopPropagation()"
			(click)="$event.stopPropagation()"
		>
			@for (color of palette().slice(0, 6); track color) {
				<button
					type="button"
					class="pptx-ng-smartart-swatch"
					data-pptx-compact
					[attr.aria-label]="'pptx.smartArt.setFill' | translate: { color: color }"
					[style.background]="color"
					(click)="handleChangeNodeStyle(hoveredNodeId()!, color)"
				></button>
			}
		</div>
	}

	<!--
		Inline node-text editor. Positioned in element-local px (== viewBox
		units, since the SVG viewBox matches the element pixel size and the
		svg fills the chrome) over the double-clicked node. Commits via the
		shared EditorStateService.updateElement path on Enter / blur.
	-->
	@if (editState(); as edit) {
		<textarea
			#nodeEditor
			class="pptx-ng-smartart-node-editor"
			[style.left.px]="edit.box.x"
			[style.top.px]="edit.box.y"
			[style.width.px]="edit.box.width"
			[style.height.px]="edit.box.height"
			[value]="edit.text"
			(pointerdown)="$event.stopPropagation()"
			(mousedown)="$event.stopPropagation()"
			(click)="$event.stopPropagation()"
			(dblclick)="$event.stopPropagation()"
			(blur)="commitEdit($event)"
			(keydown)="onEditorKeydown($event)"
		></textarea>
	}

	<!-- Polite live region: announces node-text edit commits to AT. -->
	<span class="pptx-ng-sr-only" aria-live="polite" role="status">{{ liveMessage() }}</span>
</div>

// packages/vue/src/viewer/components/SmartArtRenderer.vue
<script setup lang="ts">
import type {
	PptxElement,
	PptxSmartArtChrome,
	PptxSmartArtDrawingShape,
	PptxSmartArtNode,
	SmartArtStyle,
} from 'pptx-viewer-core';
import { setSmartArtNodeStyle } from 'pptx-viewer-core';
import {
	buildChromeStyle,
	buildSmartArtA11y,
	computeDrawingViewBox,
	projectDrawingShapes,
	resolvePalette,
	revealedSmartArtNodeCount,
	shouldCommitSmartArtNodeText,
	smartArtConnectorPaint,
	smartArtNodeLabel,
	styleShadowFilter,
} from 'pptx-viewer-shared';
import type {
	ElementAnimationState,
	RenderedShape,
	SmartArtConnectorPaint,
	SmartArtNodeLabel,
} from 'pptx-viewer-shared';
import type { CSSProperties } from 'vue';
import { computed, nextTick, ref } from 'vue';
import { useI18n } from 'vue-i18n';

import { getContainerStyle } from '../composables/element-style';
import {
	inlineEditorRect,
	nodeIdsInRenderOrder,
	textNodeIdsInRenderOrder,
	useSmartArtInlineEditState,
} from '../composables/smartart-inline-edit';
import type {
	RenderedCircleNode,
	RenderedPolygonNode,
	RenderedRectNode,
	SmartArtLayoutResult as ComputedLayout,
} from '../composables/smartart-layout';
import { computeSmartArtElementLayout } from '../composables/smartart-layout';
import { injectSmartArtNodeEdit } from '../composables/smartart-node-edit';
import { useSmartArtHoverRect } from '../composables/useSmartArtHoverRect';
import SmartArtNodeStyleBar from './SmartArtNodeStyleBar.vue';

/**
 * SmartArtRenderer - Vue port of the React SmartArt renderer
 * (`viewer/utils/smartart*.tsx`).
 *
 * Data path: this component renders from the **pre-computed drawing shapes**
 * (`smartArtData.drawingShapes`) extracted by the core engine from
 * `ppt/diagrams/drawing*.xml`, mirroring React's `smartart-drawing.tsx`.
 * That is the path React prefers when drawing shapes are present, and it
 * avoids reimplementing the ~2800 LOC of layout math in the
 * `smartart-cycle/process/hierarchy/...` family.
 *
 * Fallbacks (mirroring `renderSmartArtElement`'s early returns):
 *  - No `smartArtData` or zero nodes → a small "SmartArt" placeholder.
 *  - Nodes present but no drawing shapes → a simple stacked block list of the
 *    node text (the common-case fallback; the full per-family layout renderers
 *    are out of scope per the porting brief).
 *
 * The whole graphic is wrapped in chrome (background / outline) when present.
 */
const props = defineProps<{
	element: PptxElement;
	mediaDataUrls?: Map<string, string>;
	zIndex: number;
	/**
	 * True only for the main editable canvas instance. The `data-testid` layout
	 * hooks are emitted solely when interactive so the identical mini-renders in
	 * the thumbnail rail / slide sorter / presenter don't duplicate the id and
	 * break single-element test locators.
	 */
	interactive?: boolean;
	/** Emit the data-pptx-element marker even when not interactive (template layer). */
	marked?: boolean;
	/**
	 * Native-animation playback state. A staged diagram build
	 * (`build.kind === 'diagram'`) reveals the leading nodes / drawing shapes for
	 * the current progress; absent or non-diagram state renders every node.
	 */
	animationState?: ElementAnimationState;
}>();

const { t } = useI18n();

// ── Resolved SmartArt data ───────────────────────────────────────────────────

const smartArtData = computed(() =>
	props.element.type === 'smartArt' ? props.element.smartArtData : undefined,
);

const nodes = computed<PptxSmartArtNode[]>(() => smartArtData.value?.nodes ?? []);

// ── Accessibility (shared view-model) ────────────────────────────────────────
//
// The generated SVG is opaque to assistive technology, so we derive a
// screen-reader description for the whole diagram (`role="img"` + aria-label on
// the chrome container) and a per-node label looked up by node id, via the
// framework-agnostic `buildSmartArtA11y` from pptx-viewer-shared.

const a11y = computed(() =>
	smartArtData.value ? buildSmartArtA11y(smartArtData.value) : undefined,
);

const nodeLabels = computed<Map<string, string>>(() => {
	const map = new Map<string, string>();
	for (const n of a11y.value?.nodes ?? []) {
		map.set(n.id, n.label);
	}
	return map;
});

/** Per-node ARIA label / SVG <title> text, by node id (empty when unknown). */
function nodeLabel(nodeId: string | undefined): string | undefined {
	return nodeId ? nodeLabels.value.get(nodeId) : undefined;
}

const palette = computed<string[]>(() => resolvePalette(smartArtData.value));

const style = computed<SmartArtStyle>(() => smartArtData.value?.style ?? 'flat');

const chrome = computed<PptxSmartArtChrome | undefined>(() => smartArtData.value?.chrome);

const containerStyle = computed<CSSProperties>(() =>
	getContainerStyle(props.element, props.zIndex),
);

/**
 * `pointer-events: none` on the root while not interactive, mirroring
 * React's `pointer-events-none` class / Angular's `rootPointerEvents`. The
 * inner `.pptx-vue-smartart-svg` is already `pointer-events: none` by default
 * CSS (with editable node groups opting back in via
 * `.pptx-vue-smartart-editable`), but nothing previously gated the OUTER
 * `pptx-vue-smartart` box itself, so its background/chrome area stayed
 * clickable even while `marked` locked the element (e.g. a template/master
 * diagram with `editTemplateMode` off). `null` while interactive so the
 * style-array merge leaves any pre-existing `pointerEvents` untouched.
 */
const rootPointerEvents = computed<CSSProperties | null>(() =>
	props.interactive ? null : { pointerEvents: 'none' },
);

/**
 * The chrome wrapper's background/outline decision, from the shared
 * `buildChromeStyle` (same function Angular/Svelte/Vanilla call directly).
 * Its `CssStyleMap` return is kebab-case; Vue's `CSSProperties` accepts both
 * kebab and camelCase keys, so this only needs a type cast, not a converter.
 */
const chromeStyle = computed<CSSProperties>(() => buildChromeStyle(chrome.value) as CSSProperties);

// ── Drawing-shape path (mirrors smartart-drawing.tsx) ────────────────────────

const drawingShapes = computed<PptxSmartArtDrawingShape[]>(
	() => smartArtData.value?.drawingShapes ?? [],
);

const hasDrawingShapes = computed(() => drawingShapes.value.length > 0);

// ── Staged diagram build (p:bldDgm) reveal ──────────────────────────────────
//
// When an active native animation carries a staged diagram build, reveal only
// the leading nodes / drawing shapes for the current progress; the view box is
// still computed from the FULL shape set so the diagram does not rescale as it
// builds. Mirrors React's `SmartArtRenderer` reveal slice.

const diagramBuild = computed(() => {
	const build = props.animationState?.build;
	return build?.kind === 'diagram' ? build : undefined;
});

const shownNodeCount = computed(() =>
	diagramBuild.value
		? revealedSmartArtNodeCount(nodes.value, diagramBuild.value)
		: nodes.value.length,
);

const isPartialBuild = computed(
	() => diagramBuild.value !== undefined && shownNodeCount.value < nodes.value.length,
);

/** Leading node prefix revealed so far (full list when no partial build). */
const revealedNodes = computed<PptxSmartArtNode[]>(() =>
	isPartialBuild.value ? nodes.value.slice(0, shownNodeCount.value) : nodes.value,
);

/** Leading drawing-shape prefix revealed so far (proportional to nodes). */
const revealedShapeList = computed<PptxSmartArtDrawingShape[]>(() => {
	if (!isPartialBuild.value || drawingShapes.value.length === 0) {
		return drawingShapes.value;
	}
	const count = Math.ceil(
		(shownNodeCount.value / Math.max(nodes.value.length, 1)) * drawingShapes.value.length,
	);
	return drawingShapes.value.slice(0, count);
});

/** Shape descriptor plus the source node id used for inline editing. */
type EditableShape = RenderedShape & { nodeId?: string };

const drawingViewBox = computed(() => computeDrawingViewBox(drawingShapes.value));

const renderedShapes = computed<EditableShape[]>(() => {
	// Text-bearing shapes map positionally to text-bearing source nodes so a
	// double-click on a labelled shape targets the right node id.
	const textIds = textNodeIdsInRenderOrder(nodes.value);
	let textShapeIndex = 0;

	return projectDrawingShapes(
		props.element.id,
		revealedShapeList.value,
		drawingViewBox.value,
		palette.value,
		style.value,
	).map((shape, i) => ({
		...shape,
		nodeId: revealedShapeList.value[i]?.text ? textIds[textShapeIndex++] : undefined,
	}));
});

/**
 * Seed text for an inline edit. The rendered lines are a wrapped view of the
 * authored string, so they are joined back with spaces rather than newlines to
 * avoid writing the wrap points into the node.
 */
function shapeEditText(shape: EditableShape): string {
	return shape.textLines.map((line) => line.text).join(' ');
}

const shadowFilter = computed(() => styleShadowFilter(style.value));

// ── SVG layout fallback (no drawing shapes) ──────────────────────────────────
//
// When drawing shapes are absent the component runs the pure-geometry layout
// engine from `smartart-layout.ts` to produce an SVG approximation.

const fallbackLayout = computed<ComputedLayout | undefined>(() => {
	if (hasDrawingShapes.value || nodes.value.length === 0) {
		return undefined;
	}
	const data = smartArtData.value;
	return computeSmartArtElementLayout(
		data ?? {},
		revealedNodes.value,
		{ width: props.element.width, height: props.element.height },
		palette.value,
		style.value,
		props.element.id,
	);
});

// ── Fallback-layout label / connector paint ──────────────────────────────────
//
// The layout descriptor's optional fields (per-node font colour / weight /
// style, off-centre label anchors for target leaders, gear legend rows and
// timeline captions, and per-connector stroke) are resolved by the shared
// decision functions below. The template binds the result and computes nothing.

/** Resolved connector paint, index-aligned with `fallbackLayout.connectors`. */
const fallbackConnectors = computed<SmartArtConnectorPaint[]>(() =>
	(fallbackLayout.value?.connectors ?? []).map((conn) => smartArtConnectorPaint(conn)),
);

/** Resolved label descriptors, index-aligned with `fallbackLayout.nodes`. */
const fallbackLabels = computed<SmartArtNodeLabel[]>(() =>
	(fallbackLayout.value?.nodes ?? []).map((node) => smartArtNodeLabel(node)),
);

const isEmpty = computed(() => nodes.value.length === 0 && !hasDrawingShapes.value);

// ── Inline on-canvas node text editing ───────────────────────────────────────
//
// A node-edit context, when provided by the host (edit mode, not presenting),
// lets a double-click on a node open an inline <textarea> over it. Commit flows
// through the SAME core op the inspector uses (`updateSmartArtNodeText` via
// `updateElement`), so undo/redo and save round-trip are identical.

const nodeEdit = injectSmartArtNodeEdit();
const editable = computed(() => Boolean(nodeEdit?.canEdit()));

/**
 * Source node ids in fallback render order (index-aligned with layout nodes).
 * Flattened over the REVEALED prefix, since that is what the layout engine was
 * handed: a staged diagram build otherwise mapped ids past the reveal point.
 */
const fallbackNodeIds = computed<string[]>(() =>
	fallbackLayout.value ? nodeIdsInRenderOrder(revealedNodes.value) : [],
);

const edit = useSmartArtInlineEditState();
const rootEl = ref<HTMLElement | null>(null);
const editorEl = ref<HTMLTextAreaElement | null>(null);
// Anchors the style-bar popover; mousemove events landing inside it must not
// clear the hover state, or the popover would unmount as soon as the pointer
// reaches the swatches it needs to be clicked.
const styleBarEl = ref<HTMLElement | null>(null);
const {
	hoveredNodeId,
	hoveredNodeRect,
	onMouseMove: onHoverMouseMove,
	onMouseLeave,
} = useSmartArtHoverRect(rootEl);

function onMouseMove(event: MouseEvent): void {
	onHoverMouseMove(event, styleBarEl.value);
}

/** Approximate rendered size of the style bar (6 swatches + padding/border). */
const STYLE_BAR_WIDTH = 168;
const STYLE_BAR_HEIGHT = 40;

/** Style-bar position, clamped so it stays within the chrome's clipped bounds. */
const styleBarStyle = computed<CSSProperties | undefined>(() => {
	const rect = hoveredNodeRect.value;
	const container = rootEl.value;
	if (!rect || !container) {
		return undefined;
	}
	const maxLeft = Math.max(0, container.clientWidth - STYLE_BAR_WIDTH);
	const maxTop = Math.max(0, container.clientHeight - STYLE_BAR_HEIGHT);
	return {
		position: 'absolute',
		left: `${Math.min(maxLeft, Math.max(0, rect.left + rect.width - STYLE_BAR_WIDTH))}px`,
		top: `${Math.min(maxTop, Math.max(0, rect.top - 22))}px`,
		zIndex: 25,
	};
});

/**
 * Enter edit mode for a node. Projects the double-clicked SVG node's on-screen
 * rect into container-relative pixels (shared `computeInlineEditorRect`) so the
 * overlay textarea sits exactly over the node, independent of canvas zoom.
 */
function beginEdit(nodeId: string | undefined, text: string, event: Event): void {
	if (!editable.value || !nodeId) {
		return;
	}
	const target = event.currentTarget as Element | null;
	const host = rootEl.value;
	if (!target || !host) {
		return;
	}
	const rect = inlineEditorRect(target.getBoundingClientRect(), host.getBoundingClientRect());
	edit.begin(nodeId, text, rect);
	void nextTick(() => {
		editorEl.value?.focus();
		editorEl.value?.select();
	});
}

/** Commit the draft text through the host op, skipping no-op edits. */
function commitEdit(): void {
	const nodeId = edit.editingNodeId.value;
	const data = smartArtData.value;
	if (nodeId && data && nodeEdit && shouldCommitSmartArtNodeText(data, nodeId, edit.draft.value)) {
		nodeEdit.commit(props.element.id, nodeId, edit.draft.value);
	}
	edit.cancel();
}

function cancelEdit(): void {
	edit.cancel();
}

/** Apply a fill colour to a node by id, routing through the host commitStyle op. */
function handleChangeNodeStyle(nodeId: string, fill: string): void {
	const data = smartArtData.value;
	if (!data || !nodeEdit) {
		return;
	}
	const next = setSmartArtNodeStyle(data, nodeId, { fillColor: fill });
	if (next !== data) {
		nodeEdit.commitStyle?.(props.element.id, { smartArtData: next } as Partial<PptxElement>);
	}
}

/**
 * Stop all keydown bubbling so parent shortcuts (Delete, arrow keys, etc.)
 * do not fire while typing in the editor. Enter commits; Shift+Enter inserts
 * a newline; Escape cancels.
 */
function onEditorKeydown(event: KeyboardEvent): void {
	event.stopPropagation();
	if (event.key === 'Enter' && !event.shiftKey) {
		event.preventDefault();
		commitEdit();
	} else if (event.key === 'Escape') {
		event.preventDefault();
		cancelEdit();
	}
}
</script>

<template>
	<div
		class="pptx-vue-element pptx-vue-smartart"
		:style="[containerStyle, rootPointerEvents]"
		:data-element-id="element.id"
		:data-pptx-element="props.interactive || props.marked ? 'true' : undefined"
		aria-roledescription="diagram"
	>
		<div
			ref="rootEl"
			class="pptx-vue-smartart-chrome"
			:style="chromeStyle"
			:role="a11y ? 'img' : undefined"
			:aria-label="a11y?.label"
			@mousemove="onMouseMove"
			@mouseleave="onMouseLeave"
		>
			<!-- Empty / no-data placeholder -->
			<div v-if="isEmpty" class="pptx-vue-smartart-placeholder">
				{{ t('pptx.smartArt.placeholder') }}
			</div>

			<!-- Pre-computed drawing shapes (preferred path) -->
			<svg
				v-else-if="hasDrawingShapes"
				class="pptx-vue-smartart-svg"
				:data-testid="props.interactive ? 'smartart-drawing-shapes' : undefined"
				:viewBox="`0 0 ${drawingViewBox.width} ${drawingViewBox.height}`"
				preserveAspectRatio="xMidYMid meet"
			>
				<g
					v-for="shape in renderedShapes"
					:key="shape.key"
					:class="{ 'pptx-vue-smartart-editable': editable && shape.nodeId }"
					:data-node-id="shape.nodeId"
					:data-smartart-node-id="shape.nodeId || undefined"
					:tabindex="editable && shape.nodeId ? 0 : undefined"
					:role="nodeLabel(shape.nodeId) ? 'img' : undefined"
					:aria-label="nodeLabel(shape.nodeId)"
					:style="shadowFilter ? { filter: shadowFilter } : undefined"
					@dblclick="beginEdit(shape.nodeId, shapeEditText(shape), $event)"
					@keydown.enter.prevent="beginEdit(shape.nodeId, shapeEditText(shape), $event)"
				>
					<title v-if="nodeLabel(shape.nodeId)">{{ nodeLabel(shape.nodeId) }}</title>
					<defs v-if="shape.gradient">
						<radialGradient
							v-if="shape.gradient.kind === 'radial'"
							:id="shape.gradient.id"
							:cx="shape.gradient.cx"
							:cy="shape.gradient.cy"
							:r="shape.gradient.r"
						>
							<stop
								v-for="(stop, si) in shape.gradient.stops"
								:key="si"
								:offset="stop.offset"
								:stop-color="stop.color"
								:stop-opacity="stop.opacity"
							/>
						</radialGradient>
						<linearGradient
							v-else
							:id="shape.gradient.id"
							:x1="shape.gradient.x1"
							:y1="shape.gradient.y1"
							:x2="shape.gradient.x2"
							:y2="shape.gradient.y2"
						>
							<stop
								v-for="(stop, si) in shape.gradient.stops"
								:key="si"
								:offset="stop.offset"
								:stop-color="stop.color"
								:stop-opacity="stop.opacity"
							/>
						</linearGradient>
					</defs>
					<image
						v-if="shape.kind === 'image'"
						:x="shape.x"
						:y="shape.y"
						:width="shape.width"
						:height="shape.height"
						:href="shape.imageUrl"
						preserveAspectRatio="xMidYMid meet"
						:transform="shape.transform"
					/>
					<ellipse
						v-else-if="shape.kind === 'ellipse'"
						:cx="shape.cx"
						:cy="shape.cy"
						:rx="shape.width / 2"
						:ry="shape.height / 2"
						:fill="shape.fill"
						:stroke="shape.stroke"
						:stroke-width="shape.strokeWidth"
						:transform="shape.transform"
					/>
					<path
						v-else-if="shape.kind === 'path'"
						:d="shape.pathData"
						:fill="shape.fill"
						:stroke="shape.stroke"
						:stroke-width="shape.strokeWidth"
						:transform="shape.pathTransform"
					/>
					<rect
						v-else
						:x="shape.x"
						:y="shape.y"
						:width="shape.width"
						:height="shape.height"
						:rx="shape.rx"
						:fill="shape.fill"
						:stroke="shape.stroke"
						:stroke-width="shape.strokeWidth"
						:transform="shape.transform"
					/>
					<text
						v-if="shape.textLines.length > 0"
						:x="shape.textX"
						text-anchor="middle"
						dominant-baseline="central"
						:fill="shape.fontColor"
						:font-size="shape.fontSize"
						:font-family="shape.fontFamily"
						:font-weight="shape.fontWeight"
						:font-style="shape.fontStyle"
					>
						<tspan v-for="(line, li) in shape.textLines" :key="li" :x="shape.textX" :y="line.y">
							{{ line.text }}
						</tspan>
					</text>
				</g>
			</svg>

			<!-- Fallback: SVG layout computed from node tree -->
			<svg
				v-else-if="fallbackLayout"
				class="pptx-vue-smartart-svg"
				:viewBox="fallbackLayout.viewBox"
				preserveAspectRatio="xMidYMid meet"
				:data-testid="props.interactive ? `smartart-${fallbackLayout.family}` : undefined"
				:data-layout-family="fallbackLayout.family"
			>
				<!-- Connectors (render first so they appear behind nodes) -->
				<path
					v-for="(conn, ci) in fallbackLayout.connectors"
					:key="conn.key"
					:d="fallbackConnectors[ci]!.d"
					fill="none"
					:stroke="fallbackConnectors[ci]!.stroke"
					:stroke-width="fallbackConnectors[ci]!.strokeWidth"
					:opacity="fallbackConnectors[ci]!.opacity"
					:stroke-dasharray="fallbackConnectors[ci]!.dash"
				/>
				<!-- Rendered nodes -->
				<g
					v-for="(node, i) in fallbackLayout.nodes"
					:key="node.key"
					:class="{ 'pptx-vue-smartart-editable': editable && fallbackNodeIds[i] }"
					:data-node-id="fallbackNodeIds[i]"
					:data-smartart-node-id="fallbackNodeIds[i] || undefined"
					:tabindex="editable && fallbackNodeIds[i] ? 0 : undefined"
					:role="nodeLabel(fallbackNodeIds[i]) ? 'img' : undefined"
					:aria-label="nodeLabel(fallbackNodeIds[i])"
					:style="fallbackLayout.shadowFilter ? { filter: fallbackLayout.shadowFilter } : undefined"
					@dblclick="beginEdit(fallbackNodeIds[i], node.text, $event)"
					@keydown.enter.prevent="beginEdit(fallbackNodeIds[i], node.text, $event)"
				>
					<title v-if="nodeLabel(fallbackNodeIds[i])">{{ nodeLabel(fallbackNodeIds[i]) }}</title>
					<!-- Circle nodes (cycle, radial, venn, target, gear, timeline) -->
					<circle
						v-if="node.kind === 'circle'"
						:cx="(node as RenderedCircleNode).cx"
						:cy="(node as RenderedCircleNode).cy"
						:r="(node as RenderedCircleNode).r"
						:fill="node.fill"
						:stroke="node.stroke"
						:stroke-width="node.strokeWidth"
						:opacity="node.opacity"
					/>
					<!-- Polygon nodes (process, pyramid, funnel) -->
					<polygon
						v-else-if="node.kind === 'polygon'"
						:points="(node as RenderedPolygonNode).points"
						:fill="node.fill"
						:stroke="node.stroke"
						:stroke-width="node.strokeWidth"
						:opacity="node.opacity"
					/>
					<!-- Rect nodes (list, matrix, hierarchy) -->
					<rect
						v-else
						:x="(node as RenderedRectNode).x"
						:y="(node as RenderedRectNode).y"
						:width="(node as RenderedRectNode).width"
						:height="(node as RenderedRectNode).height"
						:rx="(node as RenderedRectNode).rx"
						:fill="node.fill"
						:stroke="node.stroke"
						:stroke-width="node.strokeWidth"
						:opacity="node.opacity"
					/>
					<!--
						Label: placement, colour, weight and baseline all arrive decided
						from shared, so an off-centre caption (target leader, gear legend
						row, timeline caption above / below the axis) lands beside its
						node rather than on top of it.
					-->
					<text
						v-if="fallbackLabels[i]!.visible"
						:x="fallbackLabels[i]!.x"
						:text-anchor="fallbackLabels[i]!.textAnchor"
						:dominant-baseline="fallbackLabels[i]!.dominantBaseline"
						:fill="fallbackLabels[i]!.fill"
						:font-size="fallbackLabels[i]!.fontSize"
						:font-weight="fallbackLabels[i]!.fontWeight"
						:font-style="fallbackLabels[i]!.fontStyle"
					>
						<tspan
							v-for="(line, li) in fallbackLabels[i]!.lines"
							:key="li"
							:x="fallbackLabels[i]!.x"
							:y="line.y"
						>
							{{ line.text }}
						</tspan>
					</text>
				</g>
			</svg>

			<!-- Per-node fill colour picker (hover swatch bar, edit mode only) -->
			<div
				v-if="editable && hoveredNodeId && !edit.isEditing.value && hoveredNodeRect"
				ref="styleBarEl"
				:style="styleBarStyle"
			>
				<SmartArtNodeStyleBar
					:palette="palette"
					@pick-fill="handleChangeNodeStyle(hoveredNodeId!, $event)"
				/>
			</div>

			<!-- Inline node text editor overlay (edit mode only) -->
			<textarea
				v-if="edit.isEditing.value && edit.rect.value"
				ref="editorEl"
				v-model="edit.draft.value"
				class="pptx-vue-smartart-node-editor"
				spellcheck="false"
				:aria-label="t('pptx.smartArt.editNodeText')"
				:style="{
					left: `${edit.rect.value.left}px`,
					top: `${edit.rect.value.top}px`,
					width: `${edit.rect.value.width}px`,
					height: `${edit.rect.value.height}px`,
				}"
				@keydown="onEditorKeydown"
				@mousedown.stop
				@click.stop
				@dblclick.stop
				@blur="commitEdit"
			/>
		</div>
	</div>
</template>

<style scoped>
.pptx-vue-smartart-chrome {
	position: relative;
	box-sizing: border-box;
	overflow: hidden;
}

.pptx-vue-smartart-svg {
	width: 100%;
	height: 100%;
	pointer-events: none;
}

/* Editable node groups opt back into pointer events so a double-click can
   enter inline edit mode without breaking element selection/drag elsewhere. */
.pptx-vue-smartart-editable {
	pointer-events: auto;
	cursor: text;
}

/* Hover ring: outline does not render on SVG <g> elements in all browsers,
   so drop-shadow is used as the visual confirmation that a node is editable. */
.pptx-vue-smartart-editable:hover {
	filter: drop-shadow(0 0 2px rgba(96, 165, 250, 0.8));
}

.pptx-vue-smartart-node-editor {
	position: absolute;
	z-index: 2;
	margin: 0;
	padding: 2px;
	border: 1px solid #2563eb;
	border-radius: 3px;
	box-sizing: border-box;
	resize: none;
	overflow: hidden;
	font: inherit;
	font-size: 12px;
	line-height: 1.2;
	text-align: center;
	color: #111;
	background: #fff;
}

.pptx-vue-smartart-placeholder {
	width: 100%;
	height: 100%;
	display: flex;
	align-items: center;
	justify-content: center;
	font-size: 11px;
	color: rgba(255, 255, 255, 0.8);
	pointer-events: none;
}

.pptx-vue-smartart-list {
	width: 100%;
	height: 100%;
	display: flex;
	flex-direction: column;
	gap: 4px;
	padding: 4px;
	box-sizing: border-box;
	overflow: hidden;
}

.pptx-vue-smartart-block {
	flex: 1 1 0;
	min-height: 0;
	display: flex;
	align-items: center;
	justify-content: center;
	padding: 2px 6px;
	border-radius: 4px;
	color: #fff;
	font-size: 12px;
	text-align: center;
	overflow: hidden;
}
</style>
