// packages/angular/src/viewer/theme-gallery.component.ts
/**
 * theme-gallery.component.ts: Angular port of React's `ThemeGallery.tsx` /
 * Vue's `ThemeGallery.vue`.
 *
 * Shows a grid of built-in deck-theme presets (`THEME_PRESETS` from
 * `pptx-viewer-core`).  Selecting one emits `applyTheme` with the chosen
 * `PptxThemePreset`; the parent (`PowerPointViewerComponent`) applies it to
 * the live deck via `applyThemeToData`.
 *
 * Rendered as a fixed overlay (like Vue's `<Teleport to="body">`).  The
 * component is `OnPush` and purely presentational; all state lives in signals.
 */
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, effect, input, output, signal } from '@angular/core';
import { LucideCheck, LucideX } from '@lucide/angular';
import { TranslatePipe } from '@ngx-translate/core';
import type { PptxTheme, PptxThemePreset } from 'pptx-viewer-core';

import { ThemeEditorFieldsComponent } from './theme-editor-fields.component';
import type { CustomThemeEdit } from './theme-editor-fields.component';
import { GALLERY_THEME_PRESETS } from './theme-gallery-presets';

@Component({
	selector: 'pptx-theme-gallery',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [NgClass, LucideX, LucideCheck, TranslatePipe, ThemeEditorFieldsComponent],
	template: `
		@if (open()) {
			<!-- Backdrop -->
			<div
				class="fixed inset-0 z-[1100] flex items-start justify-center bg-black/40 pt-20"
				(click)="onBackdropClick($event)"
				[attr.aria-label]="'pptx.themeGallery.close' | translate"
			>
				<!-- Panel -->
				<div
					class="w-[640px] max-w-[90vw] rounded-lg border border-border bg-popover shadow-2xl p-4"
					role="dialog"
					[attr.aria-label]="'pptx.themeGallery.ariaLabel' | translate"
					aria-modal="true"
				>
					<!-- Header: title + description + close icon -->
					<div class="mb-3 flex items-start justify-between">
						<div>
							<h2 class="text-sm font-semibold text-foreground">
								{{ 'pptx.themeGallery.title' | translate }}
							</h2>
							<p class="text-xs text-muted-foreground">
								{{ 'pptx.themeGallery.description' | translate }}
							</p>
						</div>
						<button
							type="button"
							class="rounded-sm p-1 text-muted-foreground transition-colors hover:bg-accent/60 hover:text-foreground"
							(click)="close.emit()"
							[attr.aria-label]="'pptx.themeGallery.close' | translate"
						>
							<svg lucideX class="h-4 w-4"></svg>
						</button>
					</div>

					@if (customizing()) {
						<pptx-theme-editor-fields
							[theme]="theme()"
							(applyTheme)="applyCustomTheme.emit($event)"
						/>
					} @else {
						<!-- Theme thumbnail grid (ThemeThumbnail parity) -->
						<div class="grid grid-cols-4 gap-2">
							@for (preset of presets; track preset.id) {
								<button
									type="button"
									class="group relative flex flex-col overflow-hidden rounded-lg border-2 transition-all"
									[ngClass]="
										selected()?.id === preset.id
											? 'scale-[1.02] border-primary shadow-lg'
											: 'border-border hover:border-primary/50 hover:shadow-md'
									"
									[title]="preset.name"
									(click)="selectPreset(preset)"
								>
									<!-- Colour preview: accent header bars + dk2/lt2 content area -->
									<div class="flex h-24 flex-col">
										<div class="flex h-10">
											<span
												class="flex-1"
												[style.background-color]="preset.colorScheme.accent1"
											></span>
											<span
												class="flex-1"
												[style.background-color]="preset.colorScheme.accent2"
											></span>
											<span
												class="flex-1"
												[style.background-color]="preset.colorScheme.accent3"
											></span>
										</div>
										<div class="flex flex-1">
											<span class="w-1/3" [style.background-color]="preset.colorScheme.dk2"></span>
											<span class="flex-1" [style.background-color]="preset.colorScheme.lt2"></span>
										</div>
									</div>

									<!-- Theme name footer -->
									<div class="border-t border-border bg-background px-2 py-1.5">
										<p class="text-center text-xs font-medium text-foreground">{{ preset.name }}</p>
									</div>

									<!-- Active / selected check mark -->
									@if (selected()?.id === preset.id || activeName() === preset.name) {
										<span
											class="absolute right-1 top-1 flex h-4 w-4 items-center justify-center rounded-full bg-primary text-[10px] font-bold text-white"
											[attr.aria-label]="'pptx.themeGallery.selectedTheme' | translate"
											><svg lucideCheck class="h-2.5 w-2.5"></svg
										></span>
									}
								</button>
							}
						</div>
					}

					<!-- Footer -->
					<div class="flex items-center justify-end gap-2 mt-4">
						<button
							type="button"
							class="pptx-rb-pill mr-auto"
							(click)="customizing.set(!customizing())"
						>
							{{ (customizing() ? 'pptx.common.back' : 'pptx.themeEditor.title') | translate }}
						</button>
						<button type="button" class="pptx-rb-pill" (click)="close.emit()">
							{{ 'pptx.common.cancel' | translate }}
						</button>
						<button
							type="button"
							class="pptx-rb-pill bg-primary text-primary-foreground hover:bg-primary/80 disabled:opacity-40 disabled:cursor-not-allowed"
							[disabled]="!selected()"
							(click)="applySelected()"
						>
							{{ 'pptx.hyperlinkDialog.apply' | translate }}
						</button>
					</div>
				</div>
			</div>
		}
	`,
})
export class ThemeGalleryComponent {
	/** Whether the gallery overlay is visible. */
	readonly open = input<boolean>(false);
	/**
	 * The `name` of the currently active deck theme (for check-mark display).
	 * Matches `PptxTheme.name`.
	 */
	readonly activeName = input<string | undefined>(undefined);
	readonly theme = input<PptxTheme | undefined>(undefined);
	/**
	 * Which face the gallery opens on: the preset grid (false) or the theme
	 * editor (true). Design > Edit Theme names the editor, so it opens straight
	 * into it rather than making the user find the footer's customise button.
	 * Only consulted as the overlay opens; the footer button still flips freely.
	 */
	readonly startCustomizing = input<boolean>(false);

	/** Emitted when the user confirms a selection. */
	readonly applyTheme = output<PptxThemePreset>();
	readonly applyCustomTheme = output<CustomThemeEdit>();
	/** Emitted when the user cancels (backdrop click, Close button, Cancel button). */
	readonly close = output<void>();

	protected readonly presets: readonly PptxThemePreset[] = GALLERY_THEME_PRESETS;

	/** The currently highlighted (not yet applied) preset, or null. */
	protected readonly selected = signal<PptxThemePreset | null>(null);
	protected readonly customizing = signal(false);

	constructor() {
		// Seed the face the overlay shows whenever it opens, or whenever the host
		// asks for a different one (Design > Edit Theme with the gallery already
		// up). The footer's own toggle is not read here, so flipping back to the
		// grid by hand is never undone.
		effect(() => {
			const customize = this.startCustomizing();
			if (this.open()) {
				this.customizing.set(customize);
			}
		});
	}

	protected selectPreset(preset: PptxThemePreset): void {
		this.selected.set(preset);
	}

	protected applySelected(): void {
		const preset = this.selected();
		if (preset) {
			this.applyTheme.emit(preset);
			this.selected.set(null);
		}
	}

	protected onBackdropClick(event: MouseEvent): void {
		// Only close when clicking the backdrop itself, not the inner panel.
		if (event.target === event.currentTarget) {
			this.close.emit();
		}
	}
}

// packages/vue/src/viewer/components/ThemeGallery.vue
<script setup lang="ts">
import { X } from 'lucide-vue-next';
/**
 * ThemeGallery - Design ▸ Themes. The Vue 3 port of React's
 * `toolbar/ThemeGallery`: a centered modal of the built-in gallery themes
 * (Office / Facet / Ion / …) shown as colour-preview thumbnails. Selecting a
 * thumbnail highlights it; the footer Apply button then emits `apply(preset)`
 * so the host re-themes the deck via core's `applyThemeToData`. Mirrors React's
 * select-then-apply flow, header (title + description), and Cancel/Apply footer;
 * class strings are copied verbatim for visual parity.
 *
 * The gallery set comes from `theme-gallery-presets` so it matches React's
 * exact 10-theme list/order (adds wisp/berlin/slice/dividend, omits core's
 * slate/metropolitan) rather than core's raw `THEME_PRESETS`.
 */
import type { PptxThemePreset } from 'pptx-viewer-core';
import { ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';

import { GALLERY_THEME_PRESETS } from './theme-gallery-presets';
import ThemeThumbnail from './ThemeThumbnail.vue';

const { t } = useI18n();

const props = withDefaults(
	defineProps<{ open: boolean; activeName?: string; canEdit?: boolean }>(),
	{ canEdit: true },
);
const emit = defineEmits<{ apply: [preset: PptxThemePreset]; close: [] }>();

/** Currently highlighted preset id (select-then-apply, mirroring React). */
const selectedId = ref<string | null>(null);

/** Seed the selection from the active theme each time the gallery opens. */
watch(
	() => props.open,
	(isOpen) => {
		if (isOpen) {
			selectedId.value = GALLERY_THEME_PRESETS.find((p) => p.name === props.activeName)?.id ?? null;
		}
	},
	{ immediate: true },
);

function handleApply(): void {
	const preset = GALLERY_THEME_PRESETS.find((p) => p.id === selectedId.value);
	if (preset) {
		emit('apply', preset);
		emit('close');
	}
}
</script>

<template>
	<Teleport to="body">
		<template v-if="props.open">
			<!-- Backdrop -->
			<button
				type="button"
				class="fixed inset-0 z-[100] bg-black/60 backdrop-blur-sm"
				:aria-label="t('pptx.common.close')"
				@click="emit('close')"
			/>

			<!-- Modal -->
			<div class="fixed inset-0 z-[101] flex items-center justify-center p-4">
				<div
					class="bg-background border border-border rounded-xl shadow-2xl max-w-5xl w-full max-h-[90vh] flex flex-col"
					role="dialog"
					:aria-label="t('pptx.themes.gallery.ariaLabel')"
				>
					<!-- Header -->
					<div class="flex items-center justify-between px-6 py-4 border-b border-border">
						<div>
							<h2 class="text-lg font-semibold text-foreground">
								{{ t('pptx.themes.gallery.title') }}
							</h2>
							<p class="text-xs text-muted-foreground mt-0.5">
								{{ t('pptx.themes.gallery.description') }}
							</p>
						</div>
						<button
							type="button"
							class="p-2 rounded hover:bg-accent transition-colors"
							:aria-label="t('pptx.common.close')"
							@click="emit('close')"
						>
							<X class="w-5 h-5" />
						</button>
					</div>

					<!-- Content -->
					<div class="flex-1 overflow-auto p-6">
						<div class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4">
							<ThemeThumbnail
								v-for="preset in GALLERY_THEME_PRESETS"
								:key="preset.id"
								:theme="preset"
								:selected="selectedId === preset.id"
								@select="selectedId = preset.id"
							/>
						</div>
					</div>

					<!-- Footer -->
					<div class="flex items-center justify-end px-6 py-4 border-t border-border gap-2">
						<button
							type="button"
							class="px-3 py-1.5 rounded bg-accent hover:bg-accent/80 text-xs font-medium text-foreground transition-colors"
							@click="emit('close')"
						>
							{{ t('pptx.common.cancel') }}
						</button>
						<button
							type="button"
							:disabled="!props.canEdit || !selectedId"
							class="px-3 py-1.5 rounded bg-primary hover:bg-primary/80 text-xs font-medium text-white transition-colors disabled:opacity-40 disabled:cursor-not-allowed"
							@click="handleApply"
						>
							{{ t('pptx.common.apply') }}
						</button>
					</div>
				</div>
			</div>
		</template>
	</Teleport>
</template>
